### ISSUE TITLE
Messages are not marked as read even after reading them

### ISSUE THREAD

**Issue by SeriousTube** [moezbhatti/qksms#1003]
This is using version 3.03 though the same problems exist with the version at the play store.

Messages are not being marked as read. I get notifications, then go to the page and read the message but they are still not marked as read.  I use another app called professional reminder. If I send a text to myself, and read it in qksms it still shows 

Quick Stop (C:0 S:1 M:0)
Stop all current reminders

C,S,M mean phone Calls, Sms, and Mms. I  have the reminder set  for every 20 minutes so it is beeping every 20 minutes which is very annoying.

I don't know if this is relevant but I have QK reply turned off since I don't like it.

**Comment by moezbhatti** [comment]
When viewing messages from within QKSMS, does anything show up as unread?

**Comment by moezbhatti** [comment]
Fixed in f03adec5c0cd447b7bcfa6547aae8f8c7e54ef9d
