### ISSUE TITLE
Setting to disable "tap outside of popup window to dismiss"

### ISSUE THREAD

**Issue by zawyer1** [moezbhatti/qksms#1008]
In the old QKSMS there used to be a setting for turning off dismissing the popup window (QK Reply) when you tapped outside of it.

Currently, the window will always close/dismiss whenever you tap outside of the window, which can sometimes close down the window by accident.

Would you consider adding this setting in 3.0 as well?

**Comment by moezbhatti** [comment]
Added in bfb97834dc44af1fdee4a7a8ccdf5b68924e373a
