### ISSUE TITLE
UI issues with resending failed texts

### ISSUE THREAD

**Issue by Iron-E** [moezbhatti/qksms#1015]
## Problem
If a text fails to deliver, it will prompt me to tap the text in order to retry sending it. However, when I tap to retry, it doesn't update the UI to let me know that it is retrying, or that my tap has been registered.

## Version info 
QKSMS 3.0.5, LineageOS 14.1

**Comment by moezbhatti** [comment]
What _does_ happen when you tap it?

**Comment by ajzett** [comment]
It doesn't actually do anything. It might just be on my side. I'll test it again.
