### ISSUE TITLE
[Question] Why were all the features removed?

### ISSUE THREAD

**Issue by soaringowl2145** [moezbhatti/qksms#1016]
So I see in the new 3.0 versions that all the features have been taken out and now must be paid for.  Will ALL of the old features be added back for at least qksms+ users? 

Also I see there is a new version on F-Droid but not yet available on G Play.  Is the F-Droid version still a beta?

**Comment by MyNameIsCosmo** [comment]
QKSMS 3.0 is a complete rewrite to focus on stability. Check out the other open issues and the GitHub Project Tracker on this repo for planned futures.

If you would like to see a feature from 2.7.3 in 3.0, feel free to fork the repo, work on it, and submit a pull request.

A lot of work has gone into 3.0, and it is still in beta, so there will be features added and changed. QKSMS+ is to help Moez stay fueled in order for him to continue providing support and adding features into the app, as well as support the work he has done already.

**Comment by moezbhatti** [comment]
As for your second question, F-Droid is actually one version behind the Google Play version. I'll fix that today. In the future they should remain in parity
