### ISSUE TITLE
QK compose missing?

### ISSUE THREAD

**Issue by kilroythe5th** [moezbhatti/qksms#1017]
after I updated QKSMS, the QK Compose feature disappeared. is there any way to bring it back?

**Comment by moezbhatti** [comment]
It's been removed from the app, as it was hardly used in the previous version. My apologies if this was an important feature for you.

If there are a lot of people requesting to bring it back, I'm certainly open to doing that in the future

**Comment by kilroythe5th** [comment]
was it difficult to maintain? It was a super convenient feature for me.

**Comment by moezbhatti** [comment]
Not difficult to maintain, but the new version of the app was built from scratch, so it would have required rebuilding the feature as well
