### ISSUE TITLE
Color configurable everywhere

### ISSUE THREAD

**Issue by halxinate** [moezbhatti/qksms#1019]
Themes are good but to please anyone I would consider color selector tool for at least text and background of balloons with the distinction of incoming and outgoing.

**Comment by moezbhatti** [comment]
I appreciate the suggestion - but unfortunately, this isn't something that most people will ever touch. For that reason, I won't be including it, as I want to be more diligent this time in making sure that the app doesn't get too cluttered.

**Comment by halxinate** [comment]
Clutter means bad organisation. I'd rather think of a better organized
settings menu. In my app I have 241 user settings organized in 18 screens
on 3 levels of hierarchy. Everybody happy.
