### ISSUE TITLE
BUG! All is white.

### ISSUE THREAD

**Issue by halxinate** [moezbhatti/qksms#1021]
Using the black theme. After the yesterday update all the icons and backgrounds are white with white text on them. Can't use the app. Themes are also white. All internal icons are white disks except for the FAB. Want to reinstall but there is no database backup.

**Comment by halxinate** [comment]
Reinstalled the app. Everything is again white on white. In night mode - white blobs on black with white/invisible text. You broke it badly man. I'm on Note 3 with Lollipop (5.0). The prior version was working perfectly fine.

**Comment by halxinate** [comment]
Tried reverting to 3.0.4 and 3.0.3 apk - same thing. But what's weird is that after the installation old messages I sent are visible, but not the replies (though I can copy the content of the invisible message using the context menu and paste it into the reply field and see the original text of that invisible message in the editText box.

New messages are invisible as well.

In the night mode, all text is white on white balloon.

The stock android Messages shows the conversation perfectly fine.

**Comment by halxinate** [comment]
3.0.3 just crashed after simply scrolling the conversation.

**Comment by moezbhatti** [comment]
Fixed in 6f9811176db8960390e8e1540d8e0b64a5bec593
