### ISSUE TITLE
Feature: Hide Message in Notification Previews

### ISSUE THREAD

**Issue by realmain** [moezbhatti/qksms#1026]
Please implement an option to hide the message content in notification previews, both on the lockscreen & when pulling down from the status bar. Only show the Name (if contact name is available) or number of the sender.

**Comment by moezbhatti** [comment]
This was removed since the feature is natively supported in Android (it wasn't when I originally built it)

Is the native support not sufficient? (genuine question - this isn't a feature I actively use)

**Comment by realmain** [comment]
Currently on Oreo, to hide messages on your phone on the lockscreen, you go to **Settings** -> **Security & Privacy** -> **Lock screen preferences** -> **On the lock screen** -> **Hide sensitive notification content**. One of the issues is that people have to hunt for this setting. Another issue is that it hides ALL notifications with "sensitive content". Some people want to only hide messages from specific apps, or the phone setting hides more info than they want. This is what it looks like when you get a text with that on:

![1](https://i.imgur.com/Enn2oIW.png)

It does not show the sender's name, so you don't know if you should check the message now or not.

It should look something like:

----

**Dan Ellis**
*New private message*

----

This is actually the first SMS app I've seen that does not have this setting.

**Comment by moezbhatti** [comment]
Thanks for the detailed response, this explains it very well!

I'll be adding this back into the app.

**Comment by realmain** [comment]
Forgot to mention, the system setting only hides the message contents from the lockscreen. It does not hide when you pull down.

Most apps such as FB messenger or [Silence SMS](https://github.com/SilenceIM/Silence) hides it in both locations. I'd prefer this way personally, for privacy sake.

**Comment by moezbhatti** [comment]
Added for 3.0.8
