### ISSUE TITLE
Impossible to delete characters when composing new sms

### ISSUE THREAD

**Issue by FrancoisMz** [moezbhatti/qksms#1028]
Qksms 3.0.5 from F-droid.
Tested on 2 models (Samsung Galaxy S6 Android 7.0 and bq Aquaris M5 Android 7.1.2).

1. Click on "+" button to create a new conversation
2. start typing characters in the search field at the top of the screen
3. try to delete these characters with the "back" button of the virtual keyboard --> nothing happens, the cursor is stuck in its place

Confirmed with both ASK keyboard (any language) and Samsung keyboard.

Did not exist on qksms 2.7.3

**Comment by FrancoisMz** [comment]
Yes, it happens regardless of the character type (letters, figures, special, capital or not).

If I select a first contact via the list and type additional characters in the search field to search for a second contact, the same phenomenon happens (the manually typed characters cant be deleted).

Note that this doesn't happen in the general search field of the welcome page, only on the contact page after pressing the "+" button.

**Comment by moezbhatti** [comment]
If you select a contact and then press backspace before typing any more characters, does it delete the contact?

**Comment by MyNameIsCosmo** [comment]
This happens to me, too.
It seems to happen when I type in a contact, then hit space.
If I don't hit space, I can delete the characters typed. If I hit space, it won't let me delete.

I can delete contacts when typed, and it does not seem to occur when contacts are selected.

**Comment by FrancoisMz** [comment]
Good  point: if I select 1 or several contacts then press backspace before typing any more characters, I can delete the contacts.
As soon as a character has been typed, backstage is deactivated.

**Comment by moezbhatti** [comment]
Reported by another user via email, using lenovo zuk z2, custom android 8.1 oreo Jaguar rom
