### ISSUE TITLE
Does not allow "generic search" for contacts or words containing UTF characters

### ISSUE THREAD

**Issue by FrancoisMz** [moezbhatti/qksms#1029]
I try to explain what I call "generic search" (I don't know how to name it).

When searching for contacts or words either in the welcome screen or in the "new conversation" screen (after pressing "+" button), when typing standard ascii characters, I would expect that the search result will also include the same characters with diacritics:
- when typing c, I would also expect to see ç included
- same thing with e which should include é, ê, ę, etc
- a --> à, ą
- l --> ł
- r -->  ř
and so on (and my list of correspondences above is not exhaustive).

Instead, it is necessary to type the exact characters with diacritics, otherwise the contacts / words are not found.

Observed on Qksms 3.0.5.
Not sure that Qksms 2.7.3 was behaving the same.

**Comment by FrancoisMz** [comment]
After verification, I confirm it was behaving "correctly" (at least, as I expect) in 2.7.3.
It applies whatever the position of the UTF letter in the contact name.

**Comment by moezbhatti** [comment]
Fixed in 4d368af1cd21fec7b65b36fe3dd21eaaca183975
