### ISSUE TITLE
Request: Disable avatars

### ISSUE THREAD

**Issue by Bill-Stewart** [moezbhatti/qksms#1030]
I don't like the contact images. I can read, after all. <grin>

**Comment by moezbhatti** [comment]
Appreciate the feedback - but this setting was almost never used in 2.7.3, so I've made the decision to leave it out (as is standard with nearly all messaging apps). If it becomes a common request then I'm open to reconsidering, but I'm going to close this issue for now.

**Comment by Bill-Stewart** [comment]
Bummer! Out of curiosity, how do you know it was almost never used in 2.7.3?

**Comment by MyNameIsCosmo** [comment]
I disabled avatars in 2.7.3, however I haven't had any quarrels with 3.0's avatars - all mine are just contact initials.

**Comment by telebiker** [comment]
> as is standard with nearly all messaging apps

What are "not all" message apps with ability to disable them? qksms was unique to offer this feature!

**Comment by moezbhatti** [comment]
Totally understand what you mean, and I may add this some day, but as it stands I want to make sure the QKSMS settings doesn't get cluttered with too many options - so I need to optimize for things that will be more useful to a larger number of people

**Comment by telebiker** [comment]
If the only problem is the limit of options in the settings, how about having "advanced settings" where geek only or minority settings will be stored?

Another solution might be sort of easter egg or special combination to access this feature (like developer menu in Android). Thus, those who don't need this won't even know it.
