### ISSUE TITLE
Show "Draft" for convo in Main Page

### ISSUE THREAD

**Issue by realmain** [moezbhatti/qksms#1033]
I don't know if this is a bug or a needed enhancement, but it'd be nice if there is a written message to send to someone but haven't been sent yet, it should say ***Draft*** in a different color (darker?) & italicized on the convo on the main page.

----

**Dan Ellis**
*Draft*

or

**Dan Ellis**
*Draft:*

----

Currently on **v3.0.5**

**Comment by moezbhatti** [comment]
As a part of this, it could be useful to sort the inbox to show these conversations first, to help you know that you've got an unfinished message

**Comment by moezbhatti** [comment]
Don't remember when exactly this was added, but this is supported as of the current version of the app (3.7.10)!
