### ISSUE TITLE
Submenu in Settings

### ISSUE THREAD

**Issue by realmain** [moezbhatti/qksms#1038]
Suggestions to make settings menu look cleaner as more settings are added. Not in any particular order.

----

**Default SMS app**

**SMS & MMS**
-> Delivery confirmations
-> Strip accents
-> Don't send message as MMS (#779)
-> Auto-retrieve MMS (#550)
-> Roaming auto-retrieve MMS (#550)
-> Max MMS attachment size
-> Blocking
-> Sync messages

**Appearance**
-> Theme
-> Night Mode
-> Font size

**Notifications**
-> QK Reply
-> LED color (#1035)
-> Vibration pattern (#388)
-> Notification display (#1026)
-> Notification reminders (#774)
-> System settings

**Comment by moezbhatti** [comment]
Really appreciate this - the settings screen is already due for a cleanup, and I was planning to do it soon :)

**Comment by moezbhatti** [comment]
Notifications moved to a sub-screen in 0027dfd8e08d5ee10702fed620dbfd2526d5b288
