### ISSUE TITLE
Picture date & time

### ISSUE THREAD

**Issue by realmain** [moezbhatti/qksms#1040]
When in an image, under the contact name (or phone number if not a contact), have it say the date and time. Time should be dependant if system settings are in 24-hr format or 12-hr format... maybe file size somewhere?

----

<- **Dan Ellis**
04/13/18 17:36

<- **Dan Ellis**
04/13/18 05:36 PM

Or

<- **Dan Ellis**
Fri 04/13/18 17:36

<- **Dan Ellis**
Fri 04/13/18 05:36 PM

**Comment by moezbhatti** [comment]
Looks like this was added some time ago!
