### ISSUE TITLE
Wake screen setting

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1048]

**Comment by alekksander** [comment]
any timeline? :)

**Comment by moezbhatti** [comment]
Unfortunately not yet! I need to buy a test phone that doesn't have this built-it. I'm currently unable to test this because I only have a Pixel and it's screen wakes up for notifications independent of the app

**Comment by alekksander** [comment]
isn't this configurable in system settings? i also have „naked” android (8.1) and the setting is there. to explain the reason why i want this in qk – is to have screen light up only on messages from certain contacts.

**Comment by moezbhatti** [comment]
Hmmm good point, I'll give that a shot

**Comment by alekksander** [comment]
Thanks!
