### ISSUE TITLE
Feature request: granular customization

### ISSUE THREAD

**Issue by J-Reis** [moezbhatti/qksms#1049]
# Additional appearance customization … 
### conversation window
+ set custom image as background
dialogue bubbles:
+ pick unique colors for outgoing & incoming
+ transparency
+ show avatars adjacent
### Contact list
+ set custom image as background

**Comment by realmain** [comment]
These should be posted as separate issues, not all in one.

Also, you can already pick unique colors for incoming messages for the conversation window.

**Comment by J-Reis** [comment]
Right, I had made a list of issues that caused me to move on from QKSMS some months ago. I don't use QKSMS presently, so my notes may reference an older version. I recommended QKSMS to a friend on the basis of it being an open source project and thus had occasion to look at the Google Play listing again. When I noticed that the description there suggested sharing any "feature suggestions" via github, I thought I'd try to be helpful and do so … and so I have. My recollection was that I could only choose a color for outgoing messages in the conversation view. With the option to color incoming messages to match outgoing or to remain the default color of the theme.

**Comment by realmain** [comment]
> had occasion to look at the Google Play listing again. 

Just an fyi, the play store version is out of date. v3.0.0 was rewritten (from scratch?). See #1055 

> My recollection was that I could only choose a color for outgoing messages in the conversation view. With the option to color incoming messages to match outgoing or to remain the default color of the theme.

Currently, you can change the theme in the conversation view, and the theme of the incoming message & send button. I don't see an option to change the color of outgoing messages.

> * transparency
> * show avatars adjacent

Can you please give more detail on what you mean here?

**Comment by moezbhatti** [comment]
I'm afraid all of these suggestions are a bit more than I'd like to allow in terms of visual customization. (aside from `show avatars adjacent`, I'm not quite sure what that means)

I'm certainly open to adding options for more visual customization, but I am simultaneously trying to curate them so that the app will always have a very clean aesthetic

**Comment by J-Reis** [comment]
Hopefully the screen caps below from ChompSMS & Handcent Next will clarify. The user pictures (avatars) are displayed next to the message bubble and said bubbles have a subtle transparency. I like the way it looks & I can achieve it with other apps but not this one.

I'm not sure I understand why the desire for a "clean aesthetic" should effect the ability of a user to customize. Surely the "aesthetic" on which the app would be judged refers only to the default settings. If a given user chooses to clutter things up … the ability to do so makes said user happy and effects the next user not at all!

<img src="https://user-images.githubusercontent.com/23666144/39010910-9dbaed48-43d5-11e8-9931-fafd3137e03c.jpg" width="300">
<img src="https://user-images.githubusercontent.com/23666144/39010904-99afc8c2-43d5-11e8-9178-d0210e6bf203.jpg" width="300">

**Comment by moezbhatti** [comment]
Thanks for clarifying

Well, if you'd like to use an SMS app which allows you to customize it to that level, then there are plenty of those available :) This is not what QKSMS is trying to achieve, however, and I intend to stick with my decision here. I'm sorry for an inconvenience.
