### ISSUE TITLE
Multi selection in search results

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#105]
https://www.reddit.com/r/Android/comments/3h7kqr/dev_qksms_is_now_completely_free_and_open_source/cu5hlz6?context=3

**Comment by ahattat** [comment]
I totally want this too :-)

**Comment by Samcfuchs** [comment]
Second

**Comment by moezbhatti** [comment]
This will be handled automatically, since search results no longer use a separate adapter
