### ISSUE TITLE
Google Error Message When I Try to "Donate" or Upgrade to "Lifetime Upgrade" - On F-driod Version. 

### ISSUE THREAD

**Issue by zinonweke** [moezbhatti/qksms#1056]
### DESCRIPTION
This issue is about a bug on your application, and its making you lose chances of being appreciated for your wonderful work. 

Your application is wonderful and very useful, but there is a problem with the version on F-driod. 

When i tried to make a donation or upgrade to "lifetime upgrade", i got a Google Error message, which completely hindered me from making the donation, and upgrading.  

I discovered that a [similar issue](https://github.com/moezbhatti/qksms/issues/363) was raised 2 years ago, but was later closed. I assume that it was closed because the issue had been resolved. But, i'm bringing it to your notice that the error still occurs on F-driod version. 

I tried out the version on Google Play, and its working very fine, and i got no error message. 

Please Note The Following:
1. The version on Google Play Store is still on 2.7.3 after the update.
2. F-driod can't use Google in-app billing. 
3. Please dump the version in Google Play Store and place some alternative for F-driod version. 

### STEPS
1. Download QKSMS from [F-droid](https://f-droid.org/en/packages/com.moez.QKSMS/)
2. Launch the application
3. Click on menu on the top left of the application
4. Go to "QKSMS+"
5. Click on "donate+unlock", a google error message comes up.
6. Click on "life time upgrade", a google error message also comes up. 

### EXPECTED
I expect that clicking on "donate" or "life time upgrade" will bring up a means of payment to support the developer for his great work or upgrade to a higher level.

### OBSERVATIONS
Clicking on "Donate" and/or "life time upgrade" brings up a google error message.

https://youtu.be/jTZFCKA4c6A

----
This bug report can also be found on [utopian-io](https://utopian.io/utopian-io/@zinonweke/error-message-when-trying-to-donate-to-the-developer)

**Comment by moezbhatti** [comment]
Thank you for the detailed report! I've addressed this in 3.0.7 :)

For versions published to F-Droid from now on, QKSMS+ will be unlocked for free, and there is just an option to donate via Paypal
