### ISSUE TITLE
Alternative option to unlock full verison & future design question

### ISSUE THREAD

**Issue by GrPK** [moezbhatti/qksms#1057]
Hello! I don't know if the version from 2 days ago *dated from 2016* was a preview or a real version used before, but that was what Im hoping to see in the next version! It was the ideal messaging app.
Moreover, I want to know if it is possible to introduce an alternative option to unlock + edition, like paypal alternative? Also, the price could be lower, because there will be no more 30% taken by Google. Thanks!

**Comment by childnode** [comment]
dup of #1056

**Comment by moezbhatti** [comment]
That was the old version of the app - 3.0.x is the new one :)

And if you'd like to download the app from F-Droid instead, the app is totally free there (once the 3.0.7 update goes live)

**Comment by sm4rk0** [comment]
@moezbhatti, you rock! Thanks!
