### ISSUE TITLE
Lost support for Android below ver. 5.0

### ISSUE THREAD

**Issue by ikocevski** [moezbhatti/qksms#1060]
Is it possible to get the app to support at least 4.4 KitKat?

**Comment by moezbhatti** [comment]
I am currently not planning on supporting anything below 5.0, as the app is using a lot of APIs that were introduced in Lollipop (primarily MMS compatibility), and the amount of work required to make it backward-compatible would just be unfeasible for me

If this changes in the future I'll let you know
