### ISSUE TITLE
Strected conversation box

### ISSUE THREAD

**Issue by Jrdnkasparek** [moezbhatti/qksms#1061]
Happens every so often when I send a message. It either happens to the message I sent or the one before that
![screenshot_20180418-112243](https://user-images.githubusercontent.com/20908630/38945302-c602790e-42fb-11e8-9841-bcd771103f2b.png)

**Comment by realmain** [comment]
Happens to me all the time. And it only happens to the sender's message.

**Comment by moezbhatti** [comment]
Missed this - this issue was fixed in 3.0.9 :)
