### ISSUE TITLE
Put phone number under contact name

### ISSUE THREAD

**Issue by realmain** [moezbhatti/qksms#1062]
In a convo, if the contact is added to phone, it should show the phone number under contact name in a lighter shade font color and smaller font size..

Helps when you have a contact with multiple phone numbers ie work, personal, home.

I don't know how hard it'd be to also show something like Mobile, Home, Work to the right of the phone number too, based on how you put them into your contacts.

**Comment by moezbhatti** [comment]
Duplicate of #439
