### ISSUE TITLE
SMS and emojis

### ISSUE THREAD

**Issue by cocoruby79** [moezbhatti/qksms#1065]
### DESCRIPTION
Can't add emojis to SMS

### STEPS
1. Open conversation
2. Type a message
3. Nom emojis icon on the launched keyboard

### EXPECTED
While typing a message, the opened keyboard should have an emojis icon to add emojis to text

### OBSERVATIONS
Hi,

I am using QKSMS for a while now and migrated to 3.0.X through F-droid last week.
Since the upgrade I can't find how to add emojis to SMS. The keyboard launched for typing does not have the icon for emojis as it had before.

I open an issue but I am afraid it could be a misuse from me...

I am using QKSMS 3.0.6 through F-Droid on LineageOS 15.1 on Oneplus 3T.

Regards.

**Comment by moezbhatti** [comment]
Could you share a screenshot of the keyboard open inside the app?

**Comment by cocoruby79** [comment]
Hi,
Here is the attached capture.

Regards.
![screenshot_qksms_20180419-093002 1](https://user-images.githubusercontent.com/38519576/38977895-01ab58bc-43b6-11e8-9e86-b270daaf85fe.png)

**Comment by realmain** [comment]
@cocoruby79 press & hold enter button shows the emojis

**Comment by cocoruby79** [comment]
Oh ! Yes ! So strange...
It works, thank you !

**Comment by zawyer1** [comment]
Some Android keyboards actually show a little emoji icon beneath the arrow, to indicate that you can hold the send button to open up the emoji menu. Apparently your keyboard doesn't have the emoji picture.

**Comment by realmain** [comment]
> Should I close the issue ?

Yes, I believe so. I don't think it's a bug from QKSMS, it's just a keyboard thing.

**Comment by moezbhatti** [comment]
Are you using the Google keyboard?

**Comment by cocoruby79** [comment]
I am using the default lineageos 15.1 keyboard.

**Comment by realmain** [comment]
AOSP Keyboard

----

AOSP Messaging

https://i.imgur.com/kUIZ66R.jpg

Has emoji icon

----

QKSMS

https://i.imgur.com/JgAGD7t.jpg

Has an enter icon (which I prefer because I use enter to make a new line a lot in text, you just have to hold it for a sec to pop up emojis)

**Comment by cocoruby79** [comment]
Yes, I understand better.
I personaly have no preference :-)

Regards.

**Comment by moezbhatti** [comment]
Ah, yes this is intentional :) If it becomes a common request to show the emoji button instead, then I may add a setting for this.
