### ISSUE TITLE
[Q] Possibility to change the status bar color ?

### ISSUE THREAD

**Issue by xerta555** [moezbhatti/qksms#1066]
### DESCRIPTION
Hello, I upgraded the application to 3.0.7 on my phone, I was at the screen in version 2.7.3.
On the old version, it was possible to change both the color of the circles representing the different contacts as well as the color of the top space in contact with the status bar.

On this new version, it is apparently only possible to change the color of the circles representing the contacts.
Has the one to change the "top" color of the application been implemented or is it not yet available?

### EXPECTED
No option to change the status bar color

### OBSERVATIONS
There is no option to changing the "top" color of the app.

Thanks in advance.

**Comment by realmain** [comment]
Most of the app is white, so the status bar is automatically white too. Do we really need to be able to alter the status bar color? Won't that make it out of place?

**Comment by moezbhatti** [comment]
Currently I'm not planning on making the status bar / toolbar themeable beyond the night mode settings. The app tends to look cleaner this way, and this seems to be the direction that a lot of beautifully designed apps are going in (example: Airbnb, Twitter, Dropbox)

**Comment by moriel5** [comment]
I personally think that the app looks much better with the status bar colored, and I had always changed it back in the 2.x times.

About other apps moving to that, it is mostly because iOS apps look like that.
