### ISSUE TITLE
Unable to long-press conversation message that contains links

### ISSUE THREAD

**Issue by Bill-Stewart** [moezbhatti/qksms#1067]
### DESCRIPTION

I'm using 3.0.7. I have messages from the number 456 that are status messages from my carrier (T-Mobile). When I enter the conversation list from that number, I can't delete any of the individual messages in the conversation. Long-press on any the messages does nothing.

### STEPS

In conversation list from a number that is 3 digits long (not sure what the threshold is), long-press on one of the messages.

### EXPECTED

Expected behavior is to see the pop-up menu with "Copy text", "Forward", and "Delete options".

### OBSERVATIONS

Nothing happens.

**Comment by moezbhatti** [comment]
Can't seem to reproduce the issue on my own device. Would you be able to attach a screenshot of the conversation?

**Comment by Bill-Stewart** [comment]
Also reproduced with phone number 2954 (long-press on a message in the conversation, and nothing happens).

**Comment by moezbhatti** [comment]
What happens if you press and hold outside of the bubble? So, just to the side of it

**Comment by Bill-Stewart** [comment]
Yes - thank you - in that case the menu (Copy text, Forward, Delete) appears.

**Comment by moezbhatti** [comment]
Ah okay. So, the real correlation here is actually not based on the sender's address, rather that there is a link in the message. When there is something clickable in the message (a link or a photo), then it breaks the long-press

**Comment by Bill-Stewart** [comment]
That would seem not to be the whole story, because there is a message in that conversation without any links, and long-press does not work for that message.

**Comment by realmain** [comment]
>When there is something clickable in the message (a link or a photo), then it breaks the long-press

Nope, I tried it on a message with no link, and it still does not work.

BUT! I tried other text messages (incoming & outgoing) that has links in them, and it doesn't work if I long-press on them. I have to hold-press outside.

> What happens if you press and hold outside of the bubble? So, just to the side of it

It works doing this.

**Comment by moezbhatti** [comment]
Hmm, interesting. If the message does not contain any sensitive information (the one without the link), could you share the text of that here?

**Comment by realmain** [comment]
MetroPCS **611** #

![](https://i.imgur.com/5oaMr0J.jpg)
