### ISSUE TITLE
Widget Doesn't Load

### ISSUE THREAD

**Issue by zainh96** [moezbhatti/qksms#107]
After attaching the widget to the home screen, a "Problem loading widget" widget is added instead.

**Comment by Samcfuchs** [comment]
Couldn't repro. Do you have specs?

**Comment by zainh96** [comment]
Nexus 5, Android 5.1.1, QKSMS 2.0.1

**Comment by moezbhatti** [comment]
This should be resolved in QKSMS 3.0. More info here: https://plus.google.com/+MoezBhatti/posts/PZiikBCtiNc
