### ISSUE TITLE
[Q] Possibility to change the status bar color ? #2

### ISSUE THREAD

**Issue by xerta555** [moezbhatti/qksms#1071]
### DESCRIPTION
Continuation of [my first question](https://github.com/moezbhatti/qksms/issues/1066), and given that you closed the thread of discussion that i had opened without leaving me just 2 or 3 hours the time that i can answer it and if necessary to bring there the first reason of my question, i thus opened this second "Issue".

So here's the rest:
At this moment there as much not to put any option concerning the color of the photos of the contacts, to modify the size of font of the text and to finish by withdrawing this application to the great potential of github...
If your first wish is to have a just primary application, a simple clone of other applications whose developers don't even want to hear the word customization then you might as well switch three-quarters of the options to the paid version.

This astonishes me enormously because on the old versions it was possible to modify it, certainly there were not many possibilities related to the colors and the forms but the minimum was present then why not at least put back what is there to the new version ?

Ok you have include the "Night Mode", but let me just say that choosing between black or white, the choice immediately becomes very narrow to just two colors, compared to before where there were just two options in my memories touching the colors, which was not to be very complex to code :-/ ...

To me it's like shooting yourself in the foot, hence my questioning.

### EXPECTED
No option to change the status bar color

### OBSERVATIONS
There is no option to changing the "top" color of the app.

Thanks in advance.

**Comment by realmain** [comment]
> Continuation of my first question, and given that you closed the thread of discussion that i had opened without leaving me just 2 or 3 hours the time that i can answer it and if necessary to bring there the first reason of my question, i thus opened this second "Issue".

You can still reply to your first issue even though it's closed... and it can always be reopened... that's how GitHub works.

> At this moment there as much not to put any option concerning the color of the photos of the contacts,

I don't understand this... you want to change the color of a contact photo???

>  to modify the size of font of the text

#953

**Comment by xerta555** [comment]
> You can still reply to your first issue even though it's closed... and it will notify everyone who replied to that issue or who are watching this project... and it can always be reopened... that's how GitHub works.

Ok thanks for this information

> I don't understand this... you want to change the color of a contact photo???

Actually the only one option related to a theme option is "Theme", by picking a color this setting change the profile background color in the SMS/MMS conversations list and the background button action color.
I really find it a pity that the option that was initially present has not been put back in place under the pretext that the application must be as "clean" as possible...

And as i navigate through the requests and feature ideas that will be added i read that message backup and restore is under development while other applications like SMS Backup & Restore
are already doing this work very well and already has more installations on the Play Store than QKSMS...

**Comment by realmain** [comment]
> message backup and restore is under development while other applications like SMS Backup & Restore are already doing this work very well

@moezbhatti is the only dev here working on his own free time. If there are others who can help out and create pull requests, it'd help a lot.

> already has more installations on the Play Store than QKSMS...

There are a lot of SMS apps on the Play Store, compared to the amount of SMS backup apps (that work).  Also QKSMS was on hiatus for a long time because it was being rewritten, which is what v3.0.0 was.

QKSMS is more known in the FOSS community than the general. Most outside of the FOSS community seem to use Textra.

**Comment by xerta555** [comment]
> @moezbhatti is the only dev here working on his own free time. If there are others who can help out and create pull requests, it'd help a lot.

I understand, i will help as much as i can.

> There are a lot of SMS apps on the Play Store, compared to the amount of SMS backup apps (that work). Also QKSMS was on hiatus for a long time because it was being rewritten, which is what v3.0.0 was.

I better understand the fact that there has been some kind of "hole" in the Github schedule regarding updates now.

> QKSMS is more known in the FOSS community than the general. Most outside of the FOSS community seem to use Textra.

I'll test this application too, but I wouldn't lose sight of QKSMS.
