### ISSUE TITLE
Send button not working when trying to create new conversation

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1079]
Device info from users who reported this via email

- Sensa LTE (HWH715BL-Q) on Android 6.0
- Huawei Honor 8 on Android 7.0
- HTC Desire 530 on Android 6.0
- HTC 10 on Android 8.0
- Huawei P9+ on Android v. 6.0
- HTC One M9 on SDK 24 
- Huawei Honor 7X on SDK 24
- Motorola G4 Play on SDK 25
- HUAWEI Mate 9 on SDK 26
- HUAWEI Mate 10 Lite on SDK 24
- Huawei P20 Pro on SDK 27

**Comment by whyicantusemyemailasusername** [comment]
not sure if the same issue but looks similar:
Can't compose a message, send button just not working. Android 8, Honor 9 Lite. 2.7.x version works normally.

**Comment by moezbhatti** [comment]
In screenshots of this issue, it doesn't show the "This is the beginning of your conversation" text, implying that the conversation isn't able to be loaded. Could be an issue with getOrCreateThreadId
