### ISSUE TITLE
MMS not received by recipients

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1082]
Sending an MMS will appear in the app to have sent, but the recipients don't receive it. This seems to be more common with group messages

**Comment by moezbhatti** [comment]
https://www.reddit.com/r/Android/comments/8ekxiq/dev_qksms_is_back/dxy2zyv/

**Comment by ThatAdonis** [comment]
Throwing things out there, but does the carrier have anything tovdo with it? Starting to notice most people that report problems with sending MMS are with T-Mobile just like me. Not saying its the culprit, but just tryna throw stuff into getting the whole MMS issue solved. Maybe son settings?

**Comment by ThatAdonis** [comment]
Apn*

**Comment by JavaCafe01** [comment]
I have cricket and I am getting the same problem, pretty sure it's not the APN settings

**Comment by matthewfcarlson** [comment]
I've seen this on AT&T as well.

**Comment by IamEli84** [comment]
I'm having group messaging MMS issues now. Pictures seem to send just fine but no one receives my messages in any group chats. 

On v3.1.2

**Comment by JavaCafe01** [comment]
Does this have anything to do with the mms limit?
Not working and on v3.1.3

**Comment by JavaCafe01** [comment]
This might be a problem with klinker's android-smsmms

**Comment by matthewfcarlson** [comment]
I would agree with that. I've been experimenting with klinkers library and running into the same issue. Picture messages send but text ones do not.

**Comment by IamEli84** [comment]
So ironically I use Klinkers Pulse texting app as my backup app and I don't have issues with group messages or picture messages. I know Moez say's he's using Klinkers library so it's weird that Pulse works okay but QKSMS doesn't. Frustrating because I'd rather be using QKSMS right now....

**Comment by moezbhatti** [comment]
@JavaCafe01 I took a look at the changes made since I imported the library, and none of them seem like they would affect this

**Comment by JavaCafe01** [comment]
There are some issues posted on the androidsms-mms repo regarding mms, dating back to 2014. None of them have been answered or replied to.

**Comment by JavaCafe01** [comment]
Version: 3.2.0

So I started using qksms for the past weeks. I have a mms group chat that works, but my other group chats don't.

Details of this working groupchat:
* Three people including me
* We all have the same area code
* Two androids and one iphone

**Comment by bronsonelliott** [comment]
QKSMS 3.3.2

I've been trying to send a picture to two different recipients but they aren't receiving it.  I've tried compression of 300kb and 600kb but still not working.  We are all on AT&T.  Text shows it was sent and I don't receive any kind of fail message.

Switched to Textra and works from there.  So seems to be isolated to QKSMS. What can I check or what other information can I provide?

**Comment by bronsonelliott** [comment]
@moezbhatti - I am not a developer so please forgive the question.  Looking the in the AndroidManifest.xml at line https://github.com/moezbhatti/qksms/blob/5e76ba9e8fbb0b2e2cf4b3e822f703dd1d8196ad/presentation/src/main/AndroidManifest.xml#L105  I notice it states 'com.klinker.android.messaging' while all of the other lines state 'com.moez'.  It seems to be related to MMS messages so I wasn't sure if that might be a possible cause for the MMS problem we're experiencing.  That seems to be the only reference to 'com.klinker.android.messaging' so the code might be choking on that.

**Comment by moezbhatti** [comment]
@bronsonelliott this is likely not the cause. This class is set up for receiving, not sending MMS. The reason it uses the `com.klinker.android...` `taskAffinity` is because it's based on a class from the [android-smsmms](https://github.com/klinker41/android-smsmms) library, where none of the others are

**Comment by Jrdnkasparek** [comment]
I am using a Pixel 2 XL on Verizon and I sort of have this issue as well. When I sent a picture to my roommate he got it(also on Verizon) but when I sent it to my friend he did not receive it

**Comment by moezbhatti** [comment]
I can't believe how hard this was to find. But, I finally figured it out a fix, and it was incredibly stupid
