### ISSUE TITLE
Wrong contact color

### ISSUE THREAD

**Issue by maxsin** [moezbhatti/qksms#1084]
### DESCRIPTION
When having contacts in conversation that do not have an image assigned they are sharing the same background color (cyan)
Example: I have a conversation with S and a conversation with L. In QKSMS they both have cyan color when in Android Messages S is red and only L is cyan.

### STEPS
1. Have two conversations with people that do not have custom images assigned
2. Observe the color asignment

### EXPECTED
Conversation colors to be randomly assigned

### OBSERVATIONS
Is this a feature not supported in the FREE version of the app?
QKSMS version 3.0.9

![clipboard01](https://user-images.githubusercontent.com/24450778/39234904-330df0d8-487d-11e8-8ddd-a613332bb50b.jpg)

![clipboard02](https://user-images.githubusercontent.com/24450778/39234903-32f1d8f8-487d-11e8-82a3-70849eec91c3.jpg)

**Comment by maxsin** [comment]
If it's a feature to have different colors per contact conversation maybe the avatar circle border can be loose.
Contacts having white background avatar will look better

**Comment by gkeegan** [comment]
Also, just saw that in #1071 that moezbhatti would like to keep the settings and theming as simple as possible.

**Comment by maxsin** [comment]
OK, thanks for the support.
