### ISSUE TITLE
No animation when tapping on a message to view the timestamp

### ISSUE THREAD

**Issue by Jatarii** [moezbhatti/qksms#1086]
Edit: in the privous ersion, there was an animation when tapping on a message. The animations is gone with the latest update (3.0.9)

**Comment by realmain** [comment]
You didn't provide any description at all for this. Are you saying that there is no animation or do you want animation?

**Comment by gkomarnicki** [comment]
This is actually a bug. I'll try to explain - when a user taps on a message, either sent or received, the timestamp abruptly appears below without any smooth animation. I've noticed this in the latest version (v3.0.9), but IIRC in earlier QKSMS v3.x versions, there was a smooth transition.

**Comment by moezbhatti** [comment]
Animations for the message view were removed to fix some glitchy UI with photo attachments. I'll need to come back and manually set them up for the specific views which should support animations, such as the timestamp
