### ISSUE TITLE
Contact photos get rescaled after being scrolled off-screen

### ISSUE THREAD

**Issue by timawesomeness** [moezbhatti/qksms#1093]
### DESCRIPTION
Some contact photos, after getting scrolled off-screen and back on-screen, are scaled improperly.

See the following image:

![Before and after scrolling](https://i.imgur.com/83tA4NH.png)

That entire page was scrolled completely off-screen and back on-screen.

The same images get rescaled each time. Group conversations never seem to have their images rescaled.

**Comment by realmain** [comment]
Please also provide device info, OS version, whether you are using a custom ROM, QKSMS version.

**Comment by moezbhatti** [comment]
I've seen this pop up a couple times, but I haven't been able to reliably reproduce it. I'll do some more testing
