### ISSUE TITLE
Lost all messages prior to update

### ISSUE THREAD

**Issue by mikefarr62** [moezbhatti/qksms#1094]
### DESCRIPTION
I hadnt really looked but I went to send my wife a text for the first time since the update and it says "This is the start of your conversation" and nothing is there. So I went into all my other contacts and its the same way. Now I go into another SMS/MMS app and its all there. QKSMS has no record of any messages prior to the upgrade.

### STEPS
1. Steps
2. to 
3. reproduce
4. the 
5. issue.

### EXPECTED
Describe the expected behaviour.

### OBSERVATIONS
Describe what happens instead of the expected behaviour.

**Comment by gkeegan** [comment]
Have you tried going into the app's settings and pressing "Sync Messages"?
