### ISSUE TITLE
 Remove setup request as the default SMS app at startup

### ISSUE THREAD

**Issue by RedMoonOTInetwork** [moezbhatti/qksms#1096]
Hi, Possibly if you could remove the initial message at startup that asks you to set the app as default for SMS messages every time, it's pretty annoying, thanks

**Comment by moezbhatti** [comment]
I agree with @realmain here.

This isn't a common enough use-case, and the fact that this screen shows up at startup will help prevent a lot of people running into issues where the app doesn't work correctly
