### ISSUE TITLE
Is this a feature of the app?

### ISSUE THREAD

**Issue by ikocevski** [moezbhatti/qksms#1097]
I got a message from my operator about missed calls but in that message just before the phone numbers were listed, there were the contact names written just as I've got them saved on my phone. Like this:

You got a missed call from *contact name phone number* 

So is this QK grabbing info of that number and putting it in the message for ease of use or is my operator somehow lurking in my contacts list?

**Comment by realmain** [comment]
It does not sound like it'd be a feature of QKSMS. It sounds like it might a feature of your phone to send an SMS to self for miss calls?

**Comment by moezbhatti** [comment]
Nope, this is a feature from your phone provider.

I doubt know the exact inner workings of it, but I doubt they're pulling the person's name from your contacts. They likely have their own database of caller IDs that they're using in order to identify the callers

**Comment by ikocevski** [comment]
1. The phone doesn't send a message to itself. No way, plus the number was clearly from my provider.

2. If it's not the app that adds the names then I'm positive they're lurking in my contact list because I've a specific way of naming them. But thanks for making this clear, I'll ask them next time I go to pay my bill.

**Comment by realmain** [comment]
Your question might be better asked in /r/androidquestions or /r/android on Resort Reddit
