### ISSUE TITLE
Possible Enhancement?: Rich notifications with copying alphanumeric codes

### ISSUE THREAD

**Issue by mbullington** [moezbhatti/qksms#1101]
Hello!

I recently switched from Facebook Messenger to QKSMS (for privacy concerns, I like the design of QKSMS, etc), however one feature of Facebook Messenger I haven't seen replicated elsewhere is pulling out phone numbers and two-factor auth codes, and allowing them to easily copy them in the notification.

Example notifications:

(000)-000-0000
Their number is (555)-555-5555
MARK READ | REPLY | COPY '(555)-555-5555'

00000
Your authentication code is 123456
MARK READ | REPLY | COPY '123456'

I feel that this could be easily implemented with the right regex, and wouldn't really raise any privacy concerns.

Thanks!

**Comment by realmain** [comment]
> wouldn't really raise any privacy concerns.

All apps have access to the clipboard, which is a privacy & security concern, unless using a special keyboard with it's own clipboard.

> two-factor auth codes

#881

**Comment by moezbhatti** [comment]
Merging with #881
