### ISSUE TITLE
Need advice on how to make my own theme

### ISSUE THREAD

**Issue by JunkyardCat** [moezbhatti/qksms#1102]
### DESCRIPTION
I was wondering if theres a easy way to change the UI like modifying the look of the send button, the place where we type our text, the bubble text, remove icons.

if not can anyone guide me on where i should modify the code to achieve this?

### STEPS
N/A

### EXPECTED
N/A

### OBSERVATIONS
N/A

**Comment by moezbhatti** [comment]
The screen you're looking to modify is `ComposeActivity`

I'm going to close this issue as it is not related to the public release of QKSMS
