### ISSUE TITLE
Mark conversation read/unread

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1112]
This existed in 2.7.3 and was very useful!

**Comment by fresheneesz** [comment]
I can't believe this was removed.. wtf.

**Comment by moezbhatti** [comment]
@fresheneesz it wasn't intentionally _removed_. QKSMS 3.0 was written from scratch, and as an oversight, I didn't think to build this again. Things fall through the cracks, I'm only human!

**Comment by fresheneesz** [comment]
Ah, gotcha. I feel like the lack of mark-unread in stock messengers is why people suck at texting so much.

**Comment by mikeblazanin** [comment]
Also looking forward to having this feature back hopefully soon!

**Comment by justiceo** [comment]
I do not see the option to mark messages as unread. Running version 3.5.4 on Pixel 2

**Comment by moezbhatti** [comment]
@justiceo long-press a conversation and then the option will reveal itself in the menu in the top right
