### ISSUE TITLE
Picture Sending issue with built in Camera Button

### ISSUE THREAD

**Issue by IamEli84** [moezbhatti/qksms#1115]
### DESCRIPTION
When sending a picture it will not go through when using the built in camera button. I can add/send okay when I select a picture from my gallery.

I am on AT&T and have my max mms attachment size set to 600kb
I am using V3.1.0 QKSMS app

### STEPS
1. Hit Plus sign next to text entry box
2. Select Camera
3. Take Picture
4. Press Send
5. Recipients do not receive picture

### EXPECTED
That the picture will send when using the built in camera button/mode

### OBSERVATIONS
Picture does not send.

**Comment by moezbhatti** [comment]
Does the app say that the image was sent successfully?

**Comment by IamEli84** [comment]
Yes it does, it will send and I'll ask recipients for confirmation in a separate txt. They won't get a pic that's sent with the camera button but will when selected from the gallery. 
On another note, I think it's just 'hanging' when sending, because people are now saying they're getting my pics twice. At least anyone that I tried sending both ways with.

**Comment by IamEli84** [comment]
Moez, this issue appears to be fixed with the v3.1.1 revision....I'll keep you posted. Thanks for the hard work!

**Comment by moezbhatti** [comment]
Thanks for the clarification! It seems like this issue varies depending on who you send the message to. If it pops up again, feel free to share any additional info in #1082
