### ISSUE TITLE
Delayed Messaging - Options

### ISSUE THREAD

**Issue by realmain** [moezbhatti/qksms#1119]
Instead of just putting **Short**, **Medium**, **Long**, it should say the amount of seconds.

**Comment by sm4rk0** [comment]
...or add **Custom**, so a user can enter a number of seconds.
I understand current approach. It's much simpler from both, the developer and the user perspective, but there are people (like me) who like to fine tune and fully control the things around them. At least add a way to "test" the delay period when selecting it. It could be triggered with tap and hold and a progress circle (like the one when sending the message) could demonstrate the delay.
Welcome back "Delayed sending"!

**Comment by eji30** [comment]
Follow up.

**Comment by ghost** [comment]
Closing this as it was changed to amount of seconds a while back
