### ISSUE TITLE
Set color per contact

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1120]
Currently, you can only set a color for the entire conversation. You should be able to set the color for each contacts - this is particularly important in group chats

**Comment by moezbhatti** [comment]
So - I only really have one thing blocking me on this. Let's say everyone in a group chat is assigned a custom colour, what colour do I pick for the phone icon and attachment button?

**Comment by GeoZac** [comment]
Fallback to app accent color,maybe?

**Comment by moezbhatti** [comment]
Hmm, yeah that could work.

While the phone icon doesn't need to be there, the attachments button definitely does. I was also planning on adding a popup in the future that allowed you to select who you wanted to call if you click the call button in a group chat
