### ISSUE TITLE
Prioritize delivered time instead of sent time for message timestamp

### ISSUE THREAD

**Issue by zawyer1** [moezbhatti/qksms#1121]
If you send a message but it fails to deliver, and you successfully retry sending the message a couple of minutes later, the "Delivered" message will show the time when the message was originally attempted to be sent, instead of the actual time it was delivered.

Additionally, when you successfully deliver a previously failed message, the notification for "A message failed to deliver" will still remain in the notification bar (and the notification light will blink) until you manually clear it. I'm still not sure what happens if you tap the notification after having already sent the message successfully (presumably it won't send another identical message, but just open the app?).

**Comment by Flexmaen** [comment]
If you enable delivery confirmations, the delivery time from the confirmation could be used also.
