### ISSUE TITLE
Notification Setting not saved when Sound set to none

### ISSUE THREAD

**Issue by vhoen** [moezbhatti/qksms#1124]
### DESCRIPTION
Whenever I try to set notification sound to none, it's not taken into account. Previous settings is kept.

### STEPS
Settings (General) -> Notifications
Tap "Sound", then select "None", press "OK"
Back on the notifications settings screen, Sound is still the one from before.

### EXPECTED
Sound should be set to none.

**Comment by moezbhatti** [comment]
Which version of QKSMS and Android are you running?

**Comment by moezbhatti** [comment]
How about Android version?

**Comment by vhoen** [comment]
My mistake, didn't think about that. I am using android version 6.0.1.

**Comment by vhoen** [comment]
Thanks for the fix in v3.2.2
