### ISSUE TITLE
MMS text contents not displayed on Nokia devices

### ISSUE THREAD

**Issue by m4mmon** [moezbhatti/qksms#1125]
### DESCRIPTION
When displaying some conversations, some messages appear empty, or only a picture is shown.

### STEPS
Phone is Nokia 7 plus (TA-1046) with Android 8.1.
Messages are the result of an import from SMS backup & restore.
Install qksms from F-Droid, launch it, make it the default application (does not seem to change anything), wait for sync to finish.
Enter affected conversation, some messages are incorrectly displayed (empty if text only, or image only if there is text and image). Screenshots in observations section.
Clean application cache and data, restart the synchronization, result is the same.

Stock SMS application (google messenger) displays those same conversations correctly.

### EXPECTED
qksms should display the content I can see in google messenger.

### OBSERVATIONS
Some conversations contain messages that appear empty, or with a picture only. These messages are correctly displayed in google messenger.
A defect observed on a message will be present every time I open the conversation, and messages correctly displayed will be correctly displayed every time.
If I select a "broken" message and copy its text (which I know exist somewhere since I can see it in other apps), clipboard remains empty.

If that helps, I tried other messaging applications, the following give OK results when I inspect random and affected conversations: Textra, chompSMS, Handcent.
Pulse has the same behaviour as qksms on the same messages. May be it uses the same API / techniques to get message contents and display it?

Example 1, single message with no picture in conversation:

qksms
![ex1_qksms](https://user-images.githubusercontent.com/14895736/39708213-18cc331e-5206-11e8-92d6-95322caf23af.png)

messenger
![ex1_messenger](https://user-images.githubusercontent.com/14895736/39708211-18828480-5206-11e8-9f73-68259d05304c.png)

pulse
![ex1_pulse](https://user-images.githubusercontent.com/14895736/39708212-18abda74-5206-11e8-9627-b9a5747607b6.png)

textra
![ex1_textra](https://user-images.githubusercontent.com/14895736/39708214-190b9374-5206-11e8-9932-e14706f78441.png)

Example 2, message with text and picture (the first picture came with some text, visible in messenger and textra screenshots):

qksms
![ex2_qksms](https://user-images.githubusercontent.com/14895736/39708217-19933680-5206-11e8-8a4c-9f58fbe6de96.png)

messenger
![ex2_messenger](https://user-images.githubusercontent.com/14895736/39708215-193c5d60-5206-11e8-8ae3-c44faf2b7df9.png)

pulse
![ex2_pulse](https://user-images.githubusercontent.com/14895736/39708216-19626c9e-5206-11e8-9417-6a8df36e1219.png)

textra
![ex2_textra](https://user-images.githubusercontent.com/14895736/39708218-19b69936-5206-11e8-9b8d-92bd12fb9d71.png)

I tried to export affected single conversations with SMS Backup & Restore and to import them in 8.1 emulator, but it is working fine.
On real phone, deleting affected conversations, cleaning caches, rebooting, reimporting, synching etc. did not change anything.

**Comment by moezbhatti** [comment]
Thank you so much for the detailed bug report!

Would you be comfortable sending me the export from one of the affected conversations? I can take a look at the metadata and see if there's anything different about it versus other messages that display properly. The conversation with Tim is the one I'm particularly interested in. You can send it to moez@qklabs.com

**Comment by moezbhatti** [comment]
@m4mmon bump :)

**Comment by m4mmon** [comment]
Sorry last time I sent some of the requested data to the wrong mail address, you should have it now.

**Comment by moezbhatti** [comment]
@m4mmon it's possible that, as you mentioned in your email, this issue may be device specific. I tested this on both of my test devices with the conversation you sent, and QKSMS seems to display it correctly on both.

The other possibility is that this was fixed accidentally - can you try syncing messages with the latest version of QKSMS and see if you're still seeing the issue?

**Comment by moezbhatti** [comment]
@m4mmon just an update, I had a user email me and they're experiencing the same issue. They are also using a Nokia phone, so it appears that the issue is in fact related to the device

I'll see if I can get a test device to use and get this figured out

**Comment by m4mmon** [comment]
Just saw your last posts. Tried to sync messages anyway, no luck.
This is somehow good news knowing there is at least someone else facing this issue, with a common denominator.

**Comment by var314** [comment]
Hi, firstly, thanks for the great app. Secondly, I am also experiencing the same problem. I do not see a text in a message with picture and text. Also I do not see a message sent to two numbers. Both are visible in stock messages app. Interestingly, QKSMS indicates the later as an mms, while the stock app contains following info: this conversation is a mass sms now, each receipient will receive an sms from you, the responses will show in separate conversations. This is not an exact text, I translated it from my language.

My phone is Nokia 8, TA-1004, Android 8.1, so different model but again Nokia.

**Comment by moezbhatti** [comment]
Apparently, this works fine in Silence: https://github.com/SilenceIM/Silence

Worth looking into, to see how they're loading the message info

**Comment by prg318** [comment]
I'm glad to see an existing issue exists for this (I missed it on my perusal).  I am more than happy to perform any debugging or troubleshooting steps on my device to help resolve this issue.

Cheers

**Comment by jdg2011** [comment]
I'm using a Nokia 6 (TA-1025) on Android 9 and having the same problem.

**Comment by patoski** [comment]
Nokia 7.1 (TA-1085) Android 9 (Pie) with the same issue.

**Comment by m4mmon** [comment]
Hi,
After my device was upgraded to Android 10 a few days ago, I have issues regarding contact search when creating messages with Messages and Textra apps.
So I tried qksms to see if it also exhibited the same behavior (it does not), but I also checked the MMS that were not correctly displayed back then and now it looks good :)
I am switching to qksms as my messaging app, and will report back in a few days/weeks if the issue appears again or not.

If the other affected users could also try?

**Comment by var314** [comment]
Hi,
I used other app for sending images, so I didn't notice. I just checked and can confirm everything is displayed correctly. My device is still on Android 9.

24 sty 2020 06:07:00 m4mmon <notifications@github.com>:

**Comment by jtmullen** [comment]
I just downloaded QKSMS after not using it for a long while due to this bug when I got a Nokia. Images seem to appear just fine now on my Nokia 6.1 running Android 9. Perhaps this has been accidentally fixed

**Comment by jdg2011** [comment]
Thanks jtmullen, I checked it out on my Nokia 6 running Android 9, and MMS shows up great!

**Comment by m4mmon** [comment]
after several days of using qksms, I can confirm it is working fine for me.
