### ISSUE TITLE
Double tapping space removes the last letter of the word and then adds the period and space.

### ISSUE THREAD

**Issue by Jaukain** [moezbhatti/qksms#1127]
### DESCRIPTION
After the latest update (3.1.2) and using the SwiftKey app, when you double tap space to add a period, it will delete the last letter of the word and add the period and space.

### STEPS
Every time you double tap space.

### EXAMPLE
If I type "Hello" and double tap space it will result in "Hell. "

I am using SwiftKey to reproduce this issue which only occurs while using QKSMS. If I switch to the LG Keyboard the double tap space doesn't add a space after the period at all. 

QKSMS Version: 3.1.2
Device: LG V30+
OS: 7.1.2 Android

**Comment by moezbhatti** [comment]
Fixed in https://github.com/moezbhatti/qksms/commit/dc4663ee14a8227154c8ba3d9e95158e9411e384
