### ISSUE TITLE
GIF compression support

### ISSUE THREAD

**Issue by Jrdnkasparek** [moezbhatti/qksms#1128]
Pixel 2 XL

Trying to send a gif and it just keeps saying failed to send, tap to try again

**Comment by JPDVM2014** [comment]
I'm having the same problem with pictures and gifs.

**Comment by moezbhatti** [comment]
Currently only regular photos support compression, which means that GIFs exceeding the max attachment size from your carrier will fail to send

**Comment by moezbhatti** [comment]
That's because those apps support GIF compression :)

**Comment by moezbhatti** [comment]
For reference: https://stackoverflow.com/questions/9392227/resizing-animated-gif-while-keeping-its-animation-using-java
