### ISSUE TITLE
Almost all messages show up twice -- major bug

### ISSUE THREAD

**Issue by zawyer1** [moezbhatti/qksms#1131]
Started using 3.1.3, and for some reason almost all messages show up twice. I jumped from 3.0.9 to 3.1.3 so it could have happened anywhere between those updates. Anyone else experiencing this? I attached some screenshots; if you are able to see any sort of pattern or reason for this, it's beyond me. And just to be clear: the messages are only displayed twice, they are not sent twice. Using Android Nougat 7.0.

![screenshot_2018-05-08-21-59-17-1947213799](https://user-images.githubusercontent.com/37254938/39781064-6a4eb5c8-530e-11e8-99d8-5111232998c8.png)
![2](https://user-images.githubusercontent.com/37254938/39781081-7444c8a6-530e-11e8-9e27-27e6504ce9d3.png)
![1](https://user-images.githubusercontent.com/37254938/39781093-7a84231a-530e-11e8-8a0c-076869518b77.png)
![3](https://user-images.githubusercontent.com/37254938/39781097-7d0adb60-530e-11e8-8935-a3f9537b71a4.png)

**Comment by realmain** [comment]
This happened to me once in an upgrade. Clearing the cache fixed it for me.

But it'd be nice to find the root of this bug.

**Comment by zawyer1** [comment]
Let me try that.

**Comment by zawyer1** [comment]
Clearing the cache did not fix the issue, but re-syncing the native Android SMS database from the settings fixed the issue.

It definitely has to do with updates. Almost like it re-syncs messages when you install a new version but doesn't replace the old, or something.

**Comment by moezbhatti** [comment]
This should be fixed with the new syncing strategy implemented in 11167aff5b90d5ef51561f82c05faa35777a2100
