### ISSUE TITLE
Group Names 

### ISSUE THREAD

**Issue by IamEli84** [moezbhatti/qksms#1132]
Feature Request: for group messaging make it possible to assign a conversation name to the group message. So in the conversation list it's one custom name instead of all the contacts names.

**Comment by realmain** [comment]
Duplicate of #45

**Comment by IamEli84** [comment]
Ahh I see that's been requested before a couple times, thanks for pointing that out. Moez you can close this one as I see you're tracking the other requests already.

thanks

**Comment by sm4rk0** [comment]
@IamEli84 you can close it, too.

**Comment by IamEli84** [comment]
Ahh I see that as well, thanks for the help guys I appreciate it....I'm new to github so still learning.
