### ISSUE TITLE
Clarify max MMS size setting

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1139]
A lot of users email explaining that MMS doesn't work, and it's generally because they set the "Max MMS attachment size" to "No limit". This is likely because it isn't extremely clear what this feature does (compress images down to that size, because it's the max size supported by the carrier).

**Comment by otede** [comment]
Is this supposed to be a clarification?
"(compress images down to >>>that<<< size, because it's >>>the max size<<< supported by the carrier)."
What size?
