### ISSUE TITLE
Improvement: Pressing the heads-up message will show the conversation without opening the app

### ISSUE THREAD

**Issue by GrPK** [moezbhatti/qksms#1142]
I saw this feature on some messages app and I really like. You can see the whole conversation with that person without having to open the app, because it opens a window from where you can type.

**Comment by moezbhatti** [comment]
If you have QK Reply enabled, then you can press the reply button to obtain this exact behaviour :)

**Comment by moezbhatti** [comment]
Response from other thread

>I was saying that the app won't auto-show the conversation, but by pressing the heads-up. Textra has something very similar, by using it you can understand what I am referring to. Also, the app should not close after sending a message, having to dismiss it by taping somewhere else on the screen

**Comment by moezbhatti** [comment]
Hmm, I understand what you're asking. I just don't think there's enough of a need here to add another setting to the app, at least for now.

The conversation history is displayed in the notification. You can reply by clicking the reply action. You can view the entire conversation by clicking on the notification, where you can reply as many times as you want without the conversation closing. All of the needs here already seem to be satisfied
