### ISSUE TITLE
Improvement: Pressing the heads-up message will show the conversation without opening the app (Again)

### ISSUE THREAD

**Issue by GrPK** [moezbhatti/qksms#1144]
I was saying that the app won't auto-show the conversation, but by pressing the heads-up. Textra has something very similar, by using it you can understand what I am referring to. Also, the app should not close after sending a message, having to dismiss it by taping somewhere else on the screen

**Comment by moezbhatti** [comment]
Hey @GrPK, just an FYI, you can comment on a thread that has been closed. That way, there's more context in the conversation, and we're not opening new issues unnecessarily. I'm going to close this to continue the discussion in #1142
