### ISSUE TITLE
[Suggestion] Create a dedicated QKSMS+ app

### ISSUE THREAD

**Issue by ajzett** [moezbhatti/qksms#1147]
I'd love to purchase QKSMS+, but in-app purchases aren't shared with family members. A dedicated QKSMS+ app would allow this.

**Comment by realmain** [comment]
In app purchases are usually meant per user, not for all.

Alternatively, you can get the full app from F-Droid and send the dev a donation.

**Comment by moezbhatti** [comment]
As mentioned by @realmain, you can download the app from F-Droid where all of the features are unlocked free
