### ISSUE TITLE
Settings - Notifications crashes app

### ISSUE THREAD

**Issue by SeriousTube** [moezbhatti/qksms#1151]
Clicking Settings then Notifications crashes QKSMS. It says "Unfortunately QKSMS has stopped.".  This is with version 3.2.0 from the Android Play Store.

**Comment by moezbhatti** [comment]
What phone and Android version are you using?

**Comment by SeriousTube** [comment]
Blu R1+ and android version 6.0.

**Comment by SeriousTube** [comment]
Version 3.2.2 just auto downloaded. The crashing issue seems to have gone away.
