### ISSUE TITLE
Suggestion for the to do list you made.

### ISSUE THREAD

**Issue by soaringowl2145** [moezbhatti/qksms#1154]
Can you please indicate which things in your to do list will require qksms+? Perhaps mark them with a tag this way we can let people know if their request will require plus or not.

I am referring to the place that says done, to do, backlog, up next, ect.

Thank you!

**Comment by moezbhatti** [comment]
Nearly all of the things on the list will not require QKSMS+.

If you'd like to see an up-to-date list of the upcoming features which will require the upgrade, you can check out the QKSMS+ screen inside of the app :)
