### ISSUE TITLE
Typing contacts in new message screen

### ISSUE THREAD

**Issue by JavaCafe01** [moezbhatti/qksms#1155]
### DESCRIPTION
When I select a contact after I type in the name or part of the name, the search bar keeps the text I typed. For example, If I type `Joh` and select the contact `John`, it gives me the contact `John` and the partial name I typed, `Joh`.

### STEPS
1. Click plus button to create new message thread
2. Type the first few letters of a contact
3. Select the contact

### EXPECTED
The bar should only contain the contact box, not the text you type.

**Comment by jugaltheshah** [comment]
I have this issue also. Additionally, there doesn't seem to be a way to actually type a message after selecting a contact, not sure if OP experienced that as well.
