### ISSUE TITLE
False matches displayed when filtering contacts with cyrillic letters

### ISSUE THREAD

**Issue by rend3r** [moezbhatti/qksms#1156]
Nubia NX569J (unofficial LOS14.1)
QKSMS 3.2.0 (F-Droid)

### STEPS
1) Create new message:
<img width="540" alt="step1" src="https://user-images.githubusercontent.com/12601181/40386409-575688ce-5e12-11e8-9b89-e62f574ff14f.png">
2) Filter contacts with cyrillic letters -> no filter is applied (Алексей in example):
<img width="540" alt="step2" src="https://user-images.githubusercontent.com/12601181/40386416-5974817e-5e12-11e8-93d7-4375eaa894f8.png">
Maybe all non-latin letters are affected not cyrillic only.

### EXPECTED
Contacts containing "Алексей" string should be present only.

Exported VCARD contains:
CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=D0=98=D0=B2=D0=B0=D0=BD=D0=BE=D0=B2;=D0=95=D0=B2=D0=B3=D0=B5=D0=BD=D0=B8=D0=B9
Dunno, but it may be helpful info.

**Comment by bungabunga** [comment]
same here! xperia XZ, android 8.0, app same version.
