### ISSUE TITLE
Attach contact card

### ISSUE THREAD

**Issue by jugaltheshah** [moezbhatti/qksms#1157]
Feature suggestion:
It seems like I cannot attach a contact with within the app (no option to do so, as there is with a picture) or via sharing from the Contacts app (no option to share with QkSMS). Would it be a lot of work to implement atleast the latter or is it just a matter of broadening the intent filter?

**Comment by moezbhatti** [comment]
It's something I certainly plan to add support for!

Related: #763

**Comment by moezbhatti** [comment]
Added in 14b2d2ef8b8ac5dec2848ca48a6f60183e1a5c0f
