### ISSUE TITLE
Add "Solar Hijri calendar" format option for messages timestamp.

### ISSUE THREAD

**Issue by runo280** [moezbhatti/qksms#1159]
### DESCRIPTION
I want to try add "Solar Hijri calendar" format as an option for messages timestamp, if I could, will you merge my PR? 😊

**Comment by moezbhatti** [comment]
Hey @runo280, sorry for the late response! I appreciate you asking about this before submitting a pull request

As this is something that won't affect the vast majority of QKSMS users, I don't believe it should exist as an option in the app. You're welcome to develop it in your own version, however!
