### ISSUE TITLE
Customize notification actions

### ISSUE THREAD

**Issue by LeonCame** [moezbhatti/qksms#1160]
It is possible to disable / hide, the interaction band in the notifications ?

DESCRIPTION
When receiving a new message, the notification system works well but, unlike other applications, an "ugly interaction white background band", (in my case)) is added below. See screenshots here:
[problem.jpg](https://partage.p-h.click/public/forum/gh/qksms/problem.jpg)

EXPECTED
NO white band, (or band with transparency black color, or customable).
[expected.jpg](https://partage.p-h.click/public/forum/gh/qksms/expected.jpg)

### OBSERVATIONS
There should not be a white band. This band should be switched off or customizable.

Thank you all, for this great project and all of your efforts!

**Comment by moezbhatti** [comment]
QKSMS will attempt to use the theme color (for the app or that conversation, if one is set), but it can't guarantee which color will be used. Ultimately it's decided by your phone, so there isn't much I can do with the colors

I do plan on making the actions customizable however (including the ability to remove them entirely), and I don't have an issue open for that yet, so I'll repurpose this one :)
