### ISSUE TITLE
Messages syncing forever?

### ISSUE THREAD

**Issue by waterlubber** [moezbhatti/qksms#1162]
I'm having an issue with using this on Android 8.0 Oreo. When I start up the app, it offers the permissions and such to grant/set as default (which I accept) and then it begins "Syncing Messages." It gets stuck here, though, and doesn't progress--even after several minutes. If it makes any difference, I'm on a Moto Z Play, unrooted, recently updated to Oreo, and also have a Substratum theme activated. The issue occurs on a fresh installation of the app (clear data + uninstall + reinstall) from F-Droid.

A thing of note: I had the app set up and configured in the past, many versions ago, but left it for a while as MMS didn't really work for me. I'm trying to give it another go.

Steps to Reproduce:
1. Clear data and reinstall the app.
2. Open app, grant permissions, watch as "Syncing messages" appears
3. Enjoy the heat death of the universe

Expected Result:
Messages would sync, preferably with a progress bar of some sort, and then everything would work with absolutely no bugs.

Actual Result:
Stuck on "Syncing messages" at the main menu.

Here's some more info:
Version: 3.2.0 (F-Droid_
Device: motorola XT1635-02 (Moto Z Play, US)
SDK: 26 (?)
Carrier: T-Mobile

**Comment by waterlubber** [comment]
Well, after leaving the app in the background it turns out the heat death of the Universe was closer than I expected. It would be great to have a progress bar/"this might take a while" message, though. Sorry to bother you.

**Comment by moezbhatti** [comment]
In the future I'd definitely like to show an actual progressbar. Glad it ended up working for you in the meantime!
