### ISSUE TITLE
BUG: 2 different conversations for 1 contact: 1 with sms and 1 for the mms

### ISSUE THREAD

**Issue by Jatarii** [moezbhatti/qksms#1165]
See title.

**Comment by moezbhatti** [comment]
If you send an SMS in the MMS conversation, which one does it show up in?

**Comment by Jatarii** [comment]
I don't send MMS because it costs to much. It's when I receive them. But there is a difference in the number:
The SMS show up with the number: 04...
The MMS show up with the number: 324...
