### ISSUE TITLE
Notification when image has been received but not downloaded

### ISSUE THREAD

**Issue by megaminxwin** [moezbhatti/qksms#1168]
### DESCRIPTION
When I'm not on data, occasionally someone will send me an image via MMS. Not being on data, I obviously can't see it, but I'm not notified that an image was even sent. In the default LG messaging app, I do get notified, so I know to turn on data and download it.

### STEPS
1. Disable mobile data
2. Be sent an image via MMS

### EXPECTED
A placeholder message tells you there is an image you can download.

### OBSERVATIONS
I never know that I've been sent an image, unless they ask about it.

**Comment by moezbhatti** [comment]
This will be implemented as part of #389

**Comment by OhSoGood** [comment]
@moezbhatti Any idea when this will be implemented? Without this, QKSMS is unusable for me and I would be so sad to have to return to Lineageos default sms app...

**Comment by moezbhatti** [comment]
Not sure - to be honest, it's not a high priority at the moment
