### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by eehpcm** [moezbhatti/qksms#1173]
### DESCRIPTION
QKSMS crashes on startup.  First reported by Daniel Reardon on Google Communities, [here](https://plus.google.com/+DanielReardon95/posts/fZ6y8Ab9ud3), confirmed by at least one other.

Around that time other Google Communities posters were reporting issues with posts not being seen by all users, which is why there may have been no response.

### STEPS
1 Fire up QKSMS

### EXPECTED
QKSMS starts and works normally.

### OBSERVATIONS
A blank window opens, then vanishes.  A system message appears "Unfortunately, QKSMS has stopped."  I've used the "Send feedback" option on the system message twice.  I have no idea if it goes to the developer or Google or is silently discarded, but there are no signs it is being dealt with.

Android 7.1.2, QKSMS 3,2,2 (from App info, not from the app itself, because the app doesn't start).

**Comment by moezbhatti** [comment]
Hmm, this should have been fixed as a result of https://github.com/moezbhatti/qksms/issues/1143 and released in v3.2.0. I wasn't aware of another startup crash

Would it be possible for you to get a logcat of the crash?

**Comment by moezbhatti** [comment]
As for the send feedback option - I'm not sure where these reports actually go. The best way to report an issue and make sure that it gets addressed is by posting here on Github

**Comment by eehpcm** [comment]
Attached logcat.  Well, it would be attached if this thing had a way of attaching files.  I'll send it to your gmail account.

The system garbage goes on a lot longer, but I don't think any of it is relevant to QKSMS.

**Comment by moezbhatti** [comment]
@eehpcm ah, this should be fixed if you go into the system settings and clear data for the app. This happened because of the difference in the ways that QKSMS handled database migrations before and after the 3.0 release. Moving forward, this issue won't be popping up again

**Comment by eehpcm** [comment]
OK, that fixed it.  Thanks.
