### ISSUE TITLE
[REQUEST]Random/Custom Color Themes on Maim Page

### ISSUE THREAD

**Issue by Secrius** [moezbhatti/qksms#1175]
DESCRIPTION
Is it possible to add a randomized color theme to the main page of qksms like Android messages? It makes finding specific conversations much easier and would add more customization and color to the landing page.

**Comment by moezbhatti** [comment]
I'm not a fan of this personally, I think that it makes the app look messy, and makes the theme selection feel less significant. Going to close this for now
