### ISSUE TITLE
Navigation bar icons invisible with the light theme

### ISSUE THREAD

**Issue by gkomarnicki** [moezbhatti/qksms#1176]
### DESCRIPTION
When using the light theme, the navigation bar icons on my Huawei Nova 2i (Mate 10 Lite) running 8.0 Oreo become invisible. I've switched back to the default EMUI Explorer theme and uninstalled Navbar Apps, thinking one of them was the cause of the bug. Still the same thing. No problem with the dark mode, however.

I'm using the latest v3.3.0, but I also noticed this on v3.2.2.

### STEPS
1. Open QKSMS
2. Disable dark mode (if it's on)

### EXPECTED
The nav bar icons should be visible at all times.

### OBSERVATIONS
The nav bar icons are invisible and the nav bar itself is black.

![screenshot_20180607-094218](https://user-images.githubusercontent.com/20436870/41074785-38945bf8-69f9-11e8-8a43-bdf2c34ca0ae.jpg)

**Comment by moezbhatti** [comment]
Another user has also reported this issue on a `SONY XPERIA XA1 ULTRA` running 8.0

**Comment by moezbhatti** [comment]
@gkomarnicki could you give thie APK a test and let me know if it solves the issue?

[presentation-withAnalytics-universal-release.apk.zip](https://github.com/moezbhatti/qksms/files/2082666/presentation-withAnalytics-universal-release.apk.zip)

**Comment by moezbhatti** [comment]
I was able to do some testing with the other user who reported it via email, and managed to figure out the root of the issue

**Comment by gkomarnicki** [comment]
@moezbhatti Still have the same issue with that APK.

**Comment by moezbhatti** [comment]
@gkomarnicki yeah, that APK didn't end up working. Here's the one that did

[QKSMS 2.apk.zip](https://github.com/moezbhatti/qksms/files/2082837/QKSMS.2.apk.zip)

**Comment by gkomarnicki** [comment]
@moezbhatti Working perfectly now. Thanks

**Comment by moezbhatti** [comment]
@jay1109 by default does your phone have a light nav bar or a dark one?

**Comment by jay1109** [comment]
A dark one

**Comment by moezbhatti** [comment]
Another user reported it still happening on a Huawei p20 lite running  8.0

**Comment by gkomarnicki** [comment]
I've got the same problem again on my Huawei Nova 2i. This is with the latest v.3.3.2, but the icons appeared ok with the QKSMS 2 apk

**Comment by KruziikG** [comment]
Same problem on my Huawei P9 Plus running Android 8.0 ,
![6cda5b3dgy1fsen38fijij20u01hcaen](https://user-images.githubusercontent.com/11470789/41509947-79bf6116-728e-11e8-9ac0-98d021795280.jpg)
