### ISSUE TITLE
Screen flashes white at startup when using night mode

### ISSUE THREAD

**Issue by spocko** [moezbhatti/qksms#1179]
### DESCRIPTION
Screen flashes white at startup when using night mode

### ENVIRONMENT
QKSMS 3.3.1
Samsung Note 4 with stock MM 6.0.1

### STEPS
1. Set Night mode to "always on"
2. Use back button to exit app
3. Open app again from launcher

### OBSERVATION
When the app first opens, a blank white screen is displayed briefly before the UI is rendered. This brief flash of white can be jarring if coming from a dark launcher screen (i.e. dark launcher screen --> full white initial screen --> dark night mode screen)

### EXPECTED
If night mode is enabled, the initial screen background should be dark or black.

**Comment by spocko** [comment]
My issue was addressed in version 3.4.3 by commit ea55af67f64168cc436ae978043a773b8a8610d7.

I am satisfied with this since I use night mode. It would be even better if this could be dynamic, i.e. if night mode is active, then default to dark theme, else default to light theme. Don't know if that is feasible with the "automatic" night mode setting. 

I think this initial screen is more noticeable in QKSMS than most other messengers because the app is a little slower to launch/render. I'll open a separate issue for that.

**Comment by moezbhatti** [comment]
Thanks, forgot to close this issue!

As far as I'm aware, it's not possible to dynamically change the initial screen that shows. It's shown before any code from the app is executed. The best solution is to minimize the startup time so that this screen goes away fast enough that it's not noticeable, as you suggested.
