### ISSUE TITLE
improve time options when receiving SMS

### ISSUE THREAD

**Issue by Flexmaen** [moezbhatti/qksms#1184]
QKSMS just shows the time, when the SMS was received on my phone.

Example:
Phone gets switched off (or loses reception) at 1:00 and will be on the network again at 9:00.
Someone sends a message at 2:00.
Phone will display 9:00, and there is no way to figure out when the message really was sent.

This is sometimes annoying e.g. if you are travelling and do not have full coverige all the time. Then you won't know if messages like "I'm there now" still are current or already old.

### STEPS
1. Switch off phone
2. Send a message from another phone to the phone number you switched off 
3. Wait for 5 minutes
4. Switch the phone on again.
5. For the message you'll only see the time when the phone was switched on, not the time when the message was sent.

### EXPECTED
It would be nice to have the option: "display sent/network time", or there is even enough space to display both times, if different.

**Comment by moezbhatti** [comment]
Going to merge this with #975
