### ISSUE TITLE
[Question] Is 3.3.x doesn't support android 5 ?

### ISSUE THREAD

**Issue by azzamsa** [moezbhatti/qksms#1188]
I can install and use version 3.2.x smoothly. But I can't install 3.3.x.

Is QKSMS stop supporting android 5 and older ?

**Comment by moezbhatti** [comment]
Fixed in 73887558fa93e0683de8a181c30e61408aec5a67

**Comment by azzamsa** [comment]
> Fixed in 7388755

Oh. Great thanks. I thought I have to buy a new phone. 
Here we get so many sms ads from provider, the default sms app can't block them. Thanks lot for QKSMS.
