### ISSUE TITLE
Problems with manually-entered numbers

### ISSUE THREAD

**Issue by eehpcm** [moezbhatti/qksms#1189]
### DESCRIPTION
Problem 1) Cannot input message after manually entering number.  This is a major issue.

Problem 2) If the number has been texted previously it's not listed in the suggestions.  This is a minor issue.

### STEPS
1. Enter a number manually rather than use an entry from contact list.
2. Suggestions from contact list are offered, but not numbers that have previously entered manually and texts successfully sent.
3. Press on enter (the ->| button)
4. Nothing happens.  It sits there sneering.  Does not open entry box for message.  Just waits for more numbers to be entered, because that's all it lets you do.

### EXPECTED
It ought to let me type the message after clicking enter (it still does if I use an entry from the contact list).  It ought to include previously-texted numbers, whose messages are still in the sent folder, in the suggestions: I don't want to add this number as a contact but I sent it a text previously and I want to send it a text again.

### OBSERVATIONS

QKSMS 3.3.2.  It allowed me to send to manually-entered numbers in 3.3.1.  I don't know if it previously suggested manually-entered numbers.

**Comment by gmplp** [comment]
Hi, I have a similar problem, but also with contacts in my contact list. 

In my case, when I add a message to an existing conversation, I can chose the Sim to be used, and the message is sent correctly. So everything works fine.

Instead, when I choose a contact from the contact list, I can write the message, but the "send" button does nothing, and I have not the choice of the sim.

(I have a Honor 6X, if this helps)

GP

**Comment by moezbhatti** [comment]
This should be fixed in the current version
