### ISSUE TITLE
Delete old messages automatically

### ISSUE THREAD

**Issue by ToNIX-** [moezbhatti/qksms#119]
Is there any way to implement a "conversation length limit" so old messages are deleted automatically?

An option to immediatly "trim all threads" when selected would also be a nice addition.

**Comment by xavihernandez** [comment]
Hi, thanks for having made QKSMS open source!
Would like to see this feature too as it is useful.

**Comment by woj-tek** [comment]
Just to chime in - would love to see it as well

**Comment by kevinbuffington** [comment]
+1  would be great

**Comment by homersimpsons** [comment]
Would love this one too :) Thank Your for your work ! +1
Make the difference beetween MMS and SMS, Don't delete unread message.

**Comment by xavihernandez** [comment]
Yep @homersimpsons even this feature must not delete locked SMS/MMS.

**Comment by homersimpsons** [comment]
@xavihernandez Yes in fact, but to my mind it's evident

**Comment by homersimpsons** [comment]
@moezbhatti would you consider implement this soon?

**Comment by moezbhatti** [comment]
@homersimpsons this will be in the next major update

**Comment by homersimpsons** [comment]
@moezbhatti Okay, thank you a lot

**Comment by woj-tek** [comment]
So I just got new version and (especially keeping in mind that large number of texts may slow down QKSMS)( having a time based purging may not be such a great idea - with some people you can have a couples of texts within a week and with others those can be thousands (literally!).

Any chances to add quantative option as well?

**Comment by homersimpsons** [comment]
Change option to list :
Disable
Time based
Number based

Maybe put this in a sub menu for clarity

**Comment by moezbhatti** [comment]
That's a good idea. This should definitely be changed

**Comment by homersimpsons** [comment]
2 others option could be :
- quantity AND time
- quantity OR time
But this could be more complex for end user, and certainly won't be used so much.

**Comment by woj-tek** [comment]
Or we could have two separate options:
- [ ] Delete messages older than x days
- [ ] Number of days

- [ ] Keep only x messages in conversation
- [ ] Number of messages


Then user can tick first and/or second option and then detailed configuration of days/quantity would be enabled.
There could be third option "Only when both conditions are met" which would translate to logical AND (as opposed to logical OR used by default in above scenario)

**Comment by homersimpsons** [comment]
I agree with you. 
With an apply button that pop up an alert to remind selection, and to tell how many SMS would be delete once applied.

**Comment by homersimpsons** [comment]
Amy news on this??

**Comment by xavihernandez** [comment]
Would be cool, as I'm not a fan of day based because my aim is to keep a little amount of messages by conversation. Time does not matter for me.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by andreyrd** [comment]
Seems the current versions of QKSMS don't have this?
