### ISSUE TITLE
QKSMS and kdeconnect

### ISSUE THREAD

**Issue by tsurrel** [moezbhatti/qksms#1194]
### DESCRIPTION
QKSMS and kdeconnect do not play well together. Kdeconnect is an Android application that can forward notifications to KDE on a Linux desktop, and get SMS replies from it.

### STEPS
1. Install kdeconnect on your phone and pair it with the kdeconnect KDE desktop app
2. A SMS is received, the notification is forwarded to the desktop
3. Reply to the SMS from the desktop
4. Open QKSMS

### EXPECTED
All messages, received and sent, should appear.

### OBSERVATIONS
The messages received and sent while connected to KDE do not appear, or are not all there ...

**Comment by gkeegan** [comment]
Try going into the QKSMS app settings and doing "sync with stock sms database" or whatever it's called. Report back with if the ones sent previously appear now.

**Comment by tsurrel** [comment]
It did bring some back, I'm not entirely sure they are all there, though.
I can not reproduce this behavior very often, I will come back with more details if I can pin how to trigger it.

**Comment by rominail** [comment]
I just have basics in Android programming but is an observer on sent sms not enough to retrieve the sms and add it to the app database
Code snippets found on stackoverflow (if it can help):
https://stackoverflow.com/questions/25244123/sent-sms-observer-has-double-the-output

**Comment by moezbhatti** [comment]
Thanks for sharing this, I believe you're right and that these are the same issue. Going to close this one and move the discussion there
