### ISSUE TITLE
Application not filtering contacts with names written in cyrillic. 

### ISSUE THREAD

**Issue by Sensetivity** [moezbhatti/qksms#1203]
### DESCRIPTION
Application not filtering contacts when they name written in cyrillic. 

### STEPS
1. Add contact with cyrillic in name. For example "Микола", "Ігор", "Ярослав". 
2. Open compose new message and try to filter typing "Мик" or some like that.

### EXPECTED
Show contacts what only contan "мик" 

### OBSERVATIONS
Showing all contacts.

**Comment by moezbhatti** [comment]
Fixed in 748fc05cc0361b7adcb93090a765ffb9aaa7ea74
