### ISSUE TITLE
Use swipe to refresh to sync messages

### ISSUE THREAD

**Issue by ImnIrdst** [moezbhatti/qksms#1204]
It's better to use [swipe to refresh](https://developer.android.com/training/swipe/) to sync messages, instead of an option in the setting menu.

**Comment by ImnIrdst** [comment]
I can code it myself if it seems interesting.

**Comment by moezbhatti** [comment]
I disagree. In most cases, the sync messages option should never have to be used. It's only used as a tool in case something goes wrong, so there's no reason to make it so accessible, where it might be triggered accidentally
