### ISSUE TITLE
Google Pixel 2: Cannot receive SMS messages

### ISSUE THREAD

**Issue by jcstaudt** [moezbhatti/qksms#1217]
### DESCRIPTION
**Phone**: Google Pixel 2
**OS**: Android 8.1.0
**QKSMS**: 3.3.3

I am able to send but not receive SMS messages through QKSMS.  Previously I could not receive them at all, but now the messages appear through Google Hangouts.  I tried setting QKSMS as my default messaging app and even uninstalled Google Hangouts, yet was unsuccessful to receive messages within QKSMS.

#### Test 1

1. Install F-Droid and open it
2. Install "QKSMS Messaging app" and open it
3. "Allow QKSMS to access your contacts?" Allow
4. "Allow QKSMS to send and view SMS messages?" Allow
5. "Use QKSMS instead of Hangouts as your SMS app?" Yes
6. Press "+" at the bottom-right of the screen
7. Select a contact and send a test message; send successful
8. Send an SMS message from another phone to the Pixel 2; SMS went to Hangouts instead

#### Test 2

9. Uninstall Google Hangouts
10. Send another SMS message to another phone
11. Send an SMS message from another phone to the Pixel 2; no message detected on Pixel 2
12. Check Hangouts account in a web browser; Hangouts had again received the message

### EXPECTED

Send SMS messages **and** receive SMS messages within QKSMS - indifferent about Hangouts.

### OBSERVATIONS

Send SMS messages **and NOT** receive SMS messages within QKSMS, but they only appear in Hangouts.

**Comment by moezbhatti** [comment]
Hey @jcstaudt, sorry I missed this! And thanks for all the detail - this is a great report.

Are you still experiencing this issue with the current version of the app?

**Comment by jcstaudt** [comment]
I recently updated to Android 9 and will conduct another test soon.

**Comment by jcstaudt** [comment]
**Phone**: Google Pixel 2
**OS**: Android 9
**QKSMS Version**: 3.4.4
**F-Droid Version**: 1.3

Repeated the test above with the same results.  Interestingly, though, several Google two-factor authentication codes were received during the time that QKSMS was installed but not active.  (QKSMS was still listed as the default SMS messaging app, even though Hangouts was the app that was delivering them.)

Whatever caused the Google two-factor authentication codes to be delivered seems to be the key here.  The confusing thing is that today I requested another authentication code and it did not appear in QKSMS, but was received in Hangouts.  Perhaps it was previously sent another way other than my browser..?  I use Firefox for everything.

Is anyone else having luck with QKSMS using a Google Pixel product?  I'm not aware of any installed software causing contention, but will provide a more detailed list of installed software if you believe this to be the issue.

**Comment by jcstaudt** [comment]
I can confirm that Google authenticator messages appear within QKSMS. Also, a small percentage of images (MMS?) make it through as well, but I haven't determined what makes these specific messages special. Outgoing SMS still work.

**Comment by jcstaudt** [comment]
Determined that this is not a bug at all! There's actually a setting that I missed in Hangouts which forces SMS/MMS to be directed to it despite **any** other app being set as the default messaging app. This was driving me crazy and wasted way too much time, but I'll cross-reference the fix here, so that someone else with the same issue may stumble across it:

> Go to Hangouts - Settings - click on your gmail Account at the bottom - uncheck Messages under Project Fi calls and SMS.

I found the solution on Reddit [here](https://www.reddit.com/r/GooglePixel/comments/8seuc4/sms_still_arriving_in_hangouts_despite_changing/).

**Comment by moezbhatti** [comment]
Thank you for following up, @jcstaudt! This solution will come in handy in case this ever comes up again for someone else
