### ISSUE TITLE
[Regression] Direct message broken

### ISSUE THREAD

**Issue by protist** [moezbhatti/qksms#1219]
### DESCRIPTION
Apex Launcher (and presumably other apps) have an option to set shortcuts on the home screen. One of these is "Direct message", which allows you to specify a contact when creating the shortcut. Touching this icon then directly opens a compose window for the previously-selected contact.

### STEPS
1. Set up a "Direct message" shortcut associated with a particular contact
2. Touch the shortcut

### EXPECTED
QKSMS should open up a compose window for the specified contact

### OBSERVATIONS
QKSMS instead opens up the contact search screen, with a text input at `Type a name or number`

### ADDITIONAL INFORMATION
This was working in previous versions of QKSMS, but is failing in the current version 3.3.3 (via F-Droid). I attempted to identify when the regression occurred, but F-Droid refused to install the previous 3.3.2, or 3.3.1.

I also tested changing the default SMS app to the default "Messaging" app on LineageOS instead. The "Direct message" shortcut works fine in this SMS app.

**Comment by moezbhatti** [comment]
Thanks for the detailed report! This was fixed in be25d0f4c43b082e37a0849a5541044c43f4336e and released in 3.3.4

I'll make sure 3.3.4 gets deployed on F-Droid in the next day or so
