### ISSUE TITLE
Option to have more horizontal bubble padding

### ISSUE THREAD

**Issue by gkomarnicki** [moezbhatti/qksms#1222]
It would be great if there was an option to increase the horizontal padding of large text bubbles. For me it feels kinda claustrophobic and busy having full-width bubbles. I'm using a Huawei Nova 2i (Mate 10 Lite) on LineageOS 15.1 with the font size set to default and display size set to small.

Maybe the right side of the bubbles of received messages could align with the right side of the compose box, like this:

![screenshot_qksms_20180627-110721-02](https://user-images.githubusercontent.com/20436870/41951787-187c73d2-79bc-11e8-9189-89d5303fa17f.jpg)

**Comment by moezbhatti** [comment]
Appreciate the suggestion, but when I previously set the bubbles to this max width, I had tons of emails where people complained about the app unnecessarily deciding to show less content.

You're the first to make this suggestion, so I think that at least at the moment, there aren't enough people who'd want this to warrant adding a setting for it

**Comment by gkomarnicki** [comment]
@moezbhatti No problem! Usually the only long text messages I get are from my carriers and I rarely read them anyway.
