### ISSUE TITLE
Strange overlay in quick reply window

### ISSUE THREAD

**Issue by spocko** [moezbhatti/qksms#1226]
QKSMS 3.3.4 on Android 6.

See attached image. Note the gray box in the lower left that is covering up the conversation. It looks like the compose box is drawn in the wrong size/location. I don't know how to reproduce this. I just captured a screenshot when it happened.

![photo_2018-06-29_19-47-41](https://user-images.githubusercontent.com/10623243/42120748-4bee144e-7bd5-11e8-91d8-b8af70cf854e.jpg)

**Comment by moezbhatti** [comment]
Fixed in ad202a2f64524a94e872efddcccc635bec01a3ca
