### ISSUE TITLE
Message detail does not displaying.

### ISSUE THREAD

**Issue by TalhaBinAfzal** [moezbhatti/qksms#1227]
### DESCRIPTION
Hi am making change in our app, In presentation.main .java I created a new package and adds an activiy in it. After adding activity app doesnot shows sms detial screen. 
Can you tell me why this is happening?

**Comment by moezbhatti** [comment]
Marking as irrelevant - the purpose of these issues is to support users of the QKSMS app, not to help other people develop their apps.

I clicked on your profile and noticed that you don't have a public fork of the app. Please make sure that your source is publicly available and that you are not in violation of the QKSMS license.
