### ISSUE TITLE
Notification Channels improvements

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1238]
For phones that support Notification Channels, the notification customization is pretty unintuitive. You need to click Settings -> Notifications -> Notifications to access them, and it's not obvious 

It looks like this

<img width="506" alt="screen shot 2018-07-02 at 12 52 11 pm" src="https://user-images.githubusercontent.com/4358785/42176395-c66da7de-7df6-11e8-9371-9579c462f767.png">

A simple way to improve this would be to add a summary to that option, saying something like "Tap to customize"

A better solution would be to display views which represent all of the various customization options of the channel (vibration, ringtone, etc), and when the user clicks on one, they'll be redirected to the channel settings

**Comment by gkomarnicki** [comment]
Either option sounds good, though for me the first one is intuitive enough. Number two seems redundant, but it may be helpful for those who aren't familiar with Oreo's notification channels.
