### ISSUE TITLE
New Logo  Proposal

### ISSUE THREAD

**Issue by moenawar85** [moezbhatti/qksms#1242]
Hello Sir... I would like to contribute with your project by created a new logo. I'm waiting for your response and answer, If you like it I will send the original file that editable in CDR / PDF and PNG also. If you have any suggestion with color or something else I will fix it.
![qk-sms logo](https://user-images.githubusercontent.com/36834147/42215402-86845e7c-7ee8-11e8-8dea-83a147051654.jpg)

![qk-sms logo_concept](https://user-images.githubusercontent.com/36834147/42215425-96840926-7ee8-11e8-8095-f0077c12207c.jpg)

Best regards, Moenawar.
Thank you indeed.

My contacts :
email : monox.rhtm@gmail.com
discord : moenawar#1364
steemit : @moenawar

**Comment by moezbhatti** [comment]
I appreciate the work you've done! However, as I've mentioned in previous icon proposals, I'm not currently looking for a new icon to use with the project. Thanks
