### ISSUE TITLE
Move About info out of Settings

### ISSUE THREAD

**Issue by spocko** [moezbhatti/qksms#1247]
Currently the About info is buried in the Settings menu at the bottom. This is not a "setting", because there is nothing that the user can change. I suggest that it be moved to the bottom of the hamburger menu.

**Comment by moezbhatti** [comment]
Hmm, I agree with you that it's strange to put it in settings when it's not a setting. I don't think that this is something that the average user will care to look at often enough that it deserves to take up space in the hamburger menu. The current setup is also consistent with the Android system, where you can find info about your device at the bottom of the "Settings"

Going to leave this as-is for now
