### ISSUE TITLE
F-Droid builds 3.3.4+ manually disabled 

### ISSUE THREAD

**Issue by ToadtoadGD** [moezbhatti/qksms#1249]
As shown on the build wiki, the builds were disabled. They now have a full Google Play release, so why can't we get the F-Droid builds? https://i.imgur.com/a/WSRdRpm

**Comment by moezbhatti** [comment]
Will be fixed once the stable release of gradle build tools 3.2 is available

**Comment by ToadtoadGD** [comment]
Alright, thanks!

**Comment by moezbhatti** [comment]
Hmm, looks like it magically started working as of the two most recent updates!
