### ISSUE TITLE
Arabic characters clipped in message view

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1251]
Arabic characters at the `start` side of the message bubble seem to be clipping early, resulting in part of the message not being visible.

I suspect the culprit to be `TightTextView`

**Comment by EgyptianM** [comment]
I can confirm it still persists if we used system fonts.

**Comment by schapira** [comment]
why it closed? is it fixed? I wait just for that fix to reuse the application

**Comment by moezbhatti** [comment]
yep, it's fixed

**Comment by schapira** [comment]
well I am using Hebrew and it shown better but still cutting the first letters

**Comment by moezbhatti** [comment]
@schapira can you give me some sample text to test with?

**Comment by yarons** [comment]
There you go:
![Screenshot_2019-03-12-16-28-37-425_com moez QKSMS](https://user-images.githubusercontent.com/406826/54208377-7b195200-44e4-11e9-848d-d1c2690c2a90.png)

It starts with פך מדיני, but it should actually start with מהפך מדיני.
I'll also add Arabic transliteration for reference:
Appears as پخ مديني
Instead of مهپخ مديني

Same goes to all the following lines after.

**Comment by moezbhatti** [comment]
@yarons can you please copy and paste the original text onto github? I'd like to test it with this exact same text on my own device

And can you confirm which version of the app you're using?

**Comment by yarons** [comment]
@moezbhatti 
This is the full message:
מהפך מדיני, מהפך חברתי, מהפך בהפרדת הדת מהמדינה. אין מהפך בלי מרצ צפו בקמפיין החדש http://bit.ly/MRZvideo לתמיכה השיבו 1 להסרה השיבו 0

With line breaks as displayed in the app:
מהפך מדיני, מהפך חברתי, מהפך
 בהפרדת הדת מהמדינה. אין מהפך בלי
 מרצ צפו בקמפיין החדש http://bit.ly
/MRZvideo לתמיכה השיבו 1 להסרה
השיבו 0

My version:
![Screenshot_2019-03-12-17-17-14-463_com moez QKSMS](https://user-images.githubusercontent.com/406826/54212536-c71bc500-44eb-11e9-8adb-26aa4e8a4193.png)

Thanks!

**Comment by moezbhatti** [comment]
Hey @yarons, sorry for all the confusion. I just realized that while I did indeed fix the issue, I hadn't released the fix yet. And so this is why you're still experiencing the issue in 3.6.3

I just tested using your text and I can confirm that the issue has been resolved, and will be pushed out in 3.6.4, hopefully later this week :)
