### ISSUE TITLE
No Lock Screen Notification on Moto X

### ISSUE THREAD

**Issue by delaing** [moezbhatti/qksms#1258]
### DESCRIPTION
There is no notification on Lock Screen when text message received.
Phone is Moto X 2nd gen with Android 5.1 OS

### EXPECTED
I installed QKSMS to try this out as a recommended replacement for stock Messaging app and changed none of the phone or app settings, yet there is no Lock Screen notification.

### OBSERVATIONS
#757 shows that this was resolved in v3.0 update.
If I switch back to using Messaging, the Lock Screen notifications work as usual.

What am I not understanding? 

Thanks in advance,
Delain

**Comment by delaing** [comment]
Any response or action taken on this? Even with latest update, still not receiving lock screen notifications.

Thank you,
Delain

**Comment by moezbhatti** [comment]
Sorry for the late response here. Is this still happening? If so, are you referring to the system notifications or the QK Reply window?

Since it's been so long I'll just close this, but if you respond I'll open it up again and throw it on the to-do list :)
