### ISSUE TITLE
Proposal to create a Privacy Policy document and also compilation of FAQs.

### ISSUE THREAD

**Issue by HarryHeights** [moezbhatti/qksms#1259]
Hello, I'm Harry. I find Qksms an amazing project and I'll love to contribute to this project with a Privacy Policy document and also I'll create a document which will be a compilation of questions and their respective answers I think new users will find useful.

The privacy policy document would contain details of how your app collects personal information if it does, and how this information is utilized. 

Would love to get a response from you.

**Comment by moezbhatti** [comment]
Hey, I appreciate the offer!

Do you have a sample of what the privacy policy might look like?

Where will you be sourcing the FAQ info from? I've already started compiling this information myself - the issue is just that I haven't decided on a place to put it yet

**Comment by HarryHeights** [comment]
Yea I've got a sample of a privacy I already did for a project. This is the [link](https://github.com/Valou3433/blade-player/blob/master/Privacy.md)

The FAQs would be compilation of questions I think users may ask. Maybe the use of some functions or what those functions are. Definitely the questions would basically be derived from the app and it's functions.

**Comment by HarryHeights** [comment]
I'm already working on the privacy policy document for Qksms. I'll leave the FAQs since you are working on it.

**Comment by moezbhatti** [comment]
Awesome, thanks!

**Comment by HarryHeights** [comment]
Welcome. I'll need some information from you though. 
What kind of information does the app collect while users utilize it? And what is the collected information used for?

**Comment by moezbhatti** [comment]
The app collects usage information (ie. when certain pages are viewed or when certain pages are clicked), for the purpose of understanding what my users find important and what I should be focusing my development efforts on

**Comment by HarryHeights** [comment]
Thanks.. That's all the information I need or not. 
One more thing, The document would contain an About us section. This gives a brief summary about the project, the developers if you work with a team or not and what inspired you to develop Qksms.
Hope I'm not bothering?

Thanks for your time.

**Comment by HarryHeights** [comment]
Hello, I just created a pull request for the privacy document. I'd hoped I got a reply from you for the "About Us" section in the document however I used my discretion to just make up something. You could make changes where it is deemed necessary. I also made side guesses about some technicalities pertaining to data collection and usage. If there are any changes you'll like to make but you are too busy you could state them and I'll edit the document and fix them in.

Thanks for having me work on your project.

It's my default SMS app especially because of the theme customization feature.

**Comment by moezbhatti** [comment]
@HarryHeights thank you very much! And sorry about the delays, just had a lot on my plate lately. Will get back to you as soon as I'm able
