### ISSUE TITLE
App hangs while "synchronizing messages"

### ISSUE THREAD

**Issue by kr428** [moezbhatti/qksms#1262]
Hard to debug: Using Signal as primary SMS/MMS messenger, I installed QKSMS a while ago (QKSMS+ from Play Store even). Worked fine. Re-flashed my ROM, re-installed all apps, re-installed QKSMS. Made it default SMS/MMS app. Granted all permissions it requested. However, starting the app I always end up with "synchronizing messages" not coming to an end until I either kill the app or restart the phone. Any way to provide more meaningful information on what happens here? 
Thanks,
Kristian

**Comment by kr428** [comment]
I'm on a Motorola G3 (2015) osprey device with AospExtended custom ROM based on Android 8.1.2, July patchlevel. Tried the latest QKSMS versions from Google Play (3.3.x) and F-Droid (3.4.0 by today as far as I have seen).

**Comment by rominail** [comment]
I have a Samsung Galaxy S4 running Android 5.0.1
Synchronisation with native database was working on previous version (don't know which one, march it was) and now it's not working from at least 3.3.3 (Installed from available f-droid previous apk)

**Comment by moezbhatti** [comment]
@rominail can you confirm that it worked fine in 3.3.2 and stopped working in 3.3.3? Then I can take a look at exactly what was changed and see if I can figure out what caused this to stop working

**Comment by rominail** [comment]
How can I dowload previous APK? The oldest one on f-droid is 3.3.3, I could have the 3.0.9 on APKMirror and synchronisation worked

**Comment by moezbhatti** [comment]
@romimail the APKs are available at github.com/moezbhatti/qksms/releases

I really appreciate your help!

**Comment by rominail** [comment]
None of the apk I dowload from the release page is able to be installed on my phone... "Error while analizing the entity" (or something slightly different, i'm doing the translation)

**Comment by kr428** [comment]
Tried 3.3.3 .. 3.3.0 on my device. In 3.3.3, though syncing messages doesn't work (which is okay to me), at least the "syncing messages" dialog seems to disappear after stopping and restarting the app so I can use it as intended. 3.3.1 and 3.3.0 immediately crash on my device. :(

**Comment by rominail** [comment]
After going through a couple of APK, I can install 3.2.0, 3.2.1 and 3.2.2, Snc is working on 3.2.2
And I can't install 3.3.0, 3.3.1 and 3.3.2

**Comment by rominail** [comment]
But without syncing you can't see older messages nor the one send from something else (I use mighty text to text from my laptop)

**Comment by kr428** [comment]
Ah, ok, I haven't tested that as it's not my use case to be honest. I'm in the process of moving SMS/MMS away from Signal as it has some drawbacks for these features.

**Comment by moezbhatti** [comment]
@kr428 in order to install an older APK, you'll first need to uninstall the existing version of the app, or else you'll see that error

**Comment by moezbhatti** [comment]
@rominail in order to install an older APK, you'll first need to uninstall the existing version of the app, or else you'll see that error

**Comment by kr428** [comment]
Did so, actually. Installing worked well but the app force-closed 
immediately after first start in some versions ...

**Comment by moezbhatti** [comment]
@kr428 does it help if you clear data for the app from your phone's settings?

**Comment by kr428** [comment]
Well no, clearing data didn't help either. However I flashed and re-installed my ROM last weekend anyway and it seems this made the problem "go away" for whichever reason. So I'm not too happy to not be able to reproduce the problem anymore, but at least it seems it "just" was an issue of my device... Thanks, anyway, for your help and sorry for bothering. :|

**Comment by rominail** [comment]
With the new 3.4.2 version it's working well!
Good job man!
