### ISSUE TITLE
Crash and opening after update

### ISSUE THREAD

**Issue by rominail** [moezbhatti/qksms#1263]
After today's (2018-07-26) update from f-droid
It crash at the opening : click on the app icon, white screen while a second and then android message 'QKSMS stopped'

Version 3.4.0
Android 5.0.1

**Comment by moezbhatti** [comment]
Can you try version 3.4.1 and let me know if that fixes the issue for you?

**Comment by rominail** [comment]
It's still crash
Report on crash : 
Package version
1180
Version
3.4.1
Device
jflte
Version ID
LRX22C.I9505XXUHPK2
Version type
User
Device model
GT-I9505
Product
jfltexx
SDK version
21
Edit
5.0.1
Incremental version
I9505XXUHPK2
Code name
REL
Board
MSM8960

I don't know if it helps

**Comment by rominail** [comment]
I'm sorry I thought it was 3.4.1 I installed but it was 3.4.0 so I didn't tryied the new one

**Comment by rominail** [comment]
Finally succeed to install the latest version from github and it opened correctly the first time, tryied to sync the message from native DB and it crashed, and crashed every time I try to launch it again
If I erase app data it launch again

**Comment by moezbhatti** [comment]
@rominail would it be possible for you to get a logcat of the crash?

**Comment by rominail** [comment]
I'll try to when I have free spare time

**Comment by moezbhatti** [comment]
Fixed in https://github.com/moezbhatti/qksms/commit/66a41841c4dfa63adc351a1515e2c95ed576c5e4

**Comment by rominail** [comment]
With the new 3.4.2 version it's working well!
Good job man!
