### ISSUE TITLE
Wrong contact photo displayed if multiple contacts share a phone number

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1264]
Example given by a user via email

> My family for example, there are 4 of us. We all have different mobile numbers, but the same home phone number. The thumbnail for all of us is displaying my son's picture.

Not exactly sure why this is happening yet, since each conversation should be using the distinct mobile number rather than the home number, and the number in the conversation is the one we use for the contact lookup

**Comment by zawyer1** [comment]
I can confirm this bug. Two of my relatives have the same profile pictures because they share their home number.

**Comment by somini** [comment]
There's another variant of this bug.

Contact "numbers" can be strings, useful to mute the spamming SMS from retailers and whatnot. QKSMS treats all "string numbers" as the same and puts them all in the same thread.

One workaround for this is opening the stock messaging app. The messages are then rearranged, and you can resync QKSMS to return everything to the correct location.

**Comment by zawyer1** [comment]
Small update on this bug. In my case, my mom and dad shared their home number, but the landline home number wasn't actually marked in the contact file as "Home", but simply as "Mobile" along with their actual mobile numbers. I assume this could have caused the big. Either way, I deleted the home number completely from my mom's contact file and re-synced the database in QKSMS -- then the correct profile picture appeared. I unfortunately never tried relabeling their home numbers as "Home" in their contact files before re-syncing the database, so I'm not sure if that would have solved the bug.

**Comment by sm4rk0** [comment]
I've tried with "Home" label and the bug is still reproducible.

**Comment by moezbhatti** [comment]
@somini I think that's a separate issue entirely, thanks for bringing that up

**Comment by moezbhatti** [comment]
@zawyer1 @sm4rk0 I don't think the labels should affect whether or not the bug occurs, it should happen as long as there's a phone number that's shared between multiple contacts
