### ISSUE TITLE
Error in Russian translation

### ISSUE THREAD

**Issue by spgrabber** [moezbhatti/qksms#1268]
### DESCRIPTION
The translation to Russian of "mark as read" button in notification area is wrong.
Now text on button in Russian actually says "Mark as unread" instead of "Mark as read".
(it is now "Отметить непрочитанным", and should be "Отметить прочитанным")

### STEPS
Use Android with Russian locale, qksms v 3.4.2, recieve SMS, look into notifications.

### EXPECTED
Correct translation.

### OBSERVATIONS
Now translation is incorrect.

**Comment by moezbhatti** [comment]
Thanks for the heads up! If you'd like to fix the translation (and any others that may be inaccurate), you can join the translation project here: https://crowdin.com/project/qksms/settings#translations
