### ISSUE TITLE
Libraries unrecognized after syncing

### ISSUE THREAD

**Issue by luife100** [moezbhatti/qksms#1269]
### DESCRIPTION
I'm using Android Studio and QKSMS version 3.3.7. Every time I press Sync most of the libraries stop working and appear unrecognized:

import android.Manifest
import android.app.AlertDialog
import android.content.Intent
import android.content.res.ColorStateList
import android.os.Bundle
import android.view.Gravity
import android.view.Menu
import android.view.MenuItem
import android.view.View
import com.moez.QKSMS.R

Its weird because if I dont sync, everything works like a charm.

### STEPS
1. File -> New -> Import Project -> Select qksms file
2. Press Sync

### EXPECTED
To continue working. I know it may be something very silly, but I'm stuck and I can´t find the solution.

### OBSERVATIONS
On the log:

-Generated Resources (warning)
Folder C:\Users\win 8.1\Documents\chapa\android\qksms-masterori\data\build\generated\source\kaptKotlin\noAnalyticsDebug |  
Folder C:\Users\win 8.1\Documents\chapa\android\qksms-masterori\data\build\generated\source\kaptKotlin\noAnalyticsRelease |  
Folder C:\Users\win 8.1\Documents\chapa\android\qksms-masterori\data\build\generated\source\kaptKotlin\withAnalyticsDebug |  
Folder C:\Users\win 8.1\Documents\chapa\android\qksms-masterori\data\build\generated\source\kaptKotlin\withAnalyticsRelease |  
Folder C:\Users\win 8.1\Documents\chapa\android\qksms-masterori\domain\build\generated\source\kaptKotlin\debug |  
Folder C:\Users\win 8.1\Documents\chapa\android\qksms-masterori\domain\build\generated\source\kaptKotlin\release |  
Folder C:\Users\win 8.1\Documents\chapa\android\qksms-masterori\presentation\build\generated\source\kaptKotlin\noAnalyticsDebug |  
Folder C:\Users\win 8.1\Documents\chapa\android\qksms-masterori\presentation\build\generated\source\kaptKotlin\noAnalyticsRelease |  
Folder C:\Users\win 8.1\Documents\chapa\android\qksms-masterori\presentation\build\generated\source\kaptKotlin\withAnalyticsDebug |  
Folder C:\Users\win 8.1\Documents\chapa\android\qksms-masterori\presentation\build\generated\source\kaptKotlin\withAnalyticsRelease |  
3rd-party Gradle plug-ins may be the cause |

**Comment by moezbhatti** [comment]
You'll need to make sure you're on the latest preview release of Android Studio
