### ISSUE TITLE
Apk will not install

### ISSUE THREAD

**Issue by Jrdnkasparek** [moezbhatti/qksms#1271]
When downloading the apk file from Github on my Pixel 2 XL the apk finishes with the message "app not installed"  This has been happening since the past few builds

**Comment by gkeegan** [comment]
Do you have qksms installed currently in any version? If so, uninstall that and then install the apk from GitHub.

**Comment by moezbhatti** [comment]
There are two instances where the downloaded apk will fail to install

1. You're trying to install an older version than the one you currently have
2. You currently have the APK from F-Droid, and are now trying to install the Github version

In both cases, the solution is to uninstall the existing version before trying to install the new one, as @gkeegan suggested
