### ISSUE TITLE
Duplicate numbers displayed for contacts when Whatsapp is installed

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1285]

**Comment by Tche333** [comment]
Is this really a bug ?
I had noticed that WhatsApp created another contact, replicating some  information already present in another same contact instance.
Shadowing those WhatsApp contacts would only provide a specific solution.
I did have same problem with Samsung cloud service recreating all my accounts, duplicating information.
2 suggestions:
1) as some contact applications, do providean option to only displaya subset of contacts found on the device: (1) by means of provider like phone, your Google account, Samsung account, WhatsApp account, ..  (2) by  means of number attributes like displaying only mobile number.
2) aggregate the numbers before displaying them, allowing to remove the duplicates. This one can be more tricky to implement if an API is used for displaying contacts and doesn't offer this capability, or simply code it if higher level language like SQL is not available for searching..
