### ISSUE TITLE
No notifications on Xiaomi Redmi 5

### ISSUE THREAD

**Issue by IstvanKohany** [moezbhatti/qksms#1289]
There are no notifications on my Xiaomi Redmi 5. QKSMS was downloaded from F-Droid, ver. 3.4.5. The notifications went missing after the last update, I think.

I checked the phone notification settings, disabled notifications from default SMS app, enabled/disabled the QK Reply function and opted -in and -out of beta version. The telephone was also restarted, but to no effect.

**Comment by Jouski** [comment]
Also affected with Xiaomi Redmi Note 5.

Actually there are notifications, but they act as "default notification" and not "message notification", so they use the same sound (or no sound) as all other applications which are not set.
