### ISSUE TITLE
Error sending message in new conversation, when contact's number contains brackets

### ISSUE THREAD

**Issue by febeslmeisl** [moezbhatti/qksms#1293]
### DESCRIPTION
Choosing a contact for a new conversation, whose number contains special signs (like brackets around the area code), sending the first message in a new conversation fails. 
(This can occur when syncronizing contact from external application to the phone: E.g. Outlook includes backets and dashes to the contact's phone number format to separate area code and extension number.)

### STEPS
1. Create (or synchronize) a contact with a number that contains brackets, like +49 (1234) 567891 - 01
2. Start a new conversation
3. Select the contact mentioned in step 1
4. Type in any message
5. Trying to send the message fails without a distictive error message

### EXPECTED
Message in the case describe above should be sent as normal (may be ommiting the special characters in the number).

### OBSERVATIONS
This issue does not occur, if the contact first sends you a message to start the conversation or if you manually type in the number (without special chars) to start it. Assignment of contact to conversation works even with the special chars, but it seems that the brackets, etc. are taken over from the contact to the conversation when starting it.

**Comment by moezbhatti** [comment]
This should be fixed in the current release
