### ISSUE TITLE
Crashed when scrolling through search results

### ISSUE THREAD

**Issue by Ravenstencil** [moezbhatti/qksms#13]
Searched for the word "test" and it crashed when I scrolled to the bottom of the results.

Approximately 12 conversations were returned.

**Comment by srcreigh** [comment]
Can't reproduce this issue. Can you provide any more details? Is it crashing for other queries? Can you tell if there is a pattern for the crashing, i.e. when it matches an MMS message?

**Comment by Ravenstencil** [comment]
It crashed on all queries. I was unable to successfully search for any message.

**Comment by Samcfuchs** [comment]
Couldn't reproduce on Moto X 2013.

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
