### ISSUE TITLE
[Request] Random material colors for each contact

### ISSUE THREAD

**Issue by NitroCipher** [moezbhatti/qksms#1309]
I switched over to this app after Android Messages destroyed itself, and I miss the random color themes that were assigned to each contact. It made it extremely easy to differentiate between contacts. Please add this!

**Comment by mddvul22** [comment]
Yes, please.  A single color makes the contacts very hard to differentiate and makes the app less user-friendly.  I'm not requesting that it be the default setting, but please let it be an option.

**Comment by NitroCipher** [comment]
Woah, i just randomly came to this issue to see if there was anything said about it recently. And i was greated by "Release 3.8"! Thanks man!

**Comment by moezbhatti** [comment]
I'll be implementing it this week!

**Comment by moezbhatti** [comment]
Duplicate of #133

**Comment by StefanBrand** [comment]
Has this been implemented? Where is the relevant commit? I'd like to have this downstreamed to /e/ foundations SMS app. :)
