### ISSUE TITLE
Some letters are missing in RTL language SMS

### ISSUE THREAD

**Issue by EgyptianM** [moezbhatti/qksms#1322]
### DESCRIPTION

![screenshot_ - - - - -](https://user-images.githubusercontent.com/12565380/46260134-bac62180-c4e2-11e8-83cc-368cb9e7cbe6.png)

In this screen shot you'll see that there are some missing letters at the right side of each message in both English and Arabic messages, but in English messages there are only 1 or 2 missing letters while in Arabic there are nearly whole words are missing.

### STEPS
1. Switch your phone language to any RTL language.
2. Open QKSMS.
3. Open any message.

### EXPECTED
To see full message

### OBSERVATIONS
Some letters are missing.

Thank you for the effort.

**Comment by EgyptianM** [comment]
> I've seen this too on my phone where some words or letters in persian are missed. I think it's because of using qt5, if you do that!
> [screenshot](https://user-images.githubusercontent.com/35726890/46366207-5f816400-c687-11e8-9f55-098c5a3d1c99.png)

What's qt5 @hamid255 ?

**Comment by hamid255** [comment]
The framework they probably used for creating qksms, @EgyptianM.
I said that because I saw two other programs with this problem (not showing Right to Left languages properly) also used Qt5.

**Comment by rezad1393** [comment]
I have the same issue.
the message is correctly got and displayed in preview and sms contacts list but inside the conversion the box that shows individual message cutts of graphically (not logically, the letters are there and can be copy pasted).

**Comment by zoli** [comment]
Isn't this dup of #1251?

**Comment by moezbhatti** [comment]
Yep, this is a duplicate

Can you comment on #1251 and let me know if this issue still persists if you set the app to use the system font?

**Comment by rezad1393** [comment]
this still persists with system font.
on a android one with android pie.
