### ISSUE TITLE
Input text box height increase on line break is delayed

### ISSUE THREAD

**Issue by DeesseFortuna** [moezbhatti/qksms#1329]
### DESCRIPTION
When typing in the input box, the box doesn't immediately expand vertically when a new line is needed - there is a short delay before expanding. Sometimes I am done the whole next line before it reacts, and then I have to wait again for the next line.

### STEPS
1. Open text
2. Type "hi"
3. Choose first suggestion to quickly fill up input box
4. Observe

### EXPECTED
Text box smoothly expands as soon as more space is required

### OBSERVATIONS
Text box does not smoothly expand as soon as more space is required

QKSMS Version 3.5.4
Android 6.0.1
ASUS ZE551KL build WW_21.40.1220.2056_20170224

**Comment by different55** [comment]
Specifically, it waits for a break in the user's typing before expanding, although the conversation history immediately shifts up in response.

**Comment by moezbhatti** [comment]
Same issue as #1078
