### ISSUE TITLE
Automatic theme for conversations

### ISSUE THREAD

**Issue by xavihernandez** [moezbhatti/qksms#133]
Hi peeps,

Could be good, I think, to have a "random colors theme". Currently you can pick a color for theming. It could be good to be able to select "random" and "multiple random". 

The first will let application chooses a color every time applicaiton is opened, or every day, etc. It's at developper discretion, or even can be a user choice (adding list where he can select to change color at "every opening", "every day", "every week", etc.), then color changes on trigger user has defined (or as I said, dev choice can be a first version).

The second is kinda like AOSP and Google messenger are designed : application (or system? I don't know how it is done because it is shared accross applications : Phone, Messenger, Email, etc.) determines a color for each contact. (see here for example http://www.guidingtech.com/assets/postimages/2014/11/2014-11-14-18.06.04.jpg, even Telegram can be an example : https://lh6.ggpht.com/U9a4KPjZCt7_fyNCOvNjcmL8rNCxdeW6GZ0INzu5hDl8-12phJenRj5dzK-Kdk6IHO23=h900).
We can even go further by letting the user select a color for a specific contact.

Anyways it's just some ideas.

Best regards.

**Comment by xavihernandez** [comment]
@moezbhatti does the last update implement this? I have read changelog and it says colors can be picked for each contact. But does each contact has its own color by defaut, or is it the color shceme set in settings?

**Comment by moezbhatti** [comment]
It's not random, but if you open the settings for a specific conversation, you can change the theme for them

**Comment by xavihernandez** [comment]
@moezbhatti  oh ok tanks so at the beggining it is color scheme set in settings, and then user can choose a color for each contact which will be saved?

**Comment by moezbhatti** [comment]
Yes exactly

**Comment by xavihernandez** [comment]
Ok thanks you! I tink it's a good enhancement. Random colors is a "pattern" used in lots of Android (from Lollipop) applications, including applications from Google.

Great work @moezbhatti :)

**Comment by xavihernandez** [comment]
Next step is to randomize colors if user wants to ;p

**Comment by xavihernandez** [comment]
@moezbhatti just tried latest version. A color can be applied to each conversation which is a good first step.
But when we go back to conversations list, this color is not kept. And we fall back to global color theme. i don't know if it is wanted or not.
Also when you are in a conversation and you tap on contact avatar, there is a quick go back to global color theme, which looks really weird.

I think that there is something you can catch to be able to have same contact than in Phone or Contact (like stock SMS application does). Unfortunately it may be embedded in system, and then QKSMS will lack permission.

**Comment by xavihernandez** [comment]
@valerio-bozzolan @szabolcsx you can discuss here about random color for conversations

**Comment by szabolcsx** [comment]
I saw this feature in Google Messenger. Basically when a new conversation is created it get's a random color. The user has the ability to change that for every conversation jus like we can now.

**Comment by xavihernandez** [comment]
@szabolcsx I don't know about Google Messenger but in stock AOSP application color is the same as in Contacts application.

**Comment by szabolcsx** [comment]
Maybe install the app and check out.

**Comment by therob84** [comment]
Is there any news about having different colored avatar letters (if no photo is available)?
It would improve eaysiness quite much and should not cost a big programming effort, should it?

**Comment by moezbhatti** [comment]
Pretty simple to do. I'm going to add an option for this when I add the new conversation opening animation - https://plus.google.com/+MoezBhatti/posts/hfavbrMmLnG

**Comment by bemug** [comment]
I'm bumping this as I'm interested in this feature.

Any news?

**Comment by johnmmcgee** [comment]
Would also be interested in an update on this as well.

Would really make the incoming message screen pop, instead of being one single color.

**Comment by nikolowry** [comment]
@moezbhatti while I really like the auto contact colors -- the text contrast in some colors make it extremely difficult to read (especially in Black theme). Is this on your radar? Should I make a new issue?

**Comment by moezbhatti** [comment]
Which colours in particular? Anything besides the yellow?

**Comment by nikolowry** [comment]
@moezbhatti besides the yellow, I find white text on the following colors hard to read -- even more so when Night Mode is triggered and preferring the Black variant:

- `#6DC966`
- `#06C9AF`
