### ISSUE TITLE
Restore freezes at one particular text

### ISSUE THREAD

**Issue by wedza** [moezbhatti/qksms#1332]
### DESCRIPTION
I've made two back-ups of my SMS before resetting my phone. But when I restore one of that two backups, QkSMS always freezes precisely at the message number 7330 (in the two backups). I've tried to wait a couple of hours, but the restoring doesn't seem to progress.

I can't even cancel or restart the restore process, I have to force close the app or restart entirely my phone to relaunch the restore.

### EXPECTED
Backup all the messages correctly.

### OBSERVATIONS
I've tried to search into the JSON file the message number 7330 to see if there was anything strange with this particular text, but I found nothing.

On Nexus 6P with the StatiXOS rom on Android Pie 9.0.0 with QkSms 3.5.4 (from F-Droid)

![image](https://user-images.githubusercontent.com/20335741/47268759-2a18b980-d555-11e8-84ac-9b4b3ad8bfac.png)

Here's a picture of what I think is the text number 7330 in the backup 
![image](https://user-images.githubusercontent.com/20335741/47268815-c80c8400-d555-11e8-8bd8-8cffeeff1f1b.png)

**Comment by wedza** [comment]
Finally, I've managed to restore my SMS by using a .ab file. But bug seems to still be here.

**Comment by moezbhatti** [comment]
I've seen this reported a couple times, though I'm not fully sure what's causing it yet. Thanks for the heads up and showing me the message contents.

Is the censored area just using normal latin characters?

**Comment by wedza** [comment]
Yes, it was. Just normal Latin characters, periods and a emoji at the end (that you see in the picture). There was definitely other messages as complex as this one.

Thanks for investigating and considering this issue ♥️

**Comment by moezbhatti** [comment]
Hmm, I don't see anything weird about the message itself then.

I'll see if there's an easy way I can update the code to still continue even if one message failed to copy, and then push up some error logs or something so I can grab some more info and fix it ideally. But at the very least, allowing the backup to proceed would be an improvement
