### ISSUE TITLE
Feature reqest - keyword SPAM filter

### ISSUE THREAD

**Issue by plg1** [moezbhatti/qksms#1335]
### DESCRIPTION
Keyword SPAM filter is a an effective way to block SPAM messages and will block messages the when number blocker fails, due to spammers  frequently numbers change.
Please note that the "Should I Answer" app, that may integrated with qksms, works only in specified counties.
Thanks

**Comment by sm4rk0** [comment]
Something like #228?

**Comment by plg1** [comment]
Yes!
Sorry, I've missed that open issue.
