### ISSUE TITLE
OnePlus 5T - Failed To Send Message

### ISSUE THREAD

**Issue by 0pLuS0** [moezbhatti/qksms#1337]
### DESCRIPTION
I just installed 3.5.4 from F-Droid, sent a message, then when someone sent me back a reply, and I replied back, I got ```Failed to send message```

### STEPS
1. Installed QKSMS 3.5.4
2. Send message
3. Received reply
4. Sent reply message back
5. Received failed to send message
6. Tried to send reply 3 times, and received same message over
7. Deleted the message and sent again, this time it sent ok.

### EXPECTED
I expect to be able to send messages and not have them fail.

### OBSERVATIONS
Message fails to send, I have 2 sim cards in the OnePlus 5T is this the problem?

I've attached a logcat...

[logcat.txt](https://github.com/moezbhatti/qksms/files/2567684/logcat.txt)

**Comment by TahitiCode** [comment]
Same issue with OnePlus 5T and QKSMS 3.6.6. No more issue when I downgraded to version 3.6.4.

I'm on Lineageos 16.0.
I have the same issue with only one sim card, or two.
I have no issue with the default sms app.

**Comment by moezbhatti** [comment]
Let me know if you're still experiencing this issue with the latest update

**Comment by 0pLuS0** [comment]
Well all these years later, and today I noticed a reply, I'm not even sure what the benefits of using qksms are, other that being open source.

I mean, in all honesty, is Google spying on our text messages? hmm

thanks

**Comment by TahitiCode** [comment]
@0pLuS0 
You can use it on a custom ROM, without Google Play Services, like [LineageOS](https://lineageos.org/) or [/e/](https://e.foundation/) for example.
