### ISSUE TITLE
White Contrast To Bright - Please Allow Default White Background!

### ISSUE THREAD

**Issue by 0pLuS0** [moezbhatti/qksms#1338]
### DESCRIPTION
OnePlus 5T OxygenOS 5.1.6
The white background of QKSMS is to washed out looking, and it would be great if this could just use a Standard white background like all of Android, instead of it's own color.

### STEPS
1. Installed QKSMS 3.5.4 from F-Droid
2. Opened QKSMS
3. Noticed the white color slightly washed out, to high of contrast, to bright

### EXPECTED
I expected QKSMS to use a default white background

### OBSERVATIONS
As I explained, the contrast is washed, out, or it's just this color of white that is to bright...

**Comment by moezbhatti** [comment]
QKSMS is using #FFFFFF for it's light theme, which is the standard in the newly redesigned Google apps and in Material Design 2.0

**Comment by 0pLuS0** [comment]
It doesn't look like a normal white, it appears more washed out, there's something not right...

**Comment by moezbhatti** [comment]
I welcome you to take a screenshot and sample the color - I promise you it's a 100% white
