### ISSUE TITLE
Texts sent, but not appearing in the list.

### ISSUE THREAD

**Issue by xircon** [moezbhatti/qksms#1339]
Texts sent are not appearing in list, texts received are in list.

### STEPS
1. Send a text
2. Text is sent
3. Does not appear in list
4. Text is received by recipient 

### EXPECTED
Text should appear in the list.

### OBSERVATIONS.
None.

Phone Honor (HuaWei) Play 64gb, Effectively Oreo, updated to latest security patches (built in app works, but displays "Unknown Sender" rather than the contact for the messages QKSMS sent).

**Comment by moezbhatti** [comment]
Looks like this is the same as issue #1324 - marking as duplicate
