### ISSUE TITLE
Crash on image view on zoom out 

### ISSUE THREAD

**Issue by brysonsbond** [moezbhatti/qksms#1340]
Happens almost everytime, when viewing an image sent or recieved in a message, when zooming out an error occurs and the app crashes.

It may have something to do with a max size that is hardcoded or expected, I am using a Galaxy S8 with a high dpi screen. If needed I can post a video of what is happening and list in detail further.

**Comment by moezbhatti** [comment]
A video would be fantastic!

Currently, in my crash logs, this seems like it's the most popular crash by far. I can't seem to reproduce it on my own device, though, even with the steps you have listed here.

I'm personally on a Google Pixel XL

**Comment by codydietrich** [comment]
This seems like the issue I have as well. Except trying to open any picture in a conversation causes a crash.

Device - OnePlus 3T
Android 8.0.0
