### ISSUE TITLE
moved archived message back to inbox

### ISSUE THREAD

**Issue by iembry** [moezbhatti/qksms#1343]
I accidentally swiped a message thus sending it to the archives. QKSMS crashed so I was not able to undo the move.

Is there any way to opt-out of the archival system via swiping? Also, how do you move an archived message back to the inbox?

Thank you.

**Comment by LeonCame** [comment]
long press on message, then icon on the top right,
(just to the left of the menu 3 points)

**Comment by moezbhatti** [comment]
In the settings you can customize (or remove) the swipe actions

**Comment by iembry** [comment]
Thank you everyone.
