### ISSUE TITLE
Clearing the search bar using "x" icon does not reset conversations list

### ISSUE THREAD

**Issue by justiceo** [moezbhatti/qksms#1344]
### DESCRIPTION
A short description of the issue. 
Clearing the search bar using "x" icon does not reset conversations list, manually deleting the query in the search bar does reset the conversations list.

### STEPS
1. Type a random string into the search bar, all conversations would be filtered out
2. You should see "Your conversations will appear here" notice.
3. Clear the search bar using the "x" icon on the left

### EXPECTED
The random string would be cleared from search bar and conversations list would be reset to original state.

### OBSERVATIONS
The random string is cleared from search bar but conversations list still displays the notice "Your conversations will appear here".

**Comment by justiceo** [comment]
Also, attempting a new search after clicking the "x" button does not display any search results.

**Comment by moezbhatti** [comment]
This seems to be resolved in the current release
