### ISSUE TITLE
Private SMS Feature

### ISSUE THREAD

**Issue by dianujnima** [moezbhatti/qksms#1346]
### PRIVATE SMS FEATURE
Hi this is more like a featured request instead of an issue I liked this app a lot its super fast which made me love this app but one think its missing is in my opinion is the option like SMS Vault/Private where when we select some contacts and when they message instead showing in the notification the content it will only show a new private message and upon opening it it will either ask for pin or fingerprint to show the message content.

This feature i am talking about is available in GoSMSPro app i quite used this feature. This feature will be great for confidential messages from bank or anywhere else like if you give ur mobile to some one by opening the main lock screen and a private message comes they cant see whats in it.

**Comment by moezbhatti** [comment]
Thanks for the suggestion - going to merge this with #377
