### ISSUE TITLE
Conversations activities are stacked

### ISSUE THREAD

**Issue by gilbsgilbs** [moezbhatti/qksms#1350]
### DESCRIPTION
Opened conversations are kept in a stack of conversation activities, which makes it difficult to return to the list of conversations from a conversation and looks buggy.

### STEPS
1. Open the list of conversations
2. Open any conversation in the list
3. Press home button (to exit the app), not "back"
4. Open QKSms again (list of conversations should show)
5. Repeat steps 2 to 4 a few times
6. Open any conversation in the list
7. Press "back" button (physical button from the phone or left arrow "←" in the top left corner).

### EXPECTED
"back" button should bring back to the list of conversations.

### OBSERVATIONS
"back" button brings back to the conversation that was previously opened. Even worse: if the same conversation was opened 20 times, it will show the same conversation 20 times.

It may be just enough to [set the conversation activity launch mode to `singleTop`](https://developer.android.com/guide/topics/manifest/activity-element#lmode).

**Comment by moezbhatti** [comment]
This will be resolved with  #1681
