### ISSUE TITLE
New conversation is not created

### ISSUE THREAD

**Issue by Walach76** [moezbhatti/qksms#1351]
### DESCRIPTION
New conversation is not created.

### STEPS
1. Open the App
2. Click the '+' button to create a conversation
3. Choose the person to contact or type a number
4. Write your message
5. Click sur send button.

### EXPECTED
New conversation created, with the number or name of the contact (if it exists)

### OBSERVATIONS
A window appears with : 
header : only the back arrow '<=' and the '...' buttons (neither contact phone number nor name)
content : the message you sent (the status of the message is really quickly displayed then disappears)
footer : normal

When you left this window open, even if you get a response to your message, the response is not displayed there. You have to press the 'back' button, and open the conversation created by receiving the response. Furthermore, in the conversation created by the response, you do not see your message.

This works with the standard messaging application. 
My phone is a Huawei P8 Lite 2017. I tried to reboot it, to stop it, to empty the cache... Nothing works...

Thanks in advance :)

**Comment by FaizKhan5** [comment]
Same problem with me

**Comment by moezbhatti** [comment]
Fixed in e610a373ca5416bc5ed5a648122a20b6e56e3727

**Comment by moezbhatti** [comment]
Looks like this isn't fixed afterall
