### ISSUE TITLE
Repeated Sounds for unread messages

### ISSUE THREAD

**Issue by lyspooner** [moezbhatti/qksms#1354]
### DESCRIPTION
When I get an sms and don't touch my phone I would like to have a sound notification every 5 minutes. 

### STEPS
1. New SMS arrives
2. I don't touch my phone
3. phone beeps every 5 minutes until the message is read. 

###
I got used to this feature on LG's Messaging app.

**Comment by moezbhatti** [comment]
Duplicate of #167
