### ISSUE TITLE
Feature Request - Built in Emoji Keyboard

### ISSUE THREAD

**Issue by whidden** [moezbhatti/qksms#1358]
### DESCRIPTION
Some keyboards do not have built in functionality for typing emojis. In such case, the only way to enter an emoji into a QKSMS message is to temporarily switch between different keyboard apps.

For example, I use the Grafitti Pro keyboard for PalmOS-style typing which does not have any emoji functionality. Every single time I want to type an emoji, I need to switch to a keyboard with built in emojis using the Android Change Keyboards menu, then switch back to Grafitti when I'm ready to start typing again. It may not sound like a big deal, but it's very clunky and gets old fast.

I realize that this likely only affects a small minority of users who, like me, don't use the default keyboard, and I also realize that it's really more a short-coming of the Grafitti keyboard than QKSMS. That said, it would be hugely appreciated if you would consider adding a menu allowing emojis to be browsed and entered into messages from within QKSMS itself rather than relying on the user's keyboard for that functionality.

### STEPS
1. Compose SMS.
2. Try to enter emoji.
3. No means within QKSMS to enter emoji.
4. Switch to a different keyboard in order to enter an emoji.
5. Switch back to preferred keyboard in order to enter text.

### EXPECTED

A menu somewhere within the compose message window which allows emojis to be scrolled through and selected would make texting much more convenient for users like me.

### OBSERVATIONS

This feature is available in Chomp SMS - emojis can be selected from the same menu where "attach a photo" is found (see attached screenshot).
![chompsms - built in emoji keyboard](https://user-images.githubusercontent.com/46266159/50550100-09996980-0c40-11e9-9cf9-bce1c05658a9.jpg)

**Comment by jediafr** [comment]
Just a quick builtin solution : a continued press on the enter key gives me access to the emojis.

**Comment by moezbhatti** [comment]
Appreciate the detailed thoughts here. I do think that this responsibility belongs to the keyboard and not the app, so this isn't a very high priority for me. I'm going to leave this open however, because implementing this opens the door to adding support for different emoji styles

**Comment by moezbhatti** [comment]
Closing in favour of #131
