### ISSUE TITLE
#bug sent messages not appear

### ISSUE THREAD

**Issue by tgbetauser** [moezbhatti/qksms#1360]
When i start a conversation for First Time, my sent messages not appear 

`App version 3.6.1`
`Android 8.1`
`Xiaomi Redmi note 5 Pro (Whyred)`

**Comment by ailin-nemui** [comment]
same issue on xiaomi miui 10. Was still working in qksms 3.5.

**Comment by RedBetaUser** [comment]
Yes, i have MIUI 10 too

**Comment by BennoGAP** [comment]
### STEPS
Send the first message to someone on MIUI10 device
 
### EXPECTED
Conversation with message appears in the message overview

### OBSERVATIONS
Directly after sending the message appears, but there is no recipient shown (-> Screenshot).
After switch back to the message overview the conversation with the contact does not appear - neither in QKSMS nor in the default SMS App.
Reverting the commit e610a373ca5416bc5ed5a648122a20b6e56e3727 fixed the issue for MIUI10 devices.

### Device
Xiaomi Mi8Pro
Android 9 (SDK 28)
MIUI 10

### App Version
3.6.1

![screenshot_2019-02-05-19-41-05-604_com moez qksms](https://user-images.githubusercontent.com/15093499/52296541-f5ebcc00-297e-11e9-9bde-b559747b6288.png)

**Comment by moezbhatti** [comment]
Sounds like you haven't set QKSMS as your default SMS app. Can you confirm this?

**Comment by tgbetauser** [comment]
No, I had it set. However now I have another rom, I will also try on this one

**Comment by BennoGAP** [comment]
With "default sms app" in my case i meant "stock sms app". QKSMS was set as default SMS app.

Error still occurs on current stock MIUI and reverting e610a37 still let it work again on Xiaomi devices.

**Comment by moezbhatti** [comment]
Thanks for digging that up. I have an older Xiaomi phone I think I can test this on. I'll give it a shot tomorrow and see what I find

**Comment by moezbhatti** [comment]
Can confirm

**Comment by tgbetauser** [comment]
@moezbhatti thanks, unfortunately now I don't have MIUI anymore but thanks for fix

**Comment by moezbhatti** [comment]
Reopening #1351

**Comment by fazlerabbi37** [comment]
@moezbhatti is this issue resolved?

**Comment by moezbhatti** [comment]
@fazlerabbi37 it's a duplicate of #1351, so I'm just leaving one of them open
