### ISSUE TITLE
Choix du son de notification

### ISSUE THREAD

**Issue by Ura34** [moezbhatti/qksms#1362]
Sur Honor 8X, il est impossible de choisir le son des notifications. Ce problème n'était pas présent sur l'Honor 6X sous Android 7.

**Comment by Jouski** [comment]
Pareil sur Xiaomi Redmi Note 5.
C'est la notitifcation sonore par défaut qui s'applique.

**Comment by Jouski** [comment]
It's not possible to choose sound notification. Only the default phone notification is used.

**Comment by moezbhatti** [comment]
Duplicate of #1308
