### ISSUE TITLE
Keyboard scrolling jumps out of field

### ISSUE THREAD

**Issue by JonnyTech** [moezbhatti/qksms#1367]
### DESCRIPTION
When scrolling through the message text, the text field loses focus

### STEPS
Create a new message then scroll to the beginning of the message (if using an AOSP keyboard this can be done by sliding finger on spacebar)

### EXPECTED
Caret should stop at first character and not scroll any further

### OBSERVATIONS
Caret leaves the text field and will not scroll back unless text field is clicked

**Comment by moezbhatti** [comment]
Just tested this and it seems to work fine for me. Let me know if this is till happening for you and I can reopen this!

**Comment by JonnyTech** [comment]
I am now on v3.8.1 and can cofirm that this issue has been resolved. Thanks for following up.
