### ISSUE TITLE
[Bug] Empty QK Reply window in latest update

### ISSUE THREAD

**Issue by zawyer1** [moezbhatti/qksms#1368]
Found a bug in a recent version of the app and had to revert back to 3.5.3.

In about 50% of messages, the QK Reply window is empty, showing no message at all. Happens both for SMS and MMS. If you enter the app normally the message is there without issue.

Don't really know how to reproduce this bug, but it works perfectly in the 3.5.3 version that I used before updating to 3.6.1. See the attached picture.

Let me know if I can be of help.

Nougat 7.0
ZUI

![screenshot_2019-01-07-14-43-38-1860427516](https://user-images.githubusercontent.com/37254938/51184299-28505f00-18d4-11e9-9fe6-1214e4654930.png)

**Comment by moezbhatti** [comment]
Fixed in a08f21de931bed635e117d048a59be492b164dab
