### ISSUE TITLE
Support for Scheduled Messages

### ISSUE THREAD

**Issue by ober37** [moezbhatti/qksms#137]
I would like to have the capability to schedule messages to be sent at a specific date / time, with a notification when it has been properly processed.

**Comment by Samcfuchs** [comment]
+1 on this

**Comment by pille1842** [comment]
Would love that!

**Comment by kocio-pl** [comment]
:+1:

**Comment by Hund** [comment]
+1 from me as well.

**Comment by haimn** [comment]
Thant's a good idea.

**Comment by reddit-is-fun** [comment]
Is this feature to be implemented? Would be extremely useful.

**Comment by CalculusWarrior** [comment]
I too would love this feature to be implemented.

**Comment by arafey** [comment]
👍

**Comment by anonsubmitter** [comment]
If this feature gets implemented I might switch over to QKSMS. :+1:

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by moezbhatti** [comment]
Added in QKSMS 3.0

**Comment by davidhedlund** [comment]
@moezbhatti Thank you very much!

**Comment by Samcfuchs** [comment]
Thanks!
