### ISSUE TITLE
qksms stopped working, Google dependency issue

### ISSUE THREAD

**Issue by z2z** [moezbhatti/qksms#1374]
### DESCRIPTION
Qksms 3.6.1 stopped working with recent update from fdroid.

### STEPS
1. Start qksms

### EXPECTED
To work

### OBSERVATIONS
Blank screen

Rom - Device : Lineage 16 / Beryllium

Log :

https://del.dog/naturiliwi.sql

Seems like there is dependencies on google play store. It starts to work properly once playstore is disabled. My playstore is not working and blocked using afwall.

**Comment by moezbhatti** [comment]
Hmm, I tested this on an emulator without Play Services and it seems to work fine. Does it crash immediately after opening the app?

**Comment by z2z** [comment]
Hi @moezbhatti,

It doesn't crash. Gets stuck on white/blank screen.

I think problem occurs when you have non functional/broken playstore.

**Comment by mblob** [comment]
I do use laum caf reloaded ROM with microg. If I do block play store app with firewall qksms get stuck forever.

**Comment by sm4rk0** [comment]
Possible workaround: try installing BlankStore. More info at [StackExchange](https://android.stackexchange.com/a/174638).

**Comment by moezbhatti** [comment]
The F-Droid build should have no dependency on any Google APIs, and doesn't contain any billing functionality

If you're still experiencing this issue let me know and I'll reopen

**Comment by z2z** [comment]
Unable to reproduce this in the new ROM. Looks good 👍
