### ISSUE TITLE
Is it possible to avoid synchronization?

### ISSUE THREAD

**Issue by HI-Lab1** [moezbhatti/qksms#1376]
### DESCRIPTION
When I try to use qksms firt time it try to synchronize all old database of sms, but there are  too much sms's inside it then qksms never end synchronization.

### STEPS
The defaul sms app in our smartphones doesn't yet work because too much sms's inside. Then we decided to pass to QkSMS but when we try to use it always it try to sync and import all old sms database. This is a problem because it can't and could recreate same situation of default sms app. How can we disable QkSMS sync at startup?

**Comment by moezbhatti** [comment]
Unfortunately this isn't possible, and this is a rare enough use case that I don't think I'll be changing this. Out of curiosity, how many messages do you have on your device? I've got nearly 100,000 and I thought that was a lot, but QKSMS seems to handle it just fine
