### ISSUE TITLE
Strange problem during restore - restore hangs

### ISSUE THREAD

**Issue by abusr** [moezbhatti/qksms#1379]
While transitioning from an old phone to a new one, the sms backup from the old phone is not restored to the new phone. The restoration hangs from the very first sms and is never completed. This is constant behavior, tested many times. Permissions for sms/storage/contacts etc all verified and given.

Source phone is android 5.1, dest phone is android 6.0.1 (Samsung).

Edited the backup json file and created a test backup file containing 1 sms. The file is parsed ok through the end. But, if the sms has a type=2 ("sent", I suppose), it is restored. If it has type=1, it hangs the restore. So this is some inner issue the program has to address. In the meantime, I cannot restore my backup and have to open the old smss with a texteditor.. 8-)

Proposed additions to the program.
1) Regardles whether each backup'ed sms can be imported or not, the program should not hang. In general. whatever is read from the backup file, should not be able to crash the program. Certainly the program has to be hardened a lot in this domain.

2) Upon each restore, a new backup file with the messages-not-restored should be created, if there were such messages, and an accompanying text report explaining the reason of the failure should also be created for the user.

Tia.

**Comment by moezbhatti** [comment]
I appreciate the detailed bug report here - going to merge this with #1332
