### ISSUE TITLE
Improve visibility on Google Play

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#138]
Right now if you search SMS, QKSMS doesn't even show up. Anyone have experience with Google Play SEO?

**Comment by l3d00m** [comment]
I have zero experience in GP-SEO, but after searching for a while I found this: 
>-Putting your main keyword in your app title (can affect 80-100 positions)
>-Frequency of keyword in body (no impact when repeated more than 5x)
>-Number of ratings: how many people have rated and reviewed your app.
>-Ratings: how high (or low) they are  
First point is the most important, last is less.  
First: Eight of the top ten results of the "SMS" search have SMS in the title. I think QK**SMS** doesn't count in this context.
Next point: The keyword SMS is only used once in the description, so you may higher the frequency. 
Last points: You should probably add a **non intrusive** rate dialog like [this one](http://nicolaspomepuy.fr/non-intrusive-app-rate/) to your app: It asks the user via a simple dialog/toast if he wants to rate the app or if he wants to do it later. This dialog shouldn't annoy the user too much and boost your position.

**Comment by moezbhatti** [comment]
Sweet, thanks for the info. I'll start working on a new description tonight

Also, this is pretty funny
<img width="644" alt="screen shot 2015-08-20 at 1 01 02 pm" src="https://cloud.githubusercontent.com/assets/4358785/9389904/98447a26-473b-11e5-8d51-f6c6febe860e.png">

**Comment by JonShepChen** [comment]
Is it possible to rename the application? (Assuming if renaming wasn't out the question)
(QKSMS to QK SMS) or (QKSMS - Quick SMS/MMS Messenger) or something along those lines.

Technical hurdles with doing this?

**Comment by moezbhatti** [comment]
Technically it is possible, but I think it'd hurt the SEO and cleanliness of the name to change it to `QK SMS`

I do like your second idea though, it covers all the big keywords

**Comment by realmain** [comment]
It looks like it shows up on Google Play now. Should this be closed?

**Comment by moezbhatti** [comment]
@realmain this is mostly related to improving the position for QKSMS in search results for more generic searches, like "SMS app"
