### ISSUE TITLE
sendMessage getResultCode is 5

### ISSUE THREAD

**Issue by liulianshanzhu** [moezbhatti/qksms#1380]
### DESCRIPTION
A short description of the issue. 
Example: Conversations aren't marked as read when they are opened from a notification.

### STEPS
1. Open the Mobile Phone
2. send Message
3. getResultCode()
4. code error
5. code = 5

### EXPECTED
The result of sending a text message back is 5

### OBSERVATIONS
getResultCode is 5

**Comment by moezbhatti** [comment]
I'm a bit late here - let me know if you're still experiencing this problem
