### ISSUE TITLE
Properly deal with plurals in translations

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1389]
We've got a plural string for deleting conversations, where we show the number when it's plural

When providing a translation on [Crowdin](https://crowdin.com/translate/qksms/1/enca-vi#q=are+you+sure), for particular languages it just says `Target language has one plural form`, and you can't provide different strings for the variant that shows the number and the variant that doesn't

**Comment by GeoZac** [comment]
Can you elaborate on this issue? Saw this while dealing with a plurals issues in your app.

**Comment by GeoZac** [comment]
Could you handle as in [here](https://github.com/LineageOS/android_frameworks_base/blob/8943bbe92bfbc3ead44f63a6a3c145a135548b7c/packages/SystemUI/res-keyguard/values-as/strings.xml#L68-L71) ?
AOSP itself has lot of instances like this, providing same string for all quantities

**Comment by moezbhatti** [comment]
Hmm... yeah that sounds like a pretty easy solution. Not sure why I opened an issue for this, sounds like it can be solved trivially by the translators
