### ISSUE TITLE
Enhancement: Possibility to customise the notification icon in the toolbar?

### ISSUE THREAD

**Issue by LrntL** [moezbhatti/qksms#1397]
I'm just posting an idea of enhancement.
Feel free to comment if you think it is interesting.

**Enhancement: Possibility to customise the notification icon in the toolbar by choosing in a list.**

Laurent

**Comment by moezbhatti** [comment]
Hmm, I don't think this is something that very many users would care much about, so in the spirit of keeping the app clean, I'm going to close this one. If it becomes a popular request I'd be happy to reconsider
