### ISSUE TITLE
Message gets stuck sending

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1401]
I've had a number of reports about this. Sometimes the user closes the app after sending messages, sometimes the user has delayed sending enabled, sometimes neither of those are true

**Comment by 190n** [comment]
I've had this issue on many occasions (I leave the app open and I don't have delayed sending enabled). FWIW, what usually works when a message gets stuck in "Sending..." is to turn on airplane mode, wait for the "Message failed to send" notification, turn airplane mode back off, and tap the message to try again.

I've found a couple issues on GitHub that seem to be related to this. This seems to be the most recent, but please let me know if there is a different one that I should move this to. Thanks for all your hard work!

**Comment by moezbhatti** [comment]
@190n when this happens to you, do you know if the message has already been sent in the background but the app just didn't update the `sending...` state? Or has it genuinely not sent

**Comment by 190n** [comment]
I just tested with a friend's phone. It actually did not send.

When I turn off airplane mode and QKSMS doesn't report that the message failed to send, that generally means it actually went through (so it's just UI not updating). In those cases, the "Sending..." text persists through force stopping the app.

**Comment by moezbhatti** [comment]
Gotcha, sounds like you're experiencing both cases of the problem then.

> When I turn off airplane mode and QKSMS doesn't report that the message failed to send, that generally means it actually went through

This makes a lot of sense, thanks for mentioning that

You were able to to test this super quickly after me posting my comment - how often does the stuck sending issue happen for you?

**Comment by 190n** [comment]
It seems to happen the most often when I haven't used QKSMS in a while. When I was testing it just now, I sent a few messages without error, then I got impatient and force stopped QKSMS. When I reopened it, the first message I sent got stuck. Once I used airplane mode to retry sending that message (which worked), I sent several more without issue.

The other bug (where it does actually send) doesn't happen nearly as often.

I've also been able to check whether a message has actually been sent using the default Messages app.

FWIW, I'm using QKSMS 3.6.4 (from F-Droid) on a OnePlus 6 running OxygenOS 9.0.5 (Android 9).

**Comment by moezbhatti** [comment]
Should be slightly improved by 797f3597258d4dae763a53038e225ab75af4b017, which also includes some better debugging

**Comment by neuroradiology** [comment]
This is still happening to me. It started 1-2 months ago. Force-closing app, airplane mode for 30 minutes, and rebooting phone did not help. Now I am basically unable to text. 

:(

**Comment by ballo** [comment]
I'm experiencing this, too, and they don't time out even if I'm in airplane mode!

**Comment by ballo** [comment]
OK so I may have a clue as to the problem. If you have a slow connection (I used up my fast data) and send a lot of photos to a lot of people at once before waiting for them to complete, they will hang indefinitely.
