### ISSUE TITLE
MMS

### ISSUE THREAD

**Issue by Jouski** [moezbhatti/qksms#1402]
### DESCRIPTION

Wiith Xiaomi Redmi Note 5, MMS are not received.

### STEPS
1. Send yourself a MMS or ask someone to send it to you (less than 300Mb)
2. Wait 
3. No MMS is received.

### EXPECTED
QKSMS should receive MMS.

### OBSERVATIONS
I checked no restriction is applied from the OS.

**Comment by moezbhatti** [comment]
Duplicate of #945
