### ISSUE TITLE
Block message by keywords

### ISSUE THREAD

**Issue by may215** [moezbhatti/qksms#1406]
Hi,
I would like to implement something like this [NekoSMS](https://github.com/apsun/NekoSMS) inside the project. Now, I saw that there are filters classes, and I thought to extend them and create KeywordsFilter class. I need some guidance please on how is the best way to implement this according to the application architecture.

The idea I thoght about, is to block messages by keywrods, don't alert about those messages, but, allow you to audit them  #later.

Thanks for your help.

**Comment by moezbhatti** [comment]
Combining with #228
