### ISSUE TITLE
Add Support for Android Q "bubbles"

### ISSUE THREAD

**Issue by Jrdnkasparek** [moezbhatti/qksms#1407]
Android Q adds an easier way to multi-task by adding bubbles (aka pretty much chat heads) to allow for fast replies, etc....

https://developer.android.com/preview/features/bubbles

**Comment by moezbhatti** [comment]
Woah! I'll have to look into this

**Comment by Jrdnkasparek** [comment]
This feature will not be a user facing feature in Android Q anymore

**Comment by GeoZac** [comment]
Available as user facing feature on [Android 11](https://developer.android.com/about/versions/11/features#bubbles_enabled)

**Comment by tentacleuno** [comment]
Would you consider reopening this? Most messengers like FBM have this capability, and it would be a shame not to extend it to SMS vs QKSMS.

**Comment by Eragonfr** [comment]
Any update on this ?

**Comment by 2br-2b** [comment]
This is a very nice feature that QKSMS is missing that I use all the time in Signal!
