### ISSUE TITLE
Strip unicode (accent) when searching for contact name

### ISSUE THREAD

**Issue by OhSoGood** [moezbhatti/qksms#1420]
With the raw SMS app (in Lineageos, I think it's the raw AOSP one), if I enter "cel" in the contact searchbox, it will return firstname/lastname with unicode chars like "céline". QKSMS does not, and it makes searches more complex/time consuming.

Could you add this feature to QKSMS?

**Comment by nath5394** [comment]
Hello, as I use /e/OS, I use QKSms as default app. So I asked there : https://gitlab.e.foundation/e/apps/Message/issues/18 if someone could help you fixing this bug. Thanks for your work !!!
