### ISSUE TITLE
Build is failing when using ./gradlew build or ./gradlew assemble

### ISSUE THREAD

**Issue by amitkma** [moezbhatti/qksms#1421]
### DESCRIPTION
I am trying to build qksms locally. So when I use this command `./gradlew build` or `./gradlew assemble`, I am getting this error. - 
```
Execution failed for task ':android-smsmms:verifyReleaseResources'.
1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /home/falcon/Projects/qksms/android-smsmms/build/intermediates/res/merged/release/values/values.xml:140: error: resource android:attr/fontStyle not found.
  /home/falcon/Projects/qksms/android-smsmms/build/intermediates/res/merged/release/values/values.xml:141: error: resource android:attr/font not found.
  /home/falcon/Projects/qksms/android-smsmms/build/intermediates/res/merged/release/values/values.xml:142: error: resource android:attr/fontWeight not found.
  /home/falcon/Projects/qksms/android-smsmms/build/intermediates/res/merged/release/values/values.xml:143: error: resource android:attr/fontVariationSettings not found.
  /home/falcon/Projects/qksms/android-smsmms/build/intermediates/res/merged/release/values/values.xml:144: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

But when i build only debug version, there are no issues as the task which fails is `verifyReleaseResource` so it executes when we try to build release variant as well.

### STEPS
1. Clone the project
2. Open in android-studio
3. Use command `./gradlew build`

### EXPECTED
It should build successfully.

**Comment by moezbhatti** [comment]
You need to compile the presentation module, not the root directory

**Comment by dhjaber** [comment]
> You need to compile the presentation module, not the root directory

hi Moez ..
how to do that ? "You need to compile the presentation module, not the root directory"
