### ISSUE TITLE
Wrong contact associated to received message when phone number is invalid, like '???'

### ISSUE THREAD

**Issue by sphakka** [moezbhatti/qksms#1432]
### DESCRIPTION
I have a contact created by Seamonkey/Thunderbird with only a dummy phone number set to '???'. My address book is synchronised to my FP (LineageOS 15.1) via google. 

Whenever I receive a message from a masked caller ID (f.i., DHL delivery notifications), it gets filed as a conversation coming from the dummy contact. 

### STEPS
1. Have a contact with only an invalid phone number, such as '???'. Note: this must be done via an external app, as the (latest?) Android contact app doesn't allow to set invalid numbers
2. Have someone send you a message with masked caller ID, or wait for one...
3. Refresh your mobile contact DB and re-sync QKSMS to the android msg DB.
4. See the received above msh as coming from the contact name associated with number '???'.

### EXPECTED
Any msg from a masked caller ID should by filed as a conversation from a specific sender identified by the 'From' header field as shown in the message details.

### OBSERVATIONS
Using a valid, though weird, combination for the dummy number, such as '###' doesn't trigger the bug.

**Comment by moezbhatti** [comment]
I believe this is actually the same problem as #1423
