### ISSUE TITLE
"Update QKSMS icon color" overrides theming engines and icon packs indefinitely

### ISSUE THREAD

**Issue by Jadelor** [moezbhatti/qksms#144]
### DESCRIPTION

On my Oneplus One, if I use "Update QKSMS icon color" even once, then the QKSMS icon no longer can be skinned by the Cyanogen OS 12 theming engine. QKSMS-picked icon will persist through icon packs and the like.
### STEPS
1. Use QKSMS's "update icon color" function to change from default app icon
2. Use Cyanogen OS's theming engine to apply an icon pack that would skin the QKSMS icon
3. Return to the app drawer / home screen
4. Observe the QKSMS icon
### EXPECTED

QKSMS's icon is skinned by the icon pack
### OBSERVATIONS

QKSMS's icon remains the one set by QKSMS.

**Comment by The0x539** [comment]
The teal icon doesn't stop getting themed, I'm pretty sure the icon pack developer just needs to supply icons corresponding to the alternate color icons.

**Comment by Jadelor** [comment]
You're right!

**Comment by moezbhatti** [comment]
The feature has been removed in QKSMS 3.0, which now uses a standard icon. This should work properly now.
