### ISSUE TITLE
Can't receive MMS with dualsim

### ISSUE THREAD

**Issue by Zoah** [moezbhatti/qksms#1444]
### DESCRIPTION
Hello,
I can't receive MMS with dualsim.
If I switch to the the stock application (messages), I can see a pending message from an unkown sender.

If I try to download this message with "messages", this exception happens:

> 06-03 16:17:12.588  3811 24681 I MessagingAppDataModel: DownloadMmsAction: Downloading MMS message 105407 (manual)
06-03 16:17:12.588  3811 24681 E MessagingApp: MmsUtils: Incoming MMS came from unknown SIM
06-03 16:17:12.588  3811 24681 E MessagingApp: MmsUtils: failed to download message content://mms/1277
06-03 16:17:12.588  3811 24681 E MessagingApp: com.android.mms.sms.MmsFailureException: Message from unknown SIM

Thank you

### STEPS
I have two SIM cards: SIM1 and SIM2.
There are from the same phone operator (so they works with the same APN).
The APN was updated.
Data connection was deactivated, since MMS have to be received event if there is no data.

**Case 1 :** I try to send MMS from SIM1 to SIM
Success - MMS marked as sent and correctly received.

**Case 2 :** I try to send MMS from SIM1 to SIM
Failure - MMS marked as sent but nothing received.

**Case 3 :** When I try to send MMS from SIM2 to SIM
Failure - MMS sent (very slowly) and received (very slowly) in the SIM2 conversation.

**Case 4 :** When I try to send MMS from SIM2 to SIM2
Failure - MMS marked as sent but nothing received.

All cases works with the stock application...

### EXPECTED
I should be able to receive MMS.

### OBSERVATIONS
MMS aren't received.

### HARDWARE/SOFTWARE
QKSMS 3.6.4 (since 3.4.4)
Oneplus 6
OxygenOS 9.0.5 (last officiel rom)
Android 9

**Comment by Zoah** [comment]
I will try to launch QKSMS from the sources and/or give you more ouputs from logcat.
If you want a specific action/log, please ask.

This issue is maybe related to #945 but dualsim wasn't mentionned.

**Comment by moezbhatti** [comment]
Thank you for the detailed report, @Zoah! If you could get a logcat recording from the time that you send the MMS, and then about a minute after that, that would be fantastic

**Comment by Zoah** [comment]
Of course ! I filtered two useless lines from the files:
- Access denied finding property
- avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs"

I also removed a bloc from another application (some personal data).
If you see personal data, feel free to edit my comment.

### STEPS
- SIM1 to SIM1:   mms received
- SIM1 to SIM2:     mms not received
reset
- SIM2 to SIM2:       mms not received
reset
- SIM2 to SIM1:     mms received, but marked as "received by SIM2" and "from SIM1"

The reset part means that I launched the SMS stock applicaiton, in order to clean pending MMS.

### LOGS

[SIM1 to SIM1.log](https://github.com/moezbhatti/qksms/files/3290335/SIM1.to.SIM1.log)
[SIM1 to SIM2.log](https://github.com/moezbhatti/qksms/files/3290336/SIM1.to.SIM2.log)
[SIM2 to SIM2.log](https://github.com/moezbhatti/qksms/files/3290338/SIM2.to.SIM2.log)
[SIM2 to SIM1.log](https://github.com/moezbhatti/qksms/files/3290337/SIM2.to.SIM1.log)

**Comment by moezbhatti** [comment]
Is this still an issue in 3.7.10?

**Comment by Zoah** [comment]
I reinstalled the app and try sending MMS to myself from both SIM.
First MMS sent toke time to get received, but it seems to work now...

#### HARDWARE/SOFTWARE
QKSMS 3.8.0 (F-Droid)
Oneplus 6
Lineage OS 16 (nightly build)
Android 9
