### ISSUE TITLE
Phone Led still blinks after reply using KDE Connect

### ISSUE THREAD

**Issue by raphj** [moezbhatti/qksms#1445]
My phone is connected to my computer using KDE Connect.

When I answer a text with the computer from KDE Connect, the phone's led notification keeps blinking. Though it is obvious that I read the very message that makes the phone blink in the first place. And I don't really want to unlock the phone to make it stop blinking.

I expect the led stops blinking after an answer using KDE connect.

The KDE Connect maintainer suggests the issue is on the QKSMS side : https://bugs.kde.org/show_bug.cgi?id=408527#c3 so here is a bug report for you :-)

**Comment by raphj** [comment]
Never mind, I just noticed a case where the phone stopped blinking after a reply from KDE connect. Closing for now.

**Comment by raphj** [comment]
Well, reopening, since this is not reliable. Sorry for the noise.

**Comment by moezbhatti** [comment]
Related to https://github.com/moezbhatti/qksms/issues/906

Need to mark the conversation as read after syncing the message

**Comment by raphj** [comment]
I can't reproduce this anymore.
