### ISSUE TITLE
Can't save a number from the app to my phone as a contact

### ISSUE THREAD

**Issue by iamowomizz** [moezbhatti/qksms#1448]
### DESCRIPTION
When I try to save a number as a contact on my phone from the app, it says cannot save invalid number

### STEPS
1. Open the app
2. Open a message you sent to a number not saved on the phone  
3. Click on the three vertical dots at the top of the app by the side of the call logo
4. Click on the number to save as contact on phone 

### EXPECTED
When I click on the number to save as a contact on my phone, I expect the number to be saved on my phone
### OBSERVATIONS
When I click on the number to save as a contact in my phone it just says cannot save invalid number

**Comment by moezbhatti** [comment]
Does this happen with every single contact, or with just a few?

**Comment by iamowomizz** [comment]
Happens with every contact

**Comment by JonTabor** [comment]
Having this issue as well

**Comment by moezbhatti** [comment]
Which contacts app do you folks use?

**Comment by JonTabor** [comment]
> Which contacts app do you folks use?

I'm just using the built-in Contacts app in Android 7.0.  App Info shows "Contacts version 1.4.17"

**Comment by moezbhatti** [comment]
Fixed in 2d1de6068f1642b604464b8771caa93ab891703f
