### ISSUE TITLE
Shortcut png images get blurry

### ISSUE THREAD

**Issue by GeoZac** [moezbhatti/qksms#1449]
### DESCRIPTION
The app shortcuts are a great feature, but the the icons get blurry when used in homescreen.

### STEPS
1. Create a app shortcut on homescreen.
2. Alternatively create customised app shortcut via applications like [Sesame shortcuts](https://play.google.com/store/apps/details?id=ninja.sesame.app.edge)

### EXPECTED
The icons shouldn't appear blurry

### OBSERVATIONS
The icons appear blurry.

### SCREENSHOTS
![IMG_20190612_221457](https://user-images.githubusercontent.com/11597134/59370525-51c8c600-8d60-11e9-90cd-ffc80d6e50de.jpg)
the screenshot shows show Google's and some other third-party app shortcuts show up in homescreen.

**Comment by moezbhatti** [comment]
hmm... weird. in this screenshot, did you create them using sesame or by dragging the options from the homescreen long-press menu?

**Comment by GeoZac** [comment]
> did you create them using sesame or by dragging the options from the homescreen long-press menu?

I think I did try both ways before I posted the issue.

Well, seems I'm not able to reproduce the issue now. Closing the issue

**Comment by moezbhatti** [comment]
Awesome!
