### ISSUE TITLE
Notification Channels Broken in Android Q

### ISSUE THREAD

**Issue by Jrdnkasparek** [moezbhatti/qksms#1453]
Pixel 3 XL Android Q Beta 4.
No longer allows to customize notifications for conversations, it doesn't remember the customizations I make. Customizations work in other apps so I don't believe this is a system issue. 

In the screenshots below you it will not let me turn notifications off for conversations nor will it allow me to customize them

![Screenshot_20190620-204906](https://user-images.githubusercontent.com/20908630/59890083-45b2b900-939d-11e9-96b4-829dcf267211.png)

![Screenshot_20190620-205629](https://user-images.githubusercontent.com/20908630/59890215-e6a17400-939d-11e9-8c8b-34433de3f65b.png)

**Comment by moezbhatti** [comment]
Hey @Jrdnkasparek, any chance you could test this again for me? It seems to be working fine for me on the latest release candidate

**Comment by Jrdnkasparek** [comment]
@moezbhatti  Yeah it appears to be working again!
