### ISSUE TITLE
MMS not sent : Sending failure

### ISSUE THREAD

**Issue by kazukyakayashi** [moezbhatti/qksms#1455]
### DESCRIPTION
When I send an MMS I get a sending error: "Sending failure. Press to try again" and this does not matter the configured compression level. As a result, the MMS is not sent.

As a result the MMS is not sent, however the MMS works very well with **Silence**. Once the MMS is sent via Silence, it appears in QKSMS but always with the error message: "Sending failure. Press to try again" although the one is well sent (with Silence)

### DEVICE
LG Nexus 5X on **/e/** | Android 8.1.0 | LineageOS API Ilama (9)

**Comment by HorlogeSkynet** [comment]
Hey there ! Exactly same issue over here, OPO, Android 8 too. At first, I've thought it was relative to connectivity, but definitely not : MMS won't go away for some weeks now.

Bye 👋

**Comment by mollusko** [comment]
Experiencing this as well, Xperia xz1c on Android 9; QKSMS 3.8.0, no amount of tweaking MMS compression levels appears to have any effect.

**Comment by christian-cleberg** [comment]
Same issue here. OnePlus 7 Pro, Android 10, QKSMS 3.8.1. I've tried all compression levels and found that MMS works in the default Messages app with no issues.

**Comment by realpixelcode** [comment]
I can't send nor receive MMS either.

QKSMS 3.8.1
Android 9
/e/ OS version 0.11-p-2020082870302-dev-FP3
Fairphone 3 (FP3)
