### ISSUE TITLE
Question : Is it possible to migrate from 2.7.3 to last 3.x.x and keep all messages/conversations stored ? 

### ISSUE THREAD

**Issue by jalba69** [moezbhatti/qksms#1460]
Hello,

I am still on the version 2.7.3, Google playstore never proposed me an upgrade and only now I discovered that there was the version 3 out when searching for dual-SIM support.

Using F-Droid app i see the possibility to update to last version there.

Only thing I am worried about is if it will be a kind of destructive update, loosing all conversations and messages stored on my phone or if passing from 2.7.3 to last 3.x.x using the F-droid will at least keep the conversations/messages, i don't mind for all other etc, just need to keep conversations. I have a few years of conversations and thousands of messages stored on my phone...

If it is not possible to do this directly by upgrading from 2.7.3 to 3.x.x , then is there a way to backup manually my conversations/messages ( might need a way to do this even if not migrating now that i think at it...) , and possibility to import them later in the version 3.x.x ?

Thanks a lot in advance.

**Comment by moezbhatti** [comment]
Your conversations are actually stored by the android system and not by QKSMS, so you can safely upgrade or switch SMS apps without losing your messages

**Comment by jalba69** [comment]
Thanks a lot for the reply, and for the nice app too ;)
