### ISSUE TITLE
Couldn't import vCard

### ISSUE THREAD

**Issue by j0lk3n** [moezbhatti/qksms#1468]
### DESCRIPTION
When I receive a vCard from someone, I cannot import it. Error: Couldn't import vCard

It would also be helpful to be able to attach vCards

### STEPS
Click on vCard you have received.

### EXPECTED
vCard should be imported into contacts

### OBSERVATIONS
Error: Couldn't import vCard

**Comment by moezbhatti** [comment]
Looks like vCard currently works fine when sent between Android phones, but QKSMS isn't able to save a vCard that was received by an iPhone. At least, this is what I've experienced myself. Does this align with what you've seen?

**Comment by moezbhatti** [comment]
Hmm, I can't get it working in any conversation anymore. I don't know how it worked before, but I think this is broken because we're asking the Contacts app to open a URI (for the vCard part) that it doesn't have permission to view
