### ISSUE TITLE
Search Should Include Group Chats and Outgoing SMS

### ISSUE THREAD

**Issue by prg318** [moezbhatti/qksms#1471]
### DESCRIPTION
When using QKSMS's search feature, no messages from group chats will be returned in search results.  In addition, any outgoing/sent messages will not be returned in this search.
Example: Search for a keyword that was used in a group chat conversation thread.
Example 2: Search for a word in a message that was sent by you

### STEPS
1. Have a group chat conversation thread in QKSMS
2. Search for a word used in the group chat conversation in QKSMS main activity
3. Notice that the group chat conversation is not shown as a search result

1. Send an outgoing message.
2. Search for a word used in the outgoing message in the QKSMS main activity.
3. Notice how the conversation thread is not shown as search result.

### EXPECTED
I would expect sent messages and group messages to be included in search results

### OBSERVATIONS
Sent messages and group chat text are not included in search results

**Comment by moezbhatti** [comment]
Outgoing messages seem to be showing up in search results fine for me (does it make any difference for you if you restart the app after sending the message) but I can confirm the behaviour here with group messages
