### ISSUE TITLE
What does each folder do?

### ISSUE THREAD

**Issue by JunChoi-KR** [moezbhatti/qksms#1472]
What does each folder do?
I'm a Kotlin beginner developer and need help.
When I look at the file, I don't know what the other folders do besides the presentation folder.
Can I just extract the presentation folder and use it?
Or does it work if I extract other folders and dependencies?
thank you.

**Comment by moezbhatti** [comment]
You can't extract any one of the modules, they're all needed in order to build the app. The presentation module is the primary app module though, so that's the one you'll need to build

**Comment by muhammadwaqar97** [comment]
i dont know about kotlin i know about java but there is many folders and i did n't understand, there is java files and also kotlin so plz help me
