### ISSUE TITLE
Unable to copy text of scheduled message

### ISSUE THREAD

**Issue by szpak** [moezbhatti/qksms#1477]
### DESCRIPTION
It's problematic to copy text of scheduled message without its sending.

### STEPS
1. Write and schedule a message
2. Try to copy it text (to reschedule it or make some modifications)

### EXPECTED
There is a way to copy text (or maybe also edit a message or reschedule it). Useful with long messages which need to be rewritten or rescheduled.

### OBSERVATIONS
It's possible only to send a message right now or delete it.

**Comment by MyFirstChoiceWasTaken** [comment]
Advisory: This looks a lot like a duplication of #1386.

**Comment by moezbhatti** [comment]
Definitely related, but I think there's enough of a distinction between them that they deserve separate issues

**Comment by szpak** [comment]
This issue should be easier to implement, so maybe the ETA is also shorter ;).

**Comment by edmundlaugasson** [comment]
Issue still not solved with current v3.7.2 release.

**Comment by moezbhatti** [comment]
This is part of 3.7.3
