### ISSUE TITLE
Conversation is Showing Empty

### ISSUE THREAD

**Issue by tcs-developer** [moezbhatti/qksms#1482]
After Reinstall Some SMS like "AX-SBIBNK" is showing in Inbox but conversations body shows Empty.

![Mess_1](https://user-images.githubusercontent.com/24837611/64769346-c3373100-d568-11e9-888d-3af52f3b7ba8.png)
![Mess_2](https://user-images.githubusercontent.com/24837611/64769348-c3373100-d568-11e9-924a-8a8461331717.png)

**Comment by moezbhatti** [comment]
If you go into the settings and click Sync Conversations, does this fix the issue?

**Comment by tcs-developer** [comment]
Already we have tried your recommendation, but it does not work it out, Please let me know other solution.

**Comment by moezbhatti** [comment]
Weird, but the conversation is still showing in the list? There should be a filter that makes it so that only conversations with >0 messages should show up there... 🤔

**Comment by moezbhatti** [comment]
Fixed in 335c5757c44db9aa6d713ea3a5649d0630408da6
