### ISSUE TITLE
No Contact Photo When Message is to/from email address

### ISSUE THREAD

**Issue by metalx1000** [moezbhatti/qksms#1487]
### DESCRIPTION
Text Messages can be received/sent to email address, but the contact's photo doesn't show up in qksms if this is the case.

### STEPS
1. Create a contact who's mobile number is an email address
2. Add a Photo for that contact
3. send/receive a message to this contact in qksms
4. Contact's image doesn't not appear in qksms

### EXPECTED
Contact's photo should appear in qksms.

### OBSERVATIONS
I have alerts texted to me from my credit card companies.
Example: 
Discover card sends the alerts from Mobile Number 1347268 (this works ok)
Synchrony Bank send their alerts from customer.service@mail.synchronybank.com (this does not show contact photo)

The messages come through fine, but if the contact has an email address as their mobile number the contact photo does not show up.

I also experience this when I send myself alerts from my web server.  under certain events my server sends my phone alerts through email as a text, but the contact photos don't show up if this is the case.

See below image with message from synchrony bank:
![576-1024](https://user-images.githubusercontent.com/1002290/64478200-de71fd00-d172-11e9-8d7b-e0e300984150.png)

![576-1024 (1)](https://user-images.githubusercontent.com/1002290/64478218-298c1000-d173-11e9-8ecc-0e9fceb39426.png)

**Comment by moezbhatti** [comment]
Related to #653
