### ISSUE TITLE
Broken app link

### ISSUE THREAD

**Issue by GeoZac** [moezbhatti/qksms#1491]
### DESCRIPTION
Broken **Should I Answer** link
The link in the blocking managers to the _Should I answer_ plugin is broken

### STEPS
1. Open app and navigate to blocking in Navigation drawer
2. in Blocking manager, Try the link next to Should I answer

### EXPECTED
Take me to the Play Store page of Should I answer app

### OBSERVATIONS
Returns a app not found page 

_The link at the official [website](https://www.shouldianswer.com/) also links to non-existent page_

**Comment by moezbhatti** [comment]
Yikes, it looks like their app isn't discoverable on the store at all. I'll reach out to them about it

**Comment by moezbhatti** [comment]
[Looks like it's back up](https://play.google.com/store/apps/details?id=org.mistergroup.shouldianswer)
