### ISSUE TITLE
Distored icon when swiping a conversation to the left

### ISSUE THREAD

**Issue by scharmach** [moezbhatti/qksms#1504]
### DESCRIPTION
Swiping a conversation to the left distorts the icon if a gesture is set up.

### STEPS
1. Open app
2. Swipe any conversation to the left
3. The gesture-icon is distorted

### EXPECTED
This is the behaviour when you swipe to the right:

![grafik](https://user-images.githubusercontent.com/9080980/65817011-a0607a00-e202-11e9-89af-7dcbeb3ee2f6.png)

### OBSERVATIONS
I would expect the same for a swipe to the left and that the icon does not distort like this:

![grafik](https://user-images.githubusercontent.com/9080980/65816986-64c5b000-e202-11e9-8557-4aefc32716ee.png)

**Comment by GeoZac** [comment]
Duplicate of #1503

**Comment by scharmach** [comment]
Ups, sorry. Searched for this but somehow missed it.
