### ISSUE TITLE
QK Reply broken on Android 10

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1509]
Related to https://developer.android.com/guide/components/activities/background-starts

**Comment by zksteel** [comment]
Hi. I've just installed QKSMS on my new phone with Android 10, and notice there is no QK Reply which I miss so much. Could you clarify that new Android restrictions means that QK Reply won't work on system version 10 and above? Or there is some kind of setting in system that cound bring back this functionality?

**Comment by moezbhatti** [comment]
Hmm.. I just tested this on Android 10 and 11 and it seems to be working fine. At least on the latest `master`. Going to close this for now
