### ISSUE TITLE
Tapping a thread to view it sometimes becomes unresponsive

### ISSUE THREAD

**Issue by e-t-l** [moezbhatti/qksms#1511]
### DESCRIPTION
Tapping a thread in order to view the conversation will randomly stop working. The issue is temporarily fixed by Force-Stopping and clearing the cache. 

### STEPS
1. Have QKSMS installed for a bit. 
2. (possibly related?) Send an SMS from a 3rd party app such as Google Assistant or Microsoft's Your Phone. (not sure if this is at all relevant, but it's the only non-standard behavior I can think of) 
3. Try to open a conversation by tapping its thread. 

### EXPECTED
Selecting a thread should open the conversation view of that thread. 

### OBSERVATIONS
From the widget, selecting a thread simply opens the most recently viewed conversation instead. From within the app, tapping a thread does nothing, and the app stays on the list of threads.

**Comment by e-t-l** [comment]
There doesn't seem to be any particular behavior that causes it. I keep noticing it at random times, when I've used QKSMS recently as well as when I haven't for a while. I was able to use a screen recorder to capture the bug in action and I uploaded to video here: https://imgur.com/a/mBT5AKP

**Comment by moezbhatti** [comment]
I wonder if this might be related to opening the app via the widget. If you force close the app and then only open conversations from within the app, do you continue seeing this issue?

**Comment by e-t-l** [comment]
No, forcing closing temporarily solves the issue. 

I thought this might be a problem with notifications and not specifically the widget, because sometimes opening a new text notification will result in the nonresponsive thread view, but I haven't been able to recreate this reliably.

It seems possible that it's an issue of the app trying to open a conversation "cold", i.e. from something outside of the app itself, like a notification or widget, without opening the app itself first. I only think this because I've been able to minimize the occurrence of these issues by keeping QKSMS running in the background and never closing it entirely.

**Comment by e-t-l** [comment]
Possibly related to the above theory is the following:

Steps
1. Ensure QKSMS is not already running in the background
2. Open a conversation from the widget
3. Press the back arrow 

One would expect this to bring up QKSMS's main thread view, but instead, it just returns to the home screen. This behavior IS reliably reproducible for me, so it would be good to know a) if other users can reproduce this, and b) if this was possibly the dev's intended behavior for this action.

**Comment by e-t-l** [comment]
Further experimentation indicates this may be a bug related to screen overscan. When overscan is enabled via ADB or through apps like Fluid NG or XDA Navigation Gestures, multiple bugs relating to SMS notifications occur. Disabling overscan appears to mitigate the QKSMS issues reported in this thread. However, a perment fix that allows QKSMS to be used in conjunction with screen overscan is still desirable.

**Comment by moezbhatti** [comment]
Closing this for the reasons we discussed via email :)
