### ISSUE TITLE
Schedule messages from csv

### ISSUE THREAD

**Issue by austinstoker** [moezbhatti/qksms#1514]
It'd be nice to be able to schedule a bunch (100+) messages from something like a csv import. I want to write birthday messages to a bunch of people in our organization in advance. It's easier to type that much on a computer plus a spreadsheet could fill the send date and time for me.  I realize this is more a feature request than a bug. If there is somewhere else o should add it I'd be glad to. Love what you're doing here. Thanks!

**Comment by moezbhatti** [comment]
Appreciate the suggestion, but I can't imagine very many people would actually go through the effort of using this, so I don't think it would be worth the complexity of building the feature and explaining how to use it properly - so I'm gonna table the idea for now
