### ISSUE TITLE
Can only save 1 picture in media directory

### ISSUE THREAD

**Issue by 05nelsonm** [moezbhatti/qksms#1518]
### DESCRIPTION
Saving pictures does not seem to create a new file, but writes over a previously saved picture

### STEPS
1. Save multiple pictures to media
2. Experience the madness

### EXPECTED
To save media as separate files

### OBSERVATIONS
Overwriting of previously saved media

**Comment by moezbhatti** [comment]
What version of the app are you experiencing this on?

**Comment by 05nelsonm** [comment]
3.7.3

**Comment by moezbhatti** [comment]
What's the filename of the image being saved?

**Comment by 05nelsonm** [comment]
It's saving them as image.jpg

**Comment by moezbhatti** [comment]
Ah! Okay thank you, this was a definite oversight by me. I'll get this fixed in the next update
