### ISSUE TITLE
Contact name appears as "null"

### ISSUE THREAD

**Issue by texneus** [moezbhatti/qksms#1519]
### DESCRIPTION
After upgrading to 3.7.3 this morning from FDroid, one person in an existing 4-way MMS thread shows as 'null' with no contact picture in the entire thread.  Prior to the upgrade it was normal.  

Ex:
![Screenshot_20191030-152949_1](https://user-images.githubusercontent.com/23441049/67919621-1b54e180-fb6f-11e9-9a40-a3161f80839a.png)

### STEPS
Not sure this is easily reproduced.  I originally installed 3.7.2 a couple of weeks ago.  Established a 4-way MMS (myself plus 3 others) in 3.7.2, then upgrade to 3.7.3.  One of the contacts is now changed to 'null' with a default avatar.

### EXPECTED
All contacts should appear named and with their contact picture when the thread is opened.

### OBSERVATIONS
Just this one lone contact in an existing thread that showed OK prior to the update seems to be affected.  All others in the thread are normal.

Despite 'null' appearing in place of a name within the thread, the name/picture of all MMS participants appears correctly on the QKSMS 'home screen' for this message.

Inside the thread, long pressing an affected text then "i" shows the proper phone number is being received and matches contact info.  The name also appears at the top of the screen along with other thread participants.
 
One on one texts received from the affected individual (SMS or MMS) still works as expected.

When syncing QKSMS to the Android SMS database, the correct name DOES appear on affected texts in the default Android 10 messaging app.  I am running GrapheneOS and believe the included messaging app is from AOSP.

I also have a 3 way (myself + 2 other participants) and that seems to be OK, but the problematic user isn't in that conversation.

**Comment by moezbhatti** [comment]
Thanks for the details, I've had a couple reports about this. Would you mind testing out v3.7.4 and see if resolves the issue? I wasn't able to see if it solves this issue exactly myself, but it did solve some other problems where names or contact photos wouldn't show up

**Comment by texneus** [comment]
Downloaded and manually installed 3.7.4 from github.  Unfortunately, no change with 3.7.4.

**Comment by moezbhatti** [comment]
Fixed in 76c89dfed6894dc6e8bd61ac38a84679c957a608

**Comment by texneus** [comment]
I can confirm it is working now in 3.5.7.  Thank you!

**Comment by moezbhatti** [comment]
Excellent!
