### ISSUE TITLE
Cannot add GIF from GBoard or SwiftKey [Android 7.0]

### ISSUE THREAD

**Issue by JonTabor** [moezbhatti/qksms#1520]
### DESCRIPTION
When using either GBoard or SwiftKey keyboard on Android 7.0, I'm unable to add a GIF to an existing or new conversation.  Tapping the GIF from the keyboard does nothing

### STEPS
1. Install either GBoard or SwiftKey keyboard (possibly others)
2. Start a new conversation in QKSMS, or enter an existing one 
3. Attempt to add a GIF using the keyboard app's built-in search tool

### EXPECTED
GIF is added to the conversation and can be sent to the recipient

### OBSERVATIONS
Nothing happens; tapping the GIF does not change anything

**Comment by moezbhatti** [comment]
I just tried this and it seems to be working fine. Perhaps it was fixed by accident. I'm going to close this for now, but please feel free to comment if you're still experiencing the issue. In that case, would you also mind sharing a video of the problem?
