### ISSUE TITLE
Images not saving to gallery 

### ISSUE THREAD

**Issue by BigPabby79** [moezbhatti/qksms#1521]
### DESCRIPTION
A short description 
Images are not saving to gallery.

**Comment by moezbhatti** [comment]
Can you provide some more detail?

The files are expected to be in the `sdcard/QKSMS/Media` directory

**Comment by BigPabby79** [comment]
When someone sends me more than one picture and I go to save them to my gallery only one image shows up in the media folder. If I try to save another picture it overwrites the last picture in the media folder. Used to they all just saved to the pictures folder no problem. 

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 12, 2019 at 8:22 PM, Moez Bhatti<notifications@github.com> wrote:   
Can you provide some more detail?

The files are expected to be in the sdcard/QKSMS/Media directory

**Comment by moezbhatti** [comment]
Ah, gotcha. This was fixed in https://github.com/moezbhatti/qksms/commit/7b9aa89d17f4257b0efd652ee661cb810f286f62

**Comment by BigPabby79** [comment]
Awesome, thank you. 

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 13, 2019 at 8:52 AM, Moez Bhatti<notifications@github.com> wrote:   
Ah, gotcha. This was fixed in 7b9aa89
