### ISSUE TITLE
3.7.8 (upgraded to) - all texts stuck at "Sending".

### ISSUE THREAD

**Issue by MyFirstChoiceWasTaken** [moezbhatti/qksms#1523]
Since my Moto G6 updated to 3.7.8 through the Play store, QKSMS can only receive.

Attempts to send messages results in the status sticking at "Sending". A long press on the message and bringing up the information relating to the message shows a "Sent" time but the recipient never receives the message.

Reverting back to 3.7.4 via the F-Droid APK restores operation.

This is on the paid-up through the Play store QKSMS+ version, I doubt that the following is causing the issue but for completeness here are the changes to my configuration choices:

Night Mode - Always on
Pure Black night mode - on
Font size - large
Use System Font - on
Delayed sending - long.

Note: My G6 is of the dual SIM variety with different networks in each slot. I cannot send a text with either unless I revert back to 3.7.4.

**Comment by alekksander** [comment]
just came here to report this. this is happening on 3.7.6 too and disabling delayed sending (as i just discovered, so perhaps not tested intensively enough) seem to be fixing it. mms doesn't handle delayed sending and works okay all time, so 99% delayed sending is at fault here ;)

**Comment by GeoZac** [comment]
Can't reproduce the issue both with delayed sending enabled and disabled, on a device running Pie based custom ROM.

_Maybe adding more info about the Android version and Device info may help dev better debug the issue._

**Comment by alekksander** [comment]
@GeoZac You are right. clean android 8.1 here

in my case delayed sending was set to short. how are You testing it? as i said it happens at random and if i send 10 messages with number respectively from 1–10 sometimes all are send fine, other times only one doesn't, but it also happen that only few went out.

**Comment by MyFirstChoiceWasTaken** [comment]
My Moto G6.

![Moto_G6](https://user-images.githubusercontent.com/42274005/69247258-0aadef00-0ba2-11ea-9235-03d7aaf3e96d.png)

Stock ROM, no changes or rooting.
