### ISSUE TITLE
Dual SIM card numbers mixed up?

### ISSUE THREAD

**Issue by zelleb** [moezbhatti/qksms#1524]
So I've got 2 SIM cards an set SIM 1 as standard for SMS in Android settings.

That little bottom right SIM icon in QKSMS has a "1" inside. All good. But once I send a message there's a SIM icon with a "2" above the conversation and vice versa.
![Screenshot_20191120-191917](https://user-images.githubusercontent.com/19358704/69266673-e36c1780-0bcb-11ea-9cff-dfef16c152af.jpg)

The first message was sent from SIM 1 which ends with 22. Second message from SIM 2 ending in 572. First reply was sent to SIM 1, second to SIM 2.

The last 4 messages where sent and received from and to SIM 1, but the little sim icon above them shows a 2 whereas the bottom right icon shows a 1.

I hope that makes sense.

**Comment by moezbhatti** [comment]
If you go into the app's settings and click Sync messages, does that seem to fix the issue?

And by any chance have you swapped the physical sim card positions recently?

**Comment by zelleb** [comment]
Syncing doesn't fix it. I had the same issue with my last phone. Same cards but swapped. 1 was in slot 2 and 2 was is slot 1.

I also switched from F-Droid to Play Store version just to test, but still the same.

**Comment by moezbhatti** [comment]
Fixed by @ewft in 13509d0d66dec05cb445331e77a9b1bfdf389f15
