### ISSUE TITLE
[Feature Request] SMS Broadcast Group

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [moezbhatti/qksms#1527]
### DESCRIPTION
I would like to group contacts under a name and reuse the group name to broadcast SMS to group of contacts and not MMS.

**Comment by moezbhatti** [comment]
Added in 7fbed6750570a40d3bc21d2d8b6fcd3d563b8233

**Comment by PrasannaVenkadesh** [comment]
@moezbhatti Thanks a lot for pointing out. I guess it is not released yet. Right?

**Comment by moezbhatti** [comment]
Correct - it'll be released in the next week or so!
