### ISSUE TITLE
SMS discarded - System notification

### ISSUE THREAD

**Issue by smarquespt** [moezbhatti/qksms#1529]
### DESCRIPTION
SMS is discarded when dismissed from notification

### STEPS
1. Receive SMS
2. Slide notification bar
3. Clear all

### EXPECTED
Notification discarded but SMS stored

### OBSERVATIONS
SMS is not shown in Qksms conversation

Notes:
QKReply Inactive
QKSMS latest
Andoid 9 (november patch)
Xiaomi Mi A1

**Comment by jkelly99** [comment]
Same condition here.
LineagOS 16
Moto G5 Plus

**Comment by lfourquaux** [comment]
Same here (LineageOS 16).
The SMS shows up if I sync with the Android database (from QKSMS settings).

**Comment by smarquespt** [comment]
Same here as @lfourquaux said.

**Comment by smarquespt** [comment]
Another issue, maybe related. 

1. Receive SMS
2. Tap notification to open QKSMS
3. Go back (arrow)

QKSMS does not retain it. Sync database returns sms back

**Comment by moezbhatti** [comment]
This was fixed in https://github.com/moezbhatti/qksms/releases/tag/v3.7.7

The update should be finally appearing on F-Droid shortly
