### ISSUE TITLE
Not all recipients in group MMS are receiving messages

### ISSUE THREAD

**Issue by texneus** [moezbhatti/qksms#1531]
### DESCRIPTION
When I send a group MMS not everyone in the recipient list receives the message.  I have had this problem since 3.7.5, and I've confirmed the problem still exists on 3.7.9 installed from here.  Sorry for just getting around to reporting this but every time I went to do so, I saw a new version with fixes that sounded like it might address this.

It is similar to #1519 in that only group MMS message are affected, except this is impacting a different person.  I don't believe this issue existed prior to 3.7.5.

Might also be related or identical to  #1528

### STEPS
Send a group MMS
Verbally confirm receipt with recipients, or wait until you realize one person in the thread doesn't know what's going on because they can't see what you said ;-)

### EXPECTED
All recipients listed should receive the MMS.

### OBSERVATIONS

- All outward appearances are that the MMS has been sent successfully to all recipients.
- The same individual is affected in multiple MMS threads.  **Perhaps coincidentally, this person is also listed last in all my MMS group texts.**
- I am able to send/receive SMS and MMS from the same person individually.  Only group MMS seems to be a problem.
- I am receiving group MMS threads from everyone in QKSMS, even the person who I can't seem to send to.  This is definitely an "I can see them, but they can't see me" issue.
- I enabled "Delivery Confirmations" to see if that might lead to any clues, but I don't see any confirmation information at all...I might not understand how this function is supposed to work.

When reverting to the Android 10 AOSP messing app on my phone:
- I see the MMS messages I have sent in QKSMS and they are in the same thread with all recipients listed.
- If I send messages in the same thread from AOSP everyone receives the message.

**Comment by moezbhatti** [comment]
I believe this should actually be fixed along with #1528! Would you mind testing this on version 3.7.10 and let me know if you're still experiencing the problem? I'll close the issue for now :)
