### ISSUE TITLE
QKSMS not showing contacts

### ISSUE THREAD

**Issue by Zafrkant** [moezbhatti/qksms#1532]
Hi,

Thank you for great contribution to community.
I'm using Xiaomi Mi Mix 2, Lineage OS 16.
With newest version 3.7.6 on F-Droid i have issue that QKSMS not showing contacts names for new conversations only those that initiated from other side. When I sent SMS everything is showing fine.
I've rolled back to 3.7.4 where everything is fine.

Best Regards, Zfk

**Comment by moezbhatti** [comment]
This has been fixed in 3.7.9
