### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ishigo1987** [moezbhatti/qksms#1533]
Hello @moezbhatti  how do you make to keep your app awake an recieve sms in background when the phone have the screen turn off on android 8+ without ongoing foreground notification and no FCM

**Comment by moezbhatti** [comment]
It doesn't need to be awake. The SMS intents have special permission by the android system to make sure that they get delivered regardless of the wake state of the phone

**Comment by ishigo1987** [comment]
thank you for your rapid answer can you provide me please a link about what you say?

**Comment by moezbhatti** [comment]
I'm sorry, I can't remember where I learned that information from. But the point is that in my case, I didn't have to do anything special, because I'm listening for Intents that are fired by the system. If I was to set up my own custom intents, then I would need some sort of foreground service

**Comment by ishigo1987** [comment]
ok thank you
