### ISSUE TITLE
Disable / cancel flash sms pop ups class 0 sms

### ISSUE THREAD

**Issue by rancidfrog** [moezbhatti/qksms#1536]
My network operator has increased the rate of flash SMSes causing pop-ups to occur all the time.

I do not want to click on okay by mistake, which will subscribe to silly services.

Is there a way to block/disable these flash sms, class 0 sms?

Or an automatic way to cancel, as clicking okay results in charges?

Thank you

**Comment by moezbhatti** [comment]
Hmm, how do these even work? I thought the whole idea of a class 0 SMS was that it doesn't get stored to the phone. QKSMS stores all messages to your device, but I don't think there's even a way for me to detect that an SMS is class 0.

Any chance you could show a screenshot of what these messages look like? I haven't experienced them myself

**Comment by rancidfrog** [comment]
![](https://i.imgur.com/eg8RHVh.png)
There might be nothing apps can do. It might be directly handled by android. I am not sure, but there might be a check for class 0 do not pass on message to apps somewhere in https://android-review.googlesource.com/#/c/14069
```
if (sms.isTypeZero()) {
            // As per 3GPP TS 23.040 9.2.3.9, Type Zero messages should not be
            // Displayed/Stored/Notified. They should only be acknowledged.
            Log.d(TAG, "Received short message type 0, Dont display or store it. Send Ack");
            return Intents.RESULT_SMS_HANDLED;
        }
```
So, changes need to be made on OS level it seems to be.
 
Android unfortunately handles class 0 sms by `return Intents.RESULT_SMS_HANDLED; `
Whereas normal sms goes through proper channels `return dispatchNormalMessage(smsb); `
https://android.googlesource.com/platform/frameworks/opt/telephony/+/master/src/java/com/android/internal/telephony/gsm/GsmInboundSmsHandler.java

That means devs need to add fix if they want to change behaviour in ROM source, otherwise clicking okay can trigger undesirable charges

**Comment by moezbhatti** [comment]
Very interesting, I haven't seen these before. You say these are coming directly from your carrier? That sounds pretty awful - sorry you have to deal with that

Thanks for looking into this by the way
