### ISSUE TITLE
Add option to have dark app bar color in dark  mode

### ISSUE THREAD

**Issue by The0x539** [moezbhatti/qksms#154]
I like night mode. I like colored message bubbles, even in night mode. However, I do not like colored app bars in night mode An actual separate app bar color option would be a bit clunky, and clunkier still if there were a separate separate one for the dark theme. A simple switch, though, to make the app use [this](https://i.imgur.com/XYwt0r3.png) color _only for the app bar_ in dark mode and actual black in AMOLED mode, is something I think could work quite nicely.

**Comment by moezbhatti** [comment]
The dark theme in QKSMS 3.0 now has a dark toolbar!
