### ISSUE TITLE
BUG: qksms doesn't input the auto-fill text into the text field when redirected to from the other app

### ISSUE THREAD

**Issue by aha999** [moezbhatti/qksms#1542]
### DESCRIPTION
When a certain ride-finding app has a send the message to that person - button to contact via sms, It inputs the predefined text into the regular SMS app just fine, but the qksms puts that text next to the number which you're sending the message to, instead of putting it into the send message field (see screenshots below of what i mean)

### EXPECTED
When i press the message button in the app that adds a text into the sms text field it should redirrect me to the qksms app AND put the predefined text into the text field for sending or editing before sending.

![photo_2019-12-18_19-39-27](https://user-images.githubusercontent.com/50620416/71114573-5f0fb300-21d0-11ea-9517-a73ff8d729ac.jpg)
![photo_2019-12-18_19-39-38](https://user-images.githubusercontent.com/50620416/71114586-63d46700-21d0-11ea-8032-41753e80d801.jpg)
![photo_2019-12-18_19-39-41](https://user-images.githubusercontent.com/50620416/71114594-6767ee00-21d0-11ea-867f-67ee8d992b31.jpg)
![photo_2019-12-18_19-39-46](https://user-images.githubusercontent.com/50620416/71114600-68991b00-21d0-11ea-84f5-999b6fb96e5a.jpg)
![photo_2019-12-18_19-39-50](https://user-images.githubusercontent.com/50620416/71114605-69ca4800-21d0-11ea-810a-8c0d7071506f.jpg)

**Comment by moezbhatti** [comment]
Fixed in 65fd1cacdba72aad929c852b016dff1e361dfeb3
