### ISSUE TITLE
How to display only message phone type Mobile

### ISSUE THREAD

**Issue by sonlv-enguys** [moezbhatti/qksms#1546]
The message list is also showing contacts without phone numbers. I wish it only showed those messages that had phone numbers.
Thank you

**Comment by moezbhatti** [comment]
The message list, or the contact list?

**Comment by moezbhatti** [comment]
You can turn this on using the "Mobile numbers only" setting

**Comment by m-alice** [comment]
Sadly, buy when you have a few numbers in one contact, and set first number as non-**mobile** - then you cannot see it. Even if another numbers in this contact set as **mobile**.
Example:
Name1 Surname1

**Comment by m-alice** [comment]
Sadly, but when you have a few numbers in one contact, and set first number as non-mobile - then you cannot see it (when forwarding a SMS). Even if another numbers in this contact set as mobile.
Examples:

This contact you can see in QKSMS
```
Name1 Surname1
+XXXXXXXXXX Mobile
+XXXXXXXXXX Home
+XXXXXXXXXX Home
```

This contacts you cannot see in QKSMS
```
Name2 Surname2
+XXXXXXXXXX Home
+XXXXXXXXXX Mobile
+XXXXXXXXXX Mobile
```

It is a bug or not?
