### ISSUE TITLE
"CHANGE" button doesn't work for setting QKSMS as the default SMS app

### ISSUE THREAD

**Issue by Kemo-Huang** [moezbhatti/qksms#1548]
### DESCRIPTION
There is no response for the "CHANGE" button at the bottom of the screen if I choose "NO" for the Android default SMS app dialog at the first time when I open the app. If I want to set QKSMS as default, I have to close and reopen the app to let the dialog display. QKSMS version: 3.7.10. Android version: 9

### STEPS
I.
1. Set the other SMS app as default.
2. Open QKSMS.
3. Click "No" in the popping dialog to not change the default SMS app.
4. Click "CHANGE" button at the bottom of the screen.

II.
1. Open QKSMS (already the default app).
2. Set the other SMS app as default without closing QKSMS.
3. Click "CHANGE" button at the bottom of the screen.

### EXPECTED
Pops the dialog again.

### OBSERVATIONS
No response.

**Comment by Uhter** [comment]
A temporary solution works for me: just reinstall.
