### ISSUE TITLE
Add option to display two separate icons for sim cards

### ISSUE THREAD

**Issue by tukusejssirs** [moezbhatti/qksms#1549]
### DESCRIPTION
In text message composition, add option to display two separate icons for sim cards on dual sim phones.

### STEPS

1. Open the app.
2. Create new message.

### EXPECTED

Two separate icons for SIM1 and SIM2.

I'd might be even better if these two icons (SIM1 and SIM2) would substitute the send button, i.e. when one clicks on them (after the message composition), that message would be sent using that particular SIM card.

### OBSERVATIONS

One icon that toggles SIM1 and SIM2. (There might be an option to toggle this behaviour, i.e. one might want the current behaviour, others the proposed one.)

---

Related #1524 #1479 #1395 #1382

**Comment by moezbhatti** [comment]
Hmm, I'm not sure if I like this solution myself. Either it would be unclear how to send a message (if the icons just look like sim cards) or it would look like there's a bug in the app that's causing it to show two send buttons. What problem would this be solving exactly?

I'm going to close this for now, but I'm open to discussing and reconsidering
