### ISSUE TITLE
Non-Contact as Spammer

### ISSUE THREAD

**Issue by peylight** [moezbhatti/qksms#1562]
Please add an option for non-contact as spammer and block it.

**Comment by moezbhatti** [comment]
This is already possible. You can block them via the conversation settings, or you can pre-emptively and manually block the phone number from the blocking settings

**Comment by peylight** [comment]
It's different as what i say.
If you have every time spam text from any numbers, then you will be tired to block one by one.
So i want to block once non-contact at once.

**Comment by GeoZac** [comment]
@peylight If you mean to block all spam messages, you could use one of the blocking manager supported by qksms.
