### ISSUE TITLE
How to activate SMS receipt ?

### ISSUE THREAD

**Issue by webmasterpf** [moezbhatti/qksms#1567]
### DESCRIPTION
I don't find how to set active the option to know if SMS was received or read.

### OBSERVATIONS
I don't find a documentation on this.

Thanks

**Comment by webmasterpf** [comment]
Found it. Fixed.

**Comment by Gaspacchio** [comment]
That's great news @webmasterpf, you should consider closing this issue now that it's resolved 👌
