### ISSUE TITLE
Sending MMS attachments fails when compression set to automatic

### ISSUE THREAD

**Issue by foafron** [moezbhatti/qksms#1569]
### DESCRIPTION
Sending images fail when Auto-compress MMS attachments set to automatic

### STEPS
1. verify Auto-compress MMS attachments is set to "automatic"
2. attach a photo
3. attempt to send

### EXPECTED
The image should appear in the message list and recipient should receive message

### OBSERVATIONS
No indication of message being sent occurs (just like there never was a message) and the recipient doesn't receive the message.  If I select a compression level other than Automatic, the message sends

**Comment by foafron** [comment]
I have updated to 3.8.1, if I clear the apps data in the storage section the first photo will now send. But then further images will silently fail again.

**Comment by moezbhatti** [comment]
Unfortunately nothing can really be changed here - the app is simply reading the default settings from the system. The solution is for the user to manually override the compression setting with something conservative like 600KB

**Comment by e-t-l** [comment]
@moezbhatti this relates to #1510, #1809, and #1743. For what it's worth, I've found a reliable workaround: 
1. Set compression to 600KB. 
2. Send a picture MMS (I usually just send it to myself)
3. Set compression _back_ to Auto.
4. **Auto-compression will now work as expected.**

I don't know why this is happening precisely, but it's definitely a bug that could be fixed. (For now, the "fix" could even be to have QKSMS silently change compression to 600KB, send a photo to a black-hole phone number, change compression back to Auto, and attempt to resend the previously-failed MMS.) 

I recommend reopening this issue.
