### ISSUE TITLE
Conversation message counts not automatically displayed when option ticked.

### ISSUE THREAD

**Issue by JonShepChen** [moezbhatti/qksms#157]
Pretty similar issue compared to #106 

If I go to "Settings -> Appearance -> Message Count" and go back to my conversation list, the conversations that were already being displayed on the screen before aren't updated with message counts until I scroll them off-screen and manually invoke a redraw by scrolling back up.

**Comment by moezbhatti** [comment]
The message count feature has been removed in QKSMS 3.0

I will later on be adding a place to view conversation statistics, but it will not be visible in the conversation list like it is now
