### ISSUE TITLE
better Legibility for drafts

### ISSUE THREAD

**Issue by vramazani** [moezbhatti/qksms#1576]
Suggestion: either make the text **bold** to stand out _OR_ add a section in the left drawer menu

**Comment by jstetten** [comment]
Yes, please. Drafts have been bumped to the top, but we really need a better way to distinguish them at a glance, like Google Messages does.

I would like to see drafts bolded, italicized, or — even better — highlighted in the appropriate contact's color. That would be quite amazing.

**Comment by moezbhatti** [comment]
Great idea - many people have complained wondering why their inbox isn't in chronological order, not realizing that drafts are sorted to the top. This would solve that
