### ISSUE TITLE
Altered ends of text messages content!

### ISSUE THREAD

**Issue by otede** [moezbhatti/qksms#1577]
### DESCRIPTION
Sometimes ends of text messages get altered. There are actual words but the end of the message does not match the end of the original sent message. I've noticed it the very first time with QKSMS and never with Google's app. 
Screenshot
https://1drv.ms/u/s!AvyUQyNGJs9mke9fg3eKbt5_979g4w?e=GEzPhH

### STEPS
1. Use regular texting without character stripping or any other alterations to the default settings of the app relating to message contents.

### EXPECTED
Messages delivered reliably.

### OBSERVATIONS
Messages delivered in a damaged state sometimes. I've observed the behavior 2 or 3 times since December 2019.

Notably, the word "faceta" is not present in the entire database of my messages. The database is several months old. My original theory was that QKSMS glitches an end of an old message and replaces the end of a new messages with it. It doesn't seem to be the case unless it happens with some database leftovers.

Device and install info
Brand: Motorola
Model: XT1562
Product: Moto X Play
Display: lineage_lux-userdebug 7.1.2 NJH47F f8afa703eb
Display Width: 1080
Display Height: 1776
Display Density: 3.0
Android version: 7.1.2
Preloaded: false
IsTablet: false

WebView version: 79.0.3945.93

Network operator: 26002 / T-Mobile.pl
Locale: en_GB
isRTL: false

Arch: armv7l
Arch supported: [armeabi-v7a, armeabi]
Orientation: Portrait
Resources-Folder: values-v24

Internal storage: 2 GB / 10 GB
External storage: 2 GB / 10 GB
SDCardStatus: null
Installer: com.android.vending
Rooted: false
Xposed: false

**Comment by moezbhatti** [comment]
Incredibly strange. Thanks for checking that that message text doesn't exist anywhere  else in your database - your guess would have been the same as mine

Is this an actual word in your language? Or is it just a random string of letters

**Comment by otede** [comment]
> 
> 
> Incredibly strange. Thanks for checking that that message text doesn't exist anywhere else in your database - your guess would have been the same as mine
> 
> Is this an actual word in your language? Or is it just a random string of letters


All of the words there are actual Polish words. Interestingly "faceta" (the Polish word for guy) is not in it's basic form. The word has a changed form due to https://en.wikipedia.org/wiki/Declension What that means? It means the word, with high probability, comes from an actual sentence where its form had to fit the context. That's why my first action was to check whether it jumped over from some other message in the system-wide (shared) text message database.

OK, I have now confirmed that the issue is independent from your app. It most surely happens between me and the sender/recipient as we are in different countries. How I know? I've been using Google Messages for the past days *exclusively*.

**Comment by moezbhatti** [comment]
Oh wow, very strange indeed. Did you ever figure out what exactly was causing this?

**Comment by otede** [comment]
> 
> 
> Oh wow, very strange indeed. Did you ever figure out what exactly was causing this?

No, never.

**Comment by moezbhatti** [comment]
Please let me know if you do - I'm very curious

**Comment by otede** [comment]
Will do! I suspect roaming. Polish T-Mobile is my provider but I currently reside in Netherlands.
