### ISSUE TITLE
Details page: Move theme button down into list

### ISSUE THREAD

**Issue by sphh** [moezbhatti/qksms#1580]
### DESCRIPTION
As described in #1579, my phone as a tiny display.

The details page puts the `Theme` button beside the contacts name and mobile number:
![Screenshot_20200217-124134](https://user-images.githubusercontent.com/4856462/74650942-0e421980-5183-11ea-9e9d-c1df80171287.png)
If the name is longer than that one displayed in the screenshot, it will use more than one line. This is good. But even better would be to move the `Themes` button down into the list of `Notifications`, `Archive`, … to get more space to display the name.

This would have the positive side effect, that the button gets a description, e.g. `Theme for this conversation`.

### STEPS
1. Open a conversattion
2. Click on the three vertical dots to open the `Details` page

**Comment by moezbhatti** [comment]
Appreciate the suggestion - but then this would break the ability to apply a colour for individual contacts in a group chat. I can't think of a simple way to buy back screen real estate while keeping that functionality, any suggestions here?

**Comment by sphh** [comment]
I was never part of a group chat per text message. Could you please post a screenshot how the `Details` looks like for a group chat? Thanks.

**Comment by moezbhatti** [comment]
![Messages - Settings](https://user-images.githubusercontent.com/4358785/74684607-5b7db580-519a-11ea-90df-ae25319a2e90.png)

**Comment by sphh** [comment]
Thanks. I see …

The only idea I have is the following: Either add a menu which pops up when pressing long on the contact or add a three dots menu button instead of the themes buttons.

BTW does `Block` block one or all members of the group?

**Comment by moezbhatti** [comment]
Currently it'll block all members in the group - which only recently occurred to me as a potential problem
