### ISSUE TITLE
Filter text before sending SMS

### ISSUE THREAD

**Issue by JoshuaFry** [moezbhatti/qksms#1582]
This is a question rather than an issue.

I am looking to view the content of a text message the user is trying to send before it is officially sent out. I want to block the text from being sent then notify the user of this action.

What would be the best way to do this using qksms?
Also, Is there an official documentation for qksms?

**Comment by moezbhatti** [comment]
https://github.com/moezbhatti/qksms/blob/0ba3ab5839d799551fe4bf2de5585026a157842a/presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt#L625

**Comment by JoshuaFry** [comment]
Thank you!
