### ISSUE TITLE
Create a backup button is not centered

### ISSUE THREAD

**Issue by aha999** [moezbhatti/qksms#1583]
'Create a backup' button at the bottom is not centered.
App version: 3.8.1 (fdroid)

![](https://i.imgur.com/HQSdYbp.png)

**Comment by GeoZac** [comment]
It's due to the length of the string in that language.

Setting a character limit should keep the view compact

**Comment by aha999** [comment]
@GeoZac maybe, but it will still not be centered

**Comment by GeoZac** [comment]
@aha999 The makeshift "Extended FAB" is not supposed to be centred, this by design

**Comment by moezbhatti** [comment]
It's supposed to be right-aligned. Just looks weird here with the long string
