### ISSUE TITLE
contact search bar RTL bug

### ISSUE THREAD

**Issue by disdagithubacc** [moezbhatti/qksms#1590]
### DESCRIPTION
can't see the letters being typed on contact search bar
### STEPS
1. click on the floating compose button
2. change keyboard to Persian
3. can't read the first or two typed letters in the search bar

### OBSERVATIONS
![Screenshot_2020-03-06-01-26-04](https://user-images.githubusercontent.com/61764238/76030770-43de5500-5f2e-11ea-9c84-63f2e0481351.png)

### my device information
LG G4 H818P
android version 7.0
rooted: no
screen density: 544 dpi
keyboard language switches between English(US) and Persian
System default language: English(US)

**Comment by GeoZac** [comment]
Adding info like Android version and system language might help in resolving the issue faster

**Comment by disdagitacc** [comment]
yea sorry
> Android version  
nougat 7.0 stock LG H818P
> system language
English(US)
