### ISSUE TITLE
QKSMS connects to external servers in the background

### ISSUE THREAD

**Issue by f6zhdkw6** [moezbhatti/qksms#1598]
### DESCRIPTION
QKSMS connects to external servers without asking the user.

### STEPS
1. Install the app for the first time. https://github.com/moezbhatti/qksms/releases/tag/v3.8.1

2. Open the app

3. Then you will see that the QKSMS app connects to several external servers in the background without asking the user.

You can check it for example with Adguard Android. https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v3.3.230

**Comment by GeoZac** [comment]
Thw github release of QKSMS are of **WithAnalytics**  variant with analytics libraries for crash reports.
But F-Droid provides apk with a variant with no analytics libraries.

_But functions like Emoji support requires connect to external servers_ .

**Comment by f6zhdkw6** [comment]
> 
> 
> Thw github release of QKSMS are of **WithAnalytics** variant with analytics libraries for crash reports.

Can you add an option for the github release to disable analytics?

**Comment by moezbhatti** [comment]
Personally I don't see the need, when those builds are easily accessible on F-Droid

**Comment by f6zhdkw6** [comment]
> Personally I don't see the need, when those builds are easily accessible on F-Droid

I do not want to use F-Droid version.

**Comment by moezbhatti** [comment]
Why not? It would be the exact same thing

**Comment by f6zhdkw6** [comment]
> 
> 
> Why not? It would be the exact same thing

F-Droid is very slow with updates and I find the release from the original developer better.

faster and more efficient.

**Comment by moezbhatti** [comment]
It should generally only be a day behind at most. Personally I don't find this to be a compelling enough reason to complicate my release process and slow down my builds by having to output two different APKs instead of one

**Comment by moezbhatti** [comment]
_Technically_ the F-Droid builds are safer too, since they provide a checksum for each apk download

https://f-droid.org/en/packages/com.moez.QKSMS/

**Comment by f6zhdkw6** [comment]
> 
> 
> It should generally only be a day behind at most. Personally I don't find this to be a compelling enough reason to complicate my release process and slow down my builds by having to output two different APKs instead of one

What do you mean exactly? You add an option for the users to disable the analytics for crash report.

There are many apps that have such an option in the settings.

Then you still have 1 APK. You can also upload this version to F-Droid. Then you will have all the same.

**Comment by f6zhdkw6** [comment]
> 
> 
> _Technically_ the F-Droid builds are safer too, since they provide a checksum for each apk download
> 
> https://f-droid.org/en/packages/com.moez.QKSMS/



> 
> 
> _Technically_ the F-Droid builds are safer too, since they provide a checksum for each apk download
> 
> https://f-droid.org/en/packages/com.moez.QKSMS/

you can also do it under github release ;)

**Comment by moezbhatti** [comment]
That would definitely be nice to have. Though admittedly it's not a high priority at the moment, since again the F-Droid build is already an option
