### ISSUE TITLE
Guesture "Mark read" does not return to conversation

### ISSUE THREAD

**Issue by sphh** [moezbhatti/qksms#1599]
### DESCRIPTION
I configured QKSMS's gestures that a left swipe marks the conversation read. Swiping left on an unread conversation marks it read. Swiping again left leaves me with this screen:
![Screenshot_20200405-101218](https://user-images.githubusercontent.com/4856462/78470167-bb162d00-7716-11ea-9e94-18ae4cb91a01.png)
The yellow bar with the tick does never disappear. It does disappear if it is scrolled out of view and back into view again.

Using the same gesture with `Mark unread` shows the bar for a short time and then the unread conversation again.

### STEPS
1. Configure QKSMS's gestures that a left swipe marks the conversation read. 
2. Swipe left on a read conversation.

### EXPECTED
The bar with the tick should disappear showing the read conversation.

### OBSERVATIONS
The bar with the tick does never disappear.

**Comment by moezbhatti** [comment]
Fixed in 86f764a288b9e91affc45381330542fc13bbc319
