### ISSUE TITLE
Sending a ~500k SMS doesn't display the text in the sent message - only displays the time.

### ISSUE THREAD

**Issue by Ravenstencil** [moezbhatti/qksms#16]
Sending a ~500k SMS doesn't display the text in the sent message - only displays the time.

**Comment by srcreigh** [comment]
Can't repro. I tried this:

1. Composed a message with 1000+ characters
2. Send the message

I didn't get your issue coming up. Do you know if you were sending via MMS or via long sms? @Ravenstencil

**Comment by Ravenstencil** [comment]
Unfortunately I don't know if it was MMS or long sms. It's entirely possible that this was an issue with my low end phone (ZTE Z995). It's really a nonsense test. The only reason I bring it up is because you should be setting a text character limit of some sort.

**Comment by srcreigh** [comment]
Hmm. I'm not sure if there should be a limit, actually. But if it's the case that your texts aren't showing up then that is definitely an issue.

**Comment by moezbhatti** [comment]
Addressed in QKSMS 3.0 as messages will correctly be split up before sending
