### ISSUE TITLE
Contact icon's font doesn't support emoji

### ISSUE THREAD

**Issue by 4rnoP** [moezbhatti/qksms#1603]
### DESCRIPTION
The contact icon of somebody without specific picture (so just with the initials's contact as icon) doesn't display correctly emojis if there are any in the contact name. 

### STEPS
1. Create a new contact with an emoji in the name
2. Start an conversation with this contact in QKSMS
3. Look at its icon

### EXPECTED
Use a font who support emojis, or remove unsupported characters before creating the icon

### OBSERVATIONS
Currently the emoji is replaced by �

![Screenshot_20200412-125102_Trebuchet](https://user-images.githubusercontent.com/25666607/79066992-4c0f7a00-7cbc-11ea-90c9-9ba8a1ecbbc9.png)

**Comment by moezbhatti** [comment]
Fixed in https://github.com/moezbhatti/qksms/commit/605f32041d1440b259c5c05a75f2116039e92d19
