### ISSUE TITLE
Create bitmap in background

### ISSUE THREAD

**Issue by cataloque** [moezbhatti/qksms#1604]
Dear developers,

In the position of qksm's code:
com.moez.QKSMS.repository.ImageRepostoryImpl: android.graphics.Bitmap loadImage(),
bitmap object is created with the invocation of decodeStream(). However, decodeStream() is a slow operation and it is in the UI thread.

You can process bitmaps in a background thread using AsyncTask.

**Comment by moezbhatti** [comment]
This method is called from a background thread. And if you look at the `options` that are passed in, this method is only decoding the bounds of the bitmap, which is a fast operation

```kotlin
val options = BitmapFactory.Options().apply { inJustDecodeBounds = true }
BitmapFactory.decodeStream(context.contentResolver.openInputStream(uri), null, options)
```
