### ISSUE TITLE
QKSMS is being identified as a threat by Avast Mobile Security 

### ISSUE THREAD

**Issue by WHGhost** [moezbhatti/qksms#1605]
### DESCRIPTION
The latest 3.8.1 version of QKSMS from the Google play store is identified as a threat by Avast Mobile Security. This does not seem to be the case with the F-Droid version. It is a problem as Avast has contracts with some manufacturers so that their malware database is used by default on some devices, causing warning to appear about the app being infected and prompting to uninstall it.

### STEPS
1. Download the latest apk from google play or fetch it from a device where it is installed
2. Upload it to VirusTotal or any other malware scanner. Here is the report: 
3. It is being reported as malicious by avast: https://www.virustotal.com/gui/file/a0b7c90ee1816f3bbe6b2aa55e55e16ce1172f17a3a8c419bb9b5bc730be9bab/details

### EXPECTED
The app shouldn't be detected as malware when downloaded from the play store.

**Comment by moezbhatti** [comment]
Agh, this situation has been such a nightmare. So many angry emails and 1 star reviews in the last few days

I've reached out to Avast and AVG which share their virus engine, and while Avast did not, AVG told me this on Friday

>Hello,
>
>Thank you for contacting AVG.
>
>Please accept our apologies for the inconvenience caused. The detection by AVG was incorrect and was removed in a recent AVG update, please wait at least 24 hours.

I asked them if it would be cleared up in other apps as well

>Hello,
>
>Thank you for your reply, we are glad that the situation was resolved.
>
>We are share virus definition database only with Avast, therefore it will be reflected also there. Unfortunately for the other companies and programs we are not responsible. Therefore if the situation will be same with them, you will need to contact them directly.

Interestingly, I'm still seeing VirusTotal indicate that Avast-Mobile is detecting a virus. Let me follow up with them and see if they can look into it

**Comment by moezbhatti** [comment]
Wait a sec - I just found something strange. I tried uploading the APK from the Github releases up to VirusTotal, which is compiled with all the same instructions as the App Bundle I upload to Google Play, and no virus is being reported there

How exactly did you get the APK that you uploaded to VirusTotal? Can you share it with me, so I can have AVG take a look at it?

**Comment by WHGhost** [comment]
After getting an alert on my phone, I extracted the apk from the phone using the APK Extractor app from Google Play, and uploaded it to virus total, which confirmed the problem. I then downloaded the latest apk from F-Droid and uploaded it to virus total too, and it wasn't detected, so it looks like it's a problem only with Google play. I then downloaded the apk using [this website](https://apkcombo.com), which claims to get it directly from Google Play. It was indeed the same file that I extracted from my phone, and was detected.
I'm not an android developer, so my knowledge about APKs is very limited, but just comparing the F-Droid and the Google Play one by opening them as archives, it looks like the Google Play one has a bunch of additional files at the root of the archive.

**Comment by moezbhatti** [comment]
I believe this should be resolved now - can anyone confirm?
