### ISSUE TITLE
Restoring Backup from .json backup doesn't work

### ISSUE THREAD

**Issue by saligari** [moezbhatti/qksms#1607]
### DESCRIPTION
Using the restore backup function from the settings doesn't show the .json backup file I put in QKSMS/backup folder

### STEPS
1. created a backup (.json file) in lineageos 16.1 (android 9) 
2. install QKSMS in (same) phone but flashed (not upgraded, new ROM) with lineageos 17.1 (android 10)
3. put .json file in QKSMS/backup
4. go to restore settings in QKSMS

### EXPECTED
.json file I put in there shows up

### OBSERVATIONS
.json file I put in there doesn't show up.

I made a new backup, removed it from QKSMS/backup, it wasn't shown in the restore settings. Put it back there, and it showed.

I opened both .json files and both start the same:

the old one: 
```

{
	"messageCount": 2198,
	"messages": [
		{

```
and the new one has 77 messages.

It seems quite peculiar to me that one .json file wouldn't show and another would.

I hope you can reproduce, or know what's happening and help! Sorry if I'm missing something obvious!

**Comment by opusforlife2** [comment]
I just encountered the same. The backup json is lying there untouched from my LOS 16 backup. Now that I'm trying to restore it on LOS 17.1, it's not working.

@moezbhatti Do you need logs or something to debug this?

**Comment by opusforlife2** [comment]
Additional info: I got the 3.9.0 update today, and now it successfully saw the backup JSON and restored it.

The only difference I can see is that I had QKSMS 3.8.1 installed as a system app through NanoDroid. The 3.9.0 update was then installed as a user app. This somehow gave the app access to the backup JSON.

**Comment by saligari** [comment]
I'm closing this issue since my .json file had this problem and @opusforlife2 hasn't added additional info.

**Comment by opusforlife2** [comment]
I don't have any more info to add currently, and since then I haven't needed to restore a backup. So yeah, if I encounter it again later, I'll see if I can capture more details.
