### ISSUE TITLE
Feature request: in app contact management

### ISSUE THREAD

**Issue by jamesongrey** [moezbhatti/qksms#1611]
In app contact managment can be wonderful
Like adding image or name for a number without saving number to contacts list
( some providers name themselves like vodafone so we cant save them to contact list and set image for them)

**Comment by moezbhatti** [comment]
Hmm, this is a can of worms I'm not currently interested in opening

As for those providers which name themselves, I believe you can still save them to your contact list if you just set their "name" as the phone number
