### ISSUE TITLE
Feature Request: Attach Voice/Sound File

### ISSUE THREAD

**Issue by Saijin-Naib** [moezbhatti/qksms#1615]
### DESCRIPTION
Alongside the ability to attach images, it'd be great if we were able to pick and/or record sounds OTF (like image from Camera UX now).

I make use of this fairly often, especially when sending content to family for events/birthdays/anniversaries, etc.

**Comment by FalcionX** [comment]
In general record voice in app will be great!!

**Comment by moezbhatti** [comment]
Duplicate of #114
