### ISSUE TITLE
Choosing different phone number for contact via radio button is broken

### ISSUE THREAD

**Issue by tslocum** [moezbhatti/qksms#1618]
### DESCRIPTION
Tapping the alternative phone number label works (the radio buttons are correctly updated).  Tapping the radio buttons results in both radio buttons being selected.  This results in the first entry always being selected.

### STEPS
1. Choose alternative phone numbers for contact when starting new message.
2. Tap both radio buttons a few times, both will be selected at once.

### EXPECTED
Both radio buttons are not able to be selected at once.

### OBSERVATIONS
Both radio buttons are selected at once.

**Comment by moezbhatti** [comment]
Fixed in 88accdb7a1924447d8148fb4c7c7bae5cf5bed47
