### ISSUE TITLE
Many emojis in a text message makes the app crash when trying to display that text.

### ISSUE THREAD

**Issue by 0cwa** [moezbhatti/qksms#1625]
### DESCRIPTION
I sent a bunch of emojis and then whatever these things are: (~￣³￣)~ and now the app crashes whenever that text I sent is loaded.  I still need to transfer my backup to a laptop so I can show you the original message, but hopefully a system log will do for now.
[logs-2020-06-27-13-32-48.zip](https://github.com/moezbhatti/qksms/files/4841210/logs-2020-06-27-13-32-48.zip)

**Comment by moezbhatti** [comment]
Thanks for the logcat! Combining this with #1512
