### ISSUE TITLE
Avatar gripe

### ISSUE THREAD

**Issue by Samcfuchs** [moezbhatti/qksms#163]
Would it be possible to make avatars appear only in group messages? I envision this going in settings along with all the other avatar settings. I don't like having avatars for most convos because I know who's sending the message, but in group chats, it becomes very useful to have them. Could we get the best of both worlds?

**Comment by moezbhatti** [comment]
Deciding not to add this, to avoid cluttering the settings menu (which is being trimmed down for QKSMS 3.0)
