### ISSUE TITLE
battery optimization not available. how it could be?

### ISSUE THREAD

**Issue by rezazarchi** [moezbhatti/qksms#1632]
hi
i want to disable battery optimization for my application. i know that showing dialog with REQUEST_IGNORE_BATTERY_OPTIMIZATIONS is the way that user can disable that. but in QK SMS, it's fully disabled even in battery settings. how can i fully disable battery optimize for my application like that?
![image of system battery optimize settings](https://i.stack.imgur.com/Xr0LR.png)

**Comment by moezbhatti** [comment]
This happens when an app is made the Default SMS app
