### ISSUE TITLE
Pinned conversation disappeared after cancelling a message sending

### ISSUE THREAD

**Issue by HorlogeSkynet** [moezbhatti/qksms#1633]
### DESCRIPTION
Hey over here :ok_hand:

Really weird behavior I've just experienced in v3.8.1 : A pinned conversation disappeared from the list after I've cancelled (OK I admit, I've pressed many times the `stop` button as it seemed not to work at the moment) the sending of a (delayed) message. 

### STEPS (maybe ?)
0. Enable delayed sending
1. Press to send a message in a pinned conversation
2. Press the cancelling button (many times ??)
3. Try to find the conversation in the list :fearful: 

### EXPECTED
The content of the message being sent would come back as draft and the pinned conversation does not disappear.

### OBSERVATIONS
Something weird happened and the draft message disappeared, as long as the conversation in the list.  
I had to re-sync messages against the Android native app to make the conversation appear again (still pinned though) :open_mouth:

---

Don't know whether it's linked to the pinned feature or not, but thought it might be better to precise.

Bye :wave:

**Comment by moezbhatti** [comment]
Any chance you're able to reproduce this bug and get a screen recording of it?

**Comment by HorlogeSkynet** [comment]
> Any chance you're able to reproduce this bug and get a screen recording of it?

Hey, actually it happened on my personal QKSMS instance and I don't feel like taking n' sharing a video of it :roll_eyes:
But as a context addition, I can tell you there are several tens of thousands messages, and sometimes the application "freezes" some seconds, and the issue I described in the OP occurred during one of those "freezes".
Thanks, bye :wave:

**Comment by moezbhatti** [comment]
Fixed in df181caf9e754c69a5c889076047ff49248b7f9e

**Comment by HorlogeSkynet** [comment]
That was fast and unexpected, much thanks @moezbhatti 👌🙏
