### ISSUE TITLE
Select all messages in a conversation

### ISSUE THREAD

**Issue by maverick74** [moezbhatti/qksms#1635]
There should be a way to, in a conversation, select all messages ( instead of having to tap each one).

This would be useful, for example, to clean messages.
e.g.: I want to delete all massages prior to this month. With this option I can select all and manually remove mark on those from the current month

Possibly related to bug #1310

**Comment by moezbhatti** [comment]
Hmm, not so sure about this one.

- If someone wants to highlight everything for deletion, they can just delete the conversation instead
- If someone wants to highlight everything for deletion except a select few messages, this will be solved by #1000 
- If someone wants to highlight everything for things after a date, this will be solved by #772

**Comment by maverick74** [comment]
I don't think 772 would be a solution, but #1000 for sure can.

Will subscribe 1000. :)

Thanks
