### ISSUE TITLE
Malware detected in Fortinet, Symantec Mobile Insight, K7GW

### ISSUE THREAD

**Issue by appmaster1998** [moezbhatti/qksms#1638]
I have check version 3.8.1 In virus total website on 8 Aug 2020 

App scan result :- https://www.virustotal.com/gui/file/93d958576ca7830348847660171d1d651204dae840c5e2966e1db48b8af1b945/detection

I see just few day ago Eset Mobile Security detects this app as a malware and this issue solved by you just in one mail write.

But today other three company detecting malware list is Fortinet, Symantec Mobile Insight, K7GW

So, @moezbhatti I request you to solved this false positive also asap quick

**Comment by moezbhatti** [comment]
Thank you, I'll reach out to these companies as well

**Comment by appmaster1998** [comment]
@moezbhatti Have you write mail to this 3 company or no?

**Comment by appmaster1998** [comment]
@moezbhatti one good news is fortinet solve false positive.

But Symantec mobile insight and K7GW still showing false positive. I hope this 2 also solve this issue fast and make your app 100% free from malware detect.

**Comment by moezbhatti** [comment]
This seems to be resolved across the board now
