### ISSUE TITLE
[Bug fix/improvement suggestion]: When searching inbox, make enter key collapse keyboard instead of creating newline

### ISSUE THREAD

**Issue by e-t-l** [moezbhatti/qksms#1641]
### DESCRIPTION
When using the inbox search, pressing the Enter/Return key creates a newline. This would only be useful when searching the exact phrasing of a multi-line string. For example, if I received a text that looked like this...
> Hello
> How are you?

...in order to search it, I would have to type "Hello{enter}How" in the searchbox. It will not be returned by searching "Hello How". Given this rare use case, it would make more sense to make the search function interpret line breaks as spaces, so that you could search for the example text by entering "Hello how". 

Furthermore, it would make more sense for the Enter/Return key to collapse the on-screen keyboard. Currently, doing this simply adds a newline character to the search string, which actually makes it more difficult to search, because most strings that users are searching for do not end in a newline character, and are thus removed from the search results. While it's currently not necessary to press Enter at the end of a search, as results are returned instantaneously, many users do it out of habit. Therefore, it would be useful for the Enter key to collapse the on-screen keyboard and clear the focus from the textbox, thereby allowing the user to scroll through the search results with more ease.

### STEPS
1. Type a string (e.g. "what's up") into the Search box.
2. Observe that there are several search results containing the string: "what's up"
3. Press the Enter/Return key on your keyboard.
4. Observe that the search results change, because the search string is now: "what's up{newline}"

### EXPECTED
Focus is cleared from the search box and the on-screen keyboard (if present) is collapsed. Newline characters are not added to the search string.

### OBSERVATIONS
A newline character is added to the search string, the search box remains in focus, and the on-screen keyboard remains on screen. If the text that the user seeks does not match the new string (i.e. with a newline character at the end), then that text will not be returned in the search results.

**Comment by jstetten** [comment]
Thanky you @e-t-l for expressing something that has been driving me crazy. This affects me every time I search.

> Furthermore, it would make more sense for the Enter/Return key to collapse the on-screen keyboard.

What affects me either more is when — for those of us who have a keyboard that inserts a space at the end of autocompleted words — search results will suddenly disappear as soon as the space is inserted, beacuse the space fails to match text exactly. It's frustrating.

Whenever this issue is tackled, could we please have whitespace of all kind truncated from the beginning and the end of the search string?

**Comment by moezbhatti** [comment]
Fixed in 408af960197a2bee25a2799a4036dc76ce45eb32

Opening a new issue for the whitespace problem
