### ISSUE TITLE
Request: Better text selection shortcuts

### ISSUE THREAD

**Issue by timonoj** [moezbhatti/qksms#1647]
Hi, 

First of all, thank you for this very clean SMS app, that so far achieves everything I need. The last version offers me to copy the number code I just received in an SMS, which is great exactly for 2-Factor authentication codes I receive constantly.

I wanted however to request a couple of features regarding text selection on an SMS. Once I long press an specific SMS in a conversation, the shortcuts I get are the ones for Information, and Delete. While I reckon the Delete button might be useful to keep for other people, I believe it would be more useful to have the Copy shortcut instead of the Information one, as it's more likely I want to copy something within the SMS, or the whole SMS altogether, than getting more detailed information about that specific SMS.

Additionally, it would be cool if it could link to some translation service, such as GTranslate, or any other free open source alternative available.

Thank you so much for the work!

**Comment by moezbhatti** [comment]
This will be resolved with #1105
