### ISSUE TITLE
Add option to show contact groups after individuals

### ISSUE THREAD

**Issue by howff** [moezbhatti/qksms#1653]
Problem: contact groups are shown before individuals, but contact groups may have many hundreds of members, so it entails a huge amount of scrolling down to find the actual person you're looking for.

Solution:
1) show contact groups at the end after the individuals
2) add an option so the user can choose whether to show groups first or last

See also #1593 which was closed but this is still a massive problem

**Comment by moezbhatti** [comment]
This has been solved for the next update
