### ISSUE TITLE
[Bug Report/Feature Request] SMS being auto-converted as a MMS when group messaging and dedicated copy text button

### ISSUE THREAD

**Issue by josephmalonda** [moezbhatti/qksms#1655]
### **BUG REPORT**

DESCRIPTION

- Sending single message to added multiple contacts is being sent as an MMS and the message cannot push through or be sent.

STEPS
1. Create a new message
2. Select multiple contacts
3. Type in your message and hit send
4. Now you wait forever trying to send the group message
5. because it is not being sent as it supposed to be as a simple SMS. It is getting converted for unknown reason as an MMS. 

This bug is somehow infuriating.

EXPECTED

- Group message should simultaneously send to each added contacts the single SMS I wanted to send and not be converted as a MMS. For this reason, I cannot send simple SMS to multiple contacts.

OBSERVATIONS

- Forever in sending status. I just want to send a group message SMS. Not MMS.

### **FEATURE REQUEST**

- Make the "Copy text" taken outside of the three-dots menu and have a dedicated button that is not hidden. _Maybe put it in between Message details button or Delete button_ for this, it is much easier and convenient to copy-text messages because it reduces few more touches just to copy a message.

**Comment by josephmalonda** [comment]
**FEATURE REQUEST**

- Having an optional notification/confirmation sound when an SMS has been successfully sent is great to have too!

**Comment by moezbhatti** [comment]
To resolve this, just disable the "Send as group message" option when composing your message. Group messages are inherently MMS messages - so you'll need to disable this you'd like to send an SMS to everyone individually

As for the Copy suggestion, this will be resolved with #1105
