### ISSUE TITLE
Ability to rename chats.

### ISSUE THREAD

**Issue by predator8bit** [moezbhatti/qksms#1659]
It would be very useful to have the ability to rename chats, editing the contact isn't always an option. For example all my work related contacts have the same first name set (company's name) and that makes it harder to select the chat I want.

**Comment by moezbhatti** [comment]
I think this is rare enough that the app shouldn't really need to solve for it.

Perhaps you could specify the company name in the Company field in your contacts instead? This would still allow you to sort and organize your work contacts, without having to mess with their name
