### ISSUE TITLE
Buttons gone hidden 

### ISSUE THREAD

**Issue by mtashackori** [moezbhatti/qksms#1661]
### DESCRIPTION
With long list of a contract numbers, the buttons for select a number doesn't shown

**Comment by moezbhatti** [comment]
I'm not sure what this means. Please share a screenshot and I'd be happy to reopen the issue

**Comment by mtashackori** [comment]
![Screenshot_20201213-131327_QKSMS](https://user-images.githubusercontent.com/16570244/102008374-205dfb80-3d45-11eb-8167-f3fc5959e9c9.png)

**Comment by moezbhatti** [comment]
Fixed in bf808a84b69173da4aeadc333413b0f8d252f537
