### ISSUE TITLE
QKSMS+ v3.8.1: dialogue for selecting one of several recipient's numbers behaves erratically (LineageOS 17.1 on FP2)

### ISSUE THREAD

**Issue by sphakka** [moezbhatti/qksms#1663]
### DESCRIPTION
With QKSMS+ v3.8.1, LineageOS 17.1 on FP2.
The pop-up dialogue for selecting one of several recipient's numbers behaves erratically when the recipient has more than 6 numbers: more radio buttons can be selected instead of only one, and no confirmation confirmation buttons appear at the bottom (pop-up is not scrollable).

### STEPS
0. Have a contact with at least 7 numbers in your address book
0. Make sure "Settings -> Mobile numbers only" is off
1. Start composing a new SMS
2. Select the above contact
3. Try to click on more radio buttons

### EXPECTED
Only one radio button should be selected. As the pop-up can't fit the screen it should be scrollable to see the confirmation buttons ("Only once", "Always") at the bottom. 

### OBSERVATIONS
More radio button can be selected. Confirmation buttons ("Only once", "Always") at the bottom can't be reached as the pop-up is not scrollable.

**Comment by moezbhatti** [comment]
Fixed in 88accdb7a1924447d8148fb4c7c7bae5cf5bed47
