### ISSUE TITLE
Is the backup format documented somewhere?

### ISSUE THREAD

**Issue by tYYGH** [moezbhatti/qksms#1664]
I have `SilencePlaintextBackup.xml` with all my SMS saved from Silence. I want to import this into QKSMS.
To do that, I need to transform the XML into something that QKSMS will understand, but I cannot find what format (syntax) is expected by QKSMS for a backup file…

**Comment by mimonirbd** [comment]
Restore this file by any app that can restore the sms like **sms backup and restore** app. Then open the qksms app and if it want to synce then give the permission.
I hope it can solve your problem.

**Comment by tYYGH** [comment]
Thank you @mimonirbd for your suggestion. I did try a couple of tools but I could not find one that I suited my situation.

Anyway, I finally managed to migrate my SMS backup :-)

First, I translated Silence’s XML file (`SilencePlaintextBackup.xml`, which is UTF-8-encoded) to JSON using this command:

```bash
tr -d '\r\n' <SilencePlaintextBackup.xml \
| grep -o '<sms[[:blank:]][^<>]*>' \
| sed -r $'
  1 i \\\n[\n
  s#[[:blank:]]+([a-z_]+)[[:blank:]]*=[[:blank:]]*("[^"]*")# "\\1": \\2,#g
  s#<sms (.*"),[[:blank:]]*/?>#  {\\1},#
  s#"(protocol|date|type|read|status|locked)": "([^"]*)"#"\\1": \\2#g
  s#: "null"#: null#g
  s#\\\\#\\\\\\\\#g
  s#&quot;#\\\\"#g
  s#&lt;#<#g
  s#&gt;#>#g
  s#&apos;#’#g
  s#&amp;#\\&#g
  $ s#,$#\\n]#
' >silence-backup.json
```

This script essentially translates XML to JSON, except the XML-encoded UTF-16 surrogate code-points (which are invalid XML to start with, and kept me from using regular XML tools). It also changes string attributes to numeric attributes where needed, and changes `"null"` strings into actual JSON null values.

Then I wrote the following Java program:

```java
////////// yg/Smses2Json.java:

public class Smses2Json {
  private static final ObjectMapper JACKSON = new ObjectMapper();
  private static final Pattern XML_ENTITY_PATTERN = Pattern.compile("&#(\\d+);");

  public static void main(String[] args) throws JsonParseException, JsonMappingException, IOException {
    List<XmlMessage> messages = Arrays.asList(JACKSON.readValue(new File(args[0]), XmlMessage[].class));

    Backup backup = new Backup();
    backup.setMessages(messages
        .stream()
        .map(x -> new Message(
            x.getProtocol(), x.getAddress(), x.getDate(),
            x.getType() == 1 ? x.getDate() : 0, // a date for an SMS received; 0 for an SMS sent
            x.getType(), x.getBody(), x.getRead() == 1, x.getStatus(), x.getLocked() == 1,
            x.getType() == 1 ? 1 : -1)) // 1 for an SMS received; −1 for an SMS sent
        .peek(msg -> {
            Matcher matcher = XML_ENTITY_PATTERN.matcher(msg.getBody());
            msg.setBody(matcher.replaceAll(match -> {
              return new StringBuilder().appendCodePoint(Integer.valueOf(match.group(1))).toString();
            }));
          })
        .collect(Collectors.toList()));
    backup.setMessageCount(backup.getMessages().size());

    if (args.length == 1) {
      JACKSON.writeValue(System.out, backup);
    } else {
      JACKSON.writeValue(new File(args[1]), backup);
    }
  }
}

////////// yg/XmlMessage.java:

@Data
public class XmlMessage {
  private int protocol;
  private String address;
  private long date;
  private int type;
  private String body;
  private String service_center;
  private int read;
  private int status;
  private int locked;

  // useless:
  private String subject;
  private String toa;
  private String sc_toa;
}

////////// yg/Message.java:

@Data
@AllArgsConstructor
public class Message {
  private int protocol;
  private String address;
  private long date;
  private long dateSent;
  private int type;
  private String body;
  private boolean read;
  private int status;
  private boolean locked;
  private int subId = -1;
}

////////// yg/Backup.java:

@Data
public class Backup {
  private int messageCount;
  private List<Message> messages;
}
```

This program takes care of the remaining XML notations (encoded UTF-16 surrogate code-points), as well as some transformations that I gathered from reading the source code of [BackupRepositoryImpl.kt](https://github.com/moezbhatti/qksms/blob/master/data/src/main/java/com/moez/QKSMS/repository/BackupRepositoryImpl.kt), and observing a sample backup made from a couple of sent and received messages.

Maven `pom.xml` file for this small project:

```xml
<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId>yg</groupId>
  <artifactId>silence-xml-to-qksms-json</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.16</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.12.0</version>
    </dependency>
  </dependencies>

  <build><plugins><plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <version>3.1.2</version>
    <executions><execution>
        <id>copy-dependencies</id>
        <phase>package</phase>
        <goals><goal>copy-dependencies</goal></goals>
        <configuration><outputDirectory>${project.build.directory}/CP</outputDirectory></configuration>
    </execution></executions>
  </plugin></plugins></build>
</project>
```

Then I compiled and ran the project:

```bash
$ mvn clean package
$ java -cp target/CP/*:target/classes yg.Smses2Json silence-backup.json | json_pp >backup-20201205120000.json
```

The output name `backup-20201205120000.json` is built like this: `backup-` + YYYY (year) + MM (month) + DD (day) + hh (hour) + mm (month) + ss (seconds) + `.json`.

Finally I copied this file to `QKSMS/Backups/` on the phone, and QKSMS recognized it and loaded it perfectly (more than 4000 messages).

Source code: https://yalis.fr/git/yves/silence-xml-to-qksms-json

**Comment by moezbhatti** [comment]
Very cool! Glad you were able to sort this out

FYI there isn't any official documentation for the backup format, since it isn't designed to work with other apps. Not that it's designed to _not_ work with other apps, there just isn't any standard for this sort of stuff

**Comment by goyalyashpal** [comment]
> Not that it's designed to _not_ work with other apps, there just isn't any standard for this sort of stuff

correction: i think u meant:

> Not that it's not designed to _not_ work with other apps, there just isn't any standard for this sort of stuff

**Comment by Pandapip1** [comment]
Would appreciate it if this could be merged into QKSMS so Silence backups could be natively loaded
