### ISSUE TITLE
Can't unlock QKSMS+

### ISSUE THREAD

**Issue by MikeOnr** [moezbhatti/qksms#1725]
Hi and congratulation for the good job you made !!

As I am running QKSMS on Hisense A5 Pro CC, I'd love to unlock and donate, but can't do it.
![Screenshot_20210122_165019290_QKSMS](https://user-images.githubusercontent.com/76921409/105513284-69a15380-5cd2-11eb-9852-96e29ffe5042.jpg)
How can I do to get it and help you ? 

Thanks

**Comment by moezbhatti** [comment]
This relies on Google Play for the upgrade, so unfortunately there isn't much that can be done here. That being said, if you download the app from F-Droid instead, everything will be unlocked for free
