### ISSUE TITLE
Release version 3.9.0 on Google Play Store

### ISSUE THREAD

**Issue by tjorim** [moezbhatti/qksms#1727]
### DESCRIPTION
Try to install or update the app from the Play Store, you will notice the version available is 3.8.1.

### EXPECTED
Instead of version 3.8.1, the latest and greatest version 3.9.0 should get installed.

**Comment by CrazyHoodlem** [comment]
I would expect that Google has some sort of delay for App Updates, as other platforms have. Either that or the devs just haven't gotten around to uploading it, which is understandable.

**Comment by NovaViper** [comment]
@tjorim You don't want to get 3.9.0, that one has been causing alot of issues. See #1712

**Comment by moezbhatti** [comment]
I'll deploy 3.9.1 once I sort out the bugs introduced in 3.9.0
