### ISSUE TITLE
[Request] app contact vcf import

### ISSUE THREAD

**Issue by doobydooby72** [moezbhatti/qksms#1752]
So i recently upgraded phone to an oppo with android 10. Prior i was using a phone with android 7.1 which worked without issue with simple contacts, simple dialer and QKSMS. Now simple contacts cant read on device contacts nor sim contacts but simple dialer can read both device contacts and privately imported contacts that only other simple apps can read (though still not sim contacts). The issue here is simple dialer shows duplicates if both on device contacts and simple contacts private database are populated.
I propose adding QKSMS' own contact database
1. So this isnt a problem
2. As to add a layer of optional privacy for users who dont want the whole device to have access to contacts (this is the angle that OpenContacts has taken, no device contacts only in app contacts and since it remains independent of the device shouldn't have issues like my phone seems to with device contacts on a per app basis). 
Thank you

**Comment by moezbhatti** [comment]
What if you just added the contacts to the device contacts, and not to the simple contacts private database? Then I think it should work correctly, just as it did on your previous phone

Unfortunately contact management is just not something that's within the scope of the QKSMS project, so I'm going to close this issue
