### ISSUE TITLE
syncing messages does not sync "sent" messages from previous apps

### ISSUE THREAD

**Issue by chicagolandcoders** [moezbhatti/qksms#1759]
### DESCRIPTION
99% of messages I ever sent while using an android phone won't sync to qksms. Absolutely all messages ever received up to 10+ years sync flawlessly.

### STEPS
1. Install qksms for the first time
2. Set as default sms app when prompted  
3. Automated sync begins
4. Sync completes in 1-2 min
5. Almost all sent messages not synced.
6. Manual resync does nothing different 

### EXPECTED
All messages show like normal 

### OBSERVATIONS
99% of messages sent by user to any contact do not sync. All conversations look like 1 way walls of text with no replies. Very rarely about 1-4 sent messages appear where they should be hence the 99%. These messages are in no way special. The 1% include both sms and mms.

Sync is flawless for messages prior to may 2019. Which is when I migrated from ios to this android phone using Samsung migration tool.

------------------------------

Info highlight from a recent recieved message

Type: sms
From: +10000000000 #fake number
Sent: 1/27/20 11:09:54 PM
Recieved: 1/27/20 11:09:54 PM
Error code: -1

------------------------------

Info highlight from an old old ios era recieved message 

Type: sms
From: +10000000000 #fake number
Sent: 1/27/20 11:09:54 PM
Error code: -1

------------------------------

Sample Info highlight from a 1% new sent message.

Type: sms
To: +10000000000 #fake number
Sent: 1/27/20 11:09:54 PM

------------------------------

Info highlight from a old old ios era sent message 

Type: sms
To: +10000000000 #fake number
Sent: 1/27/20 11:09:54 PM
Error code: -1

---------------------------------

Also any new sent messages show up normally

Device: Galaxy S10, snapdragon 865 version
Fully updated android 11
Provider AT&T

**Comment by moezbhatti** [comment]
Why did you close the issue – did it start working correctly?

**Comment by chicagolandcoders** [comment]
It turns out that the Samsung messages app (default to all new galaxy devices) does not store sent messages in the native Android sms database. This prevents ALL 3rd party sms apps from syncing sent messages that were sent using the Samsung app. They store all messages in their own private databases (600mb of appdata in 1 year of use). Probably for dirty reasons.

The issue is not yours, it's poor design on Samsung part or maybe they're forcing dependency on their app.
