### ISSUE TITLE
payment for backup and restore

### ISSUE THREAD

**Issue by hrv231** [moezbhatti/qksms#1775]
### DESCRIPTION
If someone is using the app with F-Droid and no google services at all, how can someone pay to unlock the backup and restore benefits?

### STEPS
1. look for a payment option with no google services
2. there isn't any

### EXPECTED
An option to activate or unlock the rest of the features if you purchase without google services, using a credit card and get an code for the app, or using paypal and get a code that you could reuse in case you change your phone to a new one.

**Comment by Eragonfr** [comment]
I have QKSMS from F-Droid and every options are unlocked. I still have the QKSMS+ thing. But you don't have to pay to use the backup and restore functionality. Exactly like if you're building the app from the git repo.

If you want to give money to the authors, looks into the readme, there are links to do that.

**Comment by moezbhatti** [comment]
Correct – QKSMS+ is included for free if you get the app from F-Droid
