### ISSUE TITLE
Unissued background connection to google

### ISSUE THREAD

**Issue by halis300** [moezbhatti/qksms#1777]
![image](https://user-images.githubusercontent.com/79767757/114905831-b13f0380-9e19-11eb-8c60-7db2764f6def.png)

QKSMS 3.9.4
Source: F-droid

The app connects without any seemingly reason to google. I detected it with NetGuard VPN App.

It might be related to:
https://gitlab.com/fdroid/fdroiddata/-/issues/2260
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8052
https://github.com/moezbhatti/qksms/issues/1708

Reported to F-Droid:
https://gitlab.com/fdroid/fdroiddata/-/issues/2365

**Comment by IdreesM0** [comment]
Now that looks like a stab in the spleen. Someone care to explain??

**Comment by halis300** [comment]
> Now that looks like a stab in the spleen. Someone care to explain??

I think, someone wrote somewhere, that QKSMS uses Google to show you update news. So nothing that big (giving Google the information, of which SMS App you are using + when you started it the first time after update + your IP address)

@moezbhatti QKSMS is the best SMS App, which I used so far. I will not switch to any other, even if it connects to Google (very rarely).

Since it did show that message again for a long time now, I can not say for sure, that it was not a bug with Netguard or an error on my side. So I am closing the issue.
