### ISSUE TITLE
Is this app abandoned?

### ISSUE THREAD

**Issue by RasheedAZ** [moezbhatti/qksms#1798]
I'm on CalyxOS (based on Android 11) trying to migrate from Textra to something on F-Droid that can schedule SMS messages. 

This looked like a promising app that I'd even pay for but it looks like it's not being maintained any more...?

**Comment by xxxxme** [comment]
Last F-Droid update was Feb 28, 2021. That's not that long ago.

**Comment by ptlambert** [comment]
For a single dev FOSS project it looks pretty well maintained to me:

https://github.com/moezbhatti/qksms/releases

**Comment by catwithbanana** [comment]
The author's profile shows commits to private repos in April and May, but there haven't been any public posts or updates since February.

I'm hoping it isn't abandoned, but I do also wonder.

**Comment by ballo** [comment]
Has anyone found a good alternative? This app has bugs which are deal-breakers like hiding conversations from me!

**Comment by moezbhatti** [comment]
Not abandoned, but I'm not able to spend as much time on it anymore. I work on it when I can – and I'll continue to do so :)
