### ISSUE TITLE
Facebook contact  photos aren't shown.

### ISSUE THREAD

**Issue by MangoScango** [moezbhatti/qksms#180]
If you've got a device that still supports Facebook contact sync, contacts that use photos from Facebook aren't shown. The qksms still recognizes the cotnact from Facebook, it just can't pull the photo properly.

**Comment by moezbhatti** [comment]
What device do you have?

**Comment by MangoScango** [comment]
Galaxy S6 Edge, Verizion.

**Comment by Stampede10343** [comment]
I have the same issue on my Verizon LG G2 with 4.4.2

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0
