### ISSUE TITLE
Opening a message thread with an attached contact card causes a crash

### ISSUE THREAD

**Issue by reeseovine** [moezbhatti/qksms#1812]
I received a group text (MMS) from a family member stating that another family member has a new phone number, with a contact card attached to it. I am not used to seeing that and for context the sender is using an iPhone. The card content is just a phone number in the "Main" slot with no name or anything else. I received the notification for it just fine but when I went to open it, QKSMS crashed, and crashes every single time I try to open the thread. It opens just fine in the LineageOS Messaging app and I can save the contact to my phone.

I don't feel comfortable sharing the content of the message here but I am open to building and testing QKSMS on my device as a bugfix is worked on.

I am running **LineageOS 18.1** on a **Google Pixel 3a**. QKSMS is **version 3.9.4 from F-Droid**.

**Comment by Man-Chicken** [comment]
Hi there,

Any idea when a new release with this fix might be coming?  I just ran into this exact issue -- the sender was also using an iPhone -- and it's a doozy!

Thanks for all the work you've done on QKSMS; it truly is the best!

**Comment by mindfilter** [comment]
Ran into the same issue. Got a Contact Card from an iPhone user, and now the app crashes/closes every time I open the thread from that person.

**Comment by cdonovick** [comment]
I also am having the bug.  I was able to work around by opening the thread in another app and deleting the message then re-syncing QKSMS.

System info:
* QKSMS+ version 3.9.2 
* Samsung xCover6 Pro
* Android 16
* One UI 8.0
