### ISSUE TITLE
Remaining characters counter not aligned properly when system font size is set to small

### ISSUE THREAD

**Issue by peepay** [moezbhatti/qksms#185]
The title pretty much sums it up, the remaining characters counter is not aligned properly when system font size is set to small.
Nexus 6, Android 5.1.1, QKSMS 2.0.1
Screenshot here: http://i.imgur.com/Q3LGPi8.png

**Comment by moezbhatti** [comment]
Fixed in 6d6b3fbf77f02bc1f601e5eaf3a16f671d3bbbdf
