### ISSUE TITLE
Wrong notification sound played when I received multiple messages

### ISSUE THREAD

**Issue by peepay** [moezbhatti/qksms#186]
Nexus 6, Android 5.1.1, QKSMS 2.0.1

I have a system-wide notification sound set for SMS messages, let's call it sound A. Then I have a specific notification sound set in QKSMS for one specific contact, let's call it sound B and that contact person B.
I received an SMS message from one of my contacts, sound A played. All good yet.
I did not read the message, it was still in my notification shade (and thus on the lockscreen notifications list too) and I received another message, this time from person B, so sound B should have played. But sound A played.﻿

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0
