### ISSUE TITLE
Smileys sent through the Samsung SMS app show as "??"

### ISSUE THREAD

**Issue by MoodZy** [moezbhatti/qksms#187]
The title pretty much sums it all. 

When I receive an SMS from my mother, who uses a Samsung device (Samsung S4 mini - Up to date) with the original SMS app, smileys are shown in QKSMS as "??" (juste two interrogation points). If 2 smileys are sent it shows "????" (2 times 2 interrogation points) etc.

I don't know if this is possible to solve in any way, but seeing the amount of people using Samsung phones everywhere, it might be something to look into.

**Comment by pikurasa** [comment]
Verified. I have had this issue as well.

**Comment by moezbhatti** [comment]
Going to close this as I suspect it has to do with it being an older version of Android, which the new version of QKSMS does not support.

If anyone sees this pop up again, let me know and I'll take a closer look!

**Comment by pikurasa** [comment]
> Going to close this as I suspect it has to do with it being an older version of Android, which the new version of QKSMS does not support.

The newer version of QKSMS will not support older versions of Android _at all_?

From what version of Android will be supported?

I ask b/c I am still using an old version of Android and have been using QKSMS.

**Comment by moezbhatti** [comment]
@pikurasa it's going to support Android 5.0 and above

**Comment by pikurasa** [comment]
@moezbhatti Thanks for letting me know.

Good luck with improvements.

**Comment by moezbhatti** [comment]
@pikurasa no problem, and thanks!

For what it's worth, I also plan to implement the [EmojiCompat](https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat.html) library in the new update. This brings fully up-to-date emoji support to any Android version, so this issue will certainly be addressed then, if not already.

**Comment by pikurasa** [comment]
Well, I can try the new QKSMS when I see it in F-Droid (which is the repo I use--and I did not see the latest yet when I checked last week) and if QKSMS works, I can tell you and share some virtual high-fives. Does that sound like a plan?

If it works at all, I will be happy. If it has emoji support, I will be ecstatic.

I am just too fond of this old phone b/c I modded it, and it runs almost exclusively free software. If I get a new phone, I loose some (all?) of those perks.

**Comment by moezbhatti** [comment]
Sounds like a plan!

I need to make some changes so that it can support the F-Droid build system. I've re-written the new version of the app from scratch, so there's some new things to be considered. Namely, I need to disable the analytics in the F-Droid variant as I'm not using free services (Amplitude and Mixpanel)

I'm going to be launching the next preview release by tomorrow, so I'll try to include F-Droid support by then.

Thanks for the patience!
