### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by andsofine** [moezbhatti/qksms#1875]

**Comment by markcellus** [comment]
Good question! Does anyone know of an alternative app?

**Comment by n-ce** [comment]
> Good question! Does anyone know of an alternative app?

[4messages](https://play.google.com/store/apps/details?id=com.goodwy.messages) is a fork of qksms which gets frequent updates.

**Comment by markcellus** [comment]
Thanks. It says the 4messages software is open source but where is the github repo?

**Comment by andsofine** [comment]
> > Good question! Does anyone know of an alternative app?
> 
> [4messages](https://play.google.com/store/apps/details?id=com.goodwy.messages) is a fork of qksms which gets frequent updates.

where is the source code?

**Comment by starlingfire** [comment]
@markcellus, @andsofine, it took all of an eight-second internet search: https://github.com/Goodwy/4Messages

That being said, that repo doesn't have any readme, or even a link to their Google Play page. However, their other repo, https://github.com/Goodwy/PlayBooks, does link to that app's play store page. 

YMMV.

**Comment by markcellus** [comment]
Seems kind of sketch. Aurora store shows that it uses Google analytics, which is a deal breaker. It's also not clear which repository the source code is actually coming from.

I'll just hold off a little longer. Qksms seems to work fairly well for me still. Thanks for recommendation though!

**Comment by andsofine** [comment]
> @markcellus, @andsofine, it took all of an eight-second internet search: https://github.com/Goodwy/4Messages
> 
> That being said, that repo doesn't have any readme, or even a link to their Google Play page. However, their other repo, https://github.com/Goodwy/PlayBooks, does link to that app's play store page.
> 
> YMMV.

it has trackers

**Comment by ghost** [comment]
Please archive this repository!
@moezbhatti

**Comment by moezbhatti** [comment]
Not abandoned – I'm resuming work on the app. I apologize for the lack of communication while I haven't been actively working on the app!

**Comment by n-ce** [comment]
@moezbhatti please close this similar issue  #1881 and other unnecessary issues #1876 #1885
