### ISSUE TITLE
Description text of pictures in the conversation list is wrong

### ISSUE THREAD

**Issue by l3d00m** [moezbhatti/qksms#188]
### DESCRIPTION

The description text of pictures (MMS) in the conversation list is wrong
### STEPS
1. Receive or send a MMS (Picture) with a description
2. Go to the conversation view
### EXPECTED

The description text should just say "description" and not "part/text/plain:description"
### OBSERVATIONS

![screenshot_2015-08-28-12-38-32](https://cloud.githubusercontent.com/assets/12055376/9544966/87c21f5a-4d85-11e5-871f-08d9c43bd29e.png)
![screenshot_2015-08-28-12-39-02](https://cloud.githubusercontent.com/assets/12055376/9544965/862fc552-4d85-11e5-8e26-2eba33e9ee57.png)

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
