### ISSUE TITLE
reminder: the developer owes you nothing!

### ISSUE THREAD

**Issue by kunago** [moezbhatti/qksms#1885]
Having read quite a lot of hateful notes about the app being abandoned, let me please speak for the developer:

He owes you nothing at all! He spent huge amounts of time developing something you took for granted and now many spread immature comments on his account. Anytime anyone decides to quit, he can quit and you should accept and respect that. That is all you can do. Deal with it! If you believe you can do better, sit down and write your own app. At the time you might be happy with it, have fun reading all the dumb comments from even dumber individuals whining for any support that they never paid for. Time costs money. Surprise!

So have fun crying in the corner and I wish the developer good luck not running into those that think everything is for free and they have the right to have it all, while others should sacrifice.

Wrong! Shut the mouth and grow up!

**Comment by kunago** [comment]
Specifical recognition:
#1881

**Comment by Ilithy** [comment]
I approve this.

**Comment by DarthPleurotus** [comment]
I'll refer you to my follow up in #1881. I agree that the developer isn't obliged to maintain the app. Given that they'd vigorously promoted it as the best solution for SMS on Android, I think the decent thing to do when ceasing active support would be to announce the change, not keep promoting an app that no longer works.

My choice of words was rash and inconsiderate; I've apologized for my tone in my previous post. But it's morally dissonant for you to call me out for comments you consider hateful and then similarly use language that promotes an environment where personal attacks are tolerated. I accept and welcome your disagreement with my opinions but reject your condescending tone and personally hurtful language.

**Comment by kunago** [comment]
In my opinion, and don't get me wrong, the developer can decide to do what he wants. You should be grateful he dedicated so much time to work on the app in the past. You have no right to blame people for their decisions and put down their work because you believe it is not fair to you personally. As I stated, you did not pay for the development so it's really unfair to give it labels like "garbage app". That is simply way too far, sorry.

Your choice of words made me reply to your comment in specific as I am a developer also so I know what it takes to create something and then receive such feedback back. This space is not meant to be used as a "review" space. This is for issues, as you know. And using "garbage app" in the issue title does not seem to be anything but an inappropriate language and misunderstanding of what GitHub is used for. As much as you may disagree with my tone and being personal, you were personal talking to the developer as well. I don't feel bad at all for pointing towards your comment.

**Comment by Ilithy** [comment]
Respect and understanding are worth gold, think about it.

From France with love.

**Comment by jasonm23** [comment]
We need people to simply understand 3F.

- Fix it
- Fork it
or
- F&%k off

**Comment by Louson** [comment]
The app is forked and maintained by /e/ https://gitlab.e.foundation/e/os/Message

**Comment by kunago** [comment]
> The app is forked and maintained by /e/ https://gitlab.e.foundation/e/os/Message

That's neat. Is there any official release on Google Play, F-Droid or anywhere else? I did not find it. Thanks.

**Comment by Louson** [comment]
Unfortunately no because I think they build it with the OS. But maybe it's just a question to point the right repository in fdroid

**Comment by jfmcbrayer** [comment]
I tried to build the /e/ fork, and I was eventually able to get it to build, but it didn't run. Possibly something to do with NTK, since that's what I had to fiddle with to get it to build.

**Comment by sbstn87** [comment]
If you guys knew something more about this fork - where to get a working APK, or is it going to be added to F-Droid, would appreciate letting people know in this thread.

Especially nowadays. when Signal has announced dropping SMS support.

Or perhaps you know any viable alternative?

**Comment by sbstn87** [comment]
I have found this fork of QKSMS:

https://github.com/wrwrabbit/Partisan-SMS

But I'm a bit skeptical about installing it.

**Comment by Npa972** [comment]
@sbstn87 hi why are you skeptical ? Security ?
There is also : 
https://github.com/Goodwy/4Messages
But for this one I'm skeptical (i thing the developer just grab abandoned app and push it on google play ?).
I'm not a developer at all just a simple user.
For the moment i use Yaata (google play) ; not open source i think but incredible sms app.
Sms are very important for me professionally speaking.

**Comment by sbstn87** [comment]
Yeah, it is a quite modified fork (of an app in which privacy and security are of paramount importance) by some random person from the internet. What can go wrong?

If I could check the source code, I would, to be sure it does not do anything sketchy.

I files a request to submit the app to F-Droid. This would ensure it's legit and nothing funny is going on under the hood.

**Comment by e-t-l** [comment]
> I tried to build the /e/ fork, and I was eventually able to get it to build, but it didn't run

Do we even know that the /e/ fork is being actively developed? The last commit was to update it to v3.9.4, around the time that Moez published the last QKSMS release, which is also versioned 3.9.4. Makes me think /e/ was simply keeping the app current with QKSMS's changes.

**Comment by Louson** [comment]
There is no release but the last commit is a month ago.

I don't think they put so many effort in it and I am not sure it is very trustable

**Comment by e-t-l** [comment]
If you're still referring to the /e/ fork, they're a reputable group and I would trust them. But it don't think they're making active improvements to qksms, is what I'm saying. I actually like what I'm seeing from Partisan-SMS. It's under active development by a privacy-oriented team that also seems good about user feedback. They said they're planning to publish an updated version on F-Droid sometime soon, and when they do I think I'll install it

**Comment by jasonm23** [comment]
Linking Partisan SMS https://github.com/wrwrabbit/Partisan-SMS

Please confirm this is the project you mean

**Comment by e-t-l** [comment]
Yeah that's the one. It was already linked in https://github.com/moezbhatti/qksms/issues/1885#issuecomment-1278097179 above so I didn't think  to relink it

**Comment by moezbhatti** [comment]
Thank you all for the support. I'm working on the app again, and I've left a bigger comment on #1881 summarizing some of my thoughts :)
