### ISSUE TITLE
[ENHANCEMENT] Difference between sent and received messsages in converstion list

### ISSUE THREAD

**Issue by l3d00m** [moezbhatti/qksms#189]
There is currently no difference in the conversation list between a received and a sent message.
Example WhatsApp: First message is sent, second is received.
![screenshot_2015-08-28-13-16-10](https://cloud.githubusercontent.com/assets/12055376/9545160/3c5b0fb6-4d87-11e5-98e0-b73b13c788da.png)

**Comment by moezbhatti** [comment]
I don't think there's a column in the SMS Conversation table that tells you the direction of the last message in the conversation, so there isn't a super efficient way to implement this without writing a custom table (which I'd like to do eventually)

**Comment by moezbhatti** [comment]
Implemented in 9ae7775052f7decad4d65a4df5f5290cfd4173f1
