### ISSUE TITLE
Fails to send message

### ISSUE THREAD

**Issue by Kcchouette** [moezbhatti/qksms#190]
- My message : 32 times the word 'test' 
- All the option by default, just check "delivery confirmations"

Results: Fails to send the message **instantaneously** after trying to send it.
On QKSMS 2.0.1
I have Android 4.2.2

Thanks in advance

**Comment by moezbhatti** [comment]
This should be addressed in QKSMS 3.0, as it now uses the official method for sending long SMS messages
