### ISSUE TITLE
3.10 crashes on run.

### ISSUE THREAD

**Issue by GOTO-GOSUB** [moezbhatti/qksms#1904]
3.10 crashes when attempting to run it on my Pixel 6 Pro (Android 13).

This was installed from the APK here on Github, and 3.9.4 worked OK.

I have tried to force close the app and clear the data and cache but all that happens is the icon zooms out a bit when tapped and then nothing. When installed over the top of 3.9.4 I get an error message advising me that the app keeps closing.

Clearing the cache and installing 3.9.4 restores operation.

**Comment by moezbhatti** [comment]
Fixed in 3.10.1. Should be live in a few minutes!

**Comment by moezbhatti** [comment]
https://github.com/moezbhatti/qksms/releases/tag/v3.10.1
