### ISSUE TITLE
BUG: Unable to receive MMS 

### ISSUE THREAD

**Issue by Moostek** [moezbhatti/qksms#1906]
### DESCRIPTION
I did not receive the MMS. The sender verified that the SMS (with a longer textation) was sent. 

### STEPS
1. The sender sent me an SMS as MMS 
2. I did not receive this MMS 

### EXPECTED
I did expect incomming MMS. 

### OBSERVATIONS
I did not receive sent MMS. 

Some more questions: 

- Is QKSMS capable to send and receive MMS? 
- How do i switch from SMS mode to MMS? 
- How do i select to send textation via MMS in QKSMS? Is it sort of automated when i add the attachment? 
I would like to make manual selection to send MMS. 

Thank you! 

Android 9 (LineageOS 16.0) @ QKSMS 3.9.4

**Comment by 002gRTEah3mRYH** [comment]
MMS are supposed to work, but doesnt work for me and some people...

**Comment by Moostek** [comment]
I also tried to update the APN for MMS service, but it did not work either. I have the double-SIM phone. The problem is that via 1st SIM i can send/receive MMS, while via 2nd SIM i can not. The operator of the SIM with non-functional MMS service told me that for MMS i need to have active mobile data. So this is it. I can not send MMS via 2nd SIM, because i use mobile data with the 1st SIM. The dual-SIM phones are not capable to have switched on active mobile data on both SIM cards, i have to choose just one. So i have been told that the only solution is use 2nd SIM with mobile data. 

So i guess this is the problem, it seems that the problem is not on QKSMS;)

**Comment by e-t-l** [comment]
@Moostek I'm sorry you have experienced this problem with your SIM providers! Since the problem cannot be solved by QKSMS, could you please Close this issue?

**Comment by Moostek** [comment]
Yes, no problem.
