### ISSUE TITLE
Welcome back, Moez!

### ISSUE THREAD

**Issue by kipuyanoo** [moezbhatti/qksms#1908]
hello again! keep it up!

**Comment by rjolina** [comment]
hooray!!!

**Comment by gun4qmm7h** [comment]
![image](https://user-images.githubusercontent.com/74073434/215129106-5821fd39-98cb-403f-ad82-4f437e2cd89a.png)

**Comment by moezbhatti** [comment]
thank you! I'm super happy to finally be working on QKSMS again

**Comment by HiddenLeveI** [comment]
@moezbhatti come back 🙏
