### ISSUE TITLE
Landscape interface is unusable

### ISSUE THREAD

**Issue by shsuenishi** [moezbhatti/qksms#191]
Tried using landscape mode in 4.1.2 and 4.4.4. Message text appears to share the same area as the punctuation bar. Typed message is visible until you hit space bar then the message is no longer visible because it is replaced by the punctuation bar or word suggestion. Message can then only be viewed if you remove the keyboard and view the full screen interface.

**Comment by oliverw1** [comment]
As a heavy user of landscape for writing texts, I too am bothered by this. Perhaps this could be solved  by using the space in which currently the addressee is shown as the actual text field. After all, most of the times, you know pretty well who you're texting, so it's not something critical to keep in landscape mode. 

This could be an enhancement request, useful for people whose phone displays aren't overly big.

To make it clear, I've added two screenshots showing the current behaviour and the way the stock messaging app does it.
QKSMS in landscape (the "i" is part of the word suggestion bar):
![screenshot_2015-11-25-00-28-37](https://cloud.githubusercontent.com/assets/4733178/11383973/2fb4460e-930c-11e5-8dd8-87d9dc6fac43.png)

Stock messaging app in landscape:
![screenshot_2015-11-25-00-16-28](https://cloud.githubusercontent.com/assets/4733178/11383954/19d5a5b2-930c-11e5-9bbc-4fd8a7fe3a66.png)

**Comment by moezbhatti** [comment]
This is fixed in QKSMS 3.0
