### ISSUE TITLE
Clicking block after opening message via notification, does not work

### ISSUE THREAD

**Issue by vdbhb59** [moezbhatti/qksms#1918]
F-Droid 3.10.1 APK only and not happening with git APK.

### DESCRIPTION
Clicking block after opening message via notification, does not work.

### STEPS
1. Open a message from notification
2. Click on 3 dots to open message options
3. Click block
4. Nothing happens (neither in reality too)

### EXPECTED
The Message should get blocked.

### OBSERVATIONS
Nothing happens.
To block then, I have to force close the app, then relaunch QKSMS app. Open the relative conversation, click 3 dots and click block. This works as expected.

This happens everytime since the latest update. Earlier this bug was not there.

**Comment by xxxxme** [comment]
Duplicate of #1932

**Comment by vdbhb59** [comment]
> Duplicate of #1932

To clarify, 1932 is a duplicate of mine (1918). I created on Feb 3, while 1932 was created on March 14.

**Comment by vdbhb59** [comment]
Any update @moezbhatti
You did update F-Droid but the code here is stuck for ages.

Edit: 16.04.2023 -- At least respond mate. You have been committing to the QKSMS private repo, and been coming and seeing the issues regularly, but not even bothering to respond. Just a simple response would be great.

**Comment by vdbhb59** [comment]
How rude. He keeps making changes every month but... Seriously...

**Comment by vdbhb59** [comment]
Closing as the developer is a hopeless fellow and does not care from everything I can see...

**Comment by Joeviocoe** [comment]
Coming up on year 3 without a release.  So marking this project as stale and no longer actively developed.  Recommending users to uninstall and use something else.
