### ISSUE TITLE
MMS having trouble

### ISSUE THREAD

**Issue by ezark** [moezbhatti/qksms#192]
MMS doesn't work as well as it does in Textra. I don't receive any pictures, and occasionally a group text will sort of work. I always have my data turned off. Textra will tell me when I need data on in order to get a text. QK never tells me, so I end up unable to receive. I can usually send to a group a text. I know this isn't very detailed, I'll give you more info if you ask me.

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0
