### ISSUE TITLE
App crashes when trying to unblock a number

### ISSUE THREAD

**Issue by takmilihsan** [moezbhatti/qksms#1966]
### DESCRIPTION
When I try to unblock a number by tapping on the cross button next to the number/contact, the app crashes. If I try to unblock again, android gives me the notification that "QKSMS keeps stopping"

### STEPS
1. Suppose a number/contact is already blocked in QKSMS
2. Go to the hamburger menu on the top left of the app
3. Go to Blocking > Blocked numbers
4. Tap on the cross to the right of the number/contact you want to unblock
5. App crashes and returns to inbox
6. Repeat steps 2-5
7. Android notification "QKSMS keeps stopping" is shown

### EXPECTED
The number/contact should be unblocked upon tapping the cross to the right in the Blocked numbers menu and future SMS from this number/contact should be received and shown in inbox

### OBSERVATIONS
The app crashes

## OTHER INFO
App version: 3.10.1
Installed from: F-droid
Android version: 13

**Comment by Cyber5imon** [comment]
Also experiencing this issue. Clicking the x next to any block number causes the app to crash.

**Comment by fred747** [comment]
Not exactly the same but unblockin a number only "holds" for a couple of hours ie the number is automatically reblocked again

**Comment by takmilihsan** [comment]
Downgrading to F-droid version 3.9.4 solves the issue for me. So, I am closing this. Sadly, the project seems abandoned, so probably there will be no more solutions to future problems.

**Comment by dhjaber** [comment]
Dears 
I have new copy that i have upgraded it from this source code and it is available on Play store here :
https://play.google.com/store/apps/details?id=com.successtech.smspro

**Comment by takmilihsan** [comment]
> Dears I have new copy that i have upgraded it from this source code and it is available on Play store here : https://play.google.com/store/apps/details?id=com.successtech.smspro

Well, no. Nowhere is it mentioned that the abomination you posted is a fork of qksms. And what are you supposed to have "upgraded"? Even if you used the source, you have just copied it without attribution (stolen) and put it up with ads (even worse). Egregious behavior!

**Comment by dhjaber** [comment]
> > Dears I have new copy that i have upgraded it from this source code and it is available on Play store here : https://play.google.com/store/apps/details?id=com.successtech.smspro
> 
> Well, no. Nowhere is it mentioned that the abomination you posted is a fork of qksms. And what are you supposed to have "upgraded"? Even if you used the source, you have just copied it without attribution (stolen) and put it up with ads (even worse). Egregious behavior!

Not true. And who said that QKSMS was stolen? It's open source, 
allowing anyone to use and create their own version. 
Your response is quite inadequate.
