### ISSUE TITLE
Received message keeps screen on

### ISSUE THREAD

**Issue by peepay** [moezbhatti/qksms#197]
Whenever I receive a message, the screen turns on and stays that way. It does not turn off after the display timeout. Basically, when I did not hear the notification sound, I have learned to check messages once I feel the phone get hot in my pocket (due to the screen being on).
This happens even though I have the "Wake phone" setting disabled both in general settings and in specific contact's settings.
Anyone else noticing this unpleasant behaviour? Do you need some additional data to investigate?
Nexus 6, Android 5.1.1, QKSMS 2.0.1

EDIT: I noticed I am not alone: https://plus.google.com/u/0/108762715235332764384/posts/FjbgtUP1pvn

EDIT 2: This happens only with one specific contact for which I have set separate notification sound, other contacts don't do this. However, as I stated, the "Wake phone" setting is disabled both in general settings and in the specific contact's settings. Also, the contact's notification settings are identical to general notification settings, except for the sound.

**Comment by moezbhatti** [comment]
Is your phone plugged into the charger when this happens or is that irrelevant?

**Comment by peepay** [comment]
Irrelevant, happens both on charger and unplugged.

**Comment by peepay** [comment]
So, @moezbhatti, do you have any clue?

**Comment by moezbhatti** [comment]
Hmm, I still haven't had this happen on my own device. Are you using the EndlessJabber/Yappy plugin by any chance?

**Comment by peepay** [comment]
Neither of those, I don't even know what they are.

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0 as the app is no longer manually waking the screen
