### ISSUE TITLE
After deleting multiple message threads, receiving a new message shows the wrong contact in the app view. Messages then sent to multiple recipients.

### ISSUE THREAD

**Issue by sparkybear** [moezbhatti/qksms#214]
After deleting multiple threads on an LG G5, on current Android build.

A new text will come in. In the app view it says the wrong contact, when clicking on the message it then shows the proper contact who sent the message. Replies are sent to both recipients until the thread is deleted, or application is force stopped. This happens after reinstallation, clearing cache, any time you receive a message shortly after deleting multiple threads.

Steps to reproduce:
1. Have multiple SMS threads in inbox
2. Delete all but 1 Thread
3. (Optional) Receive a new message from a new recipient
4. Reply to the non-deleted thread

Expected Behavior:

Message will be sent to displayed recipient.

Current Behavior:

Message is sent to the recipient of one of the deleted threads, not the displayed recipient, and a new messaging thread to the unintended recipient will be created.

Appears to send message to the recipient of the most current, deleted thread.

Workaround: 

Force Closing the application

This has occurred on multiple phones and across updates to Android, the LG G3, G4, and a Nexus 5.

**Comment by sparkybear** [comment]
I've updated this request with steps to reproduce as well as with more information regarding the hardware and software that the behavior is found on.

**Comment by moezbhatti** [comment]
The caching system has been re-done in QKSMS 3.0. I've tested this with the steps described and can't reproduce it anymore
