### ISSUE TITLE
Group Chat MMS Failing to Work

### ISSUE THREAD

**Issue by IronPiston** [moezbhatti/qksms#216]
Using AT&T, I cannot send an MMS message to people in a group chat. I seem to be able to receive without issue, but any sent messages say sending perpetually. I am using auto configure APN for MMS, so I am using http://mmsc.mobile.att.net, Port 80, proxy.mobile.art.net

**Comment by IronPiston** [comment]
Using Textra with these same settings, the messages send instantly and MMS has absolutely no issue

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0, as it no longer requires manual entry of APN settings and uses the system sending methods
