### ISSUE TITLE
Modify Recents pane for QKSMS to match color theme 

### ISSUE THREAD

**Issue by sentrysticks** [moezbhatti/qksms#219]
If you see the attachment QKSMS is a nice fuchsia color for me but when I hit Recents it shows a big black border with the green icon and I would love to see it match if I change it! Idk if there's an easy way to do this but it would definitely add to the overall Polish of the app.

keep up the great work! 
![screenshot_2015-10-02-10-41-50](https://cloud.githubusercontent.com/assets/11378947/10253431/3a4dd772-68f2-11e5-8477-1105934c3147.png)

**Comment by l3d00m** [comment]
Leaving [this](https://www.bignerdranch.com/blog/polishing-your-Android-overview-screen-entry/) here.

**Comment by moezbhatti** [comment]
QKSMS doesn't use the themes xml in order to do its theming, because it has so many different colours. To implement this would require hardcoding a *lot* of themes for all the different color options

**Comment by moezbhatti** [comment]
AFAIK, not possible without a ton of tedious hardcoding. Closing for now

**Comment by moezbhatti** [comment]
Figured out how to do it.
