### ISSUE TITLE
Notification disappears if phone locks while in app

### ISSUE THREAD

**Issue by eoinobrien** [moezbhatti/qksms#224]
If I lock my phone while in the app and I receive a message, the notification quickly pops and disappears again.
I also tried to see if being in another conversation to the one that received the message affected it, but it seems the message disappears no matter what conversation I'm in when the phone locks.

This is on a Galaxy S6 SM-G920F, Android 5.1.1 and QkSMS 2.0.1

**Comment by moezbhatti** [comment]
Works fine on my phone. Anyone else have this issue?

**Comment by ziem** [comment]
In my case it also disapears. @moezbhatti Is it expected behaviour?
Motorola Moto E 4G XT152, Android 5.0.2

In my opinion it should only disappear when I click tick button on quick reply dialog or when I'm in conversation with the person which sent message.

**Comment by pwnulatr** [comment]
Bug is still present on Samsung-SM-G925A, Android 5.1.1, QKSMS 2.5.4

Seems to mark message as read when this happens.

**Comment by benrolfe** [comment]
Same issue on Moto G 3.

**Comment by Tapemaster21** [comment]
Same issue, OnePlus 3T LineageOS. QKSMS Version 2.7.3.

**Comment by moezbhatti** [comment]
This is fixed in QKSMS 3.0
