### ISSUE TITLE
MMS picture messages don't render if visible when conversation is opened unless first scrolled off screen.

### ISSUE THREAD

**Issue by The0x539** [moezbhatti/qksms#248]
Certain issues prevent me from getting screenshots, but:

If you have a picture message that's recent enough that it shows up within the first screen of a conversation so it's visible without scrolling, it doesn't render unless scrolled off-screen and then scrolled back onto the screen. While invisible, timestamps and such just act as if there's a bubble there when there isn't.

**Comment by glitchphan** [comment]
![screenshot_20151225-215923 01](https://cloud.githubusercontent.com/assets/14065496/12105378/7417d796-b311-11e5-9959-a32e803fb627.png)
![screenshot_20151225-215936 01](https://cloud.githubusercontent.com/assets/14065496/12105386/7c6a1d0a-b311-11e5-877b-b47512f01b66.png)

**Comment by The0x539** [comment]
Yep, that.

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0
