### ISSUE TITLE
Add full Pebble support

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#256]

**Comment by glitchphan** [comment]
Would be nice :)

**Comment by moezbhatti** [comment]
@glitchphan are you a pebble user? What kind of features would you like to see with the pebble support?

**Comment by glitchphan** [comment]
I am a Pebble and Pebble Time user. I have been using Gadgetbridge lately instead of the official app so that I don't have to sideload updates. It would be cool if qksms could send its own notification with options to reply or call when Dialer for Pebble is installed or something like that. In GB there is the option to turn off SMS messages so that another app can send them. I'm sure I've thought of more features as I receive messages in different situations, so I will have to write those down as they come to me :).

**Comment by moezbhatti** [comment]
Awesome, yeah let me know if you think of anything else. Pebble sent me a watch, so I can add these features myself now

**Comment by glitchphan** [comment]
Noticed something the other day: When I have Gadgetbridge set to never send SMS, meaning the Pebble Time is receiving the notifications from QkSms (or Android?), multiple messages come in as "2 more messages", "3 more messages", etc. They "stack up" kinda, and anything past the first one is unreadable. If I have Gadgetbridge set to send the SMS notifications, meaning it will be handling the SMS, they are all separate and individually readable, but I think I was having issues with MMS that way. The point, though, is that if you add any enhancement to the SMS notification for Pebbles, see if you can do anything about that stacking/counting up problem.

**Comment by roidelapluie** [comment]
+1 glitchphan big sms are splitted up in two and this comes from QKSMS.

SMS replies on pebble should be managed by Gadgetbridge, not by QKSMS. GB does not support actionables notifications. ( @ashimokawa could confirm? )

**Comment by ashimokawa** [comment]
Pebble wants you to support their ecosystem, that probably would involve using PebbleKit Android, so you can send notifications to the pebble independently from the Android notifications. Be aware that PebbleKit communication can be intercepted by any application on the phone without  requiring any permission. So this feature should be optional if you go that way.

Right now  we (Gadgetbridge) just extract the information from the QKSMS Android notification you send or listen to the systems SMS Intents (depending on the users settings). Both have their pros and cons, but if we (Gadgerbridge) are smart enough we should combine both: Get the data from the SMS Intent (to get the phone number for replys) and associate this with the notification on screen, so we can dismiss it or open QKSMS on the phone. Would be a hack but, it should be possible.

But most of Pebble users, maybe >99%, are not interested in Gadgetbridge, and just go with the official Pebble App, so you might serve more happy users if you go their way. We will continue supporting everything we can in the open source ecosystem as good as we can, and that includes QKSMS.

@roidelapluie 
If you configure Gadgetbridge to use the regular SMS support (while still using QKSMS), does the message also get split? And what were the reasons again, that you prefer getting the notification from QKSMS as a generic notification? Was is "dismiss" and/or "open on phone" support?

**Comment by glitchphan** [comment]
For me it was that there is no notification on the watch when receiving a picture message with no text. :)

**Comment by moezbhatti** [comment]
RIP Pebble

**Comment by protist** [comment]
FWIW I'm still keen on Pebble support. Does closing this issue this mean that there is no more Pebble support planned? I know that Pebble is dead, but could you add support via Android Wear? I'm not sure if this is how it works, or how easy this is.

**Comment by moezbhatti** [comment]
@protist it's no longer planned, as I simply don't have the time to prioritize it. Unfortunately it's completely different than Android Wear and would require dedicated time (and hardware) to be able to work on it

**Comment by protist** [comment]
@moezbhatti Fair enough. That makes sense. Thank you for the answer.
