### ISSUE TITLE
[Feature request] Add the ability to change the "wallpaper" with photos 

### ISSUE THREAD

**Issue by LifeIsStrange** [moezbhatti/qksms#267]
Like the https://play.google.com/store/apps/details?id=com.jb.zerosms
It's an absolutely needed Feature for personnalisation, with this each human can create his design :) 
Thanks for making opensource software, your app is awesome.

**Comment by licaon-kter** [comment]
+1

**Comment by LifeIsStrange** [comment]
You are everywhere licaon ^^

**Comment by licaon-kter** [comment]
No, you are just in my path... 

:)

**Comment by LifeIsStrange** [comment]
Haha =) not just F-Droid, I'm a big fan of free Software and I looove github (which is sadly proprietary :/ ) 
Actually I try to contribute to servo which is the layout engine of the future (x30 Faster than gecko and blink !!)  it will be a revolution for the web :) and for the Firefox marketshare. 
I lost also my free time on uBlock Origin which is the technical successor of Adblock plus.

**Comment by moezbhatti** [comment]
Not going to be implementing this, as it doesn't agree with the design of the app
