### ISSUE TITLE
[Feature Request] Option to change received/sent message bubble colour

### ISSUE THREAD

**Issue by RedDragonx** [moezbhatti/qksms#275]
I'm using Amoled screen so I'm always using dark mode to save battery, but the received message bubble colour is grey in the dark mode so sometime it's not comfortable to read. I wish you can add an option to change received/sent message bubble colour. I used to use Textra and my received bubble is blue and sent bubble is green, it's really easy to read in the dark mode.

**Comment by sm4rk0** [comment]
It's already possible to enable/disable sent/received message bubble color.
Go to Settings -> Appearance -> Message bubbles
They can be gray (if disabled) or whatever color you have chosen in Color scheme setting.

**Comment by sm4rk0** [comment]
Sorry, now I understand - you want to be able to set different colors for sent/received bubbles...

**Comment by RedDragonx** [comment]
Yes, that's what I want. Can you add that feature to QKSMS?

**Comment by gaston68cz** [comment]
I would like this setting too

**Comment by raceman95** [comment]
Would be great to be able to customize the sender and incoming message bubble colors seperate from the theme color, and also the text color in the bubble. Also a no bubble option (a "clear" option) so then it would look like hello. Hello was honestly the best texting app I've ever used from a UI/design perspective.

**Comment by moezbhatti** [comment]
Don't think I'm going to add this feature, as it doesn't agree with the app's design language in my opinion. Also would like to avoid cluttering the settings
