### ISSUE TITLE
[Feature Request] Categories

### ISSUE THREAD

**Issue by airon90** [moezbhatti/qksms#277]
Hi, I love your app but it miss a feature that prevents me to use your app.
I use the default messaging app on the ASUS Zenfone 2, ASUS Messaging. 
Normally SMS are listed in the Main category. Then, there are two other categories:
- VIP: shows all messages of VIP contacts, set in the ASUS Contacts app. Those message are shown also in the main section and the profile pic has a VIP badge
- Private: all messages sent in the Private category are protected by a numeric password. Those messages are not shown in the main category

I don't use VIP category but I use Private category and by now, QKSMS doesn't show any private messages, as they have been deleted.

Is it possible to implement categories? Instead of just VIP category, you should implement a category for every group in the contacts.

**Comment by moezbhatti** [comment]
I do not plan on implementing a VIP category, but I will be implementing a private category. As such, I'll merge this issue with #377
