### ISSUE TITLE
Conversations list CAB options

### ISSUE THREAD

**Issue by arkon** [moezbhatti/qksms#284]
I feel like some improvements could be made to the the contextual actions in the conversations list:
- Redundant "Done" actions in both the FAB and overflow menu, which could just be replaced with an "X" icon at the top left
- FAB could be a more common action like deleting threads?
- Non-standard circular checkboxes beside the user avatars remind me more of radio buttons than checkboxes

**Comment by moezbhatti** [comment]
Agree with all of this

**Comment by moezbhatti** [comment]
This will be incorporated into #874
