### ISSUE TITLE
Import/export messages

### ISSUE THREAD

**Issue by glitchphan** [moezbhatti/qksms#285]
The ability to export SMS/MMS messages and then import them on another device would be extremely useful to those of us that change phones often!

**Comment by xavihernandez** [comment]
And it would be good if export format is compatible with SMS backup & restore (because it is the most common tool used for SMS/MMS backup).

**Comment by cirelli94-unimib** [comment]
Even better it would be cloud backup support.
Maybe with automated/scheduled options.

**Comment by glitchphan** [comment]
I'm not much of a fan of putting personal information in cloud services, but I could see how some people might like it :).

**Comment by licaon-kter** [comment]
There are options for private local cloud ( eg. Syncthing, Seafile ) so it could be useful for some.

**Comment by valerio-bozzolan** [comment]
I think that you can follow the [Slight backup](https://f-droid.org/repository/browse/?fdid=de.shandschuh.slightbackup) format. It's a simple `.xml`.

**Comment by glitchphan** [comment]
Is that convertible to vCard/vcf ?

**Comment by collectorgeneral** [comment]
+1 here too. I am looking everywhere to backup my messages but alas, nothing simple. I would LOVE it if this app implements this feature. As someone mentioned above, something like an XML format would be fantastic. Clould is upto you (dev), but I am more of a local backup guy. See if you can do something about it.

**Comment by xavihernandez** [comment]
@collectorgeneral at this point, you can use [SMS backup & restore](https://play.google.com/store/apps/details?id=com.riteshsahu.SMSBackupRestore) or [Sligh backup](https://fossdroid.com/a/slight-backup.html) to backup SMS.

**Comment by jtsurf18** [comment]
SMS backup and restore is nice, but built in would be awesome. Glad to see this is still being considered

**Comment by moezbhatti** [comment]
Implemented 10b37d43891eaa6d8cacb6657726b478f591fee1...dc3e54a85a221b7eb0e286485eb741694092c2ca!
