### ISSUE TITLE
Emoji-only messages displaying as pseudo-stickers

### ISSUE THREAD

**Issue by The0x539** [moezbhatti/qksms#286]
This used to be a thing, but then I believe it got trampled by the kraken. I brought it up on G+ but it never rematerialized.

**Comment by moezbhatti** [comment]
There's an option in the settings that should turn the feature back on

Unless you're talking about something else?

**Comment by The0x539** [comment]
Not seeing it.

**Comment by The0x539** [comment]
I don't mean emoticon to emoji conversion if that's the setting you're referring to, I mean displaying emoji-only messages as bigger and without a bubble, a la stickers in certain non-SMS apps, albeit smaller.

**Comment by moezbhatti** [comment]
Ahhh, I remember what you're talking about now

I'll have to look into this
It was a pretty neat feature

**Comment by JayDoc386** [comment]
Please bring this to QKSMS 3.0.

**Comment by spocko** [comment]
Android Messages does this.

**Comment by digitalcircuit** [comment]
It might be worthwhile noting [Quasseldroid, a GPLv3 open source IRC messenger](https://quasseldroid.info/ ), does exactly this.  The developer `justJanne` exists [on GitHub](https://github.com/justjanne/ ) and freenode IRC/`#quasseldroid` in case you'd like to contact her with questions.

From a quick glance, most of the magic is in [`Patterns.kt`](https://git.kuschku.de/justJanne/QuasselDroid-ng/blob/5ac008f5948bf343e2e3d6a5f314963166b9da8c/app/src/main/java/de/kuschku/quasseldroid/util/Patterns.kt#L122-131 ) and [`EmojiData.kt`](https://git.kuschku.de/justJanne/QuasselDroid-ng/blob/5ac008f5948bf343e2e3d6a5f314963166b9da8c/viewmodel/src/main/java/de/kuschku/quasseldroid/util/emoji/EmojiData.kt ).
