### ISSUE TITLE
[feature-request] Sliding between Conversations

### ISSUE THREAD

**Issue by mandeeps708** [moezbhatti/qksms#290]
It would be great if QKSMS have this feature.
When in conversation view, swipe (slide) left to bring the next conversation. It's a one of the most needed feature. 
Suppose, if there is a long list of conversation, it would be easier to slide and read the conversations rather than going back and opening one by one.

I know it has the last opened conversation feature when we swipe right. But you can divide half of the screen like Upper half of the screen brings back the main Inbox (sliding right, as per now). And the bottom half of the screen may be used as navigating through different conversations (left and right). Just a suggestion.

**Comment by moezbhatti** [comment]
I don't plan to add this. It would add an unnecessary amount of complication for a very non-standard UX pattern that I can't see many people using
