### ISSUE TITLE
Quick reply window shows up when unlocking screen to an already open conversation (bug?)

### ISSUE THREAD

**Issue by alaskan-hippie** [moezbhatti/qksms#293]
Scenario: receive a message, enter app to view message, after which I lock my screen with the app still up, a new message comes in from the same sender, I unlock my screen and the quick reply window is open for that new message while displaying overtop of the same conversation open below the quick reply window.

I'm not sure if this is a bug, but it's not ideal for use. It delays access to the actual conversation. Perhaps add some test to see whether qksms is up/active when unlocking screen to determine whether to open quick reply window?

**Comment by moezbhatti** [comment]
QK Reply has been removed in QKSMS 3.0 in favor of rich notifications
