### ISSUE TITLE
Can't send quick message sms when declining the call. 

### ISSUE THREAD

**Issue by bendingtime** [moezbhatti/qksms#297]
Phone - One Plus One X
Oxygen OS 2.1.4

### DESCRIPTION
Can't send quick message sms when declining the call. 

### STEPS
0. Set Qksms as default message app,
1. Do not pick up call,
2. Select "send quick message",
3. Choose one of the pre-definied messages,
4. Select "send",
5. Confirmation "Message Sent" appears but there is no sms in qksms app, and no real sms is sent.

### EXPECTED
Sent sms while not picking the phone up.

### OBSERVATIONS
Everything works fine when the default google message app is selected.

**Comment by moezbhatti** [comment]
Fixed with #534
