### ISSUE TITLE
Picture in mms conversation is missing after leaving the conversation and coming back

### ISSUE THREAD

**Issue by bendingtime** [moezbhatti/qksms#299]
Phone - One Plus One X
Oxygen OS 2.1.4
### DESCRIPTION

Picture in mms conversation is missing after leaving the conversation and coming back
### STEPS
1. Open conversation in QKsms app,
2. Exchange some messages without picture attachment,
3. Send message with picture attached,
4. Go back to other conversations using arrow in left top corner of the app,
5. Open previously left conversation,
6. Picture is missing, all other messages are left intact,
### EXPECTED

Remember the picture attached in mms in conversation view
### OBSERVATIONS

When you will scroll the conversation down, to hide the messages which should have the pictures and then scroll up, pictures will be visible again.

**Comment by Berzerker** [comment]
I can confirm that this happens as well, any updates for a fix timeline?

**Comment by xavihernandez** [comment]
I can confirm too, I was about to open an issue about it. =)

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0, Preview 5
