### ISSUE TITLE
Quickreply mark as read cancels delay message

### ISSUE THREAD

**Issue by licaon-kter** [moezbhatti/qksms#300]
In version 2.2.4.

Steps to repro:
- set a delay for sending, say 10 seconds
- get a message while using the phone
- reply to message in quickreply
- press send
- before 10 seconds pass, press mark _message as read_ in quickreply

Expected behaviour:
Message will be send after the delay

Actual behaviour:
Message is not sent

**Comment by moezbhatti** [comment]
QK Reply has been removed in 3.0, so I'll close this now
