### ISSUE TITLE
Feature Suggestion: delivery report symbol on contact name

### ISSUE THREAD

**Issue by ilali** [moezbhatti/qksms#305]
Please add a symbol or any other feature in order to understand last sent SMS to the contact is delivered to him/her, directly from last active conversation list.
Now in order to see delivery report user should open the conversation and look at tick symbol in last message, but adding a symbol to the name of contact person in last active conversations list also will be more convenient.

**Comment by licaon-kter** [comment]
+1

**Comment by kolAflash** [comment]
Standard Cyanogenmod 13 SMS/MMS app puts a mark/hook symbol at each message which has been delivered. Would be great to also have this in QKSMS.

**Comment by moezbhatti** [comment]
In QKSMS 3.0, the icon has been replaced by text that explicitly says `delivered`!
