### ISSUE TITLE
Enhancement Request: larger or user settable QK Compose size

### ISSUE THREAD

**Issue by gappleto97** [moezbhatti/qksms#319]
The window is very small on my 6P. It would be nice if this could be made larger based on screen size, or if the use could configure its size in the QK Compose settings.

**Comment by dethstar** [comment]
+1 I just tried it and it's so small in my Moto X Play too.

**Comment by gappleto97** [comment]
Could be a resolution issue

**Comment by moezbhatti** [comment]
For some reason there's too much padding. Not sure what's causing it yet, but I do notice it also

**Comment by moezbhatti** [comment]
The feature has been removed in QKSMS 3.0
