### ISSUE TITLE
Contacts/Dialler creating empty threads

### ISSUE THREAD

**Issue by McFarrell** [moezbhatti/qksms#32]
When browsing either the contacts app or the dialler app on lollipop, in my case both apps are Google's apps, tapping on a contact you have never sent a SMS to before seems to create an empty thread in Qksms. This is a pain as if you tap on a landline number, it is always certain to create an empty thread. This can lead to having multiple empty threads at the top of the app to scroll through unless deleting them everytime.

Screenshot below:

![screenshot_2015-03-04-15-55-37](https://cloud.githubusercontent.com/assets/11316479/6487302/4c8a46ca-c288-11e4-83cb-ad12406602af.png)

**Comment by fcastilloec** [comment]
This also used to happen when the contacts have multiple number associated with them. I thought that was the reason but it's actually what you mentioned. Empty conversations are added for NUMBERS that haven't been used.
This also explains the multiple numbers in one contact, if none of their numbers have been use before I see as many empty conversations as the contact's numbers. If I have used on of the contact numbers to text before, only the other numbers get added as empty conversations.

This is extremely easy to replicate. As ***McFarrell*** mentioned, one just have to open any contact (that hasn't been used for texting before) through the Google Contacts app, and without a fail you'll see the empty thread(s) in QKSMS

**Comment by srcreigh** [comment]
Just got a repro. Sweet. Thanks guys, we will be looking into this.

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0

A conversation won't be displayed unless it contains at least one message
