### ISSUE TITLE
When on quickreply window, notification doesn't close when more than one message is received from the same person. Pressing 'Reply' again will result to a blank conversation window.

### ISSUE THREAD

**Issue by elijahaquino** [moezbhatti/qksms#322]
### DESCRIPTION

Notification / Heads-up still keeps showing "x new messages" whenever I receive one message, pressed 'Reply', then received another message from the same person. 
### STEPS
1. Receive a message from Contact A
2. Press 'Reply'
3. Receive another message from Contact A while sending a reply
### EXPECTED

Notification will be closed
### OBSERVATIONS

Notification is still there, indicating that there are x number of messages received. When 'Reply' is pressed again, a blank conversation without a contact name will appear.

**Comment by moezbhatti** [comment]
QK Reply has been removed in QKSMS 3.0, so I'll close this now
