### ISSUE TITLE
Add meaning to tap of number in conversation with unknown

### ISSUE THREAD

**Issue by fredcooke** [moezbhatti/qksms#325]
Took me far too long to find that a touch of the # in the circle did what I wanted. Seems more logical to use the name/number space for this.

**Comment by fredcooke** [comment]
Note, low priority, serious stability issues involving data loss and crashes must come first.

**Comment by fredcooke** [comment]
Important when no reply received (unreciprocated) as no way to save freshly used number in this case. Have to wait for a reply or reenter in contacts.

**Comment by fredcooke** [comment]
/don't add comments with zero useful content.

**Comment by moezbhatti** [comment]
Adding contacts has been made more intuitive in QKSMS 3.0
