### ISSUE TITLE
notification not working when "do not disturb mode" is enable

### ISSUE THREAD

**Issue by wilfriedroset** [moezbhatti/qksms#326]
I'm running the latest version (from the play store) which is 2.4.1 on a brand new Nexus 6P running latest android 6.0.1.
I'd like to use do not disturb mode (A.K.A priority mode) and still got notify of the message for some person.
Every thing work flawlessly with the standard "messenger" app or with "Textra" (which I don't like).
The problem is that when the phone is in priority mode I don't have any sound/vibration/led notification neither from person in favorite or not.
### DESCRIPTION

Notification not coming through when in priority mode
### STEPS
1. Define at least on person as favorite in contact app (with a star).
2. Configure do not disturb (Setting -> Sound & notifications -> Do not disturb)
3. Configure messages to "from starred contacts only"
4. Set the default sms application to "messenger" (the stock one)
5. Set the phone in priority mode, return to home screen (you also can turn off the screen)
6. Send a message from a number which is starred (Person A) -> You should get a notification (sound/vibrate/led whatever...)
7. Send a message from a number which is not starred (Person B) -> You should not get a notification (no sound/ no vibrate/ no led but still the icon)
8. Set the default sms application to "qksms"
9. Send a message from a number which is starred (Person A) -> You should not get a notification (no sound/ no vibrate/ no led but still the icon)
10. Send a message from a number which is not starred (Person B) -> You should not get a notification (no sound/ no vibrate/ no led but still the icon)
### EXPECTED

Step 9 should behave exactly like Step 6
When in priority mode, The phone should sound/vibrate only for starred contact, instead of that the phone doesn't sound/vibrate at all.
### OBSERVATIONS

Android 6.0.1
QKSMS 2.4.1

Setting in QKsms:
Under notifications
SMS notifications enabled: True
Notfication led: False
Wake phone: False
Show ticker: False
Private notification: Show all
Vibration: True
Notification sound: Default
Call buton: False
Mark as read: False
Under QK Reply, All False
QK compose enabled: False

**Comment by wilfriedroset** [comment]
The issue is still here with the latest update (2.5.4) on nexus 6p (android 6.0.1).

I reproduce the bug with the same steps describe in the first comment.

**Comment by wilfriedroset** [comment]
up

**Comment by moezbhatti** [comment]
Fixed in 359f38202c518781c6d5486a36e4a635b5c96a01
