### ISSUE TITLE
Newly saved contacts not used  for display until app restart

### ISSUE THREAD

**Issue by fredcooke** [moezbhatti/qksms#329]
Message a number. Get a reply. Touch the #. Save the number. Return to the app. Still shows # and number. Kill app. Open again, usually shows correctly.

**Comment by seriosbrad** [comment]
My new contact isn't displaying a name even after restarting the app, or even phone.  It's been more than a week since I added the person.

v3.6.8

**Comment by moezbhatti** [comment]
Until I get this fixed, you can open the Compose screen to force the app to sync with your contacts

**Comment by seriosbrad** [comment]
Fastest reply ever, thanks for the tip! Man, I guess I don't send messages to a lot of people eh

**Comment by moezbhatti** [comment]
Leaving a note that once this is fixed, I should also store the contact's photo URI so that the app doesn't need to try and query for it based on the phone number when we already had it
