### ISSUE TITLE
Scrolling resets on successful send

### ISSUE THREAD

**Issue by fredcooke** [moezbhatti/qksms#332]
Write a message, send it, scroll up to review something, when the message sends, scroll is reset to the bottom again. The widget for send status should be kept the same and just the content of it replaced, or some such similar difference from the current code.

**Comment by sm4rk0** [comment]
Related to #272

**Comment by sm4rk0** [comment]
Fixed with #588

**Comment by fredcooke** [comment]
Appears to be fixed in 2.7.3 as per above comment re #588, so I'm closing this one. Thanks! :-)
