### ISSUE TITLE
Improve icon quality from empty screen

### ISSUE THREAD

**Issue by M2ck** [moezbhatti/qksms#342]
![screenshot_2016-01-07-15-42-26](https://cloud.githubusercontent.com/assets/6850125/12173294/38790aba-b556-11e5-9b13-7dc420465ec8.png)

**Comment by licaon-kter** [comment]
Maybe even use the QKSMS icon actually?

**Comment by cirelli94** [comment]
![image](https://cloud.githubusercontent.com/assets/1636493/18352142/74fd7fbe-75dd-11e6-833c-9973a6ee2e71.png)
It seems solved!
