### ISSUE TITLE
Clean Messaging: Spam & Ad Blocker - Report as inappropriate?

### ISSUE THREAD

**Issue by M2ck** [moezbhatti/qksms#345]
[https://play.google.com/store/apps/details?id=com.msun.cleanmessaging&hl=en](https://play.google.com/store/apps/details?id=com.msun.cleanmessaging&hl=en)
[https://play.google.com/store/apps/details?id=com.msun.cleansms&hl=en](https://play.google.com/store/apps/details?id=com.msun.cleansms&hl=en)

Warning this app is a fork of your work but without mention about you and your app.
Last but not the least this app is bloated by ads and asks approximately 20$ for remove them.

How proceed? Contact developer for ask him to add mention or directly report this app as inappropriate?

**Comment by enervated** [comment]
Nice catch. I love the obviously-fake reviews. Gotta love scumbags.

**Comment by moezbhatti** [comment]
Ah shit. I'll talk to some people and see what I can do

If anyone has any advice, it would be greatly appreciated

**Comment by enervated** [comment]
https://support.google.com/googleplay/android-developer/answer/1085703?hl=en

**Comment by moezbhatti** [comment]
I'll reach out to their team and see if we can resolve this peacefully. If not, I'll take action through Google

**Comment by enervated** [comment]
You think people who would rip off an entire app to monetize it and also post fake reviews about it are just going to pull it down because you included a smiley in your email asking them to?

**Comment by moezbhatti** [comment]
Doubtful. But if they open-source their version and credit QKSMS, then they're not doing anything wrong

**Comment by enervated** [comment]
Ah, of course. I was being sarcastic; that was not a serious question. No offense was intended. I had been thinking they did not credit QKSMS and honestly did not check. Well, best of luck to you.

**Comment by moezbhatti** [comment]
Ah okay no worries

I'll keep you guys posted as to what happens

**Comment by triq6** [comment]
# 4. Intellectual Property Rights

> The design of the CleanMessaging Service along with CleanMessaging created text, scripts, graphics, interactive features and the like, except Status Submissions (as defined below), and the trademarks, service marks and logos contained therein (“Marks”), are owned by or licensed to CleanMessaging, subject to copyright and other intellectual property rights under Indonesia and foreign laws and international conventions. The Service is provided to you AS IS for your information and personal use only. CleanMessaging reserves all rights not expressly granted in and to the Service. You agree to not engage in the use, copying, or distribution of any of the Service other than expressly permitted herein, including any use, copying, or distribution of Status Submissions of third parties obtained through the Service for any commercial purposes.

The words "QKSMS" do not appear anywhere on their site...
> User Provided Information: You provide certain Personally Identifiable Information, **such as imei number, phone country, phone number that sent you sms, sms content,** push notification name (if applicable), billing information (if applicable) and mobile device information to CleanMessaging when choosing to participate in various uses of the CleanMessaging Service, such as registering as a user, updating your status or requesting status for your contacts. In order to provide the CleanMessaging Service, CleanMessaging will periodically access your address book or contact list on your mobile phone to run our service.

So they can collect all of your SMS content??

**Comment by azzamsa** [comment]
great job @M2ck, thanks lot.

**Comment by moezbhatti** [comment]
Going to consolidate this with issue #786
