### ISSUE TITLE
MMS doesn't work on Project FI

### ISSUE THREAD

**Issue by orihs** [moezbhatti/qksms#347]
Can't receive any pictures on Project Fi (haven't tested group MMS). From what I've been able to find it seems like it's because Project Fi uses the new (5.0?) version of APN that QKSMS doesn't use yet, because service switches between providers.

**Comment by Ste4thOverride** [comment]
The app has to be updated to support the current API level 24 to resolve this issue. Alternatively you have to manually enter the MMS settings when you switch between the various networks Sprint, T-mobile, and USC. 

MMSC Fi T-mobile - http://mmsc1.g-mms.com/mms/wapenc 
MMSC Fi Spint - http://mmsc2/g-mms.com
MMSC Fi USC - http://mmsc1.uscc.net/mmsc/MMS
MMS Proxy - Leave Blank
MMS Port - Leave Blank

As a note these at any time Project Fi might change this information and your MMS would stop working so this is a temporary fix until the app supports the newest API level that supports apn changes.

**Comment by moezbhatti** [comment]
> The app has to be updated to support the current API level 24

Is there some documentation somewhere that talks about this?

**Comment by Ste4thOverride** [comment]
I have contacted the Project Fi team and they have been unable to provide specific information and documentation other than to refer to the current available API information for Android. They have mentioned they will look at the developer issues to see if they can provide additional help in the future.

**Comment by AshenDrop** [comment]
Any updates on this? Really love the app, but MMS not working is definitely a dealbreaker. I know it's a huge undertaking to update the whole app's api version, especially for only a small group of users, though.

**Comment by moezbhatti** [comment]
QKSMS 3.0 now uses these updated APIs, these issues should be resolved!
