### ISSUE TITLE
Message not available message permanently displayed

### ISSUE THREAD

**Issue by fredcooke** [moezbhatti/qksms#348]
No idea what caused this, picked up my phone, unlocked, and there it was, had to kill/close the app to make it go away. I forgot the exact text, but searching the source, it was this one:

```xml
 <string name="service_message_not_found">Message expired or not available.</string>
```

Aside from the fact that it should go away, I'd love to know what happened. Did I lose data? Was this relative to something incoming? Something outgoing? Help :-)

**Comment by moezbhatti** [comment]
Not exactly sure. I remember this issue used to happen about a year ago, but I can't remember what the cause was. The code was written long long ago :(

**Comment by fredcooke** [comment]
I'm going to close this on the basis that I've not had it happen again, and probably neither have you. Feel free to reopen if it does and/or comment if you figure out why it did. Cheers.

**Comment by dcdruck** [comment]
For what it's worth, this just happened to me in 2.7.3 on my OnePlus 3 with an AT&T SIM. I have no idea what happened to trigger the message. The only way I could get rid of it was to close QKSMS.

**Comment by fredcooke** [comment]
Ha! The bug lives on! Can you say if you were using it for a while before it happened? Or did it happen at fresh install? Or fresh upgrade? For me it was right at the start, and not since.

If you can't reopen, and would like it open, just say so, and I'll reopen it.

**Comment by dcdruck** [comment]
I had just installed the app for the first time about 3 hours prior to getting the error, so it was more or less right at the start for me too.

I'll leave the decision to reopen or not to someone more qualified than me to make that call. It mostly has be wondering if a message failed to be received or not. If I notice it again, I'll post another comment.
