### ISSUE TITLE
Text input box does not grow with typing

### ISSUE THREAD

**Issue by fredcooke** [moezbhatti/qksms#354]
Which makes it impossible to read and review large messages while authoring.

**Comment by DFyson** [comment]
this would be awesome to have!

**Comment by amorenew** [comment]
may help
https://github.com/skyfe79/KeyboardEditText

**Comment by fredcooke** [comment]
FYI, years ago pidgin did something like this. They used to have it configurable size, and I had it big, then they made it automatic but too tight at the small end, and it annoyed a lot of people. Now the behaviour is a reasonable min size (I think you already have this for texts, but it could be configurable?) and it grows as you need the space. I'd be OK with there being a limit on how much it can grow, say, half the screen, but having it not grow is super painful.

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0
