### ISSUE TITLE
Draft indicator is pushed off screen if the contact name is long

### ISSUE THREAD

**Issue by fredcooke** [moezbhatti/qksms#355]
The draft is there, and not lost, but you can't tell it's a draft because the name is so long that the name reaches the end and is truncated and has ... appended.

**Comment by therob84** [comment]
I can confirm this for v 2.5.2 as standard app at my Fairphone 2 | Android 5.1!
In german I can only read in blue "Ent..." for draft after a long contact name.

**Comment by fredcooke** [comment]
Behaviour in 2.7.3 seems different, though it's still crappy. Now the time/date gets pushed over off the screen and partially or perhaps completely truncated.

**Comment by moezbhatti** [comment]
No longer an issue in QKSMS 3.0

**Comment by therob84** [comment]
Any wild guess, when you will release 3.0? Eagerly waiting ;-)

Am 5. April 2018 06:32:44 MESZ schrieb Moez Bhatti <notifications@github.com>:

**Comment by moezbhatti** [comment]
I started rolling it out today! I'm expecting to have it ready for a full rollout by next week

**Comment by therob84** [comment]
Cool :-) Also for F-Droid I hope?!

Am 5. April 2018 07:57:48 MESZ schrieb Moez Bhatti <notifications@github.com>:

**Comment by moezbhatti** [comment]
It will be - once I figure out why the F-Droid build isn't working!
