### ISSUE TITLE
Unread highlighting not easy to distinguish

### ISSUE THREAD

**Issue by fredcooke** [moezbhatti/qksms#357]
The text is gently bold, but at a glance this is easily missed.

**Comment by moezbhatti** [comment]
Any idea how to make it more visible? We're also showing an icon on the right side and highlighting the date

**Comment by fredcooke** [comment]
Perhaps a different background colour, inverted or some such? IMO they should be very obvious over the read ones.

**Comment by moezbhatti** [comment]
This has been impreoved in QKSMS 3.0, all the text becomes bold
