### ISSUE TITLE
Menu not reachable from body of last message if last one is incoming

### ISSUE THREAD

**Issue by fredcooke** [moezbhatti/qksms#359]
On most messages tap anywhere for the menu (required to get details for time stamps that I feel should be visible in the first place, but I digress), however if the last one is from the other person, you can't tap the message to get this menu, and can only tap the timestamp below it, which is a small finger target.

**Comment by sm4rk0** [comment]
Duplicate of #171?

**Comment by fredcooke** [comment]
I had not noticed the #171 behaviour, I think this is different as it doesn't matter what's in the message.

**Comment by fredcooke** [comment]
2.7.3 cannot reproduce anymore, must have gotten fixed with the #171 fix, I guess. Good stuff.
