### ISSUE TITLE
Use system setting for 24 hour time

### ISSUE THREAD

**Issue by srcreigh** [moezbhatti/qksms#36]
See http://en.wikipedia.org/wiki/24-hour_clock

We should be display 24 hour time as `mm:ss`, not `m:ss`. Thanks to Mihai via team@qklabs.com for this report.

**Comment by l3d00m** [comment]
It's working correctly, you just have to switch Settings - Appearance - Display timestamps in 24-hour format (at bottom).
It should probably automatic check this if user is in 24-hour locale.

**Comment by ab-smith** [comment]
Instead of having a specific parameter on the app, it is probably better if it relies on the system settings.

**Comment by moezbhatti** [comment]
http://stackoverflow.com/questions/4392636/how-do-i-check-if-system-is-12-or-24-hour

**Comment by moezbhatti** [comment]
Added in 09a8b38
