### ISSUE TITLE
Back button in top bar appears when in base list screen

### ISSUE THREAD

**Issue by fredcooke** [moezbhatti/qksms#360]
I'll have to update this on when/how this happens, but you press it intuitively and exit the app. It shouldn't be shown when not in a message or config screen or something...

**Comment by fredcooke** [comment]
Figured out how to reproduce this:

1. Be in a message of a specific person.
2. Go to another app.
3. Tap the QKSMS app icon.
4. App opens in list screen with name of previous person and back arrow showing.
5. Back arrow exits app.

**Comment by moezbhatti** [comment]
When I go back to QKSMS, it reopens the conversation that was open

Are you leaving by pressing the home button or recents?

**Comment by fredcooke** [comment]
It's not how I leave (both produce the same result if "recents" means "running/used application list"), rather it's how I reenter. If I use the app list and touch away to another, and then app list again to come back, I see the conversation still open. If I go out of the other app with home, then press QK icon it does what I described, try it.

**Comment by fredcooke** [comment]
2.7.3 this no longer occurs. However the variance in behaviour based on HOW you enter the app seems to still be a thing, with different symptoms. Cross linking with #638 for reference.
