### ISSUE TITLE
Scrolling up and down in the message list hides new button

### ISSUE THREAD

**Issue by fredcooke** [moezbhatti/qksms#362]
Scrolling up and down in the message list makes the new message button vanish. Yes, this is on purpose too, but it's irritating in the way it does it.

**Comment by tomose** [comment]
Agreed, it seems like style over function here. What if I want to start a new message while looking at the bottom of my message list? Why should I have to scroll up to see that button?

**Comment by therob84** [comment]
I do agree that this is no helpful feature, more a anti-feature and should be removed.

The user should be able to compose a new message **ANYTIME **he wants without beeing annoyed, and not only in times the programm wants...

**Comment by buckelieg** [comment]
+1000 to this issue.

**Comment by moezbhatti** [comment]
This behaviour has been changed in QKSMS 3.0
