### ISSUE TITLE
Can't donate through Google 

### ISSUE THREAD

**Issue by steelcowboy** [moezbhatti/qksms#363]
Hi! I just want to say that QKSMS is absolutely amazing! I just started using it, and tyvm for such a great FOSS messaging app!

I downloaded the app from F-Droid, and when I go to donate through Google it tells me that this version of the app is not configured for billing through Google Play. Does this mean I have to install through the Play Store, or is something just not set up yet?

Thanks again for all your hard work, awesome job devs!

**Comment by moezbhatti** [comment]
Hmm, I'm not sure if it's supported by the F-Droid version. You may need to download it from Google Play

If you try it and it works, let me know!

**Comment by moezbhatti** [comment]
Should be fixed as a result of #644
