### ISSUE TITLE
Notifications in "full" private mode should be merged

### ISSUE THREAD

**Issue by xavihernandez** [moezbhatti/qksms#369]
What's happening?
I have set notification as "full" private mode (both senders and messages are hidden), and when I receive messages from X contacts I have X notifications.

What should happen instead?
I think notifications should be merged in one and only notification with number of messages.

Cc @l3d00m

**Comment by moezbhatti** [comment]
I agree, good catch

**Comment by homersimpsons** [comment]
Notification could also display the number of different conacts.

**Comment by xavihernandez** [comment]
@homersimpsons  yep it could :).
 Since it's at user discretion it's ok for me.

**Comment by moezbhatti** [comment]
This should work properly with the system level notification privacy options in QKSMS 3.0
