### ISSUE TITLE
QK Default MMS Settings are incorrect for StraightTalk AT&T (Bring Your Own Device Plan)

### ISSUE THREAD

**Issue by ghost** [moezbhatti/qksms#374]
The QK Automatic MMS settings for my IMEI number, as currently recommended by StraightTalk for my AT&T (Bring Your Own Device Plan) SIM card, are incorrect.

My old AT&T Network settings were:

NAME: straight talk
APN: tfdata
PORT: 80
MMSC: http://mms-tf-net
MMS PROXY: mms3.tracfone.com
MMS PORT: 80

The current AT&T Network settings are:

APN: RESELLER
MMSC: http://mmsc.mobile.att.net
MMS PROXY: proxy.mobile.att.net
MMS PORT: 80
APN TYPE: default,mms,supl

(Note: For the APN TYPE, I cannot stress enough NO SPACES!. I also named the APN "Straight Talk")

SMS and MMS were both working fine for the last two years on my N5. Two weeks ago, I tried sending an MMS group message another app, SMSSecure; half the recipients received the message, half got an empty message. I verified that the APN settings had changed directly via the Straight Talk website, both by inputting my IMEI number, and by inputting my phone number. Updating the APN data appears to have corrected the issue.

This issue was the same with Wifi turned on, and with it turned off.

I don't know that all AT&T SIM cards are affected by this change. My card is about two years old. At one time, with an older Android phone (Straight Talk Bring Your Own) and an older AT&T SIM card, I used the following settings:

Name: Straight Talk
APN: att.mvno
Port: 80
MMSC: http://mmsc.cingular.com
MMS Proxy: 66.209.11.33
MMS port: 80

The "tfdata" settings failed to work on that ancient "att.mvno" SIM card.

**Comment by moezbhatti** [comment]
QKSMS 3.0 no longer requires manual entry of MMS APN settings
