### ISSUE TITLE
MMS Configuration Layout Improvements

### ISSUE THREAD

**Issue by ghost** [moezbhatti/qksms#375]
The current MMS Configuration tool is awkward and not clear about QK SMS requires the user to do.

I have MMS settings correctly set under my APN configuration. Do I need to re-do the settings again? If QK MMS settings don't match my APN settings, what are the ramifications?

If I choose not to set MMS settings under QK, will QK still work correctly? If I use system settings, how do I make the MMS setup reminders go away?

Can I view what QK has determined my settings should be, without seperately entering MMSC, MMS proxy, and MMS port to verify that they are correct? 

I propose the following layout for QK MMS configuration:
## Current MMS configuration layout:

MMS Configuration

Automatically Configure MMS

MMSC

MMS proxy

MMS port
## Suggested layout:

MMS Configuration

MMS Configuration Preference
- (selected preference in small text)

MMSC
- ("Default" or MMSC setting in small text)

MMS proxy
- ("Default" or proxy setting in small text)

MMS port
- ("Default" or port setting in small text)

---

"MMS Configuration Preference" would bring up a dialog with three options:
- Use device MMS settings
- QK automatic MMS configuration
- Manual MMS configuration

---

For the "Use device MMS settings" option:
- "Use device MMS settings" would be listed in small text under "MMS Configuration Preference"
- "Default" would be listed under (each, in small text) MMSC, MMS proxy, and MMS port
- MMSC, MMS proxy, and MMS port would all be ghosted, and not edit-able
- This should be the default preference

For the "QK automatic MMS configuration" option:
- "QK automatic MMS configuration" would be listed in small text under "MMS Configuration Preference"
- Auto-populated field settings would be listed under (each, in small text) MMSC, MMS proxy, and MMS port
- MMSC, MMS proxy, and MMS port would all be ghosted, and not edit-able

For the "Manual MMS configuration" option:
- "Manual MMS configuration" would be listed in small text under "MMS Configuration Preference"
- MMSC, MMS proxy, and MMS port would each be edit-able
- User-defined field settings would be listed under (each, in small text) MMSC, MMS proxy, and MMS port

---

The QK SMS dialog that asks the user to "Set up MMS?" should give the following options:
- Use my device's MMS settings (save and go to QK)
- Let QK SMS automatically configure my MMS settings (bring up list of networks, save, go to QK)
- I want to manually configure my MMS settings (bring up dialog with MMSC, proxy, and port)

**Comment by moezbhatti** [comment]
I agree that the current one is super awkward. Luckily the new MMS APIs allow you to send MMS without needing to ask the user for this info - so I've been able to completely remove the dialog in QKSMS 3.0
