### ISSUE TITLE
QK Reply showing wrong contact and no message

### ISSUE THREAD

**Issue by stevenroose** [moezbhatti/qksms#376]
Most of the time when I receive a message, QK Reply shows a wrong contact and no message inside the popup. I did not dare to enter something in the reply field, but when clicking outside of the popup or `...` > "Open conversation" shows the wrong message thread too.

This has been happening for about 6 months. The reason I did not report this before is because I was trying to discover what triggered this. It happens about 80% of the time, so makes QK Reply really useless actually. 

QKSMS version: 2.5.1
Android version: 6.0.1 (build number MMB29S)

**Comment by stevenroose** [comment]
Hmm, this seems to be related to #87 where I also mentioned that I had the issue. No fix yet and it is no longer "occasionally" with me.

Perhaps a reason is that I have a rather large number of conversations and messages (there is no option to autodelete after some time?) so QKSMS tends to be a little laggy from time to time.

**Comment by moezbhatti** [comment]
The new version of QK Reply should fix this issue. Hoping to have it released very soon, just been busy

**Comment by stevenroose** [comment]
Should it have landed already?

**Comment by NaKroTeK** [comment]
Having same problem with : 
Qkqsms 2.7.3
Android 6.0
Moto g 3rd generation

**Comment by moezbhatti** [comment]
QK Reply has been removed in 3.0, so I'll close this now
