### ISSUE TITLE
Request : Show Text with correct Font in Selection

### ISSUE THREAD

**Issue by homersimpsons** [moezbhatti/qksms#378]
Help the user to choose is Font by showing him the font name with the font style.
Another Request : Let the user import his fonts (with only some specified format, for exampe : ttf)

**Comment by LevynTheVariant** [comment]
This is precisely why I was scouring the internet right now, to find out if this was possible. 
Adding this feature would have me sold on this for as long as I have a mobile.

**Comment by moezbhatti** [comment]
The font selection has been removed in QKSMS 3.0

I plan to later add a toggle to switch to the system font, but this won't require a preview
