### ISSUE TITLE
Enhancement: Support Samsung Galaxy S6 Edge

### ISSUE THREAD

**Issue by doychi** [moezbhatti/qksms#379]
Samsung has a nice feature in the Mesages app for the Galaxy S6 Edge, where the message notification pops person on the Edge Screen if they are one of the 5 people assigned to the edge.

Please add this feature to QKSMS.

**Comment by moezbhatti** [comment]
As far as I know, there is not a public API for this and it only works with the stock messaging app. I'm going to close this issue for now

Please correct me if I'm wrong - if you can find a link to some documentation regarding how to implement this functionality on a Samsung device then I'd be happy to look into it!
