### ISSUE TITLE
Hang Problem

### ISSUE THREAD

**Issue by brok85** [moezbhatti/qksms#382]
Dear QKSMS Developers,
I am implementing a hang-bug detection tool and I am analyzing QKSMS (master version downloaded today) with it. I found that the main thread of QKSMS, frequently calls 3 particular functions:

1)
com.moez.QKSMS.mmssms.Transaction.sendSmsMessage(Transaction.java:200)
android.content.ContentResolver.insert(ContentResolver.java:1231), 

2)
com.moez.QKSMS.mmssms.Transaction.sendSmsMessage(Transaction.java:237)
android.telephony.SmsMessage.calculateLength(SmsMessage.java:424), 

3)
com.moez.QKSMS.mmssms.Transaction.sendSmsMessage(Transaction.java:256)
android.telephony.SmsManager.divideMessage(SmsManager.java:410), 

when an SMS is sent. In my experiments, the execution of those functions on the main thread may be the main cause of the eye-detectable delays (i.e., hang-bug) experienced with QKSMS.

Moving work off the main thread leads to higher responsiveness of the app. I suspect that it is actually possible to run those functions on a background thread. Therefore, do you think that it is possible to move off the main thread those functions to improve responsiveness? Also, where you aware of these problems?

Thanks for any information,
I hope I can help improve QKSMS.

**Comment by moezbhatti** [comment]
Hey, thanks for letting us know! I'm going to look into this later this week and verify, and hopefully we can improve the responsiveness.

The code that involved this was written quite some time ago, and unfortunately I haven't thought much about it since then. Because of that, it could be a pretty easy fix. I'll keep you posted

**Comment by moezbhatti** [comment]
Is this tool available for public usage? I'd be interested to know which other areas of the app are seeing issues like this

**Comment by brok85** [comment]
Thanks for the reply and for taking a look into it!

Unfortunately we are still developing the tool so it is not available yet. 

Thanks for any info you will give me about the reported issues :)

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
