### ISSUE TITLE
[BUG] Scroll bar is missing in conversation and list

### ISSUE THREAD

**Issue by therob84** [moezbhatti/qksms#384]
I can't see any scroll-bar when scrolling through the conversation list or inside a conversation.

As I can't find any reason why this should not be there, I conclude it is a bug?!

I use v2.5.2 as standard app with Android 5.1@Fairphone2.

**Comment by moezbhatti** [comment]
I'd like to add fast-scroll functionality to both of these screens

**Comment by sm4rk0** [comment]
Duplicate of #271
