### ISSUE TITLE
[Feature Request] Delivery Report only for the next message

### ISSUE THREAD

**Issue by therob84** [moezbhatti/qksms#385]
I would love if qksms would integrate a fast way (like a shortcut) to activete the "Delivery Report" just for this one message which is currently typed and will be send next.

Maybe just a new button in the compose window or a new entry in the "..."-option menu or something else, which is reachable within one click and which is only temporarely without changing the standard settings of the delivery reports.

Thanks for implementing this.

**Comment by moezbhatti** [comment]
The use case for this is a bit too narrow in my opinion, and not worth cluttering the attachments UI. Going to close the issue
