### ISSUE TITLE
Reset "Update QKSMS icon color" feature

### ISSUE THREAD

**Issue by M2ck** [moezbhatti/qksms#395]
Because it break custom icon packs

**Comment by moezbhatti** [comment]
Works fine for me with Nova Launcher

How do you get it to break?

**Comment by M2ck** [comment]
Works only with default icon, what is your icon pack?

**Comment by moezbhatti** [comment]
Ah, yeah that's probably why. I have it set to the default one. Why not do that, then? Set it to the default, and then your icon pack will work

**Comment by M2ck** [comment]
It will be more user friendly to consider add an option for reset theme settings (something as requested in #406).

**Comment by moezbhatti** [comment]
I agree, I think that would be pretty useful

**Comment by moezbhatti** [comment]
Related to #141 

Should be fixed in QKSMS 3.0
