### ISSUE TITLE
[IMPROVEMENT] Searching for a Contact (and its conversation)

### ISSUE THREAD

**Issue by therob84** [moezbhatti/qksms#396]
At the moment, the search function only crawls through the messages contents to look for the search word.

But I do missing the option, that I can also search for a contacts name to directly jump into the corresponding conversation (without scrolling 1 minute down in the start view, if it is a month ago).

Can this be please implemented? Maybe with a small radio buttion to choose between "messages" and "persons".

Thanks!

**Comment by moezbhatti** [comment]
This has been implemented in QKSMS 3.0
