### ISSUE TITLE
[IMPROVEMENT] "Compose New" should load conversation history, after a contact is selected

### ISSUE THREAD

**Issue by therob84** [moezbhatti/qksms#397]
At the moment during composing a"new message" the conversation history is empty, which makes sense. But also after I already typed and selected a contact, it stays empty and I just see my composing message.

It would be a big improvement, if also the conversations history is loaded, after I selected exactly one contact, for which a history is available. 
It would mean, that the "compose new" window should turn into the "reply" window, after a contact is selected in the receiver box. 

This would avoid the need to scroll down the long list of conversations, to find a contact and its conversations from a longer time ago.

Thanks for implementing this.

**Comment by moezbhatti** [comment]
Only reason it doesn't show the history is in case you're creating a group conversation, in which case it wouldn't make sense to show the history for the single contact

**Comment by therob84** [comment]
I agree. But this is no argument, why the history is not shown if only ONE contact is selected, right?

To be clear: I go to the "+" (compose new message), type the name of the contact and select ONE contact from the drop-down list and type in the message box. 
And now history appears, although it would make 100% sense, right?

Unfortunately it is even not possible to simple search for a contact to jump into its history, as I recently stated under #396

**Comment by moezbhatti** [comment]
Yeah, you have a good point. I'll need to improve the contact selection then, so it can accurately tell once they're finished selecting the contacts

**Comment by moezbhatti** [comment]
This has been implemented in QKSMS 3.0, including support for showing the history for a group conversation
