### ISSUE TITLE
"Strip Unicode" strips too much information.

### ISSUE THREAD

**Issue by Regnareb** [moezbhatti/qksms#409]
When the option "Strip Unicode" is checked, it will "fix" characters that should stay. Like "é, è, à".
It should strip only the unicode characters and not ANSI ones, only the ones that would decrease the number of letters allowed in one SMS (160).

é, è, à, and other characters still let you do 160 characters long messages. It makes the messages hard to understand sometimes without all that information.

**Comment by moezbhatti** [comment]
This should be handled properly now in QKSMS 3.0
