### ISSUE TITLE
Enhancement Request: Hide the "(No Subject)" text in conversation list for MMS messages

### ISSUE THREAD

**Issue by erawhctim** [moezbhatti/qksms#41]
Similar to [issue #26](https://github.com/qklabs/qksms-tracker/issues/26), the `(No Subject)` text shows up under the list of group participants for a group message in the main conversation list. It'd be great to get rid of this, or toggle it via settings.

**Comment by fcastilloec** [comment]
I don't really understand what this is about. You're description sound exactly like issue #26 and that's been fixed already. Maybe if you provide a screenshot it'll be more helpful or a more detailed description.

**Comment by erawhctim** [comment]
Sorry about that, let me clarify.

The previous issue #26 was referring to the `<Subject: No Subject>` text that shows up within each individual message bubble as part of the "conversation view" for MMS group messages. 

My issue here is with the `(No Subject)` text that shows up beneath the list of group members in a single row of the "conversation list".

I'm referring to the left-most UI screen as the "conversation list", and the right-most UI screen (the one that slides over after selecting a conversation) as the "conversation view".

**Comment by srcreigh** [comment]
Thanks for the report. This is definitely a bug!

**Comment by arzoo1** [comment]
Rather than hiding "(no subject)" in the conversation list, why not show the part of the last message, the same as sms? This is how other messaging apps (such as Chomp) work.

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0
