### ISSUE TITLE
[IMPROVMENT] Go back to main screen after display switched off for 5(?) minutes

### ISSUE THREAD

**Issue by therob84** [moezbhatti/qksms#410]
**Scenario**: after working with qksms (composing, sending...) and you changed the app or switched off the display and go back to qksms:

**Current behaviour**: qksms is exactly continued at the screen where you left it (despite a real "kill app" was performed)
This behaviour is OK for a couple of minutes, if you want directly jump into the old conversation again.

**Desired behaviour**: If qksms is inactive for, let's say 5 min, it should start again in the main message screen to have a better overview. Could be opt-in in settings (with desired minutes, or disabled).

In the past it happended very often for me, that I don't want to see the old conversation again while there no new messages have been received. But I want to check the other conversations or start a new one --> main screen is neccassary.

**Comment by moezbhatti** [comment]
It's standard behavior to retain the state of the app until it is completely killed, so I won't be making this change
