### ISSUE TITLE
[IMPROVEMENT] Changelog-Screen + Why there is no CHANGELOG on Github (and F-Droid), but only at google?

### ISSUE THREAD

**Issue by therob84** [moezbhatti/qksms#412]
I can't find any changelog in Github or F-droid, only at google (more or less).
Why?
It should be included in the "readme" file or better in a separate changelog file, shouldn't it?

And by using the "changelog" function in qksms itself I never know if this content is gathered from any server (thus is beeing up-to-date) or if it is only the date of the app included? 

Furthermore in the changelog-screen there should be noted, which version currently is installed. Otherwise I then have to go to settings-->About to see the current version, have to remeber what the "changelog-screen" told me and not really know, If already any new version is out, as there is no timestamp in the changelog-screen, when it was updated.

**Comment by moezbhatti** [comment]
The changelogs are currently loaded from a firebase server.

All of them are pulled, but in the app, only current and past changelogs will be shown. So let's say you have version 2.5.2, then the changelog window will show you the history up until version 2.5.2 and hide 2.5.3. You're right though, a better behaviour would be to have all of them show, and somehow highlight the current version installed. The current way of doing it is confusing

**Comment by moezbhatti** [comment]
There's no full changelog history available anywhere else though because I'm not really sure how to display the firebase data somewhere else

If anyones interested, you can view the raw json here - https://qksms-changelog.firebaseio.com/.json

**Comment by Avispa** [comment]
Re-Open please. Despite the fact that there is still no change log on Github and/or f-droid also the provided firebasio-link ends at version 2.7.3.
Especially, but not only, for those major version steps I prefer heavily to have a look into the change log first.

**Comment by MyNameIsCosmo** [comment]
Related: https://keepachangelog.com/en/1.0.0/

**Comment by Avispa** [comment]
> If you go to releases, it shows changes for each version
You're right. Thank you. However...

> Initial preview release for QKSMS 3.0 [full stop]
.. is the comment for the major version jump. Is it just me who get's the feeling not everything is said here?

**Comment by MyNameIsCosmo** [comment]
QKSMS 3.0 was a complete rewrite, so nothing from 2.7.3 was preserved.
It could have what was originally in the README.md, where QKSMS 3.0 is a complete rewrite.
