### ISSUE TITLE
[BUG] empty screen after: new SMS --> Click at lockscreen notification --> read SMS --> tap "back" arrow

### ISSUE THREAD

**Issue by therob84** [moezbhatti/qksms#415]
### DESCRIPTION

--> Receiving a new SMS 
--> Clicking at the lockscreen notification 
--> reading SMS 
--> go "back" with the app-intern or system-back arrow
--> **empty screen appears** with "conversations" in the title, nothing more
--> qksms needs to be killed in the android task manager and to be restartet

Just noticed for current v2.5.3 (at Android 5.1)

**Comment by lnxtxx** [comment]
Same issue here, after update to v2.5.3, but restart QKSMS doesn't help.
Android 4.4.4.
Screenshot: http://i.imgur.com/NZWVCZs.png

**Comment by moezbhatti** [comment]
When you receive the SMS, is QKSMS already open in the background?

**Comment by therob84** [comment]
As I did not killed the app before actively (and no exit button exists) and I used it before: 
yes, it is opened in the background.

>  but restart QKSMS doesn't help.
As workaround: You have to kill the app first (by taskmanager) and then restart QKSMS.

**Comment by lnxtxx** [comment]
After few tests: conversations list disappear when I change orientation from portrait to landscape.
Restart helps if I also change orientation to portrait.

**Comment by moezbhatti** [comment]
I've followed your steps and can't seem to reproduce this issue. Other people have been reporting it too though. Is there any other information you can give me?

**Comment by therob84** [comment]
Hm, funnily: at the moment I could not reproduce it either by sending me a sms myself or by selecting a sms and labeling it as "unread"........
But I can assure you that I noticed it at least 10 times in the last weeks....

And sometimes the "blank screen" also appears in other situations (whose appearance I could not categorize up to now...)

**Comment by lnxtxx** [comment]
Steps to reproduce my issue (Android 4.4.4, QKSMS 2.5.3):
1. lock portrait orientation
2. power off device
3. power on device
4. launch QKSMS -> conversations list is present: http://i.imgur.com/PpQiOjf.png
5. unlock orientation
6. rotate device to landscape orientation -> conversations list disappears: http://i.imgur.com/DHwHPwX.png
7. rotate device to portrait orientation -> conversations list isn't present: http://i.imgur.com/KO9tnlW.png
8. force quit QKSMS
9. launch QKSMS in portrait orientation -> conversations list is present: http://i.imgur.com/GGxp6Jx.png
10. force quit QKSMS
11. launch QKSMS in landscape orientation -> conversations list is present: http://i.imgur.com/aSRP6FJ.png
12. rotate device to portrait orientation -> conversations list disappears: http://i.imgur.com/KGtQVWI.png

Additional information: problem still exists if I clear apps data.

**Comment by romelemperado** [comment]
I noticed this too in the v2.5.3 version in the Playstore after update.. When I rotate the app the inbox is white screen only..

**Comment by lnxtxx** [comment]
It seems that v2.3.4 fixes my issue.

**Comment by moezbhatti** [comment]
Awesome.

Can anyone else confirm if 2.5.4 fixes this?

**Comment by billic** [comment]
not sure same bug:

conversation switches after switch device orientation: 
1) rotate to landscape mode
2) open a conversation A http://i.imgur.com/K4vfZw9.jpg
3) close conversation A
4) rotate to portrait mode
5) open conversation B (http://i.imgur.com/6HMd1ml.jpg)
6) rotate to landscape mode -- u can see conversation A with wrong title: http://i.imgur.com/g10Pmxr.jpg
7) rotate back to portrait mode. Here we have again conversation B, but with same wrong title: http://i.imgur.com/a1u11hl.jpg

should I open new issue or find another existing one?
I have 2.5.4 version of qksms from f-droid repo

**Comment by moezbhatti** [comment]
@billic yeah, that'll be a new issue. If you could open up a new one I'd appreciate it!

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0
