### ISSUE TITLE
[Bug] SMS Rendering

### ISSUE THREAD

**Issue by f380cedric** [moezbhatti/qksms#416]
QKSMS makes this randomly
<img src="https://cloud.githubusercontent.com/assets/10184070/13434596/b404e12c-dfd6-11e5-9e2f-5320a8233832.png" width="150">
<img src="https://cloud.githubusercontent.com/assets/10184070/13434597/b408484e-dfd6-11e5-8aac-94e45b9f1452.png" width="150">

But the rendering should be (stock sms app) 
<img src="https://cloud.githubusercontent.com/assets/10184070/13434617/cd05c006-dfd6-11e5-8da8-8e44221f4d57.png" width="150">
<img src="https://cloud.githubusercontent.com/assets/10184070/13434777/679fe704-dfd7-11e5-99ae-0650f33e127e.png" width="150">

I do not know why it did that, and it seems to appear completely randomly

**Comment by tlofgren** [comment]
I found a similar issue. It seems to be restricted to short messages. Here the first 2 photos are QKSMS, the last one is what it should look like in my stock messaging app.

![screenshot_2016-03-11-10-57-35](https://cloud.githubusercontent.com/assets/5882380/13726740/68b3874a-e892-11e5-9acc-e49bab9a5257.png)
![screenshot_2016-03-11-10-57-19](https://cloud.githubusercontent.com/assets/5882380/13726742/7036bdca-e892-11e5-8c78-6fcdd3db746a.png)
![screenshot_2016-03-12-20-40-08 01](https://cloud.githubusercontent.com/assets/5882380/13726750/14977918-e893-11e5-81dc-7af8c57dd294.png)

**Comment by moezbhatti** [comment]
Fixed in #621
