### ISSUE TITLE
Telephone number link to contact with different format

### ISSUE THREAD

**Issue by RemiLatapy** [moezbhatti/qksms#423]
### DESCRIPTION
Using different format for number (#) when sending a SMS create different conversations and won't display contact (name and picture). (french number format)

### STEPS
French gsm number looks like: +33 6 XX XX XX XX

0. Register a contact (yourself for example) with in this format: +33 6 XX XX XX XX and set a contact picture.
1. Send a sms to 06 XX XX XX XX
2. Send a sms to 33 6 XX XX XX XX (without "+")
3. Send a sms to the contact by choosing him directly

### EXPECTED
Only one conversation with the name of the contact and his picture.

### OBSERVATIONS
The result is one conversation without picture and named with the number 06XXXXXXXX containing SMS from step 1 and 3.
And another conversation without picture and with named with the number 336XXXXXXXX containing the sms from step 2.
When clicking on conversation picture, both are well linked to the contact.

**Comment by DFyson** [comment]
related: #328

**Comment by moezbhatti** [comment]
Merging issues
