### ISSUE TITLE
[Feature request] Option to delete blocked messages automatically

### ISSUE THREAD

**Issue by notfoss** [moezbhatti/qksms#424]
Thanks for providing an option to block messages from certain numbers. But as it is implemented currently, it moves the blocked messages to a dedicated view, something similar to the "spam" folder associated with emails.

Now, it would be great if we can have an option to either delete all blocked messages as they arrive, or have them delete automatically after a certain period (preferably user-configurable).

Thanks

**Comment by moezbhatti** [comment]
Merging with #1236
