### ISSUE TITLE
Sent message is described as "sending..."

### ISSUE THREAD

**Issue by ronczes** [moezbhatti/qksms#431]
Hello, 
all my messages keep "sending...", even after delivery do recipent
see attached picture

if you know how to fix it, please let me know

regards
Bartek

![screenshot_2016-03-10-12-08-38](https://cloud.githubusercontent.com/assets/17762636/13668162/3658c126-e6bb-11e5-87af-fd1b05c6f12e.png)

**Comment by moezbhatti** [comment]
This should be addressed in QKSMS 3.0
