### ISSUE TITLE
Proximity sensor triggers call contact on flip case cover

### ISSUE THREAD

**Issue by licaon-kter** [moezbhatti/qksms#432]
Using a [flip case type cover](http://cdn01.androidauthority.net/wp-content/uploads/2014/08/StilGut-UltraSlim-Leather-Case-for-HTC-Desire-816.jpg), closing the flap will call the contact even if device is horizontal on table.

**Comment by frogoscar** [comment]
The Proximity Sensor is too sensible, it starts the call when in the conversation even not near user's ear, but put your hand on hover.

**Comment by moezbhatti** [comment]
This feature has been removed in QKSMS 3.0
