### ISSUE TITLE
[Feature Request] Merge conversations

### ISSUE THREAD

**Issue by sling-shot** [moezbhatti/qksms#433]
### DESCRIPTION
It would be extremely helpful in certain situations if 2 or more conversations could be merged into a single conversation. Example in case of a person having 2 different mobiles numbers and using whichever depending on which has the best reception at his location. A conversation with him will be split over 2 unless both can be merged.

Also commercial SMS say from a bank arrive from different headers such as VM-SBI, VX-SBI, TV-SBI etc. Merging them into a common SBI or a user selected option could make life much easier.

This feature is present in another application called Disa.

**Comment by M2ck** [comment]
Duplicate of #313
