### ISSUE TITLE
Switching conversation after orientation switch

### ISSUE THREAD

**Issue by billic** [moezbhatti/qksms#437]
### DESCRIPTION
This looks like two orientation modes are independent: qksms remember last opened conversation is landscape mode and returns to it from any other conversation when rotating from portrait mode

also: after this switch conversations have wrong title (from another conversation)

### STEPS
1. rotate to landscape mode
2. open a conversation A http://i.imgur.com/K4vfZw9.jpg
3. close conversation A
4. rotate to portrait mode
5. open conversation B (http://i.imgur.com/6HMd1ml.jpg)
6. rotate to landscape mode -- u can see conversation A with wrong title: http://i.imgur.com/g10Pmxr.jpg
7. rotate back to portrait mode. Here we have again conversation B, but with same wrong title: http://i.imgur.com/a1u11hl.jpg

### EXPECTED
No changes between landscape and portrait modes

### OBSERVATIONS
conversation switches to another and changes conversation title (from some another conversation)

I have 2.5.4 version of qksms from f-droid repo

**Comment by moezbhatti** [comment]
I can't seem to repro this. It works fine for me. Anyone else?

**Comment by billic** [comment]
@moezbhatti  Hm. After steps from #443 I could not reproduce this bug. rotation switching to new conversation, nor another one. Probably this is the same bug, but with different actions at step 6.

**Comment by moezbhatti** [comment]
This should be fixed as of 2.6
