### ISSUE TITLE
"Strip Unicode" function does not strip non-ASCII chars

### ISSUE THREAD

**Issue by KosiehBarter** [moezbhatti/qksms#450]
### DESCRIPTION

Device: Lenovo A2010-a
ROM: Stock (Possibly others, CyanogenMod not tested - not complete), Android Lollipop 5.1
Input language: Czech (cs-CZ)
Tested keyboards: Google Keyboard, Sony Xperia (manually installed through TWRP)
Logcat / ADB: Not available, ROM is stock, without root.
### STEPS
1. Go into Settings - General
2. Turn Strip Unicode on
3. Return back, write a message or any other text
### EXPECTED

All non-ASCII characters (ě, š, č, ř, ž, ý, á, í, é, ň, ó, ú, ů also with their upper-case counterparts, using only alphanumerical characters) should not appear.
### OBSERVATIONS

All invalid characters (mentioned above) appear and therefore shortening maximum length of the message.

**Comment by moezbhatti** [comment]
Merging with #409
