### ISSUE TITLE
Quick Reply crashes. 

### ISSUE THREAD

**Issue by VermeGeo** [moezbhatti/qksms#454]
### DESCRIPTION

The app crashes if the quick reply window is drawn over the app itself, apparently only if it's reached from the lock screen. 
### STEPS
1. Open QK. 
2. Lock the screen with the power button, or allow it to lock itself. 
3. Receive a text message. 
4. Turn on the screen and hit 'Reply' on the notification.
   5a. Type a reply and hit send. 
   OR 
   5b. Dismiss the quick reply window.
### EXPECTED

The reply window should simply close. If a message has been typed when the window is dismissed then it should be saved to draft. If a message had been SENT then it should in fact be sent, after which the quick reply window should simply close.
### OBSERVATIONS

The screen will go dark and revert to the conversations menu, and if attempting to send a message then said message is not sent, nor is it saved as a draft. It simply disappears.

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
