### ISSUE TITLE
[request] add ability to archive threads

### ISSUE THREAD

**Issue by 0xdec** [moezbhatti/qksms#461]
Most SMS apps have an archive function for message threads. It's a feature that I miss, as it allows the user to hide old threads that they don't necessarily want to delete, or keep sensitive/private messages hidden.

**Comment by sudhirkhanger** [comment]
Indeed I miss this feature sorely on qksms. When this is implemented I would like to see the following two UI features.

* A Google Messenger style swipe to archive.
* Ability to mark a message as archived from notification.

**Comment by henrikku** [comment]
I'd like to bump this, especially since it was mentioned in 2014 [here](https://www.reddit.com/r/Android/comments/2b06q4/dev_hi_there_have_you_met_qksms/cj0y4q0).

**Comment by CalculusWarrior** [comment]
I agree, this is a critical function for me. While I can get by without it, I prefer to archive messages from people I've not heard from in a while, allowing for a cleaner home page.

**Comment by moezbhatti** [comment]
This has been implemented in QKSMS 3.0

**Comment by 0xdec** [comment]
Yay! v3 looks great so far!
