### ISSUE TITLE
Launch icon unread count indicator not actual value 

### ISSUE THREAD

**Issue by ervinmartirosyan** [moezbhatti/qksms#463]
### DESCRIPTION
Launch icon unread count indicator not actual value.

### STEPS
1. Receive some sms
2. Delete some sms/all sms
3. Check launch icon indicator

### EXPECTED
Launch icon indicator shows unread messages count.

### OBSERVATIONS
Launch icon indicator shows not actual unread messages count.

**Comment by ervinmartirosyan** [comment]
I have found that issue can be easly reproduced if delete unread message (bold title)

**Comment by ab-smith** [comment]
Confirmed when deleting an unread conversation (sms thread) without entering it (long press on the conversation list)

**Comment by moezbhatti** [comment]
Fixed in https://github.com/moezbhatti/qksms/commit/9fe4fb6df9553a1d56f06aa719abd7804f13ba6c
