### ISSUE TITLE
broken html links in sms body 

### ISSUE THREAD

**Issue by foormanek** [moezbhatti/qksms#465]
### DESCRIPTION

When sms body contains web link and this link contains phone number, then contact name for this number gets inserted into the link, effectively breaking it.
### STEPS
1. Receive a sms containing web link with a phone number from contacts somewhere in it.
2. try to go to the link.
### EXPECTED

Leave web links intact
### OBSERVATIONS

web links do not work

**Comment by moezbhatti** [comment]
The contact matching has been removed in QKSMS 3.0, so link functionality should work as expected now
