### ISSUE TITLE
Long Messages not sending as MMS

### ISSUE THREAD

**Issue by hary585** [moezbhatti/qksms#467]
### DESCRIPTION

When I send long messages, I had been under the idea that they were sending as MMS, but as SMS.
### STEPS
1. Make a message longer than 160 characters (I sent a message that had as many characters as 4 individual SMS messages.
2. Hit send
3. Check recipient phone
4. The messages sent as individual SMS messages.
### EXPECTED

I expected to see the messages sent as one long MMS, but instead it sent as individual messages.
### OBSERVATIONS

I made sure that all settings pertaining to long messages were enabled (under general, and MMS) and unlimited MMS attachment. 

I'm willing to give more information if you would like to know anything.

**Comment by moezbhatti** [comment]
This is fixed in QKSMS 3.0
