### ISSUE TITLE
Crash when opening the message report dialog

### ISSUE THREAD

**Issue by bensoibj** [moezbhatti/qksms#472]
### DESCRIPTION

I'm just testing QKSMS; I have used the stock SMS app until now. Whenever I want to see the report of a message which has not been sent with QKSMS (rather with the stock app of Android 5.1.1), QKSMS crashes. The reason might be that the stock app did not store all the time stamps (only time sent, but not time delivered). However, since all the information in the message report is also contained in the dialog "message details", it is not a big issue and the dialog "message report" could be just removed.
### STEPS
1. open message thread and navigate to an older message, which has not been sent with QKSMS.
2. long-press the time stamp to open the context menu
3. choose "view report" (Bericht ansehen in German)
### EXPECTED

A dialogue window opens showing the message report dialog with the receiver's number, receiving status, delivery time.
### OBSERVATIONS

The app crashes and is getting closed.

**Comment by moezbhatti** [comment]
This is resolved in QKSMS 3.0
