### ISSUE TITLE
Nb of unread messages doesn't disapear

### ISSUE THREAD

**Issue by Lolowild** [moezbhatti/qksms#476]
Despite the fact that I read all the messages, the little bubble on the app icone doesn't disapear. And the number seems to change when I open certain conversation. 

I think it's happening when I mark a message as read from the popup Window (the check button on the Quick view). 

Hope my explanation will help.

**Comment by moezbhatti** [comment]
For repro: This happens generally when an unread message is deleted

**Comment by moezbhatti** [comment]
Duplicate of #311
