### ISSUE TITLE
[Enhancement] Ability to switch view from conversation to inbox/outbox/all

### ISSUE THREAD

**Issue by gaston68cz** [moezbhatti/qksms#481]
At some situations (after an import of messages are some conversations broken, or if I can view all messages received in a few last days) is more effective to view list of received / sent / all messages sorted only by their timestamps. Can you add these views as an alternative to the conversation view?
There are almost no applications with this feature.

**Comment by moezbhatti** [comment]
Likely won't be adding this, in an effort to reduce clutter in the app
