### ISSUE TITLE
Feature request: Option to select MMS of SMS for *each* message with multiple recipients

### ISSUE THREAD

**Issue by BatmanAoD** [moezbhatti/qksms#485]
### DESCRIPTION

_All_ messages with multiple recipients should off the option to use either SMS or MMS, _without_ requiring adding a subject or going into the settings menu.

It often makes sense to send some messages with multiple recipients as individual messages (e.g. "anyone available to meet up for lunch today?"), but others as MMS (e.g. group conversations with an expected back-and-forth between multiple people).

A nice sub-feature would be the ability to easily respond to _just_ the sender of an MMS using an SMS.
### STEPS

Draft a new message with multiple recipients, or reply to an MMS. Select "SMS" or "MMS" mode.
### EXPECTED

The UI should provide a way to toggle the send-mode (e.g. by long-pressing on the send-button, or as a new graphical element).

**Comment by moezbhatti** [comment]
Added in 3.3.0 but forgot to update this issue: https://github.com/moezbhatti/qksms/commit/fc99ae83ad98229cb72ea199faebb7bb4f13ffe0

**Comment by BatmanAoD** [comment]
@moezbhatti Thanks! Just downloaded the app again and it works beautifully. Will be switching to qksms as my daily driver now.
