### ISSUE TITLE
Issue Determining "current conversation" instead of "last conversation selected"

### ISSUE THREAD

**Issue by Stryfex** [moezbhatti/qksms#487]
When I get a message from someone and click it in the notification or quick reply widget, it doesn't actually link to that conversation in the main app window, but rather the most recent conversation that I had open in the main window.
### STEPS
1. Jerry and I are having a conversation in main window
2. Leave app for home screen
3. Receive SMS from Bob
4. Click Notification/QuickReply
### EXPECTED

I am brought to my conversation with Bob
### OBSERVATIONS

I am brought to my conversation with Jerry

**Comment by moezbhatti** [comment]
This should be resolved in QKSMS 3.0
