### ISSUE TITLE
SMS send to a number without country code are put into separate conversation list.

### ISSUE THREAD

**Issue by sledgehammer999** [moezbhatti/qksms#488]
I am using QKSMS 2.5.3 from f-droid on android 5.1.1.

I don't know if this is possible in other countries but in Greece you can send an sms to a Greek number by omitting the country code in front of that number. However, sms received from that number will always have the country code prefixed.
Greece's code is +30 and mobile numbers are 69XXXXXXXX.

QKSMS, considers `(+30) 69XXXXXXXX` and `69XXXXXXXX` 2 separate numbers and splits the conversation into 2 different lists.
I migrated from an 4.0.x aosp installation that handled this correctly(using stock messaging app) and was very confused why I lost some of my conversations. Until I realized QKSMS has another list for the same number.

Can you fix it?

**Comment by glombek** [comment]
This also affects displaying messages from contacts. If I store the local number, messages received will not pull in the correct contact info.

To add to the confusion, in the UK +44xxxxxxxxxx is the same as 0xxxxxxxxxx - the country code replaces the 0.

**Comment by taiko000** [comment]
This issue still exists in the latext Google Play version 3.6.x and makes the app pretty much unusable if nearly all contacts do not have a country prefix.

**Comment by moezbhatti** [comment]
Fixed in 5927138a29c09cf054ab85ac3dce4f96b91c37ec
