### ISSUE TITLE
Pictures only sends when Wi-Fi is disabled. 

### ISSUE THREAD

**Issue by Yefssy** [moezbhatti/qksms#49]
Description
Pictures only sends when Wi-Fi is disabled.

Steps
1. Send a picture with Wi-Fi enabled.

Expected
The picture will send with Wi-Fi enabled, or disabled.

Reality
Picture doesn't send with Wi-Fi enabled.

**Comment by srcreigh** [comment]
This makes me sad. I think I know how to fix it, but it'll be pending for a while.

**Comment by moezbhatti** [comment]
QKSMS 3.0 now uses the official system methods for sending MMS, which seem to eradicate this issue in my testing.
