### ISSUE TITLE
Crash when receiving delivery report

### ISSUE THREAD

**Issue by yossjackson** [moezbhatti/qksms#496]
### DESCRIPTION

Crash when receiving delivery report
### STEPS
1. Sent SMS.
2. ... waiting delivery confirmation ... 
3. BANG !
### EXPECTED

Simple: show the mark whithout crashing, done ! :-)
### OBSERVATIONS

My english is not so good, sorry. "I think" when receiving SMS delivery reports app crash and stop. Said before "I think" cause precisely app crash at that moment, but when check the SMS shows the mark as delivered.

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
