### ISSUE TITLE
Wrong visual effect going from MessageList to ConversationList

### ISSUE THREAD

**Issue by yossjackson** [moezbhatti/qksms#497]
### DESCRIPTION

Wrong visual effect when returning to conversations list. The windows rolls to the right but under shows desktop wallpapers, not conversation list, after conversation windows left the screen space it shows up conversation list again.
### STEPS
1. Open conversation
2. Return to conversation list.
### EXPECTED

When rolling to the right the conversation windows (visual effect), it should show conversation list, not desktop wallpaper.
### OBSERVATIONS

Wrong visual effect when returning to conversations list. The windows rolls to the right but under shows desktop wallpapers, not conversation list, after conversation windows left the screen space it shows up conversation list again.

**Comment by sm4rk0** [comment]
Can't reproduce. Which Android and QKSMS version are you using? Maybe custom ROM?

**Comment by yossjackson** [comment]
Blue Studio C 5 + 5, Android 5.0, QKSMS 2.6.0

2016-05-12 14:59 GMT-04:00 Marko Stanković <notifications@github.com>:

**Comment by moezbhatti** [comment]
I'm not able to reproduce this. Does it happen for you every time?

**Comment by romelemperado** [comment]
Yes. Same with #529.. More detailsvon #529 avout this issue..

**Comment by searchy2** [comment]
Weird, this error is no occuring for me on KitKat 4.4 emulator. Mind you, this is the same emulator that I reported there being no issue before! Interesting :confused:

**Comment by jackm** [comment]
I just started using QKSMS today and I can confirm that this bug happens every time on my Nexus 5 running Android 4.4.4 (stock ROM) when going back to the conversation list. It happens when going from an SMS message window or going from the settings window back to the conversation list.

**Comment by moezbhatti** [comment]
This has been reimplemented, so the issue should no longer persist in QKSMS 3.0
