### ISSUE TITLE
System to choose new features

### ISSUE THREAD

**Issue by cirelli94** [moezbhatti/qksms#503]
### DESCRIPTION

It lacks a way to let the community choose the new features to be implemented.
### STEPS

Starting to use a sistem like http://www.allourideas.org/
### EXPECTED

The improvements will be made in order of most usefulness
### OBSERVATIONS

I think this should be made only if Moez agree.

**Comment by moezbhatti** [comment]
Would be super useful, especially if they could access it from within the app

**Comment by cirelli94** [comment]
The better free way I found until now is: [all our ideas](http://www.allourideas.org/qksms)
