### ISSUE TITLE
Random message receiver

### ISSUE THREAD

**Issue by davidhedlund** [moezbhatti/qksms#509]
### DESCRIPTION
QKSMS 2.5.1 conversations are not always sent to the selected receiver. Sometimes they are send to someone else on the contact list.

Have this been fixed (is this a duplicated issue then)?

### STEPS
Use QKSMS for a longer period of time and you perhaps will notice this bug.

### EXPECTED
The messages should go to the intended receiver only, of course.

### OBSERVATIONS
Sometimes they are send to someone else on the contact list.

**Comment by JPFrancoia** [comment]
How often does it happen ?

**Comment by davidhedlund** [comment]
I experienced this just once but that was enough for me to stop using it. I'm 100% sure that this bug is valid.

**Comment by moezbhatti** [comment]
This issue should be fixed as of version 2.6

**Comment by davidhedlund** [comment]
@moezbhatti Thank you.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
[mylabel:quarantined](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aquarantined%22+in%3Acomments&type=Issues&ref=searchresults)
