### ISSUE TITLE
MMS/Group messages not producing notifications

### ISSUE THREAD

**Issue by tgp1994** [moezbhatti/qksms#510]
### DESCRIPTION

When a MMS or group message is received, QKSMS does not produce any notification - no sound, popup, icon, anything. The only way you can tell if a new message was received is if the app is opened, and a thread has the new message dot on it. Normal SMS messages are notifying as expected.
### STEPS
1. Receive MMS or group message
2. Wonder what your friend is talking about when they ask why you didn't respond to their message
### EXPECTED

To receive a notification exactly like receiving SMS's.
### OBSERVATIONS

Absolutely nothing observable occurs when an MMS or group message is received. However, if one opens the QKSMS app, it does show as new in there.

**Comment by alittleton** [comment]
I'm having this exact problem with my phone (Galaxy S5 running Marshmallow).

**Comment by tgp1994** [comment]
@alittleton I was getting worried that my phone was just being special, I guess it's nice to know that someone else is seeing the issue though.

**Comment by qraq** [comment]
Unfortunatelly I have it too on Xperia Z5 Compact ( Marshmallow 6.0.1)

**Comment by frogoscar** [comment]
Me, too

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
