### ISSUE TITLE
Display seconds in timestamps.

### ISSUE THREAD

**Issue by DFyson** [moezbhatti/qksms#512]
The timestamps in the message details should be more precise and show seconds. This would also be nice in the conversation timestamps but that should likely be more of a display/formatting option. This has been mentioned in #358.

**Comment by moezbhatti** [comment]
Added for v3.3.3 in https://github.com/moezbhatti/qksms/commit/93448822953c3f1c1e3e2c8d295c2ae941967af9 but I missed updating this issue!
