### ISSUE TITLE
Inconsistant formatting of message details

### ISSUE THREAD

**Issue by DFyson** [moezbhatti/qksms#516]
For messages with 'delivered' in the details, it is formatted as single line with colon whereas the rest is formatted over two lines, no colon.
Would also be nice to see formatting improve a little such as bold labels ('sent', 'recieved', etc).

**Comment by moezbhatti** [comment]
This was removed with the initial release of 3.0, and added back correctly for 3.3.3 in https://github.com/moezbhatti/qksms/commit/93448822953c3f1c1e3e2c8d295c2ae941967af9
