### ISSUE TITLE
Blocked conversations re-appear in Inbox

### ISSUE THREAD

**Issue by aqeeliz** [moezbhatti/qksms#517]
### DESCRIPTION

Many times blocked conversations re-appear in the Inbox. I block the conversations, and they move from Inbox to "Blocked" view, and when I check again (after getting new SMS) they seem to be back in Inbox.

Update: Just checked Qksms again, when there is no new SMS, and they are all back.
### STEPS
1. Select a Conversation
2. Select "Block" from top menu 
3. Conversation hides from Inbox
### EXPECTED

Blocked conversation should never show up in Inbox again.
### OBSERVATIONS

Some of the the blocked conversations creep back in Inbox.

**Comment by aqeeliz** [comment]
@moezbhatti Is there any way I can help with reproducing/debugging the bug?

**Comment by moezbhatti** [comment]
Have you noticed any pattern as to when they reappear? I've been using the feature for months and haven't seen this happen

Which app version and phone / android version are you on?

**Comment by aqeeliz** [comment]
I stopped using QK SMS for a while, re-installed it and the issue is still there.

I am using Android, my previous phone (when I reported it first) was Samsung Galaxy Nexus (Kitkat), and my current phone is Huawei Honor 7 (Lollipop). One thing that might be common between them both is Galaxy Nexus didn't had much RAM, and Honor 7 does very excessive RAM management, closing everything when screen turns off or anything that goes in background. So is it possible that before the change is saved, Android closes the app?

To give some more info about the issue this time:
I blocked couple of conversations after installing the app, and they never came back. Then day before yesterday, I noticed 3 spam conversations that apparently I missed in my inbox. I blocked them (they disappeared from Inbox), pressed home button, turned off screen. Some time later, I re-opened the app, and they were back in Inbox. Blocked them again, confirmed they have moved to 'Blocked' screen, but now they are back again. It's those same 3 conversations. I have 3 other conversations that I've blocked and they have never moved back to Inbox.

I am using version 2.7.3

**Comment by aqeeliz** [comment]
Did some more testing yesterday.

Blocked conversations only come back to inbox if I remove QKSMS from recent apps list soon after blocking them. I am not sure about the exact time, but if I don't remove the app from recent apps list for long enough, the changes take permanent effect.

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
