### ISSUE TITLE
Formatting issue with short text, screenshots included.

### ISSUE THREAD

**Issue by tomose** [moezbhatti/qksms#519]
Nexus 6, 5.1.1, stock, no funky fonts or anything.
QKSMS v2.6.1
### DESCRIPTION

Short text on multiple lines is formatted to a single or double columns. See attached screenshots.
### STEPS

Attached are pictures of me sending the text:
"Test
Lol"

Without quotes, obviously, and sent as one text with the linebreak.
### EXPECTED

Should look like:
"Test
Lol"
### OBSERVATIONS

Should not look like:
"T
e
s
t
L
o
l"

![screenshot_2016-06-09-13-27-18](https://cloud.githubusercontent.com/assets/13343483/15945314/97f2ad20-2e46-11e6-9169-b4198163f65d.jpg)
![screenshot_2016-06-09-13-28-01](https://cloud.githubusercontent.com/assets/13343483/15945313/97e29ee4-2e46-11e6-8ea2-f34921c50095.png)

**Comment by moezbhatti** [comment]
This seems  to be working properly in QKSMS 3.0
