### ISSUE TITLE
Delayed submission doesn't delay at all

### ISSUE THREAD

**Issue by notorand-it** [moezbhatti/qksms#520]
### DESCRIPTION

I have configured delayed submission for SMSes but they get submitted as soon as I hit the submission button (->).
### STEPS
1. Go to settings-->General
2. Enable Delayed messages (wording could be different as I use Italian)
3. Set delay in seconds to 5 or whatever else you want
4. Go back to application main screen
5. Type and Send an SMS to someone
### EXPECTED

A delay to occur before the SMS submission is done
### OBSERVATIONS

The SMS is sumbitted immediately

I am running CyanogenMod 13.1-ZNK2K .

**Comment by homersimpsons** [comment]
I'have got this bug too, nexus 5 stock android 6.0.1

**Comment by notorand-it** [comment]
What does it mean "needs repro"?  I wrote the steps to reproduce the problem...

**Comment by moezbhatti** [comment]
Sorry for the late response @notorand-it 

The tags are more for myself as the developer, and although these steps probably do work for some people on certain phones, they don't reproduce the issue on my own device

**Comment by notorand-it** [comment]
Do you mean that you can actually send delayed messages?

**Comment by moezbhatti** [comment]
Correct, this works fine on my phone

**Comment by notorand-it** [comment]
I will test that once more. My latest try is from 20 days ago, when delayed messages were still sent immediately.
Which system/version are you using?

**Comment by notorand-it** [comment]
V2.7.3 still doesn't work on CyanogenMod 13.

**Comment by moezbhatti** [comment]
Kk. I'll take a look at that while I'm refactoring the app and see if I can figure out the cause of that

**Comment by symbolisch1234** [comment]
same problem. unfortunate, because it was the reason i installed QKSMS. :-(

Sony Xperia M (nicki)
freshly installed Lineage 14.1

**Comment by moezbhatti** [comment]
Will fix as part of #979
