### ISSUE TITLE
Disable/Enable option for auto-link

### ISSUE THREAD

**Issue by kristoffer09** [moezbhatti/qksms#522]
### DESCRIPTION
Could auto-link on received and sent messages be disabled? Possible URLs are automatically converted into hyperlink. This could be harmful if someone messages you a malicious link, or even unintentionally, if you forgot to add space after the period. For example. (the above link is malicious.do not click it)

### STEPS
1. Send any message with possible URL (e.g. possible.url)

### EXPECTED
auto-links should be disable in text message

### OBSERVATIONS
possible URLs are automatically converted into hyperlink.

**Comment by searchy2** [comment]
Why would a user wish for hyperlinks to be disabled? Most people send and receive text messages between friends. If a friend was sending me malicious links, they'd be in ### BIG trouble!

**Comment by homersimpsons** [comment]
You can, temporarily install 2 browser, then each time you will click a link it will ask you which browser you want to use (I you select only once each time) 
Then just go back to avoid open the malicious link

**Comment by moezbhatti** [comment]
I think this is a feature too few people care for, to be worth adding to the app
