### ISSUE TITLE
[Feature Request] Batch edit a conversation

### ISSUE THREAD

**Issue by homersimpsons** [moezbhatti/qksms#525]
Hello,

In top menu of a specific conversation, I think it could be use full to add an opion to batch edit. It would be easier to delete or lock multiple sms at once.

When activating this 'mode' a check box need to appear in the same line of each sms/mms to allow to select or no this sms/mms
At the bottom there could be other option like: invert selection, select all, unselect all and apply to selection with 2 options :  lock or delete. In both case a popup should appear to ask confirmation (in case of deletion, you need to add a warning to prevent that it is irreversible)
If locked sms are selected to be deleted add in the warning that x sms are locked and will be deleted.

Thank you for QKsms :)

**Comment by searchy2** [comment]
Yes, this feature might be useful. The clutter might outweigh the benefit though. Also, might be making it a bit too complicated for regular users.

**Comment by moezbhatti** [comment]
Merging with #42
