### ISSUE TITLE
Deleted failed message appearing in notification

### ISSUE THREAD

**Issue by srcreigh** [moezbhatti/qksms#53]
via [Sebastian on G+](https://plus.google.com/+S%C3%A9bastienBernardEnderGeek/posts/FYVnkb3bg1e)

When my phone fails to send a message, there is always a second message that I deleted a long time ago in the notification "X messages failed" I already deleted the whole conversation but this message is always here.﻿

**Comment by moezbhatti** [comment]
Fixed in QKSMS 3.0
