### ISSUE TITLE
Notification coloring is hard to read.

### ISSUE THREAD

**Issue by tomose** [moezbhatti/qksms#532]
Nexus 6, 5.1.1, stock, no funky fonts or anything.
QKSMS v2.6.1

The icon, title of QKSMS, and the read/reply/call text are all difficult to read due to being white.

![screenshot_2016-06-21-14-15-28](https://cloud.githubusercontent.com/assets/13343483/16247330/1f9ef186-37be-11e6-958d-cb8438448375.jpg)

Hangouts for example, uses a green icon, with green text. Gmail is red.

Also, just as a visual improvement... if the contact does not have an icon associated or a number has no contact, I don't see why an icon should be displayed to the right (the blank white circle). Is it not possible to show a transparent icon there so as to look empty?

**Comment by moezbhatti** [comment]
Are you using the white theme in the app?

**Comment by tomose** [comment]
Moez you are correct, I am an idiot. This is a non-issue.
