### ISSUE TITLE
QK don't check Telephony.Sms.SEEN to display Notifications and ignore if it's the default SMS App

### ISSUE THREAD

**Issue by ffgiraldez** [moezbhatti/qksms#533]
### DESCRIPTION
QK don't check Telephony.Sms.SEEN column in order to display sms notifications
QK it's not the default SMS App and an SMS arrive the device will display 2 notifications one for the Default SMS App and one for QK. Also if Default App mark as seen the SMS QK ignore that and display the notification.

### STEPS
1. Use as Default SMS App one that mark as seen SMS (very simple demo will be enough)
2. QK should NOT be the Default SMS App
3. Receive an SMS
4. Duplicated notifications in the device, one for Default SMS App and one for QK

### EXPECTED
QK should take care of SEEN Sms value in order to display notifications

### OBSERVATIONS
Not sure if an SMS app it's not the default one, should display any notification at all, but for sure should check seen value.

Other SMS App Like native one(LG, Samsung, etc...) don't display notifications if they are not the default SMS App

**Comment by msesma** [comment]
It shouldn't show any notification, of course.
Some SMS apps like messenger hide some messages of certain Types like ENQUEUED while not being default app , but all must support SEEN state.

**Comment by moezbhatti** [comment]
QKSMS right now will still show notifications if it's not the default SMS app (this needs to be fixed), but it does respect the SEEN state. It only displayes notifications for messages that are not READ and not SEEN

**Comment by ffgiraldez** [comment]
@moezbhatti i dont' see nothing in code that check if the message is seen in order to display the notification, i don't search too much, but at least in MessagingReceiver or NotificationService i cannot find it.

It's true that you mas as seen messages, but not discard them.

**Comment by moezbhatti** [comment]
Any time a message is received, I still ping the notification manager, but it will only show notifications for UNREAD and UNSEEN messages

https://github.com/moezbhatti/qksms/blob/master/QKSMS/src/main/java/com/moez/QKSMS/transaction/NotificationManager.java#L137-L137


https://github.com/moezbhatti/qksms/blob/master/QKSMS/src/main/java/com/moez/QKSMS/transaction/SmsHelper.java#L350-L350
