### ISSUE TITLE
Cannot answer a call with an SMS if QKSMS is the default app

### ISSUE THREAD

**Issue by ab-smith** [moezbhatti/qksms#534]
### DESCRIPTION
Most recent android dialer offers the capability of rejecting an incoming call using predefined text messages (something like: I'm busy, I'll call you back). When using QKSMS, we lose this  feature.

### STEPS
1. Set QKSMS as default app on a Phone A
2. From a phone B, call A
3. Reject the incoming call on A with a message using the dialer feature

### EXPECTED
Phone B receives a message

### OBSERVATIONS
Phone B does NOT receive the message

Checked against Samsung default messaging app, Google Messenger and hangouts, Textra, etc. and all worked. Tested both on Samsung and Nexus devices.

**Comment by moezbhatti** [comment]
Merging with #531

**Comment by moezbhatti** [comment]
Fixed in https://github.com/moezbhatti/qksms/commit/34efcf34fad5dc8fd4f3620849a786417ad308f6

**Comment by moezbhatti** [comment]
Proper fix in dcf9cfd

**Comment by ab-smith** [comment]
:+1: fix working
