### ISSUE TITLE
long messages are always splitted

### ISSUE THREAD

**Issue by amine5chetibi** [moezbhatti/qksms#535]
### DESCRIPTION
Long messages are splitted even if "Split SMS" option is disabled 

For information:

- I use a GS4 on KitKat (4.4.2)

- issue is not observed on A5 Lollipop (5.1.1)

### STEPS
1. Ensure that "Split SMS" is disabled
2. Send a long sms from a GS4 Kitakt to a GS4mini
3. GS4mini receives the long sms as one chunk
4. Send again a long sms from A5 Lollipop to the same GS4mini 
5. GS4mini receives 4 sms (1/4, 2/4, ...)  

### EXPECTED
Sending long SMS as one chunk

### OBSERVATIONS
long SMS is splitted when sent from a GS4 Kitkat
long SMS is not splitted when sent from A5 Lollipop (5.1.1)

**Comment by moezbhatti** [comment]
If you restart QKSMs on the A5 Lollipop, are messages still being split?

Are both phones on the same telephone carrier?

**Comment by moezbhatti** [comment]
@amine5chetibi can you provide this information please

**Comment by amine5chetibi** [comment]
When i first created this issue, there wasn't a split issue on A5 Lollipop. This unexpected split was observed only Samsung GS4 running on Kitkat.

After some investigations, i found that the unexpected split was caused by:

1. a an incorrect initialization of "Split Sms" option.

1. "Split SMS" option value can't be changed dynamically (without restarting Qksms) 

So, to bypass this issue, i had to: 

1. Enable "Split Sms" option

1. Disable "Split Sms" option

1. Quit Qksms, using settings-> Application or just by restarting the device

1. Restart Qksms

1. The sms are not splitted anymore

For information, i had the same behaviour with "conversion to MMS" option

**Comment by moezbhatti** [comment]
Okay, thanks for the details. I should have what I need to fix this now

**Comment by moezbhatti** [comment]
Fixed in https://github.com/moezbhatti/qksms/commit/1feab612b7314cda0cc49a3ca918101e313d511e
