### ISSUE TITLE
Transitions are not disabled in QKSMS even if they are in Android

### ISSUE THREAD

**Issue by drws** [moezbhatti/qksms#536]
### DESCRIPTION

There are transitions in QKSMS that cannot be disabled if Animation off is set in Android's Developer options. These settings effectively disable all the transitions in apps and system, except for certain particular transitions in some games. But QKSMS is an ordinary semi-lightweight Modern Look app, so it should have its transitions implemented with standard Android API functions.

This bug reports concentrates on the fact that the transition is non-standard, so this is not a duplicate of #497 (nor #529) - but it would probably solve them both. 
### STEPS
1. Go to the conversation
2. Return to inbox
### EXPECTED

Inbox is displayed as fast as possible.
### OBSERVATIONS

Weird, slow transition appears which unnecessarily delays the display of expected screen while also producing a few bugs. Inbox is displayed, but not as fast as possible.

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0
