### ISSUE TITLE
Auto delete old messages

### ISSUE THREAD

**Issue by drws** [moezbhatti/qksms#537]
### DESCRIPTION
This is an enhancement suggestion to implement a function which automatically deletes messages which are too old (the threshold should be settable) or if message count threshold is reached in a conversation ("only keep last X messages").

**Comment by homersimpsons** [comment]
Already asked #119

**Comment by drws** [comment]
Sorry. I searched before and don't know how could I miss it...

**Comment by homersimpsons** [comment]
Not a problem you can't know about all the issues and if key word is not used search will not lead you to the correct issue
