### ISSUE TITLE
Wrong number of new messages displayed  

### ISSUE THREAD

**Issue by pdouret** [moezbhatti/qksms#539]
Dear

If you do the following steps you will receive notification from qksms and wrong number of unread message will be  displayed 
### STEPS
1. Open qksms 
2. Select a few conversation 
3. Click on send
4. You will receive some qksms notifications and qksms will display one more unread message which does not exist. If you redo the same, one unread messages will be added but it doesn't exist.

**Comment by moezbhatti** [comment]
Merging with #311
