### ISSUE TITLE
Feature Request: Overlay Textures

### ISSUE THREAD

**Issue by AnonymousDapper** [moezbhatti/qksms#544]
Have an option to overlay textures over the accent areas (title bar, status bar, navigation bar, etc) and/or background area.
In the newer versions of Microsoft Office, the user can choose a light geometric pattern to lay over the menu bar. I'll add pictures when I'm not on mobile.

**Comment by moezbhatti** [comment]
Likely just going to leave it as solid colors for the time being, unless this becomes something much more requested
