### ISSUE TITLE
SMS written while in flight mode are not automatically sent once we exit it

### ISSUE THREAD

**Issue by ab-smith** [moezbhatti/qksms#545]
### DESCRIPTION
SMS written while in flight mode are not sent once we exit it.

### STEPS
1. Switch phone to flight mode
2. Select contact and type SMS
3. Press send. The sending will fail which is normal.
4. Exit flight mode. The SMS are not sent automatically.

### EXPECTED
Send pending SMS once we exit the flight mode.

### OBSERVATIONS
In the native application (in my case, Samsung default messaging app), during flight mode, an attempt to send the SMS will mark it as pending and send it automatically when the network is back (exiting the flight mode).

**Comment by homersimpsons** [comment]
It can be an improvement of #493

**Comment by moezbhatti** [comment]
Added in https://github.com/moezbhatti/qksms/commit/44ae58ae55c71449593003e2227174de75f2fd54
