### ISSUE TITLE
Search option in the conversations list does not include contacts names

### ISSUE THREAD

**Issue by ab-smith** [moezbhatti/qksms#546]
### DESCRIPTION

The search option looks only inside the texts and not the contact name, which is pretty useful.
### STEPS
1. Have some threads (multiple conversations)
2. Go to conversations list, press the search button
3. The app looks only inside the sms content and not the contacts names
### EXPECTED

Search for contacts names as well in the conversations list.

**Comment by sureshlsdj** [comment]
This issue is still there. Please help me out to search contact name in search screen

**Comment by moezbhatti** [comment]
Added for QKSMS 3.0

**Comment by sureshlsdj** [comment]
May I know when it will be launching...?

**Comment by moezbhatti** [comment]
@sureshlsdj I'm hoping to launch the beta within the next 3 weeks
