### ISSUE TITLE
QKSMS not entering landscape layout

### ISSUE THREAD

**Issue by kkwaiser** [moezbhatti/qksms#549]
### DESCRIPTION
Following resolution of the bug affecting [loss of conversation](https://github.com/moezbhatti/qksms/issues/443) when [switching to landscape](https://github.com/moezbhatti/qksms/issues/469), the QKSMS app is now reluctant to enter landscape at all. Billic's final comment within issue 443 is the same issue.

### STEPS
1. Open QKSMS in portrait
2. Put phone in landscape layout

### EXPECTED
QKSMS should switch to landscape. 

### OBSERVATIONS
If the phone starts in landscape mode (i.e., open a browser and switch to landscape) and QKSMS is then launched or switched to, it will then toggle between layouts without losing the conversation. 

Tested on a Moto G running Android 5.1 and Samsung SM-G900v running Android 5.0 with QKSMS 2.6.3.

**Comment by moezbhatti** [comment]
Fixed in 84a9612
