### ISSUE TITLE
Disable MMS auto-retrieve

### ISSUE THREAD

**Issue by ToNIX-** [moezbhatti/qksms#550]
Is there any way to add an option to disable MMS auto-retrieval just like Messenger? That way, when your data is off, you get a notification with a download button.

**Comment by realmain** [comment]
This is what the settings for AOSP Messaging app has for this, just for ideas:

![1](https://i.imgur.com/NDtwMhC.png)

(copying this from #779 because it makes sense here)

**Comment by moezbhatti** [comment]
Merging with #389
