### ISSUE TITLE
change deprecated setOnPageChangeListener

### ISSUE THREAD

**Issue by amorenew** [moezbhatti/qksms#556]
### DESCRIPTION

hi
in **WelcomeActivity**
you can change deprecated 
**mPager.setOnPageChangeListener(this);**
to
**mPager.addOnPageChangeListener(this);**

also in every textview you can change
**android:singleLine="true"**
to
 **android:lines="1"**

reference link: http://stackoverflow.com/questions/30867852/viewpager-setonpagechangelistener-deprecated

**Comment by moezbhatti** [comment]
This has been resolved in QKSMS 3.0
