### ISSUE TITLE
Cannot type text and then add an image/photo/picture

### ISSUE THREAD

**Issue by Gitoffthelawn** [moezbhatti/qksms#557]
### DESCRIPTION

Cannot type text and then add an image/photo/picture.
### STEPS
1. Start typing a new message, like "Here is a photo of my cat chasing a yeti."
2. Try to add a photo of your cat chasing a yeti.
3. But there is no way to add a photo once the user writes any text.  There is only a _send_ button in the UI once any text has been typed.
### EXPECTED

Have a way to add a photo after the user types some text.
### OBSERVATIONS

The user has to start over and remember to always add any photo before typing any text.

**Comment by moezbhatti** [comment]
This is fixed in QKSMS 3.0
