### ISSUE TITLE
No notification when app is open and screen is locked

### ISSUE THREAD

**Issue by benrolfe** [moezbhatti/qksms#560]
### DESCRIPTION
This scenario only happens when the screen is locked, and **QK SMS** is open in the background.
When a new SMS arrives, the notification sound is made - however the notification does not appear on the lock screen.
*This only happens if QK SMS is open in the background.*

### EXPECTED
Notification should appear, even if app is open in the background.

**Comment by detly** [comment]
On my system, if I'm watching the lock screen when an SMS arrives, the notification appears but then disappears a fraction of a second later.

**Comment by sm4rk0** [comment]
Duplicate of #224
