### ISSUE TITLE
Force close Problem In Sub Settings page

### ISSUE THREAD

**Issue by romelemperado** [moezbhatti/qksms#561]
### DESCRIPTION

Force close after rotation when you are in  sub settings page
### STEPS
1. Go to any sub setting page(ex: general settings)
2. Rotate the app fro land scape or vice versa then hit back button. The app should force close

Device: Android nexus 6P 
QKSMS version: 2.7.0/Play store version
### EXPECTED

There should be no force close when going to previous page
### OBSERVATIONS

This is only happening if you are in the sub setting page.

**Comment by StephaneBausseron** [comment]
#585 is the same issue (and have a patch as attachment).

**Comment by moezbhatti** [comment]
Should be fixed in https://github.com/moezbhatti/qksms/commit/2765ff3d13bdde76728b1cf17a05b67bb32fc127
