### ISSUE TITLE
duplicate messages recieved on lg devices

### ISSUE THREAD

**Issue by kilroythe5th** [moezbhatti/qksms#568]
DESCRIPTION:
with any message I have recived, two appear in the thread
STEPS:
try installing QK on an lg device to see if the bug happens with all lgs
EXPECTED:
Normally, when one recives a message, only one notification appears, and only one message appears in the thread.
OBSERVATIONS:
Instead of one message recieved, two appear, regardless of signal strength

**Comment by moezbhatti** [comment]
What version of android are you using?

**Comment by kilroythe5th** [comment]
android 4.4

**Comment by kilroythe5th** [comment]
on another device, the lg nexus 5 on marshmallow, there was also the issue

**Comment by cmydjbf** [comment]
I meet the same problem with you.
My device: 
System:android 4.4,
brand:huawei,
(Dual sim card)

**Comment by frogoscar** [comment]
Sometimes, with 2.7.1 Samsung Galaxy S6, A5

**Comment by kilroythe5th** [comment]
the strange thing about this bug on my device (lg ultamate 2) is that it hasn't always done it.initially when I installed the app, it didn't happen, but then it just appeared for no apparent reason. this, however was not the case on the lg nexus 5

**Comment by kilroythe5th** [comment]
the problem seems to have dissapeared after I reinstalled the rom on my phone, and has not come back since. I don't know if the problem dissapeared because of that, or if it was because the app has had several updates since then. If anyone else still has the problem, please mention it, but on my part, the bug is gone.
