### ISSUE TITLE
Encoding UTF-8 has no effect

### ISSUE THREAD

**Issue by StephaneBausseron** [moezbhatti/qksms#569]
### DESCRIPTION
build.gradle try to set encoding to UTF-8.

But a mistake is in gradle file:
    compileOptions {
        compileOptions.encoding = "UTF-8"
       [...]
    }

compileOptions is specified two times.

Moreover, UTF-8 is the default encoding charset, so it is not usefull to specify it.

**Comment by moezbhatti** [comment]
cc @mvdan

**Comment by mvdan** [comment]
It's an explicit default. Feel free to remove it.

**Comment by moezbhatti** [comment]
@mvdan thanks for the clarification
