### ISSUE TITLE
QKSMS Freezes with large conversations with QK Reply (10,000+)

### ISSUE THREAD

**Issue by adrianjord** [moezbhatti/qksms#573]
### DESCRIPTION

I've just tried switching from Textra to QKSMS, however I'm not one to delete conversations, and I have conversations that are 10,000+. When trying to us the QK Reply pop up on a large conversation, after pressing send the app never says the message was delivered and I will be unable to open the app again until it crashes which can takes  a few minutes, and the message never was delivered.
### STEPS
1. Have a conversation that is 10,000+ messages
2. Have that person message you
3. Use the QK Reply pop up to reply
### EXPECTED

The QK Reply window closes and the message gets delivered with a toast saying Message Delivered.
### OBSERVATIONS

The QK Reply window closes, the toast never comes up, the app freezes, trying to open the app doesn't do anything, freezes entire phone sometimes.

**Comment by alekksander** [comment]
got 4600+ messages, and this symptoms are not occurring…yet. however there is a noticeable lag when entering conversation. it's not always present, but i think before 2.7 update it was way less frequent, and app run smoother in general. now it uses more cycles, which reflects on app\system responsiveness.

**Comment by moezbhatti** [comment]
QK Reply has been dropped in favor of rich notifications in QKSMS 3.0. And although not completely related, conversation opening performance for large conversations has been drastically improved

Closing issue
