### ISSUE TITLE
Performance hardwareAccelerated

### ISSUE THREAD

**Issue by paradoxfm** [moezbhatti/qksms#577]
### DESCRIPTION

For speedup application and remove lags in large list
### STEPS
1. add hardwareAccelerated=true into android mainfest
### EXPECTED

Smooth scroll lists
### OBSERVATIONS

https://developer.android.com/guide/topics/graphics/hardware-accel.html

**Comment by moezbhatti** [comment]
> Hardware acceleration is enabled by default if your Target API level is >=14

This should already be enabled :)
