### ISSUE TITLE
Incoming message resets scroll position

### ISSUE THREAD

**Issue by Ketrel** [moezbhatti/qksms#581]
### DESCRIPTION

Receiving a message to a conversation while not at the newest position auto scrolls down to the new message.  This causes one to lose their place when reading and for large conversations and/or active ones, it can make it impossible to read
### STEPS
1. Be at a position in a conversation where the latest message is not visible
2. Receive a new SMS/MMS to that conversation
### EXPECTED

Position is preserved, conversation/notification indicates unread message until scrolled down to new message or conversation is re-entered from the conversation list.
### OBSERVATIONS

Conversation automatically scrolls to the position of the message just received and position at the time of receipt is lost.

**Comment by sm4rk0** [comment]
Duplicates #538

**Comment by Ketrel** [comment]
As mentioned elsewhere, this issue was specific to the issue occurring within the same conversation that that the incoming message arrives in.

**Comment by sm4rk0** [comment]
I agree. This is still reproducible with v2.7.2.

**Comment by Ketrel** [comment]
(Still marked as closed, can it be repopened or should I re-file?)

**Comment by moezbhatti** [comment]
Sorry for the late response @Ketrel, just took a look and you're definitely right. I've reopened this one

**Comment by moezbhatti** [comment]
This is fixed in QKSMS 3.0
