### ISSUE TITLE
MMS Pics group Conversations

### ISSUE THREAD

**Issue by psyscope** [moezbhatti/qksms#582]
### DESCRIPTION
When going through group conversations. I see the picture, but when I click on it, is a different picture.  Give us an option to resync the database ....

### STEPS
1. Steps
2. to 
3. reproduce
4. the 
5. issue.

### EXPECTED
Describe the expected behaviour.

### OBSERVATIONS
Describe what happens instead of the expected behaviour.

**Comment by moezbhatti** [comment]
Duplicate of #92, closing this one
