### ISSUE TITLE
QKSMS crashes upon entering from notification and switching to landscape

### ISSUE THREAD

**Issue by kkwaiser** [moezbhatti/qksms#584]
### DESCRIPTION
When going from lock-screened portrait mode to landscape, the QKSMS app crashes.

### STEPS
1. Close QKSMS
2. Lock screen
3. Send text to phone
4. While in portrait mode, double-tap text notification on lock screen
5. Enter password
6. Once QKSMS opens to new message, rotate phone to landscape, possibly tap screen to prompt switch to landscape
7. Observe crash

### EXPECTED
Should rotate to landscape without crashing

**Comment by moezbhatti** [comment]
These steps don't cause a crash for me, which Phone and Android version are you running?

**Comment by kkwaiser** [comment]
QKSMS 2.7.1 on Samsung Galaxy S5 (SM-G900V) with Android 6.0.1.

**Comment by sm4rk0** [comment]
Reproduced it with v2.7.1 on Moto X with LP5.1
https://gist.github.com/sm4rk0/a864ce1670224f9562a038eba56b148c

**Comment by moezbhatti** [comment]
Fixed in https://github.com/moezbhatti/qksms/commit/c34ab39eab257df0c78c6c9e8a40ef7cf07c6d1c

**Comment by kkwaiser** [comment]
Fix confirmed. Thanks!
