### ISSUE TITLE
Permissions FLASHLIGHT and CAMERA seem not used

### ISSUE THREAD

**Issue by frogoscar** [moezbhatti/qksms#593]
### DESCRIPTION
The Intent **MediaStore.ACTION_IMAGE_CAPTURE** (android.media.action.IMAGE_CAPTURE) already does taking-photo when user wants to send a photo MMS. Permissions android.permission.CAMERA and android.permission.FLASHLIGHT seem not necessary.

To be removed perhaps.

### OBSERVATIONS

**Comment by frogoscar** [comment]
Pull request https://github.com/moezbhatti/qksms/pull/594

**Comment by searchy2** [comment]
Camera permission requests all camera features. Might be helpful for adding video later? Most applications request Camera so it is familiar to the end user.
