### ISSUE TITLE
How to send MMS (MultimediaMessages and videos,songs etc)

### ISSUE THREAD

**Issue by BrandedAlok** [moezbhatti/qksms#599]
Please tell ? I am only able to send text messages and smileys just:(

**Comment by homersimpsons** [comment]
When in a conversation, hit the + button (right to text field) and choose picture, after selecting/taking the picture you can write your text (SMS)

**Comment by BrandedAlok** [comment]
oh okay works well thank you so much sir. i m impressed by your work and deication.
