### ISSUE TITLE
MMS from gallery to favorite contact with multiple numbers

### ISSUE THREAD

**Issue by fcastilloec** [moezbhatti/qksms#6]
**Steps:**
**1.** Browse a gallery app and select a picture to share.
**2.** Select QKSMS under the share menu
**3.** QKSMS compose window appears. Select a contact from the "Favorite Contatcs" list. This contact has to have multiple phone numbers associated to the same contact.
**4.** Send the picture.

**Expected:**
QKSMS should ask me which phone number do I want to use to send and then just send the picture without a problem.

**Reality:**
QKSMS attempts to send the picture to all phone numbers under the same contact, which is not what I want to do. This doesn't happen if I just type the contact name instead of selecting from Favorites, because I can see the contacts phone number being used.
A new conversation is created that has as members all the phone numbers from the same contact. I know that they are all the phone numbers of the same contact because this problem gets pushed to Yappy, and there I can see all the phone numbers under that conversation.
The first time this new conversation is created it shows the wrong contact picture. It actually shows the picture of a different contact.

I'm attaching a screenshots of the problem so it's easier to understand. The screenshot shows that the second conversation has Jennifer Thomas and somebody else (+1). The contact picture is not of Jennifer Thomas, and the "+1" is the same contact but a different phone number.
After restarting QKSMS (removing it from memory) the picture gets updated and now there's no contact picture at all and just the number "2" is displayed. Meaning there's two contacts in that conversation.

Another thing that can be see in the screenshot is that the first conversation reads that my message could not be sent, because one of Jennifer's numbers is a land line. One of the problems that arise when you send the MMS to all phone numbers under that contact.
![screenshot_wrong picture](https://cloud.githubusercontent.com/assets/1280530/6317490/40de7312-ba24-11e4-8fc2-552eaf18d4b8.png)

**Comment by srcreigh** [comment]
Great bug report @fcastilloec. Thank you!

**Comment by srcreigh** [comment]
Will try and repro this myself soon. Don't have service currently, so I'm going to mark it as "needs-repro".

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
