### ISSUE TITLE
I always receive two same message at one time when i set qksms as my default sms app. 

### ISSUE THREAD

**Issue by cmydjbf** [moezbhatti/qksms#600]
### DESCRIPTION

A short description of the issue. 
Example: Conversations aren't marked as read when they are opened from a notification.
### STEPS
1. Steps
2. to 
3. reproduce
4. the 
5. issue.
### EXPECTED

Describe the expected behaviour.
### OBSERVATIONS

Describe what happens instead of the expected behaviour.

**Comment by cmydjbf** [comment]
How can I solve the problem (or this is a bug on my device?)

**Comment by searchy2** [comment]
Hi! 

If you have multiple SMS clients installed, you will receive more than one notification for each SMS you receive. Are you receiving two messages in QKSMS? If there are two duplicate messages in each conversation list, then that is a bug. However, if you receive multiple notifications, that is a simple configuration fix.

-Ray

**Comment by moezbhatti** [comment]
What's the other SMS app that shows the messages?

**Comment by cmydjbf** [comment]
i only enabled one sms app (qksms).
Others are disabled.

**Comment by cmydjbf** [comment]
The conversation in qksms is like this :
--hi
--hi
            Hello--
            Hello--
--how are u
--how are u

**Comment by jenslody** [comment]
I had the same issue with 2.7.2, downgrading to 2.7.1 helped.
I just downloaded and installed 2.7.3 manually and it seems this issue is fixed.

**Comment by jenslody** [comment]
Unfortunately this is not rue.
I just received a doubled SMS again.
I will downgrade to 2.7.1 again.

**Comment by Janaue** [comment]
Hi I have the same problem on xiaomi miui 8. All other apps are disabled and this app is the default app....

**Comment by Janaue** [comment]
Same thing on version 2-7-1

**Comment by fantasio31** [comment]
Same situation for me on Xiaomi Redmi 3 with global ROM (Android 5.1.1) with QKSMS 2.7.3.

**Comment by fantasio31** [comment]
For information, using QKSMS 2.7.1 from F-droid solved this issue for me too.

**Comment by budulinek** [comment]
Hi, I have the  same issue with Xiaomi phone.

**Comment by budulinek** [comment]
Downgrade to 2.7.1 did not help.

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0

**Comment by budulinek** [comment]
Not fixed. QKSMS correctly shows only one incoming message. But other messaging apps (default SMS app) still show two incoming messages. It means that QKSMS still saves two incoming SMS messages to the phone (though only displays one).

In addition, after your workaround, QKSMS does not show sent messages at all (even though the default messaging app shows them).

Thanks!

**Comment by budulinek** [comment]
OK, issue solved in the latest preview release. Sorry for the confusion.
