### ISSUE TITLE
DrmUtils' utility? (aka what does it do)

### ISSUE THREAD

**Issue by searchy2** [moezbhatti/qksms#601]
DrmUtils is evoked in MessageUtils and deals with Ringtones. Guess is it is a remnant of when carriers controlled Ringtones. Is ringtone DRM still used/necessary in 2016?

Please update as to what DRM does in an SMS application. Thank you!

**Comment by moezbhatti** [comment]
I believe we talked about this on Slack - so I'll close the issue
