### ISSUE TITLE
Some changes in Settings does not apply immediately

### ISSUE THREAD

**Issue by frogoscar** [moezbhatti/qksms#602]
### DESCRIPTION

Some changes in Settings does not apply immediately, for example : Split SMS, Strip unicode, Vibrate  on message delivery, etc.
### STEPS
1. Go to **Settings** -> **General**
2. Toggle for example **Split SMS**
3. Go to one conversation
4. Send a long SMS
5. Spliting SMS does not behave as its status in Settings
### EXPECTED

The change in Settings be taken into account immediately
### OBSERVATIONS

The change in Settings is not taken into account immediately, while it is taken into account after completely closing and restarting the App .

**Comment by frogoscar** [comment]
I have found the cause, it is because that in the method 

Don't you think that the class **_Settings_** is redundant ? There is already the two classes _**QKPreferences**_ and _**QKPreference**_.

I have created a Pull Request which solves this issue. But you could decide what is better to deal with this issue.

**Same for the other place where Settings is used instead of QKPreferences.** Need to do the same thing for the other items in the Settings.

**Comment by moezbhatti** [comment]
You're right, I plan to get rid of the `Settings` object when I refactor some of the SMS/MMS code

**Comment by moezbhatti** [comment]
We'll leave the issue open until that has been removed from the app

**Comment by frogoscar** [comment]
Thank you.

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
