### ISSUE TITLE
Sometimes Split SMS have duplication

### ISSUE THREAD

**Issue by frogoscar** [moezbhatti/qksms#607]
### DESCRIPTION

For example, the long SMS has been split into 4 short SMS, there are two 2/4 received on the side of recipient).
Quite frequent.
### STEPS
1. Install QKSMS 2.7.1
2. Activate option "Split SMS" in Settings
3. Send a long SMS to the recipient
### EXPECTED

No duplication of split SMS.
### OBSERVATIONS

There is duplication.

**Comment by moezbhatti** [comment]
Was this issue addressed in your Pull Request?

**Comment by frogoscar** [comment]
I have not yet figured out how to solve this. A bit hard.

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0, the code for handling split messages has been completely re-written
