### ISSUE TITLE
Sometimes Split SMS have delay

### ISSUE THREAD

**Issue by frogoscar** [moezbhatti/qksms#608]
### DESCRIPTION

For example, the long SMS has been split into 4 short SMS.
The 1/4 and 2/4 have been received on the side of recipient, but 3/4 and 4/4 will wait several second to be received.
Or sometimes 3/4 and 4/4 are even not received, until that the conversation continues (sender or recipient sends some new SMS), the old non-received SMS will be received.
Quite frequent.
### STEPS
1. Install QKSMS 2.7.1
2. Activate option "Split SMS" in Settings
3. Send a long SMS to the recipient
### EXPECTED

No delay
### OBSERVATIONS

There is delay

**Comment by moezbhatti** [comment]
This seems to be fixed in QKSMS 3.0
