### ISSUE TITLE
Draft SMS are not saved in certain context

### ISSUE THREAD

**Issue by frogoscar** [moezbhatti/qksms#609]
### DESCRIPTION

Draft SMS are not saved in the following two contexts.
### STEPS

[Initial State]:
- Two mobiles (Smartphone A and Smartphone B) using QKSMS 2.7.1

[PROCEDURE1]:
- Press on Compose (the Floating Action Button) and send an SMS from Smartphone A to Smartphone B
  => The SMS is sent and received correctly from Smartphone A to Smartphone B
- On Smartphone A press on Compose, select the same Smartphone B recipient, write something and press on "back key" of the smartphone.

[PROCEDURE2]:
- On Smartphone A select Compose new SMS, do not enter a recipient, enter a message and click on "back key" of the smartphone.
### EXPECTED
- For PROCEDURE1 = > The pop up should appear on screen saying: "Saved draft" and the unsent SMS should be saved in the conversation already established.
- For PROCEDURE2 = > The pop up should appear on screen saying Discard message because "No recipient have been selected.This message will be discarded." The draft SMS will not be saved.

> Current behavior on native SMS application for Android
### OBSERVATIONS

[BUG1]:
=> The unsent SMS is not saved in the conversation already established although a pop up message appears saying "Saved draft".

[BUG2]:
=> The unsent SMS is not saved in the conversation list of QKSMS although a pop up message appears saying "Saved draft".

**Comment by maxsin** [comment]
@frogoscar, can you confirm that message entered in QKSMS and tagged as Draft (even though it's now saved/visible in QKSMS) is visible in the SMS Stock App?
At least for me that's what I've noticed while replicating Procedure1
