### ISSUE TITLE
Which folders have the core files to use QKSMS as a plugin?

### ISSUE THREAD

**Issue by dgorrd** [moezbhatti/qksms#610]
I'm trying to figure out which folders and files would be the minimum (lite) version of QKSMS.  I downloaded the zip file with the project and tried to build it buy Android Studio reported that one statement in one of the files required a minimum API of 21, so I stopped there.  Can anyone give me some tips on which folders in the project are core functionality to be able to use both SMS and MMS, and which can be removed?  I'd like to omit styles if possible as I want to use the project as a plugin for my app.

**Comment by frogoscar** [comment]
[https://github.com/moezbhatti/qksms/tree/master/QKSMS/src/main](https://github.com/moezbhatti/qksms/tree/master/QKSMS/src/main)

**Comment by searchy2** [comment]
If you just want the capability to send SMS, the SMSManager class is pretty useful. https://developer.android.com/reference/android/telephony/SmsManager.html

**Comment by searchy2** [comment]
Also, qklabs.slack.com is a good place to discuss and ask questions :1234:

**Comment by dgorrd** [comment]
Thanks for the replies. I will check those out.  I also need MMS capability, and basic storage, reading operations.  A lite version of SMS/MMS app would be most useful.
