### ISSUE TITLE
Notification pops up when in conversation with Quick Reply disabled

### ISSUE THREAD

**Issue by frogoscar** [moezbhatti/qksms#611]
### DESCRIPTION
When Quick Reply is disabled in Settings, when you are in a conversation, when receiving SMS, notification pops up.

### STEPS
1. Deactivate Quick Reply
2. Enter to one existent conversation
3. From another device, send a SMS to this test device

### EXPECTED
Whether Quick Reply is set to FALSE or not, notification should never pop up when in a conversation.

### OBSERVATIONS
Described above

**Comment by frogoscar** [comment]
In the source code, this block of code almost has no effort.

    // If this message is in the foreground, mark it as read
    Message message = new Message(context, lastMessage.mMsgId);
    if (message.getThreadId() == MainActivity.sThreadShowing) {
        message.markRead();
        return;
    }

because MainActivity.sThreadShowing is always **0** (sThreadShowing = 0; in onResume() and onPause() of MainActivity.java)

And when Quick Reply is disabled, getNotificationPriority(Context context) in NotificationManager.java will return **NotificationCompat.PRIORITY_HIGH** (which will make the notification a pop up).

**Comment by moezbhatti** [comment]
Thanks for the report - I have an idea in mind how to fix this properly

**Comment by frogoscar** [comment]
Thank you very much.

**Comment by frogoscar** [comment]
Fix in https://github.com/moezbhatti/qksms/pull/617
