### ISSUE TITLE
Favorite contacts

### ISSUE THREAD

**Issue by Fabrice35** [moezbhatti/qksms#612]
### DESCRIPTION

Impossible to disable favorite contacts on Samsung Galaxy A5 2016
Impossible to enable favorite contacts on Samsung Galaxy S5 NEO
Android 6.0.1 / QKSMS 2.7.1
### STEPS
1. Go to settings
2. Go to general settings
3. Switch favorite contacts
4. Go to the main screen
5. Click "+" to compose
### EXPECTED

It should be possible to popup or not the list of favorite contacts.
### OBSERVATIONS

No change in the composition screen after switch favorite contacts option.

**Comment by StephaneBausseron** [comment]
Please restart your phone and check if setting is taken into account after ?

**Comment by Fabrice35** [comment]
I tried, there was no change after reboot.
The option is now active in the general preferences, there is still no favorite contacts in the composition screen.

**Comment by moezbhatti** [comment]
This has been removed in QKSMS 3.0
