### ISSUE TITLE
Handle markdown and URL

### ISSUE THREAD

**Issue by eiffel-fl** [moezbhatti/qksms#614]
### DESCRIPTION

With the markdown syntax activated the underscore contained in urls will be deleted because of markdown.
So the URL will be incorrect and the user will get a 404 error.
### STEPS
1. Activate markdown syntax ;
2. Send yourself an URL like this http://www.dailymotion.com/video/x3guigq_funny-animals-keyboard-cat-96-tears_animals ;
3. Click on the URL ;
4. Get a 404 error because the URL was reformated and is not good anymore.
### EXPECTED

The URL should not be reformated.
### OBSERVATIONS

The underscore in the URL are used as markdown marks so they are removed from the url.
### PATCH

I will be treated as a clown but a simple patch consists to inactivate markdown for the message if it contains an URL.
Here is a quick and dirty patch : https://framabin.org/?7db6d7ef7dc80b19#XhSyE7pM1a4fm7sfVOmjOZU3wqQ8bYuLbhSVUjEZuVA=
### DISCUSSIONS

I think that it is important to discuss this problem because it is not as simple as it seems.

My solution is clearly not good, but it is pretty hard to handle correctly URL because what is **exactly** an URL ?

In QKSMS it seems that \w{\w|\d}*.\w+ is an URL, but how are we supposed to handle an URL like this : http://wayback.archive.org/web/\*/http://google.com (remove the backslash before the asterisk) or the one I gave in example above.

I know that using hyphens in URL should be preferred over using underscore.

So I do not think that it is possible to handle **ALL** the URL  but we can clearly find a better solution than mine.

**Comment by moezbhatti** [comment]
Will be included in #980
