### ISSUE TITLE
Reply pop-up doesn't support landscape layout

### ISSUE THREAD

**Issue by kristoffer09** [moezbhatti/qksms#615]
### DESCRIPTION

When replying in pop-up window when in landscape mode, it will rotate back to portrait. See image below.
### STEPS
1. Open any app that is in landscape mode by default
2. Wait for a message (or message yourself)
3. Reply through pop-up window while in app 
### EXPECTED

Can reply through pop-up window without rotating back to portrait mode. As I remember it works fine before 2.7 update.
### OBSERVATIONS

Default view (Landscape mode):
![screenshot_2016-08-30-16-47-28](https://cloud.githubusercontent.com/assets/16292888/18082708/9ebcb840-6ed2-11e6-8c24-c00a565a1d0f.png)
when replying:
![screenshot_2016-08-30-16-48-19](https://cloud.githubusercontent.com/assets/16292888/18082707/9ebb1544-6ed2-11e6-972d-11e35c8dbcb3.png)

**Comment by moezbhatti** [comment]
The popup has been removed in QKSMS 3.0 in favor of rich notifications, which do support landscape typing!
