### ISSUE TITLE
Conversation still has "Draft" mark when no Draft at all

### ISSUE THREAD

**Issue by frogoscar** [moezbhatti/qksms#616]
### DESCRIPTION

This happens only when after user is asked to set QKSMS as Default SMS App.
Version of QKSMS 2.7.1
### STEPS
1. Start QKSMS for the first time or previously already set other App (for example the Standard SMS App) as Default SMS App 
2. Enter into a conversation or Press Compose Button (the Floating Action Button)
3. Type some text
4. Press Send button
5. When it asks to set as Default SMS App, accept
6. Press Send button
7. SMS is well sent
8. Go back to Conversation List Activity
### EXPECTED

The conversation that we just manipulate should not have "Draft" mark.
### OBSERVATIONS

The conversation that we just manipulate has "Draft" mark. Although there is no Draft at all.

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
