### ISSUE TITLE
An NullPointerException with content://mms-sms/conversations/ on Samsung Device

### ISSUE THREAD

**Issue by frogoscar** [moezbhatti/qksms#618]
### DESCRIPTION

No crash (so this issue is not that urgent).
But an Exception (NullPointerException) comes out when I some manipulation of QKSMS 2.7.1 on Samsung S6.
When I do the fix of issue https://github.com/moezbhatti/qksms/issues/611
### STEPS
1. Send some SMS from another device to your device conncted to Android Studio or ADB
2. In the logcat you can see the exception
### EXPECTED

No exception.
### OBSERVATIONS

Exception :
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference` 

Due to 

`context.getContentResolver().query(MMS_SMS_CONTENT_PROVIDER, new String[]{SmsHelper.COLUMN_MMS}, "_id=" + id, null, null);`

`public static final Uri MMS_SMS_CONTENT_PROVIDER = Uri.parse("content://mms-sms/conversations/");`

in    **com.moez.QKSMS.data/Message.java**
### Related discussion

http://stackoverflow.com/questions/12926141/content-mms-sms-conversations-return-nullpointerexception-at-android-ics-sams

http://stackoverflow.com/questions/13553046/sgs-3-bug-related-to-sms-conversations-list

**Comment by moezbhatti** [comment]
This should be resolved in QKSMS 3.0

**Comment by bradcypert** [comment]
Just curious, what was the solution to this?

**Comment by moezbhatti** [comment]
It wasn't solved intentionally, but the codebase was rewritten from scratch and I haven't seen this issue pop up in the crash logs, so I assume that I might have just been something stupid in the last version. The new version is also using Kotlin, which helps quite a bit in preventing stupid mistakes that lead to NullPointerExceptions
