### ISSUE TITLE
Qksms closes spotify and grinds device to a halt when opening the full sms application

### ISSUE THREAD

**Issue by Trustmega** [moezbhatti/qksms#623]
### DESCRIPTION

When listening to spotify in the background and opening the full qksms app the device grinds to a halt and spotify is forced-closed.
### STEPS
1. Play music on Spotify
2. Do other stuff with spotify in the background for a while
3. Get text message
4. Open the full qksms app
5. The device grinds to a halt and Spotify suddenly stops and disappears 
### EXPECTED

Smooth opening of qksms and no crashes of other apps
### OBSERVATIONS

I don't think that the problem lies with Spotify but that qksms eats all available memory or something like that, & that makes Android force close other apps to free up RAM.

qksms version: 2.7.1
Android version: 6.0.1
Phone: Samsung galaxy s5 international edition (SM-G900F)

**Comment by moezbhatti** [comment]
This has been fixed with QKSMS 3.0
