### ISSUE TITLE
SPACE does not "create" new recipients in AutoCompleteContactView any more

### ISSUE THREAD

**Issue by frogoscar** [moezbhatti/qksms#626]
### DESCRIPTION

In the AutoCompleteContactView, if we enter a phone number which is not in Contact, and press SPACE button, it does not create new recipient.
I remember that SPACE could "create" new recipients in previous versions.
In QKSMS 2.7.3
### STEPS
1. Launch QKSMS
2. Press Compose button
3. In the AutoCompleteContactView, type a phone number that is not in your Contact, for example : 0788445566
4. Press SPACE button
5. 0788445566 is not added as a new recipient (with [Android Chips](https://github.com/klinker41/android-chips))
### EXPECTED

SPACE could "create" new recipients in AutoCompleteContactView
### OBSERVATIONS

As described above

**Comment by romelemperado** [comment]
Same here you need to click on the message box for the number to be added on the new recipient.

This happens only if you are typing the number directly and not in your contact.

**Comment by moezbhatti** [comment]
Come to think of it, I don't think this even _should_ work, in case you're searching a contact name and need to include a space
