### ISSUE TITLE
Marking one message as read causes all QKSMS notifications to disappear

### ISSUE THREAD

**Issue by woj-tek** [moezbhatti/qksms#631]
### DESCRIPTION

When having notifications for more than one thread/message/contact, marking one of them as read from notification causes all notifications to disappear.
### STEPS
1. receive >2 messages from separate contacts;
2. >2 notifications are displayed;
3. select one of them in the notifications and from the expanded actions choose 'mark as read'
### EXPECTED

Single message is marked as read and other notifications persists;
### OBSERVATIONS

All notifications from QKSMS are gone

**Comment by moezbhatti** [comment]
I can't reproduce this myself

Does this happen for you while the app is open in the foreground, or no matter which app you're looking at?

**Comment by woj-tek** [comment]
OK, I've just tested it again and seems to work fine now. I'll update the ticket if I found a way to reproduce it (or was there an improvements recently?)

**Comment by deplacer** [comment]
Same here.. to reproduce mark more than 2 conversation as unread to show notifications.
click the top notification.

**Comment by moezbhatti** [comment]
@deplacer are you able to reproduce it? Or does it work fine for you?

**Comment by deplacer** [comment]
Yes I can.. try to mark 3 conversation as unread to produce notification without waiting incoming sms then minimize qksms and click the top notification.

**Comment by sm4rk0** [comment]
Isn't this related to #356 and thus #303, too?

**Comment by woj-tek** [comment]
Reading linked issues... yeah, seems so -- most likely the underlying mechanism is the same: no matter how the "read action" is executed it clear the notification for all conversations, be that marking from notification or opening thread.

**Comment by moezbhatti** [comment]
This is fixed in QKSMS 3.0
