### ISSUE TITLE
Unable to enter sms body with Anysoftkeyboard in landscape

### ISSUE THREAD

**Issue by marmistrz** [moezbhatti/qksms#632]
### DESCRIPTION

Unable to enter sms body with Anysoftkeyboard in landscape
### STEPS
1. Install Anysoftkeyboard and enable it
2. Launch qksms, enter an existing conversation
3. Enter landscape
4. tap the field for the new message. The field is small, about one line small
5. type something. A list of suggestions will appear. The new message field will become even smaller and the message content can't be visible

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0
