### ISSUE TITLE
Enter button option shows up in other apps at times

### ISSUE THREAD

**Issue by CarsonCook** [moezbhatti/qksms#633]
### DESCRIPTION

The choice made for the usual enter button (default is smily face) will sometimes show up in another apps' keyboard. Has happened for me in Google Search bar and Facebook Messenger.
### STEPS
1. Open keyboard in QKSMS
2. Open keyboard in another app
### EXPECTED

Other apps should have their usual enter button (e.g. Facebook Messenger has a new line button there)
### OBSERVATIONS

Smily face/other option shows up instead of Facebook's new line (or Google's search button).
### Screenshot

![14348840_1112350258820002_288283609_n](https://cloud.githubusercontent.com/assets/14897740/18421908/2ce74e80-7862-11e6-9110-3ad59daa7551.png)

**Comment by moezbhatti** [comment]
Hahaha, I first saw this before you censored the screenshot

**Comment by CarsonCook** [comment]
I was too much of an OG

**Comment by moezbhatti** [comment]
Should be addressed in QKSMS 3.0
