### ISSUE TITLE
Starred contacts does not revert after switching this option off

### ISSUE THREAD

**Issue by padr** [moezbhatti/qksms#636]
### DESCRIPTION

Moto 4 Android 6.0.1
I set ( in general settings) Starred contacts to show. This is useful as a type of work-around to make it easier to send group SMS. However I then saw that after adding say 8 or 9 in the compose screen - I regularly send an SMS to a group of 10 - the compose screen send to section became too cluttered. 

When I went back and switched off Starred Contacts the setting restored itself to on ( albeit with the arrow pointing left beside the "STARRED CONTACTS" text in the compose screen - the actual contacts not showing but the "STARRED CONTACTS" text remaining). A further visit to the general settings screen showed the option slider to have restored itself to the right i.e. on. This persisted after a restart and an uninstall and reinstall
### STEPS
1. Switch general settings to show starred contacts
2. Note that the compose screen now shows starred contacts ( 4 across) 
3. Switch starred contacts off in the general settings screen
4. "STARRED CONTACTS" remains in the compose screen
5. General setting slider has gone back to to the right
### EXPECTED

All reference to starred contacts should disappear from the compose screen
### OBSERVATIONS

I note that in settings "QK Compose" the text says "QK Compose, starred contacts. Entering into the settings screen only "QK Compose enabled" setting is present with the slider set to the left

**Comment by padr** [comment]
Seems similar to #612 although opposite effect

**Comment by moezbhatti** [comment]
The feature has been removed in QKSMS 3.0
