### ISSUE TITLE
Old Pictures Show Up

### ISSUE THREAD

**Issue by CarsonCook** [moezbhatti/qksms#637]
### DESCRIPTION

Sometimes in quick reply old pictures (or long texts with emojis) replace the last text sent by the phone owner.
### STEPS
1. Receive text
2. Enter quick reply
### EXPECTED

Your old texts are all shown.
### OBSERVATIONS

The last text sent by the phone owner is sometimes replaced by the first picture sent to that contact. Less often it's a very long text with emojis.

**Comment by moezbhatti** [comment]
This is resolved in QKSMS 3.0
