### ISSUE TITLE
2.7.3 update issues

### ISSUE THREAD

**Issue by fredcooke** [moezbhatti/qksms#638]
Just upgraded from 2.5.4 and want to say thanks for all of your work, especially:
- fixed rotation support
- fixed scrolling to the bottom all the time
- timestamps for messages are now configurable

Cheers! :-)

However:

When you press the back button from a conversation to the message list, it flickers to the background briefly before showing what it should. Kinda annoying and a regression IMO.

My contacts which have names STILL show just the number in some certain cases. This is old but I was hoping it'd be fixed by now.

These from five minutes playing around. Will add anything new that I find tomorrow. Too late to send SMSes now.

**Comment by fredcooke** [comment]
Oh, and the icon disappeared from my main page/launch bar/whatever it's called in KitKat. This might be KitKat, fdroid, or you - I don't know.

**Comment by fredcooke** [comment]
The back button behaviour is only present if you enter the app from the list. Not if you open it from the launch screen. Something similar in an old version. I recall discussing it with you on here. Maybe I'll find and mention the issue number.

**Comment by fredcooke** [comment]
I lied. Seems to be present on a direct launch, too. Though in one session it was not happening.

**Comment by fredcooke** [comment]
360 (that I'll close now) was the vaguely similar thing that happened. I don't know why, but the way you enter the app affects how it behaves. What part of the code is responsible for this? Some init routine that only runs sometime or something like that?

**Comment by fredcooke** [comment]
Another few things that I've noticed;

1) Sometimes when you reenter the app you end up in a text message you weren't reading and sometimes when that happens going back/out goes to another message, and another, and so forth, before finally ending up in the conversation list like the first press should have done. Some sort of back stack mismanagement for sure.

2) It's super slow sometimes, one such time resulted in the device crashing, which can't be QK's fault, but seemed to be triggered by the slow opening of the app. I've *NEVER* had it crash like that before. So it's suspicious to me.

**Comment by moezbhatti** [comment]
Can confirm, I get this issue depending on how I enter the app. I recently changed how the conversations -> messages logic worked, and I think that may have screwed with some things.

Restructuring this is going to be a big part of QKSMS 3.0

**Comment by fredcooke** [comment]
Fair enough, I guess. Overall this version feels less buggy, but the speed/visual artifacts is a little annoying and a lot worse than 2.5.4.

How about that number/name issue??? :-D

**Comment by fredcooke** [comment]
I've been using this for a month now and I have to say, the slowness and lagginess and android-crashing-ness of it is pretty annoying. As is the MASSIVE back stack bug. Sometimes it's 50 layers deep. That's a lot of pressing back.... and regularly the same convo appears 10 times in a row or something like that. 

Another thing I've noticed is that there seems to be some interaction between QKSMS and Xabber XMPP client. Maybe some intent being fired and received in unintended places? Not 100% sure what's going on.

The slowness has to be solvable, as does the back stack thing. Those bugs are pretty horrendous in terms of usability. Sometimes it's reasonable. Other time's it grinds the machine to a halt. It's the only app I've ever had those "stopped responding" messages from.

Far worse than the number/name thing, which, btw, seems to be +64 21 XXX XXXX vs 021 XXX XXXX based. All instances are stored in contacts in international, and show in the app in local.

**Comment by fredcooke** [comment]
Oh yeah, and a minor thing that's mildly annoying usability wise:

Rotation and draft.

Type some stuff, rotate, two things happen:

1) The keyboard vanishes. Not sure if you actively have to ask it to stay, or if you're accidentally tellin it to go, but it should stay. 
2) The "saved draft" pop up comes. I understand that the view is killed off by the OS during a rotation, but from the user's perspective the app has not been killed off, nothing needed to be saved, it just rotated. Similarly, if the text hasn't changed since it was last saved, don't show the saved thing, it's already saved, repeatedly saving the same content makes zero sense. 

I guess I want to see "saved draft" when I exit the conversation. Only? Not sure. But not on rotation, that's for sure.

**Comment by moezbhatti** [comment]
Thanks for the additional feedback
I'm working on a major overhaul of the app (hence the lack of updates in the last few weeks) but I'll be sure to take this stuff into account

**Comment by moezbhatti** [comment]
Closing this as QKSMS 3.0 is being written from scratch, and won't retain the old issues

**Comment by fredcooke** [comment]
Better to keep them open and tag with "affects" versions? I take it 3.0 is not a real installable thing at this point, right? So people who are still using it should see open issues against older variants unless confirmed fixed in some 2.x.y version. My 2c.

**Comment by moezbhatti** [comment]
@fredcooke Hmm, makes sense. For future releases I think it would make sense to leave the issues open until the next build has been released

Right now I'm treating this as a purge of sorts, as I've admittedly done a poor job at maintaining the issues and now there are hundreds of open issues dating back to 2015. Trying to slowly prep the repo for the next release, which I'm hoping to push by the end of the month
