### ISSUE TITLE
Notification Reply Sent to incorrect recipient Android Nougat

### ISSUE THREAD

**Issue by MoodZy** [moezbhatti/qksms#639]
### DESCRIPTION

When you receive SMS messages from a lot of persons and they stack up in your notifications (on your lock screen). If you answer to the last visible SMS through the lock screen notification, the SMS will be sent to the incorrect person (i.e. the last received SMS)
### STEPS
1. Receive a lot of SMS messages.
2. Lock your device.
3. Try to answer the last visible SMS received.
4. Unlock your device.
5. Go see in the QKSMS app to view the SMS sent to the incorrect person.

This happens on Android Nougat (7.0). Not sure if it happens with the other versions
### EXPECTED

The SMS should be sent to the correct person.
### OBSERVATIONS

The SMS answer is sent to the last SMS received instead of the last visible SMS.

**Comment by moezbhatti** [comment]
I can't seem to reproduce this issue

**Comment by cyrosy** [comment]
I'm having the same behavior, even when I do not lock my phone.
Answering via notification answers to the last received SMS, not the selected one.

**Comment by xavihernandez** [comment]
Same here, happens when several messages are not answered/read yet.

This is a **HIGH CRITICAL** issue. This can lead to unconmfortable situtation.

Is there any news on that?

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0

**Comment by xavihernandez** [comment]
Great, can't wait to try!
