### ISSUE TITLE
Enter button: when send 2 sending indicator shown

### ISSUE THREAD

**Issue by deplacer** [moezbhatti/qksms#643]
### DESCRIPTION

Enter button set to send message.
When you send using keyboard enter button, 2 "sending.." indicator are shown.
### STEPS
1. Go to Settings> General> Enter button > Send message
2. Go to any conversation and try to send message but send using the keyboard enter button.
### EXPECTED

Only 1 sending indicator..
### OBSERVATIONS

When you send message using keyboard enter button two message will send. First one is your real message and second one is just a empty message.. It shows 2 sending... indicator.

QKSMS APP
![screenshot_20160922-162444](https://cloud.githubusercontent.com/assets/7690158/18741946/56fb18f2-80e4-11e6-8ca3-d07baf007192.png)

MESSAGING APP
![screenshot_20160922-162936](https://cloud.githubusercontent.com/assets/7690158/18741947/57065686-80e4-11e6-9d51-d6d8e7941d14.png)

**Comment by moezbhatti** [comment]
Does this show up in all of your conversations, or just that one?

**Comment by deplacer** [comment]
Only on the conversation where i send a message using the keyboard enter button.. 
That 2 sending.. indicator only appears if i use the keyboard enter button to send.. 
But if i send using the arrow button it works fine.

**Comment by sm4rk0** [comment]
I can confirm this, too. QKSMS 2.7.3 on Lollipop 5.1, Motorola Moto X.

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0
