### ISSUE TITLE
Notification cannot clear if QKSMS is not default app

### ISSUE THREAD

**Issue by deplacer** [moezbhatti/qksms#645]
### DESCRIPTION

sms notification cannot be clear when qksms is not default app.
### STEPS
1.  Set qksms as default app.
2. Wait for new sms notification or mark any conversation as unread.
3. Change default messaging app to any messaging app. 
4. Swipe notification to clear. Still reappear.
### EXPECTED

Sms notification should be clear when swipe.

**Comment by moezbhatti** [comment]
Fixed in https://github.com/moezbhatti/qksms/pull/717
