### ISSUE TITLE
Enhancement request on mms and programmed sms

### ISSUE THREAD

**Issue by dylanmance** [moezbhatti/qksms#646]
I really love the app but I just had a tiny little issue while sending pictures via mms. I wanted to send several pictures from my phone storage but the app won't let me select more than one, it would be great if we could send several in one mms.

Also I always type the text first and add the pictures right before sending but if you type text in QKSMS the button to add pictures disappears to become the sending button, I think it would be great to have two separate buttons.

And one final thing that I miss from an app I previously used (that wasn't as good though), it would be really great if you added a feature to program a sms to send at a given time and date, the option could show in the same button than the one for adding pictures maybe ?

Thanks a lot for all your work on this amazing app !

**Comment by ciper** [comment]
I agree with the missing feature of having multiple images per mms message. If I switch to a different SMS app this is possible. 

A related missing feature is that in other apps you can attach a text description to an image and its sent ad one bundle. In qksms it seems to support this but the text and the image are sent as two different messages

**Comment by moezbhatti** [comment]
QKSMS 3.0 now supports sending multiple images in MMS
