### ISSUE TITLE
Selecting "Reply" from peek notification should also dismiss the peek notification when the QR box comes up.

### ISSUE THREAD

**Issue by dar-irl** [moezbhatti/qksms#649]
Just a small feature/improvement suggestion, since I've found this to be a little annoying.

If I receive a text notification, and I select the "reply" button from the peek notification to bring up the QR box, the peek notification stays on my screen for a couple more seconds even with the QR box there too. Would it be possible for the peek notification to be dismissed when I tap "reply" to bring up the QR box? Because otherwise it's just redundant to have both, and the peek notification can potentially block or cover up the QR box on smaller devices.

**Comment by moezbhatti** [comment]
QK Reply has been removed in QKSMS 3.0, so I'll be closing this issue as it's no longer applicable.

The reply mechanism will now just use the rich notifications API in Android
