### ISSUE TITLE
Search functionality on contact names

### ISSUE THREAD

**Issue by 8bitrebellion** [moezbhatti/qksms#650]
It doesn't search contact names. Like I have hundreds of threads, and I want to send a message to my mom(contact name saved as 'mom'), now instead of scrolling and looking for thread named on my mom, it is more convenient if I can search word 'mom' and the thread appears.
Sorry, if I have written a long post.

**Comment by lucyyu24** [comment]
duplicate #546

**Comment by sureshlsdj** [comment]
Hi @lucyyu24 
Is this searching contact name feature include or not. I have checked current code, there is no change in it. Please let me know about this feature
