### ISSUE TITLE
Random texts sent

### ISSUE THREAD

**Issue by markingitup** [moezbhatti/qksms#652]
Turned off airplane mode this morning and 3 very old texts were resent to 3 different people (2 starred, 1 not starred) 

Tried to reproduce the issue but couldn't... Just don't want it to keep happening as it was very early in the morning. 

Just installed QKSMS yesterday. Love it other than this issue happening.

**Comment by DFyson** [comment]
Funny I just had exactly the same thing happen to me just now but was looking for a specific bug. It's really irritating flooding people with tons of random old messages. What happens is old failed-to-send sms are automatically retried when coming out of airplane mode. I recall seeing this as a new feature in the past year, but it obviously needs some tweaking. It should likely have a retry timeout option. If not sent within say 30min, then give up.

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0
