### ISSUE TITLE
In group messages the name of the sender does not appear right away

### ISSUE THREAD

**Issue by yzerman19** [moezbhatti/qksms#654]
### DESCRIPTION

When receiving a message that is part of a group message, I cannot tell who sent that message.
### STEPS
1. Have someone send a message to several recipients, including you.
2. Enter the group chat and look at the bottom for the latest message.
3. The avatar and name of the sender will not be there. It is up to my imagination to determine which person in the group sent that message.
### EXPECTED

The avatar and name of the sender should appear immediately when the message first is viewed.
### OBSERVATIONS

The avatar and name of the sender do not appear immediately. I am trying to pinpoint what triggers the name and avatar to eventually appear there. It usually take a combination of scrolling the message, or touching the box to enter a reply, or leaving the app and coming back to the message, etc..

**Comment by moezbhatti** [comment]
This is fixed in QKSMS 3.0
