### ISSUE TITLE
Draft message disappears if there was no recipient

### ISSUE THREAD

**Issue by svxsvx** [moezbhatti/qksms#661]
### DESCRIPTION

If there is so far no recipient entered in a new Message the draft will not get saved.
### STEPS
1. Hit plus-button.
2. Enter message
3. In case it's relevant:
   1. Send message without recipient entered yet.
   2. State is now: failed send with error. Send button is a cross now instead of an arrow.
      _(By the way also really confusing because it implies on the first view "cancel" or in that case "delete (message)" even if recipient is entered afterwards. Who dares to touch the **"delete message" button** to get the send button back!?!)_
4. Go back via on-screen back button (the one next to "compose")
### EXPECTED

Best solution: In the list of send messages one (or more) entries with empty/unknown recipients.
But at least hitting the plus button and finding my message again.
### OBSERVATIONS

Message gone. No way to get back to the message.

**Comment by moezbhatti** [comment]
This is fixed in QKSMS 3.0
