### ISSUE TITLE
Crash when opening new SMS or scroll in widget

### ISSUE THREAD

**Issue by Exagone313** [moezbhatti/qksms#662]
Hi,
Today, QKSMS crashed, and since this it crashes if I open a conversation with a new SMS received (or when receiving an SMS with the conversation already opened), or when I scroll down/up on the widget. I rebooted the phone multiple times but it persists. Tried to clear the cache of the application.
I have no idea why it crashed in the first place, so I don't know how to reproduce it.

I'm gonna reinstall it. I copied the _/data/data/com.moez.QKSMS_ directory just in case it could be useful.
I use the latest version from F-droid (2.7.3).
(Reinstall "corrected" the bug, just lost the custom color for app icon)

**Comment by moezbhatti** [comment]
Going to close this issue just as there isn't enough information to be able to reproduce it. The crash should show up in the Crashlytics logs though, so I should be able to hunt it down
