### ISSUE TITLE
Multi-line message should be aligned right

### ISSUE THREAD

**Issue by marmistrz** [moezbhatti/qksms#663]
If a messages takes only one line, the container doesn't fill width and is aligned right. If a message takes more than one line, the container takes full width and the text is aligned left. It should be aligned right in the container. 

If you give me some hint, I can make a pull request. I don't have much experience with the Android platform but have programmed a little in JavaFX.

**Comment by Bill-Stewart** [comment]
That's a style preference. I don't like right-alignment (for left-to-right languages).

**Comment by moezbhatti** [comment]
Most of the major messaging apps align to the left, and don't provide an option to align right for LTR languages. Because of this I'm not planning to add support for right alignment in messages, but I appreciate the suggestion
