### ISSUE TITLE
Capturing an image from app directly does not attach 

### ISSUE THREAD

**Issue by ciper** [moezbhatti/qksms#667]
### DESCRIPTION

I have the same issue on two phones. Both are using the latest version of qksms from the app store. The picture seems to take but I'm returned to a blank text message box 
### STEPS

Open an existing conversation 
Click the arrow button on the blank message 
Click the camera icon
Take a picture 
You are returned to a blank message with no attachment 
### EXPECTED

The image taken with your default camera application should be attached to the new mms message 
### OBSERVATIONS

Absolutely nothing happens. The image isn't vanishes.

**Comment by ciper** [comment]
This issue is still present

**Comment by moezbhatti** [comment]
Merging with #75
