### ISSUE TITLE
Unread count does not appear in Nova Launcher/TeslaUnread on Samsung

### ISSUE THREAD

**Issue by Bill-Stewart** [moezbhatti/qksms#671]
I am using Nova Launcher Prime 4.3.1 and TeslaUnread 5.0.6 on a Samsung Galaxy J7 running Android 6.0.1.

I installed QKSMS and set it as the default messaging app, and configured TeslaUnread to display unread message thread counts for it.

I am able to receive messages without problems, but the unread thread count never appears on the QKSMS app icon.

When I revert to using the Samsung messages app, the unread thread count on its icon works without a problem.

**Comment by moezbhatti** [comment]
Works on my phone, anyone else having issues?

**Comment by Bill-Stewart** [comment]
Hi Moez, does it still work for you if you disable notifications in QKSMS?

**Comment by moezbhatti** [comment]
Merging with #311
