### ISSUE TITLE
[Enhancement] Group messaging

### ISSUE THREAD

**Issue by TheFreeBeginner** [moezbhatti/qksms#674]
Hello everybody !

I'm new here on github, and i'm beginning in the beautiful world of the open source world :)

I have a proposition for this great app (well done moezbhatti, i love it !).

I didn't find a feature that i often use on the stock messaging app : to create a group of contacts to send it some sms. You can already send several people an sms but you cannot save this group of people (with a name, for example "Family" or "Teamwork") to use it other times.

Thank you !

**Comment by muhammadkamranlatifraza** [comment]
Yes dear this would be awesome

**Comment by klemens-u** [comment]
+1 that would be a killer-feature! Please implement!

**Comment by moezbhatti** [comment]
Merging with #45
