### ISSUE TITLE
Wish: another icon for this app

### ISSUE THREAD

**Issue by Spielmops** [moezbhatti/qksms#676]
I configure Android-phones for other people. And install QKSMS, But everytime, I give them their phone back, they complain about that Q-icon, which does not tell them anything about an SMS-app ....

**Comment by moezbhatti** [comment]
While it looks like it's just a Q, it's meant to resemble the outline of a message bubble

**Comment by moezbhatti** [comment]
Closing for now because I can't see myself prioritizing this anytime in the reasonably near future
