### ISSUE TITLE
SMS via custom protocol

### ISSUE THREAD

**Issue by FoliniC** [moezbhatti/qksms#677]
### DESCRIPTION
Send SMS using custom protocol
### EXPECTED
Some provider (Vodafone) offer plans without SMS or costly plans with way too much SMS.
QKSMS should send SMS via a different provider (http://www.agiletelecom.com/Documentation.aspx) via custom protocol.
The interface should ask for credentials in settings and let user choose which provider use when sending SMS.
I would like to implement it if not already possible.

**Comment by moezbhatti** [comment]
Currently we have no plans to support a service besides standard SMS, but thank you for bringing this up
