### ISSUE TITLE
[Enhancement] - Add to Contacts

### ISSUE THREAD

**Issue by CaseyRedisAtWork** [moezbhatti/qksms#679]
It would be useful to be able to add to the contacts list from a received message.  As an example, several months ago I met a distant family member and gave him my phone #.  He recently texted me and all that shows up (naturally) is his phone number.  In the stock messaging app, I can open the message and "add to contacts" and put his name, address, etc. there.  The same functionality seems to be missing (or impossible for me to find) in QKSMS.

**Comment by sm4rk0** [comment]
Just tap the contact icon in conversation list (i.e. before you open the conversation) and it offers adding the number to contacts.

**Comment by CaseyRedisAtWork** [comment]
OK so I feel stupid now!  I guess I had tried a variation on what you're
saying and was clicking on the phone-number itself, not the icon to the
left of it.  Clicking (or long-pressing) the number only brought up the
conversation or details about it.  Now I see that clicking on the icon
itself does exactly what you say and what I was looking to accomplish.

Sorry for my mistake.

Best,
Casey

**Comment by xczv** [comment]
Now, what if you have the icons hidden? Maybe there should be a way to add contacts if you have icons hidden...
