### ISSUE TITLE
Previous Message Windows Don't Close

### ISSUE THREAD

**Issue by Addizzle** [moezbhatti/qksms#680]
### DESCRIPTION
All pervious message windows stay open. After you are done replying hitting the back button takes you to the last person or persons you have been texting, not the main list. You must keep hitting back until you close out all previous recent replies to get to message list.

### STEPS
1. Reply to mutiple different people from the notification pull down.
2. Hit home button
3. Open qksms

### EXPECTED
The last message window you sent should now be displayed. Hit back once and it should take you to the main messges list. 

### OBSERVATIONS
The last message window you sent should now be displayed. Hit back until you get to the message list. The first back press will open the second to last person you sent to, the 2nd press will take you to the third person you sent to etc. Until you get to message list.

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0
