### ISSUE TITLE
Strip Unicode Table is not complete and all correct

### ISSUE THREAD

**Issue by frogoscar** [moezbhatti/qksms#682]
### DESCRIPTION
Some characters in the Table of StripUnicode (in StripAccents.java) is not correct, and it lacks of a lot of UniCode Accent Characters.

### STEPS
1. Go to Settings
2. Turn on Strip Unicode
3. Send a message with Unicode Accent Character

### EXPECTED
The function StripUnicode strips almost all the Unicode Accent Character.

**Comment by moezbhatti** [comment]
Merging with #409
