### ISSUE TITLE
Unable to view old messages

### ISSUE THREAD

**Issue by nileshcool** [moezbhatti/qksms#684]
### DESCRIPTION
I am using the APP on Moto E3 POWER, though everything is working fine but I am unable to see old messages in the conversation. For example, at the home screen it is shown 11 messages in the conversation, but if I open the conversation I only get to see 4 messages. I have tried to search for options in setting but couldn't get anything.

### STEPS
1. Messeage counter shows 11 messages in conversation
2. But only 4 are shown if conversation is opened

### EXPECTED
All the conversations should be shown. 

### OBSERVATIONS
Only a few recent dated conversations are show, and old messages are not shown

**Comment by akashdeepsingh9988** [comment]
This problem is also occurred in my phone. Check app permissions and reinstall the app.

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
