### ISSUE TITLE
QK Reply Window Does Not Show Actual Message

### ISSUE THREAD

**Issue by enervated** [moezbhatti/qksms#685]
I have the QK Reply setting enabled, but it's rare that the QK Reply window shows the actual SMS message content. Usually, I get the window, but no message showing. tapping the expand button does nothing.

![qksms_popup](https://cloud.githubusercontent.com/assets/11533799/21295344/2ffb667c-c521-11e6-968a-a85959cd5f3e.png)

Nexus 6P
Android 7.0
QKSMS 2.7.3

**Comment by enervated** [comment]
I'm using Nova Launcher. I just found that if I change the Nova Launcher setting "Look & feel" > "Screen orientation" from "Lock Portrait" to Default, the problem seems to go away.

**Comment by enervated** [comment]
It actually still happens sometimes, but not as often as before. I would still consider it an issue.

Even when it doesn't happen, the window always starts as shown in the screenshot above. Sometimes the window expands to show the message; other times, it stays like that.

**Comment by moezbhatti** [comment]
QK Reply has been dropped in favor of rich notifications in QKSMS 3.0, so I'll close this now
