### ISSUE TITLE
Feature: configure number of lines displayed when writing text

### ISSUE THREAD

**Issue by thdox** [moezbhatti/qksms#686]
### DESCRIPTION
When I write a text, only *three* lines of text are displayed. 

### EXPECTED
When I write a long text, this happens frequently with my so, I would like to be able to see more than three lines. As an example, chompSMS is displaying 8 lines of text. chompSMS is not open source.
Now I have a 5.5 inches screen, and 3 lines are too small on my screen, even when keyboard is displayed, there is plenty of space to display more than 3 lines. I would love to be able to see more, whatever the way it is implemented, either an option stating the number of lines, or an option saying 50% lines from past messages and 50% for the message I am currently writing.

**Comment by lucyyu24** [comment]
duplicate #394
