### ISSUE TITLE
MMS can not be sent or received on version 2.7.3

### ISSUE THREAD

**Issue by frogoscar** [moezbhatti/qksms#687]
### DESCRIPTION
MMS can not be sent or received

### STEPS
1. Download version 2.7.3 of QKSMS from Google Play
2. Try to send or receive MMS

### EXPECTED
MMS can be sent and received correctly

### OBSERVATIONS
MMS can not be sent or received.

**Comment by moezbhatti** [comment]
This should be resolved in QKSMS 3.0, as it now uses the official MMS APIs and does not require configuration of the APN settings
