### ISSUE TITLE
Flashing "Recent Apps" Screen bug

### ISSUE THREAD

**Issue by paulhurgh** [moezbhatti/qksms#688]
### DESCRIPTION
When the "Home Screen" button (circle) is pressed, the animation stutters and briefly flashes the "Recent Apps" screen. 

### STEPS
1. From any screen in the QKSMS app, press the "Recent Apps" button (square)
2. From the "Recent Apps" screen, go back into the QKSMS app
3. Now press the "Home Screen" button (circle)
4. You will see the animation stutter and the "Recent Apps" screen briefly flash before going home (really brief!)

### EXPECTED
A fluid animation back to the home screen

### OBSERVATIONS
The animation to go back home is jerky due to a bug that briefly flashes the "Recent Apps" screen

**Comment by paulhurgh** [comment]
I'm not sure how much help this is, but I've rolled back through previous versions to see when this bug appeared. **v2.5.5** was the last version without this happening, it seems that something in the **v2.6.0** release created this bug. 



What I think may be causing this:

I think QKSMS's behavior (animation?) to go to a different screen (such as the home screen) simply reverses the animation made to enter the app. 

So, when freshly opening the app from the home screen and going back to the home screen without pressing the "Recent Apps" button, it reverses the animation made to enter making it a clean exit. However, when going back into QKSMS from the "Recent Apps" screen, and then going to the home screen, it attempts to reverse the animation that was completed for coming into the app from the "Recent Apps" screen. But maybe the OS overrides this animation to go back home, which creates that brief flash of the "Recent Apps" screen.

**Comment by moezbhatti** [comment]
This has been resolved with QKSMS 3.0
