### ISSUE TITLE
notifications should not appear on blocked messages

### ISSUE THREAD

**Issue by CLS-CLS** [moezbhatti/qksms#689]
i have blocked some spam numbers. When a message from a blocked number is received i get a sound notification and also there is a visual notification that i have one unread message (the number one appears on top of the q icon). in order to dismiss the visual notification i have to go to the blocked measages and mark it as read.  i believe there should not be any notification for blocked messages. thats the point of having blocked messages in first place

### EXPECTED
not having any notification when receiving a blocked message

### OBSERVATIONS
i get a sound and a visual notification just like the normal messages

**Comment by moezbhatti** [comment]
Fixed in 282732e18fa56eea84d66b29a0866253e419f9fe
