### ISSUE TITLE
Backpress should unselect selected conversations (if any).

### ISSUE THREAD

**Issue by m-murad** [moezbhatti/qksms#690]
### DESCRIPTION
In one or more conversations are selected and the user presse back key the app closes.

### STEPS
1. Open the app
2. Select one or multiple conversations 
3. Press back key
4. The app closes 

### EXPECTED
If one or more conversations are selected, pressing backpress should deselect the conversations. If no conversations are selected the the app should close.

### OBSERVATIONS
The app is closing on backpress even if conversations are selected.

**Comment by free4murad** [comment]
@moezbhatti 
Should I make a PR for this?

**Comment by moezbhatti** [comment]
@free4murad yeah, that would be fantastic!

**Comment by moezbhatti** [comment]
This will be implemented as part of #874
