### ISSUE TITLE
Travis build for the app is failing.

### ISSUE THREAD

**Issue by free4murad** [moezbhatti/qksms#692]
### DESCRIPTION
The travis build for the app is failing even if the PR is fine. This is because google has changed the names of certain ABIs.

### STEPS
1. Create a PR and it will fail.

### EXPECTED
The build should not fail for legitimate PRs.
I suggest updating the `travis.yml` file. If that is done the travis build will not fail for legitimate PRs.

**Comment by free4murad** [comment]
@moezbhatti
should i make a PR.

**Comment by moezbhatti** [comment]
@free4murad if you could look into this, that would be fantastic

**Comment by free4murad** [comment]
@moezbhatti 
Will make a PR in a day or two.
