### ISSUE TITLE
Useless OverFlow menu in SearchActivity.

### ISSUE THREAD

**Issue by m-murad** [moezbhatti/qksms#693]
### DESCRIPTION
No need of OverFlow menu in `SearchActivity`/`SearchFragment.`

### STEPS
1. Open the app.
2. Click on search button in toolbar.
3. `SearchActivity` containing the `SearchFragment` opens.
4. `SearchActivity` has an overflow menu which is same as that of the previous activity.

### EXPECTED
There should be no OverFlow menu in search activity.

### OBSERVATIONS
When a user is searching for a message there is no need for options like `Settings`, `What's new` or `Donate`.

**Comment by moezbhatti** [comment]
I think it makes sense to keep this menu persisted across the screens, so that it's accessible regardless where you are. I'll leave this as `wontfix` for now
