### ISSUE TITLE
Multiple images, or image + text come through as a slideshow.

### ISSUE THREAD

**Issue by jsr0213** [moezbhatti/qksms#694]
### DESCRIPTION
When someone sends you multiple images, or an image and text, it comes through as a video slideshow.

### STEPS
1. Have someone send you multiple pictures, or a picture and text in the same MMS message.

### EXPECTED
Either the images should be displayed sequentially in the body of the message, or tapping the image should open to a gallery.
As for the photo and text in the same message, the image should be displayed in the message with the included text just below it.

### OBSERVATIONS
A video slideshow consisting of a very tiny version of the pictures sent, or a slideshow consisting of a tiny picture followed by a brief flash of the text message sent in the same MMS message.

**Comment by heather1209** [comment]
This caused an issue with my husband and I as I didn't realize he sent multiple pictures in one message

**Comment by moezbhatti** [comment]
This will finally be resolved in QKSMS 3.0

I'm currently working on the new MMS implementation

**Comment by moezbhatti** [comment]
Resolved in https://github.com/moezbhatti/qksms/commit/5c13f9b86e9e5ca2f3e6e416e7b9aa5e068beaa6
