### ISSUE TITLE
Dual Sim support 

### ISSUE THREAD

**Issue by amritghimire** [moezbhatti/qksms#696]
### DESCRIPTION
I wish there was an option to select the sim on long press on send button so that user can select the sim to send as in Stock messaging app.

**Comment by tridip40** [comment]
I am not able to compile it in android studio.. can you help? how to run it? download ZIP and then what to do

**Comment by akashdeepsingh9988** [comment]
You have two options to compile and build app.

**# First Method**
 1. The first one is downloading zip file. (Download zip)
         
![2](https://cloud.githubusercontent.com/assets/25174957/22218933/dfeff1b4-e1ce-11e6-955e-84be43f0c217.PNG)

        2.  After extracting file, open the android studio .
         3. Then open the project using import option.

![1](https://cloud.githubusercontent.com/assets/25174957/22218994/17bf59e0-e1cf-11e6-8183-a84faf013711.PNG)

       4. After import android studio take some time to setting or downloading needed files. After successful     import the app  you can compile and run the app.

**# The Second method**
   The first method sometimes shows errors while building the app.
   The second method is better than first.
1. Download the github desktop software.
2. login with your username and password.

![3](https://cloud.githubusercontent.com/assets/25174957/22219252/13fc181a-e1d0-11e6-9dd2-46ecfde6632e.PNG)

3. Now open the repository of the app and click on clone or download. 

![2](https://cloud.githubusercontent.com/assets/25174957/22219302/451418bc-e1d0-11e6-897e-4d26b812b007.PNG)

4. click on open is desktop. 
5. Now choose directory for storing app files.

![4](https://cloud.githubusercontent.com/assets/25174957/22219371/8ed895c2-e1d0-11e6-9e3e-22344ffe1dd1.PNG)

6. Now the app files starts cloning. 

![5](https://cloud.githubusercontent.com/assets/25174957/22219448/c528e17c-e1d0-11e6-8be2-197ad7f626b2.PNG)

7. After the cloning process is done, open the android studio and import the project using import option.

**Comment by sm4rk0** [comment]
@amritghimire There's an identical issue already: #207, together with two closed duplicates: #381 and #480.
@tridip40 Commenting on an issue unrelated to your problem is creating unnecessary noise. [Here](https://github.com/moezbhatti/qksms#collaboration)'s the recommended way of communication for your kind of problem.

**Comment by moezbhatti** [comment]
@sm4rk0 thanks so much for helping maintain these issues. I've been MIA for the last couple weeks, but I plan to catch up on all these issues tomorrow.

Again, I really appreciate it!

**Comment by sm4rk0** [comment]
@moezbhatti I'm not an Android developer, but was a tester once upon a time, so that's the least I can do.
