### ISSUE TITLE
support WebSMS API

### ISSUE THREAD

**Issue by h4711** [moezbhatti/qksms#699]
### DESCRIPTION
It would be great if QKSMS would support the WebSMS API for sending SMS.

The development of WebSMS seems to have stopped now, but there are some 'WebSMS connectors' that do their job. Additionally user won't have to switch the app, if they want to send via one that many existing connectors. Additionally one can have only one SMS App allowed to store and receive messages on recent Android, so there's a need for one integrated app.
https://github.com/felixb/websms/

WebSMS is GPL3, too.

### STEPS
1. Install one (or more) of the WebSMS connectors from Play Store or F-Droid.
2. Open QKSMS and try to configure the connector(s).
3. send a message with QKSMS

### EXPECTED
QKSMS provides the necessarry settings ui to configure installed WebSMS connectors and makes it possible to use them for sending SMS.

### OBSERVATIONS
In step 2 you're it's not possible to configure the connector(s).
In step 3 the SMS gets send using the OS, but you're not asked if you want to use a connector.

**Comment by h4711** [comment]
The mentioned url https://github.com/felixb/websms/ only contains the websms app and example code how to access the websms api.
The api itself is seperated already: https://github.com/felixb/websms-api

**Comment by moezbhatti** [comment]
I'm going to avoid implementing a proprietary service for this, considering it's unsupported now and Pushbullet does this without needing an integration in the app
