### ISSUE TITLE
Allow message popup to be disabled

### ISSUE THREAD

**Issue by fresheneesz** [moezbhatti/qksms#705]
Whenever I get a text, it pops up over whatever app I'm in. This is hella annoying and I don't see any way of turning it off. 

I've already turned off "heads up" (pop-up notifications) in my android Notifications settings, but it doesn't help. Is there some option I'm missing, or does this need to be added.

**Comment by thabubble** [comment]
The option should be in Settings > QK Reply > QK Reply enabled
