### ISSUE TITLE
Feature request: Mark message as unread

### ISSUE THREAD

**Issue by fresheneesz** [moezbhatti/qksms#706]
Honestly why doesn't *any* sms application have this? This is super important. I don't want to forget messages that I want to read but can't answer at the moment. I want *other* people to have this feature so they don't forget about my messages. This should be priority one to implement.

**Comment by Bill-Stewart** [comment]
This may be because there is no API available that allows you to mark a message as unread.

**Comment by fresheneesz** [comment]
Not true. I use an app called "mark unread" that does it. I have to go into the app, it asks me to change it to the default, I say yes, then I can mark something unread. When I go back to my normal app, it is now unread there. So the API is indeed there.

**Comment by sm4rk0** [comment]
You can already mark a conversation as unread. Just tap and hold until it's selected, then tap the envelope icon. Also, any message can be locked. That prevents it from being deleted when deleting a conversation containing it, and it puts a small locker next to message's time/date so you can use it as a kind of a bookmark.

**Comment by fresheneesz** [comment]
Huh, you're right. I didn't see that. Great! Thanks!
