### ISSUE TITLE
Searching contact history sms

### ISSUE THREAD

**Issue by nieXas** [moezbhatti/qksms#707]
### DESCRIPTION
If i search to start a conersation for a contact, I select it, but I dont see the previous messages.

### STEPS
1. Steps
2. to 
3. reproduce
4. the 
5. issue.

### EXPECTED
Once I select a contact, I should see my lrevious messeges.

### OBSERVATIONS
I get an empty new message screen

**Comment by sm4rk0** [comment]
You didn't enter precise steps to reproduce, but I suppose they are:
1. Start new conversation (tapping the "+" button)
2. Type part of recipient's name in "Enter recipients" field
3. Select a recipient's phone number

Current behavior seems correct to me, as you can enter more recipients at any time, so anything else than an empty message screen would be unfeasible to code. It's the same/similar scenario as if you were composing a new email in an email client (vs. replying to an existing email thread).

**Comment by moezbhatti** [comment]
This has been implemented in QKSMS 3.0
