### ISSUE TITLE
Can't Set QKSMS as Default Texting app on Republic Wireless

### ISSUE THREAD

**Issue by dafechtor** [moezbhatti/qksms#710]
### DESCRIPTION
I recently installed QKSMS on a Moto G4 running Android v. 6.0.1. The cellular provider I'm using is Republic Wireless, an MVNO that uses an unnamed GSM network as its underlying carrier (probably T-Mobile; possibly AT&T), and that, like Project Fi, automatically defaults to Wi-Fi connections whenever possible, seamlessly transitioning from one to the other as necessary to maintain the best possible connection.

For whatever reason, I'm not able to set QKSMS as my default SMS app without generating a notification that reads, "Change messaging app. Your messaging app does not work with Republic Wireless. Please use Google Messenger."  Despite that message, I am able to send texts using QKSMS, and if I open QKSMS, I can see all the texts that I've received using Messenger.

It's not a matter of Republic Wireless not allowing *any* alternative SMSs. A friend suggested that I install chompSMS as a test, and, sure enough, I *was* able to set that app as my default messaging app even though I can't do so with QKSMS.

I asked the tech-support reps at Republic Wireless what specifications a messaging app need to meet to be allowable as a default app on a phone using their service, but they're not replying. On the other hand, a member of their "community of expert users" suggested that for messaging apps to be compatible with Republic Wireless's system, they need to support for Android's System messaging API, not the Legacy messaging API.  (This is admittedly over my head technically, so for all I know QKSMS already supports Android's System messaging API!)

Is there anything that can be done to make QKSMS acceptable to Republic Wireless?  Looks like a wonderful app--small, powerful, and attractively designed--but it'd be a pain for me to use if I can't set it as my default messaging app.

### STEPS
1) Install QKSMS on any of the cell phones that Republic Wireless has approved as "bring-your-own-phone" devices (https://republicwireless.com/bring-your-own-phone/)
2) Try setting QKSMS as the phone's default SMS app by going to apps-->settings-->configure apps-->Default Apps-->SMS app, and set QKSMS as the default.
3) You'll immediately get the notification mentioned above.
4) Switch back to Messenger as the default app
5) open QKSMS despite its not being the default, and send a text, which will go through fine. You'll also see all the texts that were previously sent/received using Messenger.

### EXPECTED
I expected that I'd be able to use QKSMS as the default app on my phone.

### OBSERVATIONS
None other than stated above. Hope someone can help, as I'd really like to be able to use QKSMS as my default texting app if possible!

**Comment by moezbhatti** [comment]
The new version of QKSMS uses the new messaging APIs. They're not fully implemented as I'm still working on the MMS implementation, but it certainly isn't and won't be using the old APIs moving forward
