### ISSUE TITLE
"enter" sends sms doesnt work

### ISSUE THREAD

**Issue by johnsliderbb** [moezbhatti/qksms#711]
### DESCRIPTION
Changing the enter button behaviour to "send message" directly after installing the app worked. However after using the app for x days this funtionality vanished even if the setting didn't change. So even when "send" is selected pressing enter just will result in a new line.

### STEPS
1. Steps
2. to 
3. reproduce
4. the 
5. issue.

### EXPECTED
Describe the expected behaviour.

### OBSERVATIONS
Describe what happens instead of the expected behaviour.

**Comment by moezbhatti** [comment]
Fixed in QKSMS 3.0
