### ISSUE TITLE
Why app connects to Amazon AWS IPs?

### ISSUE THREAD

**Issue by kelmas** [moezbhatti/qksms#716]
### DESCRIPTION
Application connects to Amazon IPs.

### STEPS
Does not depend on user behavior.

### EXPECTED
SMS app is not expected to send/receive data, esp. to/from AWS.

### OBSERVATIONS
Multiple connections established.

**Comment by alekksander** [comment]
I've noticed this behaviour too, and I'm not one bit less curious.

**Comment by kelmas** [comment]
No response so likely this is unwanted calling-home functionality. I'll take a look at the app code.

**Comment by alekksander** [comment]
did You find anything curious?

**Comment by moezbhatti** [comment]
Sorry for the late response

QKSMS uses Crashlytics, which connects to AWS

https://twitter.com/crashlytics/status/685455519625117700
