### ISSUE TITLE
Performance improvement suggestion

### ISSUE THREAD

**Issue by struggggle** [moezbhatti/qksms#718]
Dear developers,

When loading images, Google suggests us to cache the bitmaps that can be reused, so as to keep a fluid and fast-loading UI.
https://developer.android.com/topic/performance/graphics/cache-bitmap.html
"...... in order to keep a fluid and fast-loading UI you want to avoid continually processing these images each time they come back on-screen. A memory and disk cache can often help here, allowing components to quickly reload processed images."

However, in the code of QKSMS, bitmap caching is not applied:
(1) com.moez.QKSMS.data.Contact.java    getAvatar()
https://github.com/moezbhatti/qksms/blob/master/QKSMS/src/main/java/com/moez/QKSMS/data/Contact.java#L352
I found getAvatar() is invoked directly by:
com.moez.QKSMS.ui.dialog.conversationdetails.ConversationDetailsContactListAdapter.java     getView()
https://github.com/moezbhatti/qksms/blob/master/QKSMS/src/main/java/com/moez/QKSMS/ui/dialog/conversationdetails/ConversationDetailsContactListAdapter.java#L38

(2) com.moez.QKSMS.common.utils.ImageUtils.java    getCircleBitmap()
https://github.com/moezbhatti/qksms/blob/master/QKSMS/src/main/java/com/moez/QKSMS/common/utils/ImageUtils.java#L47
I found getCircleBitmap() is invoked by:
com.moez.QKSMS.ui.view.AvatarView.java     setImageWhenReady()
and setImageDrawable() is invoked by:
com.moez.QKSMS.ui.view.AvatarView.java   setImageDrawable()
setImageDrawable() is invoked by:
com.moez.QKSMS.ui.dialog.conversationdetails.ConversationDetailsContactListAdapter.java   getView()

getView() callbacks are frequently invoked in the UI thread and this means that there will be many bitmap objects being created if we not define a cache to store them. 

For performance considerations, maybe we can define memory cache and disk memory cache to store the bitmap objects. Then app can reuse them instead of creating new bitmap objects continuously. In addition, since image decoding is slow, we can perform these operations in worker threads (e.g., via AsyncTask).

Thanks.

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0!
