### ISSUE TITLE
Decoding image without resizing

### ISSUE THREAD

**Issue by struggggle** [moezbhatti/qksms#719]
Dear developers,

When loading an image, Google suggests us to resize the image before decoding them, so as to save memory resource and avoid OutOfMemory exception.
https://developer.android.com/topic/performance/graphics/load-bitmap.html
" To avoid java.lang.OutOfMemory exceptions, check the dimensions of a bitmap before decoding it, unless you absolutely trust the source to provide you with predictably sized image data that comfortably fits within the available memory "

I noticed that in the following code of QKSMS, image resizing is correctly applied:
com.moez.QKSMS.common.google.ThumbnailManager.java    requestDecode()    (line number:)
https://github.com/moezbhatti/qksms/blob/master/QKSMS/src/main/java/com/moez/QKSMS/common/google/ThumbnailManager.java#L474
com.moez.QKSMS.ui.view.ComposeView.java    doInBackground()   (line number: 919)
https://github.com/moezbhatti/qksms/blob/master/QKSMS/src/main/java/com/moez/QKSMS/ui/view/ComposeView.java#L919

However, in the code below, images are decoded directly without resizing:
(1) com.moez.QKSMS.data.Contact: android.graphics.drawable.Drawable.java   getAvatar()  (line number: 352)
https://github.com/moezbhatti/qksms/blob/master/QKSMS/src/main/java/com/moez/QKSMS/data/Contact.java#L352

(2) com.moez.QKSMS.data.ContactHelper.java    getBitmap()   (line number: 186)
https://github.com/moezbhatti/qksms/blob/master/QKSMS/src/main/java/com/moez/QKSMS/data/ContactHelper.java#L186

I am curious about the latter cases. Why these methods do not resize images? Are these images all of small sizes? Do you think they will affect QKSMS's performance?

For the images to be displayed, in many cases, they are larger than required. Because the bitmap display in an app is memory consumption, maybe we should resize the images before decoding them, which can reduce memory overhead and help make app more smooth in user interaction.

Thanks.

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0, as the app now uses Glide for image loading, which handles resizing for us!
