### ISSUE TITLE
Receiving each SMS twice

### ISSUE THREAD

**Issue by Janaue** [moezbhatti/qksms#720]
### DESCRIPTION
Each SMS appears twice with version 2-7-3. Same thing on version 2-7-1 from fdroid

like here
https://github.com/moezbhatti/qksms/issues/600

**Comment by fantasio31** [comment]
Same situation for me on Xiaomi Redmi 3 with global ROM (Android 5.1.1).

**Comment by fantasio31** [comment]
Same situation for me on Xiaomi Redmi 3 with global ROM (Android 5.1.1).

**Comment by sm4rk0** [comment]
Duplicating issues does not help in solving the problem.
If you have the same problem as described in an existing issue, then don't create a new one. Just comment on the existing issue, if you can some useful information except from "me, too". For example: the version of QKSMS, the version of Android, phone model,...
