### ISSUE TITLE
Call from conversation calls to "null"

### ISSUE THREAD

**Issue by nightmercury** [moezbhatti/qksms#723]
### DESCRIPTION
Call from conversation calls to incorrect number and contact called "null".  

### EXAMPLE
Call from conversation  does not go through because number is either incorrect or empty.  This happens for some contacts, calling from some contacts works ok. 

### STEPS
1. Open conversation 
2. Press call/phone button 
3. Observe 

### EXPECTED
Calling to the conversation contact

**Comment by Lucentio** [comment]
I am also getting this problem, so far in 100% of attempts, call fails as number is shown as null. The phone is a ZTE Axon 7 Mini running 6.0.1

**Comment by moezbhatti** [comment]
This should be resolved in QKSMS 3.0
