### ISSUE TITLE
MMS picture quality very poor

### ISSUE THREAD

**Issue by kalenpw** [moezbhatti/qksms#724]
### DESCRIPTION
Every MMS image I received is compressed to very low quality. I've gone into settings and set the Maximum MMS attachment size to unlimited which did not resolve it. 

### STEPS
1. Send picture message to my phone
2. Examine quality of said picture message

### EXPECTED
High quality or slightly lower quality images than the original.

### OBSERVATIONS
Very low quality images. 

Image received through QKSMS [image](http://i.imgur.com/WYLFXQG.jpg)
Image received through Samsungs sms app [image](http://i.imgur.com/uz01BWw.jpg)

**Comment by moezbhatti** [comment]
Receiving MMS should now retain the original quality in QKSMS 3.0

**Comment by otede** [comment]
Still an issue. I don't consider 40 KB or less to be an acceptable image for images received via MMS. Images received via Google Messages are 160 KB or more.

**Comment by wsdfhjxc** [comment]
I can confirm. Despite selecting "2000KB" or "No compression" option, pictures are still heavily compressed. No such problem with Textra, but I'd rather use an open source app, so it's a shame.
