### ISSUE TITLE
Removing other notifications

### ISSUE THREAD

**Issue by dev-farmaan** [moezbhatti/qksms#725]
### DESCRIPTION
All message notification get cleared when even one of them is swiped

### STEPS
1. Receive a message from sender X
2. Receive a message from sender Y
3. Don't open the app
4. Swipe the message notification from the notification shade for sender X to clear it
5. Message from both the sender gets cleared from notification shade

### EXPECTED
Notification from the person whose notification is swiped should be cleared only

### OBSERVATIONS
Notification for all the message gets cleared

**Comment by sm4rk0** [comment]
Duplicate of #356
