### ISSUE TITLE
Feature request: view additional lines for editing long text message

### ISSUE THREAD

**Issue by taid26** [moezbhatti/qksms#726]
### DESCRIPTION
When I write a text, only three lines of text are displayed.

### Feature request.

Handcent app has feature of opening a dialogue box which enables user to see multiple lines of a long text as it is being written  - this would be helpful in QKSMS for those who write long text messages.
As an alternative the option to have a larger editing screen would be appreciated - seeGitHub #686#

  At the moment only three lines are visible and nimble fingers are needed to scroll up or down.

**Comment by lucyyu24** [comment]
duplicate #394
