### ISSUE TITLE
Can't send/receive MMS 

### ISSUE THREAD

**Issue by tclarkey** [moezbhatti/qksms#731]
### DESCRIPTION
I have a S7 edge on Verizon Nougat 7.0.  I can't receive/send group messages.  I have clicked on the message to auto configure based on VZW configuration but it doesn't appear to do anything.

### STEPS
See OBSERVATIONS

### EXPECTED
I expect the message to go to the group and I expect to receive group messages.

### OBSERVATIONS
When I start a group conversation from another phone (adding myself as a recipient) I don't receive the message.  If I start a group conversation, none of the recipients receive the message.

**Comment by ObviouslyGreen** [comment]
Been having this problem as well, using LG G4 using Marshmallow

**Comment by itd-corp** [comment]
ObviouslyGreen Really? I see source code is commented..

**Comment by moezbhatti** [comment]
This should be resolved in QKSMS 3.0, as it now uses the official MMS APIs and does not require configuration of the APN settings
