### ISSUE TITLE
Clicking the Call icone do nothing

### ISSUE THREAD

**Issue by RANIERO1** [moezbhatti/qksms#732]
I've Huawei p9 nougat stock firmware unroot when i try to Call from qksms clicking on the Phone button in the messages view the app open the phone app, do not even paste the phone, just open the phone app,exdialer, don't start the call nor even paste the phone so i have to close exdialer go back to qksms read the phone number open exdialer and write it manually to call

**Comment by MIC132** [comment]
I have the same problem.
On Huawei Nova, with the EMUI 5.0 update.

**Comment by RANIERO1** [comment]
Me too in emui 5, also no draft can be saved everytime i go out from the app for seconds everything unsent got deleted. Still more than 1 month bug unfixed

**Comment by maxsin** [comment]
I too can reproduce this on Huawei P9 Lite (2017) with MUI 5.0

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0
