### ISSUE TITLE
Enhancement request: Implement text preprocessor

### ISSUE THREAD

**Issue by loolooyyyy** [moezbhatti/qksms#734]
### DESCRIPTION
Some helpful text messages have useless advertisement appended/prepended to them. A text preprocessor would help to remove them.

### STEPS TO IMPLEMENT
1. Create text preprocessors such as replace by regex, remove n-th line, ...
2. Call the preprocessor from the right place (message receiver?)
3. Create the UI options
4. Decide whether if it must be configurable for each address? 
I'd like to remove the text <you can have a free apple pie> when it's appended to my balance inquiry, but most definitely not when it's from my sister. This only applies if I have the operators number and my sister's number both in the contacts list. If I do not have the operators number in the contact list (which I think is always the case?) it can be simply a <ignore for contacts> option.
5. Add a caution: the text will be permanently removed. (I'd think it's too much trouble storing the original text message).

**Comment by moezbhatti** [comment]
This is an interesting suggestion, but at least in the near future it's quite out of scope of what our development plans are. I'll be closing it for now

**Comment by loolooyyyy** [comment]
I've already implemented that in qksms but it was messy, so I removed the fork. The changes are currently in a cloned repo in my account and I'm still working on it, then I can make a nice PR. Merge if you see the changes fit.

**Comment by moezbhatti** [comment]
Awesome, thanks @loolooyyyy
