### ISSUE TITLE
Support for "Google Voice" text (SMS/MMS) messaging

### ISSUE THREAD

**Issue by htartisan** [moezbhatti/qksms#737]
### Feature request

Support for "Google Voice" text (SMS/MMS) messaging functionality.  

### Description

I (like other people I know) use my "Google Voice" phone number as my primary contact number for calls and text messages.  Up until recently, I have been using Google Hangouts as my texting app (SMS/MMS) because it allowed me to send and receive messages BOTH through the text messaging features provided by my carrier (Sprint) AND through the TCP/IP based Google Voice service.  (Note: I have my Google Voice number set as the default to send messages from, but the Google Hangouts app allows me to select standard SMS when a new conversation is created.)  I really liked having both messaging features in one app!

UNFORTUNATELY, Google has decided to remove SMS/MMS functionality from Google Hangouts.  To make matters worse, there don't seem to be any other apps that support both SMS/MMS and Google Voice messaging.

**Comment by jordanade** [comment]
A partial solution that would by itself solve an large existing problem for Google Voice users would be to allow a checkbox in settings where outgoing SMS messages are sent using Google Voice instead (say, using this code at https://github.com/Ratief/XVoicePlus/blob/master/app/src/main/java/com/runnirr/xvoiceplus/gv/GoogleVoiceManager.java). 

(For now) the user would continue to use the Google Voice app as the primary interface, but this feature would essentially take all of the various mechanisms of sending SMS (voice control, smart watch, etc.) and make them compatible with Google Voice.

**Comment by moezbhatti** [comment]
Don't think I'll be adding support for this, as it makes the implementation of message sending much more complicated and it's not something that very many people have asked for. Open to changing my mind if it becomes much more requested in the future
