### ISSUE TITLE
Cannot send images

### ISSUE THREAD

**Issue by davisdude** [moezbhatti/qksms#738]
### DESCRIPTION
Using the stock messenger app on Samsung (Messenger), I could send images fine. While trying out QKSMS, no images can be sent from any method. They just remain stuck with the message `Sending...` underneath. Text messages sent after the image go through, but still not the image.

### STEPS
I have tried various methods without success:

#### From Screenshots
1. Take a screenshot,
2. From the screenshot, select "Share", then choose a contact.
3. Send the message. The message gets stuck in `Sending...`

#### From the app
1. Open a conversation
2. With no text in the conversation, click the "plus" button on the right-hand side.
3. Select a picture from the gallery (taking a picture also fails) and send it.

### EXPECTED
The picture will be sent to the desired contact and received.

### OBSERVATIONS
The message is never sent and just says "Sending..." in the bottom underneath the message.

### Additional information:
- Samsung Galaxy S7 on a Verizon plan.
- Tried with Wifi enabled and disabled, fails both ways
- Always show time message is sent/received is enabled

#### Update:
After switching back to the stock messenger app, all images sent almost immediately.

If I try to edit the message with the picture (while it's still sending), the image is lost, but any text stays.

**Comment by mpkosewski** [comment]
I have same issue. I used this app before but forgot how slow and laggy it gets not to mention makes my S6 super hot

**Comment by CloneMMDDCVII** [comment]
If it stays stuck on sending, it means your configuration is wrong.

Most carriers require a cell data connection in order to send/receive mms, so enabling wifi is irrelevant.

The Automatic Configure MMS was wrong for me, although on a different carrier.
The only thing I had to do was to remove the proxy field from the configuration for it to work with me.

**Comment by rcspam** [comment]
I'm on a Galaxy S3... Same problem happened for me, no images come on the recipient phone, only the text...Nothing say me that the image is not send or receive... And this is the case since several months.

**Comment by noconflicts** [comment]
I just loaded QKSMS on a Galaxy s7 (Verizon). Having the same issue sending or forwarding images.

**Comment by moezbhatti** [comment]
Working on fixing this in QKSMS 3.0, I'll be using the more recently available APIs which the current version of QKSMS does not make use of

**Comment by moezbhatti** [comment]
Version 6 now supports sending MMS

**Comment by davisdude** [comment]
When should this updated version be available on the play store? Currently, the last update was September 2016.
