### ISSUE TITLE
Can't send/receive MMS with Viettel mobile

### ISSUE THREAD

**Issue by majorcoderx** [moezbhatti/qksms#739]
I don't known on your telecom that can active. 
I'm try with my telecom network in my country, it not active.

**Comment by CloneMMDDCVII** [comment]
The Automatic Configure MMS was wrong for me, although on a different carrier.
The only thing I had to do was to remove the proxy field from the configuration for it to work with me.

**Comment by moezbhatti** [comment]
QKSMS 3.0 no longer required manual entry of MMS APN settings, this issue should be resolved in the next release
