### ISSUE TITLE
MMS doesn't work on AT&T

### ISSUE THREAD

**Issue by srcreigh** [moezbhatti/qksms#74]
Getting reports that AT&T simply doesn't work on QKSMS. I'm leaving this here so we can add custom reporting code and send it to people to report back to us.

**Comment by CptanPanic** [comment]
I just wanted to add that I am on cricket, which uses the att network also and was unable to get mms to work. Note that textra does work for me, but would love to help get QKSMS to work.

**Comment by Samcfuchs** [comment]
I use ATT and I have had no problems with MMS. I was able to send a photo to a friend with no problems.

**Comment by littleTrex** [comment]
I have AT&T as well, and I was able to send photos a week ago, but now I can't send them.

I have the Moto G 2015.

**Comment by CptanPanic** [comment]
I just tried for with latest build on cricket and was not able to send mms.

**Comment by littleTrex** [comment]
Is there any way we can submit debug logs?
My MMS seems to be working now again.

**Comment by cobraguy** [comment]
I'm unable to send or receive MMS on my Galaxy S5 with AT&T.

**Comment by Samcfuchs** [comment]
I think photos are now kind of hit or miss, and group texting is really unusable.

**Comment by 2016rshah** [comment]
I'm on a galaxy s4 and group texting is, like @Samcfuchs said, completely unusable.

**Comment by cobraguy** [comment]
I have new information to contribute. I don't keep my data on, so I have the automatic data setting checked. If I turn on my data, MMS will work. However, I won't get a notification of the new message unless I am in the conversation of the person who sent the MMS.

**Comment by cobraguy** [comment]
If I decide to let Qksms turn my data on and off automatically, then an MMS won't send unless I receive one and vice versa.

**Comment by Samcfuchs** [comment]
No MMS support on ATT as far as I can see. That includes group messages and photos. Until this is fixed, I will not be using this app. I really want to, but I can't until this is fixed.

**Comment by gappleto97** [comment]
I'm an AT&T. Group chats are working, but the moment I try to add an attachment nothing sends.

**Comment by gappleto97** [comment]
Any update on this? Had to switch back to Textra for the time being, but I'd much rather use an OSS.

**Comment by moezbhatti** [comment]
Unfortunately not. Not much work done on MMS recently

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0 Preview 6, as the app now uses the official system APIs for sending MMS

**Comment by niftylettuce** [comment]
@moezbhatti is this released to F-Droid yet? I still have issues with this

**Comment by niftylettuce** [comment]
@moezbhatti see this thread here https://issuetracker.google.com/issues/37074617#comment17 - I believe this is due to VPN.  Can you make a "legacy" vs "system" setting in QKSMS by chance?
