### ISSUE TITLE
Support MMS please

### ISSUE THREAD

**Issue by majorcoderx** [moezbhatti/qksms#740]
### DESCRIPTION
I don't send and receive MMS, and when I open source, I see source is commented.

**Comment by themelisx** [comment]
Probably you have change targetSDK to 23 and above.
From api 23 and later, startUsingNetworkFeature throws exception because does not supported.
I did'nt find any solution yet

**Comment by xiaoruby** [comment]
I didn't find neither. It's so hard.

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
