### ISSUE TITLE
Class android.text.format.Time has been deprecated since API 22

### ISSUE THREAD

**Issue by frankFic** [moezbhatti/qksms#742]
Hi!

I noticed that class android.text.format.Time is used in QKSMS at multiple places (I just list some locations I found, may miss some):
[line 169, 173, 180, etc. in NetworkPolicyManager.java](https://github.com/moezbhatti/qksms/blob/835e2659b228e27378d4d8672840653a55052969/QKSMS/src/main/java/android/net/NetworkPolicyManager.java)
[line 865 and 867 in MessageUtils.java](https://github.com/moezbhatti/qksms/blob/835e2659b228e27378d4d8672840653a55052969/QKSMS/src/main/java/com/moez/QKSMS/common/utils/MessageUtils.java#865)

This class has been deprecated since API 22 due to multiple reasons (see https://developer.android.com/reference/android/text/format/Time.html).

Although the class may not cause problems for now, I still think it would be better to use other alternatives to avoid future bugs.

**Comment by moezbhatti** [comment]
Removed for QKSMS 3.0
