### ISSUE TITLE
QKSMS does not fill the screen on the Samsung Galaxy S8

### ISSUE THREAD

**Issue by elongpre** [moezbhatti/qksms#743]
### DESCRIPTION
QKSMS does not fill the screen on the Samsung Galaxy S8

### STEPS
1. Have a Samsung Galaxy S8
2. Open or switch to QKSMS

### EXPECTED
The app should fill the screen except for the Android navigation buttons at the bottom of the screen 

### OBSERVATIONS
There is a small strip across the top and bottom of the app where you can see the the last thing on the screen before opening or switching to QKSMS. 

Here you can see the top and bottom edge of my home-screen, including cut off labels for the bottom-most apps:
![18471387_10154847794309440_615577097_n](https://cloud.githubusercontent.com/assets/1074802/26027990/59990118-37dd-11e7-9e39-ba7a4a991dcd.png)

**Comment by geomtech** [comment]
That is normal, S8 use a different resolution, so QKSMS have to add the good resolution.

Google docs help to resolve that, they send recently something to developers to resolve this

**Comment by apriendeau** [comment]
As of the new Samsung update, it will ask you at the bottom to fill this screen and it should fix this issue.

**Comment by BretzJohnny** [comment]
Pixel XL 2 has the same issue as of the time of this post.

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0
