### ISSUE TITLE
Feature Request: Block all SMS from contacts not in addressbook

### ISSUE THREAD

**Issue by aqeeliz** [moezbhatti/qksms#745]
### DESCRIPTION
Add an option to block all SMS by default, unless they are from someone in address book.

### OBSERVATIONS
SMS spam is a big issue here. Currently there is an option to block numbers, but that still means getting few spam messages in inbox everyday. An ability to block all unknown numbers (combined with the already existing ability to block numbers) would make a completely spam-proof SMS app.

**Comment by lucyyu24** [comment]
duplicate #664

**Comment by azzamsa** [comment]
what is the status of this feature ?, is this feature already implemented ?.

I really need this feature, there are some proprietary messaging app out there, with no privacy for users. so I will stick with Qksms. 

here, spam is the big issue, I got more than 10 spam sms everydays. so this feature is all what I need.

**Comment by emrecio** [comment]
*bump* just installed it per CallControl recommendation, and there's no option to block EVERYONE not in contacts list

**Comment by bjrne** [comment]
I disagree that this is a duplicate @lucyyu24. #664 is about notifications, this issue (as I understand it) is about blocking messages completely, which QKSMS also supports in some form.

With the help of the "Should I answer" connection, I was able to block all number which are not in the address book, however that also blocks all calls of those numbers. There was no way to use it for the sms rules without it blocking calls, which I still want to receive. So unfortunately, this was not an option, although the sms blocking worked perfectly.

So either an allowlist, or at least an option to block all messages from unknown numbers would be awesome.
