### ISSUE TITLE
Widget - update after new SMS

### ISSUE THREAD

**Issue by raduvatav** [moezbhatti/qksms#749]
### DESCRIPTION
Widget isn't updated (refreshed) after SMS sent.

### STEPS
Send SMS either from the widget (Screenshot_01) or from the main app (Screenshot_03).

### EXPECTED
The widget updates after SMS sent and contains the sent SMS, as seen in Screenshot_02 and Screenshot_04 in the "Messaging" widget.

### OBSERVATIONS
The widget isn't updated after SMS sent, as seen in Screenshot_02 and Screenshot_04 in the "Conversations" (qksms) widget.

Notes: 
- I used qksms to send both SMS "Test" and "Test2". qksms is set as the default messaging app.
- I don't have gapps installed

Screenshot_01:
![screenshot_01](https://user-images.githubusercontent.com/9903511/27725281-425ab264-5d7e-11e7-87d4-c2fb2a8a0a42.png)

Screenshot_02:
![screenshot_02](https://user-images.githubusercontent.com/9903511/27725282-426019b6-5d7e-11e7-8377-e27554e6b535.png)

Screenshot_03:
![screenshot_03](https://user-images.githubusercontent.com/9903511/27725284-426d034c-5d7e-11e7-9fda-9fa9d7009816.png)

Screenshot_04:
![screenshot_04](https://user-images.githubusercontent.com/9903511/27725280-4258db7e-5d7e-11e7-8802-9d7d16b25e64.png)

Sysinfo:
![screenshot_05_sysinfo](https://user-images.githubusercontent.com/9903511/27725283-426b0bc8-5d7e-11e7-87f0-d404f89e4a7f.png)

**Comment by moezbhatti** [comment]
Fixed in bb8b2e6cdc29d267e18a43b37ef4ce63ede1b3d5
