### ISSUE TITLE
GIF keyboard support

### ISSUE THREAD

**Issue by smith901** [moezbhatti/qksms#751]
`This text field does not support GIF insertion from the keyboard.` toast message.
Reproduce by starting message, pressing emoji key, GIF Button has line through.

Please add GIF insertion so that we can fully text and me specifically get away from stock and Google apps.  Option seems to be there, just not implemented or supported on my device: Blu Vivo XL2, Android Version 6.0, SDK Version 23, Kernel 3.18.19.
![screenshot_20170711-124351](https://user-images.githubusercontent.com/26862709/28082273-a7423618-6637-11e7-9c0e-f7e47bb0fa71.png)

**Comment by tparrott** [comment]
Agreed, I can't use this app without gif support. Any workaround appreciated.

**Comment by moezbhatti** [comment]
For reference: https://stackoverflow.com/questions/48108889/gboard-enable-gif-insertion-on-edittext
