### ISSUE TITLE
Feature rq: Activity stack limit

### ISSUE THREAD

**Issue by nobuyukinyuu** [moezbhatti/qksms#753]
Hi,

I love using qksms and have had it as my default SMS client for several months now. However, I noticed that overtime when using it it has become very unresponsive and can sometimes take a long time to switch to the task.  

Often times this coincides with hitting the back button returning me to the same conversation multiple times as well as other conversations which I might have closed out of or moved away from earlier.  I don't know if this is intended Behavior, but there doesn't seem to be a limit to how large the activity stack can be.

Regardless of whether or not this is a bug, it seems like a workaround solution can happen if the app has some kind of hard limit to the amount of activities it can generate on that stack.  Preferably, I'd like to be able to have the back button always return me to the conversation list if I'm in a conversation thread.

Thanks for reading!

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0
