### ISSUE TITLE
Mms not sending on Verizon s6

### ISSUE THREAD

**Issue by TheLostAndroidUser** [moezbhatti/qksms#755]
### DESCRIPTION
Used automatic and manual apn setting but mms still not going through

### STEPS
1. Open a conversation 
2. Press +
3. Add picture
4. Send 

### EXPECTED
Picture sends 

### OBSERVATIONS
Pictures do not send

**Comment by CloneMMDDCVII** [comment]
The Automatic Configure MMS was wrong for me, although on a different carrier.
The only thing I had to do was to remove the proxy field from the configuration for it to work with me.
