### ISSUE TITLE
Notification doesn't show on lock screen.

### ISSUE THREAD

**Issue by russianspy1234** [moezbhatti/qksms#757]
### DESCRIPTION
Been using this app for a few days and am having an issue.  For some reason, notification do not show on my lock screen.  They show up in the notification drawer when the phone is unlocked just fine, but don't show on lock screen.  Using Honor 8 on Android 6.0.

### STEPS
1. Receive text message.
2. Press power button.

### EXPECTED
Notification on lock screen should show when message is received and has not been read.  Should show either sender, or sender and message depending on privacy.

### OBSERVATIONS
No notification shown on lockscreen for received text.  Other notifications (e.g. Pushbullet) show up fine.

**Comment by CloneMMDDCVII** [comment]
The Automatic Configure MMS was wrong for me, although on a different carrier.
The only thing I had to do was to remove the proxy field from the configuration for it to work with me.

**Comment by Tapemaster21** [comment]
This is probably because if you leave the app focused/open, and the screen goes off or you turn the screen off, then you do not receive notifications. It's a peculiar bug.

**Comment by moezbhatti** [comment]
This is resolved in QKSMS 3.0
