### ISSUE TITLE
notification LED not working on Huawei P9 Lite (Android 7.0)

### ISSUE THREAD

**Issue by prohde** [moezbhatti/qksms#758]
### DESCRIPTION
I am running an Huawei P9 Lite with Android with EMUI-Version 5.0 and Android 7.0.
When I recieve a message I can hear the notifcitation sound but the notification LED is not blinking.

### STEPS
1. recieve message
2. wait for LED to blink

### EXPECTED
The LED should blink.

### OBSERVATIONS
The LED does not blink.

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0
