### ISSUE TITLE
App icon not showing unread message count on Huawei P9 Lite (Android 7.0)

### ISSUE THREAD

**Issue by prohde** [moezbhatti/qksms#759]
### DESCRIPTION
I am running an Huawei P9 Lite with Android with EMUI-Version 5.0 and Android 7.0 and QKSMS is set a standard messaging app.
When I recieve a message the App icon does not get an unread messages counter.

### STEPS
1. recieve message
2. take a look at the App icon

### EXPECTED
The App icon should get an unread messages counter.

### OBSERVATIONS
An unread messages counter is added to the former messaging app.

**Comment by moezbhatti** [comment]
Merging with #311
