### ISSUE TITLE
Not Sending SMS via Samsung Galaxy S7

### ISSUE THREAD

**Issue by joyyesheart** [moezbhatti/qksms#761]
### DESCRIPTION
All attempts to send SMS to someone in my Contacts fail, even after repeated attempts.

### STEPS
1. Click icon for draft new message
2. Draft it (a short one)
3. App says it's "sending ...." which continues for a minute or two
4. Eventually, the app gives me an alerts saying the attempt to send the message "Failed."
5. Repeated attempts to send or re-send yield the same failed result.

#### EXPECTED
An SMS app should both send and receive SMS messages easily and quickly. And at all.

### OBSERVATIONS
Send the message.
Give info on why it failed to send.
Offer a Help button/function.
Offer a User's Manual or Tutorial for Troubleshooting. 
It shouldn't be so hard to perform such a basic function.

**Comment by joyyesheart** [comment]
Apparently, the SMS was finally sent, although I received no notification from the app that it did.
When the person replied and I opened the conversation, her response was there, but there was no record or evidence of the original sms I'd sent her.

**Comment by joyyesheart** [comment]
I just sent an SMS text to another phone number I own, as a test. The text was received right away, even while the QKSMS app was still "sending..." Eventually, in spite of having received the text at my other phone number, the QKSMS app on to phone used to send the text notified me the attempt to send the message had "Failed."

**Comment by nobuyukinyuu** [comment]
Samsung enhanced text services has played not-nice with QKSMS for me in the past.  Maybe try disabling the service and waiting 24h and seeing if the problem persists?

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0
