### ISSUE TITLE
Project Fi configuration 

### ISSUE THREAD

**Issue by resrzfl** [moezbhatti/qksms#764]
### DESCRIPTION
Auto Configuration on Pixel w/Project Fi after not receiving some texts. 

### STEPS
n/a, just auto configuration 

### EXPECTED
Auto config to specific or various service providers to receive texts. 

### OBSERVATIONS
Have installed a new SIM and QKSMS pop-up noted need to auto config.  It set Sprint as service, but Project Fi switches btw Sprint, TMo, and US Cellular. Does QKSMS auto reconfig when the service switches automatically?  If not, may explain missing texts. Thanks in advance for assistance.

**Comment by moezbhatti** [comment]
This should be resolved in QKSMS 3.0, as it now uses the official MMS APIs and does not require configuration of the APN settings
