### ISSUE TITLE
Is QKSMS dead?

### ISSUE THREAD

**Issue by BarkBarkBarkBarkBark** [moezbhatti/qksms#765]
Last update was on early 2016. It's half of 2017 and (as a daily user) I must ask - what the hell is going on? Is this project dead, and I must start looking for an alternative? 
Need clear answer.

**Comment by moezbhatti** [comment]
not dead! we did halt development on the project for about a year, but we're currently in the process of rebuilding the app. we're expecting to push out the new release sometime in september
