### ISSUE TITLE
Use of deprecated Resources.getDrawable() 

### ISSUE THREAD

**Issue by frankFic** [moezbhatti/qksms#766]
Hi there,

I just found that QKSMS is still using Resources.getDrawable() on [line 477 in ThemeManager.java](https://github.com/moezbhatti/qksms/blob/835e2659b228e27378d4d8672840653a55052969/QKSMS/src/main/java/com/moez/QKSMS/ui/ThemeManager.java#L477) and [line 260 in SwipeBackLayout.java](https://github.com/moezbhatti/qksms/blob/835e2659b228e27378d4d8672840653a55052969/QKSMS/src/main/java/com/moez/QKSMS/ui/SwipeBackLayout.java#L260).

This API has been deprecated since Android 23 and I have found that you have already used ContextCompat.getDrawable() at other locations in QKSMS.
I think it's better to replace all the usages of this deprecated API.

Thanks!

**Comment by moezbhatti** [comment]
Fixed for QKSMS 3.0
