### ISSUE TITLE
app hanged when searching conversation

### ISSUE THREAD

**Issue by gbmaniac** [moezbhatti/qksms#768]
### DESCRIPTION
App hanged if I empty search bar after filling it.

### STEPS
1. Click the search icon
2. Enter any search filter
3. Empty search bar (backspace all the way)
4. Hang

### EXPECTED
Search bar should be able to be filled and emptied numerous time.

### OBSERVATIONS
The application hanged.

**Comment by sm4rk0** [comment]
I can confirm.

**Comment by moezbhatti** [comment]
Search has been completely re-written in the new update, so I'll close this for now
