### ISSUE TITLE
QKSMS closes completely when swiped from task manager

### ISSUE THREAD

**Issue by Sytred** [moezbhatti/qksms#769]
When QKSMS is closed by swiping it away in the task manager, it doesn't run in background and is unable to receive any message until opened again. The messages that were not received won't ever be received, even when the app is opened again. (Wiko Ufeel Prime)

1. Open QKSMS
2. From your task manager, swipe the app to one side in order to close it.

QKSMS would normally stay open in background and be able to check for new messages.

Instead, new messages are never received.

I don't know if this is specific to my phone, but I think so because it is quite annoying and more people would be complaining. I have the (bad) habit of "closing" all apps from the task manager, and with QKSMS I miss many messages...
The problem was seemingly "solved" by adding hideFromRecents:true to the manifest (by the way, am I allowed to do so, since I don't redistribute the apk ? I do think I won't receive updates though, but anyway I needed to fix this) ; then QKSMS doesn't show in the task manager and hence can't be closed. There are probably other ways of doing this more properly, but I've never actually done any Android programming, so any fix that worked quick was fine for me.

I just wanted you to be aware of that. Thanks for reading :) And if I'm not allowed to do this, please tell me, I'll uninstall the apk, delete all files and install the official Google Play app again.

**Comment by moezbhatti** [comment]
This should no longer happen in QKSMS 3.0
