### ISSUE TITLE
Icon colour change bug

### ISSUE THREAD

**Issue by eehpcm** [moezbhatti/qksms#770]
Changing the icon colour kills QKSMS stone dead and deletes the icon from the launcher.  Takes around a second or so for QKSMS to realize it's dead.  QKSMS is truly removed from the launcher, there's no active spot with an invisible icon, just a dead space.

QKSMS cannot be added back to the launcher unless the icon colour is reset to the default (white) colour first.

This occurs using the Nova launcher with QKSMS in the dock.  I also tried it with QKSMS on the home page but not in the dock.  The first time I tried it outside the dock I got a pop-up telling me it had died and did I want to restart it, but when I tried to restart it nothing happened.  The other times I've tried it with QKSMS outside the dock I didn't get that pop-up.  Note that I've only tried it outside the dock four times (and got the pop-up once) and tried it in the dock *many* times and not seen the pop-up.

Note that I'm using Jina as my drawer and use it to add QKSMS to the home screen.  This may be why nothing seems to happen when I try to add non-white QKSMS to home screen, but is more likely down to Nova itself rejecting the attempt, resulting in Jina failing to confirm that QKSMS has been added to home screen (because it hasn't).

May be related to #395 and/or #141.  Or not. :)

This is on Android 7.1.1.  QKSMS 2.7.3 (I signed up for beta last night but playstore hasn't caught up yet).  Nova 5.3.  Jina 3.0.7ga881

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
