### ISSUE TITLE
Creates a new conversation from call history

### ISSUE THREAD

**Issue by maxsin** [moezbhatti/qksms#771]
### DESCRIPTION
When sending a message to a contract from the call history it creates a new conversation but without the contact information.

### STEPS
- Display the call history list
- Tap & Hold a contact and select Send message
- New QKSMS screen is displayed but without contact information 
- Asks for Sender when hitting the send button (which makes sense since there is no contact displayed)

### EXPECTED
New conversation from call history to be initiated.

### OBSERVATIONS
The above mentioned scenario can not be reproduce if the contact selected already has a conversation in the QKSMS app.

QKSMS version: 2.7.3
DEVICE version: HTC M7 with Android 5.0.2 and Huawei P9 lite (2017) with Android 7.0

**Comment by moezbhatti** [comment]
This seems to be fixed in QKSMS 3.0
