### ISSUE TITLE
Defining a set of Quick Responses issue

### ISSUE THREAD

**Issue by maxsin** [moezbhatti/qksms#773]
### DESCRIPTION
When defining a set of Quick Responses, each time, a new EMPTY value is set for 1st. 
All the others values entered are shifted down. 

### STEPS
- Go to defining set of Quick Responses screen
- Try to enter a value for the first box
- Save and return
- First box is empty, all the other are shifted down with one position.

### EXPECTED
All item can be saved, no matter the position.

### OBSERVATIONS
Maybe introducing a Reorder functionality if user wants to swap positions.

QKSMS version: 2.7.3
DEVICE version: HTC M7 with Android 5.0.2 and Huawei P9 lite (2017) with Android 7.0

**Comment by moezbhatti** [comment]
Merging with #455
