### ISSUE TITLE
Multiple Conversations - Same Contact Though

### ISSUE THREAD

**Issue by getfoundational** [moezbhatti/qksms#777]
After installing QKSMS and opening it, I have several conversations that show up where it is the same person I am texting with, but some of the texts show in one conversation and some show in another one.

I used SMS Backup and Restore to download the SMS information to XML and I can see where some of the messages show the contact's number in the a variety of formats like:
+1 (aaa) bbbcccc
+1aaabbbcccc
(aaa) bbbcccc

I am not 100% sure what caused this.  I did install a contact number formatting app that did appear to clean up and standardize my contact's numbers, but that does not seem to have helped this.

This seems to have the effect of splitting the conversations with the same person in to multiple threads/conversations within QKSMS.

Worth noting, Textra and Google Messages do not exhibit this behavior.  They both show all of the messages under one conversation with that contact.

Is there something that can be done with QKSMS to have it work in the same way, or perhaps have an option available to "clean up" the text message database to allow it to then display things in this same way?

Thank you.

**Comment by moezbhatti** [comment]
This should be addressed in QKSMS 3.0

If it occurs again, please feel free to reopen!
