### ISSUE TITLE
Notification badge is shown for blocked conversations

### ISSUE THREAD

**Issue by bigftguy** [moezbhatti/qksms#780]
### DESCRIPTION
Blocked conversations are marked as unread and shows badge icon counter on the app icon. Even if you manually open each blocked conversation and turn off notifications there they are still displayed on unread counter badge. Samsung Galaxy S8.

### STEPS
Receive new message to blocked conversations (spam messages are received from the text name sender, not number, if that matters).

### EXPECTED
Not showing badge counter for blocked conversations (may be set it toggle).

**Comment by moezbhatti** [comment]
Merging with #311
