### ISSUE TITLE
Notification turned off icon changes only after app restarted

### ISSUE THREAD

**Issue by bigftguy** [moezbhatti/qksms#781]
### DESCRIPTION
Notification icon in conversations list is shown only after the application is restarted. Galaxy S8

### STEPS
1. Open conversation
2. Turn off notifications for it (touch the button)
3. Go back to conversations list
4. "no notification" icon is not displayed
5.  Restart the application
6.  Icon is displayed in conversation list

### EXPECTED
Icon should be displayed without app restart

### OBSERVATIONS
Icon is displayed in conversation list till the app is restarted

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0
