### ISSUE TITLE
Feature request: show unread counter badge on the app icon for notification turned off conversations

### ISSUE THREAD

**Issue by bigftguy** [moezbhatti/qksms#782]
### DESCRIPTION
When notification is turned off for some conversations (not blocked ones) the badge counter icon is not shown upon receiving the new messages to that conversations, no other notifications are shown also. 

So you will never know (till you open the app) that there are new unread messages.
Instead of that the unread counter badge is shown for new messages in blocked conversations.

**Comment by moezbhatti** [comment]
Merging with #311
