### ISSUE TITLE
Feature request: Use android OS sound\vibration settings

### ISSUE THREAD

**Issue by bigftguy** [moezbhatti/qksms#783]
It would be great if vibration will turn on only when the vibration is turned on in android settings (when notification sound is turned off), so when sound is on - only sound notification is used, when sound is off - vibration.

**Comment by moezbhatti** [comment]
This has been implemented in QKSMS 3.0. More info here: https://plus.google.com/+MoezBhatti/posts/PZiikBCtiNc
