### ISSUE TITLE
No scroll bar in conversations on Galaxy S8

### ISSUE THREAD

**Issue by bigftguy** [moezbhatti/qksms#784]
### DESCRIPTION
No scrollbar is visible in Galaxy S8 when viewing conversations and conversation lists. Only in app settings scrollbar is shown.

### EXPECTED
Scrollbar should be visible so you can understand how many messages you have.

**Comment by sm4rk0** [comment]
Duplicate of #384 and partially of #271.
I hope it's included in upcoming update.

**Comment by moezbhatti** [comment]
The current version of QKSMS doesn't have scrollbars, but they're being added in the next release (along with fast-scroll support)
