### ISSUE TITLE
Freezing during opening on Galaxy S8

### ISSUE THREAD

**Issue by bigftguy** [moezbhatti/qksms#785]
### DESCRIPTION
Sometimes when opening the message app only the keyboard is shown (keyboard at the bottom and nothing above it, just home screen with icons) and after 2-3 seconds the main app window loads above the keyboard. 

### STEPS
Dont know how to reproduce. It happens from time to time.

**Comment by moezbhatti** [comment]
Performance has been drastically improved in the new release, so this should be a non-issue moving forward :)
