### ISSUE TITLE
SwipeBackLayout doesn't show conversationList when swipe or back pressed KITKAT api 19

### ISSUE THREAD

**Issue by omidjoon** [moezbhatti/qksms#787]
when I swipe left to right on kitkat the conversationList doesnt show then after a while it comes up 
![screenshot_1506584500](https://user-images.githubusercontent.com/8603801/30954678-e9f80b24-a43d-11e7-83f1-c7a2dcf8918a.png)

**Comment by moezbhatti** [comment]
This system has been completely re-written for QKSMS 3, closing this!

**Comment by omidjoon** [comment]
i dont understand what you mean "This system has been completely re-written for QKSMS 3, closing this!"

**Comment by moezbhatti** [comment]
@omidjoon I am currently working on a new version of QKSMS, and I'm building it from scratch. I have a new system for handling navigation, so this issue will no longer exist in the new update

**Comment by omidjoon** [comment]
ok thanks i hope you will be success . we are waiting for this update . be lucky
