### ISSUE TITLE
Text formatting is confusing to use

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#79]
## Problems
- The average user won't know what "Markdown" is
- We don't outline which parts of markdown we even support
- For people who don't already know the syntax, we don't state how to actually use the feature
## Proposed behavior
- Have a button on the toolbar opens a little pop up showing something alone the lines of BOLD | ITALICS | UNDERLINE
- When the user clicks on one, then starts typing, their text will automatically be stylized. Behind the scenes we've inserted the magic markdown characters for them, and they're invisible because the editor is showing the formatted text
- If they click one of the styling options while the cursor is inside a span of styled text, it'll undo that style for that selection

**Comment by l3d00m** [comment]
[Here](https://github.com/l3d00m/Vulcan/blob/develop/app/src/main/java/com/fractalwrench/vulcan/common/FormatUtils.java) is a basic markdown parser using Java Patterns/regex.  
I'm also offering my help with a markdown parser.

**Comment by Samcfuchs** [comment]
I think this would be useful. I'm used to writing markdown, but most people aren't, and the app needs new users who aren't coders.

**Comment by homersimpsons** [comment]
Or at least show a how-to pop-up on parameter, and precise that a lot SMS app doesn't handle this syntax so formating char will show up.

**Comment by moezbhatti** [comment]
The feature hasn't been supported in quite some time now
