### ISSUE TITLE
[Feature Request] Mailing-List of SMS

### ISSUE THREAD

**Issue by But2ene** [moezbhatti/qksms#791]
Hello,
First, thank you for your hard work, I switched recently to QKSMS. And it works well, so I'll keep it.
I come here (is this the right channel?) because I have a little project to implement on top of QKSMS, but I lost myself a bit in the amount of code here. I hope you could hint me to the right answer?

# Situation
A friend of me can't download nor update new apps on her old phone, and it's not practical for grouped conversation with other friends. So we are limited to SMS, but they don't handle grouped conversation very well either, the single thread for sending and receiving sms don't work.

# Solutions
I aim to get a single threads of grouped messages for each people in our little group. Like sending and receiving messages from/to a mailing list but with SMS. I took a look at SMS gateways (OVH is a little expensive, 0.07€/sms) and the GroupMe app works only in the US :/ 
So, hey, I thought, I'm relatively used to code, so let's develop it !

# Implementation
I have a second SIM card for my phone (so, a spare phone number).
Basically, a solution can be to send messages to a particular phone number (a sms server phone). It contains a (hardcoded?) list of recipients, their phone numbers and their nickname.
This phone checks if the SMS is from a particular list of phone numbers (my friends), and checks if it starts with a specific string, like a 'G'. if that's the case, it lightly reformats the message body (to add a sender nickname). Then it transfers the message to the others people in the group. That's it, no need for dynamic changes for now.

# The question(s)
Supposing everything is well defined until here, my questions to implement it is : 
1. Should the code to read and analyze received sms should be in an override of `MessagingReceiver.onReceive` method or in another place ?
2. Is the `HeadlessSmsSendService.onHandleIntent` method the right one to call to transfer the SMS to the others recipients ?

Thank you for your patience for this very long message :)

**Comment by moezbhatti** [comment]
Hey, sorry for the late response!

1 - Correct, this is the entry point for all incoming messages.

2 - Kind of. You don't actually need to use the HeadlessSmsService though. If you take a look inside that method, you can see what it does to send the message. In particular, you'll need to use a `Transaction` and a `Message`
