### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by cameronbroe** [moezbhatti/qksms#793]
I am unsure if this is actually my device or if there is a problem with QKSMS, but I figured I'll post an issue here just in case there is a bug somewhere in QKSMS causing it. So, a description of what is happening is the application becomes slow and begins to lag after being open (even when switched to from other apps) for a long period of time. Specifically, inputting text becomes very sluggish and navigating around message threads is very sluggish. Usually terminating the app through the Android recent apps screen speeds it back up. It seems like there may be a memory leak somewhere. If I find some time, I'll load a dev version of the app on my phone and see if I can do some profiling. Maybe ADB can help me identify the specific issue. If I diagnose the issue, I'll see if I can put a PR together. Just curious if anybody else is having performance issues.

Steps to reproduce:
* Use QKSMS for an extended period of time
* Use the app normally

Here is some device information
* App version: 2.7.3
* Android version: 7.1.1
* Device: Motorola Z2 Force
* Keyboard app: SwiftKey

**Comment by therob84** [comment]
I can verify this behaviour. Therefore normally after 1-2 days I swipe-out the app form android taskmanager and restart the app. Than it works quite OK.

I am uncertain, if on this issue is still worked - or if QKSMS-improvement is terminated .... @moezbhatti ?

- QKSMS 2.7.3 / Android 5.1 / Fairphone 2

**Comment by Swedneck** [comment]
Sometimes it takes a few seconds to launch when I click the icon, running AICP custom ROM on Lenovo p2.

**Comment by moezbhatti** [comment]
This should be resolved in QKSMS 3.0. More info here: https://plus.google.com/+MoezBhatti/posts/PZiikBCtiNc
