### ISSUE TITLE
Saving draft messagers

### ISSUE THREAD

**Issue by rain-19** [moezbhatti/qksms#795]
I really like this app, but i have not one small thing about save draft messagers, eg:  once you have chosen a contact, then typed your message, and back out off the messaging app. It will save the draft but with no contact , and it cant be seen in main menu. So you have to go back into messaging, draft text is there but again no contact saved, so your having to type the contact again. 
Could you please look into this issue. Since i regualary use this app. But bit would help if this feature was fixed or added ? 

Thanks

Regards

Sob

**Comment by moezbhatti** [comment]
This has been addressed in QKSMS 3.0. Closing!
