### ISSUE TITLE
Red number, despite no new texts

### ISSUE THREAD

**Issue by WkrKorea** [moezbhatti/qksms#796]
Even though I've read (and re-read, just in case) all the texts in QKSMS, the icon in Android has a red circle with 9. Recently 8. It keeps climbing.

This is probably due to spam texts that the Should I Answer? app is deleting. Maybe QKSMS it's hiding those texts instead of deleting them?

That makes the red number unhelpful.

To see what I'm seeing, get a phone number that spammers have, install QKSMS and Should I Answer? apps, link them in the QKSMS settings, and wait for the spammers to send texts.

**Comment by WkrKorea** [comment]
The number doesn't have to do with the "Should I Answer?" app, but with Amber alerts, bad weather alerts, etc. They're still going to the old messaging app by LG, but can't be opened there, since it's no longer the default.

**Comment by NM8Services** [comment]
Yes this is annoying. Where to turn the count off or clear it abs then turn it off. I can't do stand seeing it.

**Comment by moezbhatti** [comment]
Related to #311
