### ISSUE TITLE
Widget shows messages in what appears to be on random order

### ISSUE THREAD

**Issue by Sage222** [moezbhatti/qksms#798]
<!--
Please search the existing issues before creating a new one
https://github.com/moezbhatti/qksms/issues?q=is%3Aissue

Fresh install. Only changed theme color to dark and background to black.  Messages in app are normal with most recent at the top.  Widget is completely different. Showing an order that appears to be random.

**Comment by Sage222** [comment]
Using dark theme and black background. (not sure if that matters) Widget does not sure majority of messages and appears to be in random order.

**Comment by Gaijin1** [comment]
Hope this gets fixed on this version QKSMS2

**Comment by moezbhatti** [comment]
Fixed in bb8b2e6cdc29d267e18a43b37ef4ce63ede1b3d5
