### ISSUE TITLE
Fullscreen and using AndroidBug5497Workaround

### ISSUE THREAD

**Issue by Gaijin1** [moezbhatti/qksms#799]
I'm trying to use what's become the standard workaround for fixing the hidden layout issue caused by the keyboard in fullscreen mode/themes, "AndroidBug5497Workaround" and am having a really hard time figuring out where to place the class and how to implement it in QKSMS.

See it here: https://stackoverflow.com/questions/7417123/android-how-to-adjust-layout-in-full-screen-mode-when-softkeyboard-is-visible/18249145#18249145

I'm still a beginner, but I've tried pretty blindly a few times, but nothing.
Can this work? If so, a guide (for a newbie) or just sharing the relevant files where you successfully implemented it would be extremely helpful, and much appreciated. Compensation could also be arranged :-)

**Comment by moezbhatti** [comment]
@Gaijin1 which screen would you be looking to implement it in?

**Comment by Gaijin1** [comment]
Thank you!
I'd want to implement it in compose and conversations where the keyboard is shown.

**Comment by moezbhatti** [comment]
Have you tried setting `android:windowSoftInputMode="adjustResize"` on the relevant activities in the androidmanifest? Does this provide the behaviour you're looking for?

**Comment by Gaijin1** [comment]
I tried that first, but it's actually an Android bug. The only way to do it is with the work around here.
I researched for a few days before asking for help. I know this is the only way, but my coding skills are too poor to know where to implement it.

**Comment by moezbhatti** [comment]
What's causing the bug? (Just so I have more context)

Is it because you need it to be a full-screen activity?

**Comment by Gaijin1** [comment]
Yes. I need to be in fullscreen. With the status bar and its icons ruins the look of my theme.

**Comment by Gaijin1** [comment]
The only other way would be to toggle fullscreen only when the keyboard is show. I can't figure that out either, or I wouldn't have opened this issue.

**Comment by moezbhatti** [comment]
You'll need to add an id to the highest level view in the layout file for each screen you want to implement this on

Then in the fragment after creating your view, call 
```java
findViewById(R.id.myRootView).getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener(){
    public void onGlobalLayout() {
        checkHeightDifference();
    }
});
```
