### ISSUE TITLE
Status of Kotlin Rewrite

### ISSUE THREAD

**Issue by BrainBlasted** [moezbhatti/qksms#800]
Hi. I was wondering if the Kotlin rewrite was seeing progress. I visit the page from time to time and see that the ETA for the rewrite has been pushed back further each month. I've been worried that something was blocking this, as the rewrite's code does not seem to be visible on the repository.

**Comment by moezbhatti** [comment]
It's getting really close! I'm hoping to have a beta release ready within the next week or so. I was blocked on working on it for a while, but as of November I've been working on the app full-time

I'm currently working on it in a private repository, but I'll be making it public once the release is ready

**Comment by jerryn70** [comment]
Can we expect the long waited dual sim support in this release ?

**Comment by alekksander** [comment]
Are You planning new logo? I'd love to see that!

**Comment by moezbhatti** [comment]
@jerryn70 not in the initial release, but I'm certainly going to support it in the near future now that there exists official APIs for it

**Comment by moezbhatti** [comment]
@alekksander yep!

**Comment by moezbhatti** [comment]
Closing the issue, as the previews are now being released

https://plus.google.com/+MoezBhatti/posts/PZiikBCtiNc

**Comment by alekksander** [comment]
@moezbhatti great news! i hope the new logo will be more like the original one rather than current one. this is all quite exciting :) Thank You for Your hard work!

**Comment by BrainBlasted** [comment]
So, now that the release is ready would you consider making the repository public?

**Comment by moezbhatti** [comment]
@alekksander if you uninstall and just re-install from the Play Store, then you'll be able to use 2.7.3 again!

**Comment by moezbhatti** [comment]
@BrainBlasted I plan to go public later this week. I have to do a bit of cleanup first, and make sure that I've added the appropriate license headers to all of the source files

**Comment by moezbhatti** [comment]
@BrainBlasted update: I've made it public. It's currently on the `qksms3` branch
