### ISSUE TITLE
Improve the theme selection menu

### ISSUE THREAD

**Issue by f380cedric** [moezbhatti/qksms#804]
### Issue
- Unable to know which color theme is used
- Unable to exit the theme selection menu without selection a color
### Steps to reproduce
- Open the app (QKSMS > 3.0)
- Slide to the right (or click on the menu icon, top left)
- Open Settings
- Click on theme

### Expected behavior
Something should indicate which color is used (e.g. check icon). The user should be able to exit this menu without selecting a theme (using the android return button).

**Comment by moezbhatti** [comment]
This has been implemented for the next release
