### ISSUE TITLE
Unable to select a ringtone

### ISSUE THREAD

**Issue by f380cedric** [moezbhatti/qksms#805]
### Issue
Unable to select a ringtone. Clicking on it does nothing.

### Steps to reproduce
- Open the app (QKSMS > 3.0)
- Go the the settings (slide to the right, settings)
- Click on ringtone

### Expected behavior
After clicking on ringtone, a system menu should appear to select a ringtone.

**Comment by moezbhatti** [comment]
This is fixed in Preview 4
