### ISSUE TITLE
"parse error" on v3 APKs

### ISSUE THREAD

**Issue by vossenjp** [moezbhatti/qksms#806]
I'm trying to install `QKSMS-v3.0.0-Preview-03.apk` from Github, but I get:
```
Parse error
There was a problem parsing the package.
```
I have "System Settings > Security > Unknown Sources: checked".  I have tried downloading from the phone and from FF on Linux and nothing works, so I don't think it's APK D/L corruption.  I've also tried `QKSMS-v3.0.0-Preview-02.apk` but I get the same error.

FDroid install of 2.7.3 works, but I get the "sending..." forever bug in a group text, so trying v3 per #270.  2.7.3 *does* seem to eventually send, but it's not really usable.  Using MMS settings as per https://www.mintsim.com/setup-for-android/ and thus far no amount of fiddling with settings (2.7.3) has helped so I was really hoping v3 would...

Note I'm running Android 4.4.4 on an old Blackphone1 that has *NO Google services* of any kind (no store, no push, no nothing).

**Comment by moezbhatti** [comment]
Are you able to install the other preview builds?

**Comment by vossenjp** [comment]
No.  As noted above `QKSMS-v3.0.0-Preview-02.apk` fails and I just tried `QKSMS-v3.0.0-Preview-01.apk` and it fails too, both with the same error.  However, `QKSMS-v2.7.3.apk` from Github (or F-Droid) installs, but then has the slow "sending..." bug.

**Comment by moezbhatti** [comment]
@vossenjp does preview 4 resolve the issue for you?

**Comment by vossenjp** [comment]
Nope, same error.  :-(

**Comment by moezbhatti** [comment]
@vossenjp I'm very sorry, I didn't read your original post carefully enough. I've realized what the issue is

Unfortunately, QKSMS 3.0 only supports Android 5.0 and above. I considered supporting earlier versions, but there were many new APIs introduced in Android 5.0 that allow me to write significantly less, and more reliable code with regard to MMS.

I apologize for the inconvenience, would love to have you using the app again if you find yourself on Android 5.0+ in the future!

**Comment by vossenjp** [comment]
Bummer, but I get it.  Thanks for the effort on both this bug and the tool.

**Comment by vossenjp** [comment]
By the way, is there any chance of porting any of the fixes, especially the one for the stuck "sending..." bug, to the v2 QKSMS that works on really old phones?  I suspect I know the answer, but it can't hurt to ask. :-)

**Comment by moezbhatti** [comment]
It likely won't happen :(

The old codebase is such a pain to work with, it's why I re-wrote the app from scratch. And since it's a completely new codebase now, the fixes aren't really possible to just port over because they're essentially two completely different apps

**Comment by vossenjp** [comment]
Yeah, that's what I thought.  Oh well, thanks anyway.
