### ISSUE TITLE
Migrate preferences from v2.x to v3.x

### ISSUE THREAD

**Issue by sm4rk0** [moezbhatti/qksms#807]
### Steps to reproduce:
Update from v2 to v3. In my case:
* back up app data (eg. via Titanium Backup)
* uninstall v2.7.3
* install v3.0.0-Preview-03 from GitHub
* restore app data

### Expected behavior:
Theme and Dark mode settings are preserved.

### Actual behavior:
Theme and Dark mode settings are not preserved.

### Note (:
Great work! It seems performance is improved.

**Comment by moezbhatti** [comment]
Added in 5871d327426652447bc41d2a1215da2b12b13320
