### ISSUE TITLE
Old (v2) launcher shortcut doesn't work with v3

### ISSUE THREAD

**Issue by sm4rk0** [moezbhatti/qksms#808]
After updating to v3.0.0-Preview-03, old shortcut does nothing (ADW Launcher).

### Root cause:
Different intent/component data
v2: com.moez.QKSMS/.ui.MainActivity-Default
v3: com.moez.QKSMS/.presentation.main.MainActivity

### Workaround:
Obviously, delete old shortcut and create a new one.

**Comment by moezbhatti** [comment]
The old icon should end up being automatically removed by the launcher. I've tested this on a few launchers and it works as expected

The new app doesn't support changing the icon color, so I won't be implementing anything to remedy this. I'm expecting it to not affect most users, but I'll be watching the reviews during the main app rollout and if it's a common issue I'll make sure to address it before it's fully deployed

**Comment by sm4rk0** [comment]
@moezbhatti just to mention that this happened again when updating from 3.3.7 to 3.4.1 (f-droid) when it changed to ".feature.main.MainActivity".
