### ISSUE TITLE
Endlessly asking to set up MMS, even after success.

### ISSUE THREAD

**Issue by Gaijin1** [moezbhatti/qksms#809]
Some apns like the most popular carrier here in Japan Don't have mmsc, proxy or port settings, so even when adding these, we get an endless loop of asking us to set up MMS when trying to make one.

As a quick work around I added to check MAX_MMS_ATTACHMENT_SIZE and set the default to ""

private boolean hasSetupMms() {
        if (TextUtils.isEmpty(mPrefs.getString(SettingsFragment.MMSC_URL, ""))
                && TextUtils.isEmpty(mPrefs.getString(SettingsFragment.MAX_MMS_ATTACHMENT_SIZE, ""))
                && TextUtils.isEmpty(mPrefs.getString(SettingsFragment.MMS_PROXY, ""))
                && TextUtils.isEmpty(mPrefs.getString(SettingsFragment.MMS_PORT, ""))) {

A cleaner method that I don't have the know-how or time to do myself would be to check if an apn, mcc or mnc has been set, or the Set MMS returned SUCCESS

**Comment by moezbhatti** [comment]
This has been resolved in QKSMS 3.0 - thanks!
