### ISSUE TITLE
Null Pointer on TextView (onMeasure) of CustomPreferences

### ISSUE THREAD

**Issue by Stackflood** [moezbhatti/qksms#810]
Hi,

I am trying to implement the custom sharedPreferences from your project. I am getting this error while running the settingsactivity in my project. I will appreciate if you can look at the issue here : https://stackoverflow.com/questions/48121115/null-pointer-on-textview-onmeasure-of-custompreferences and suggest what I am missing.

Thanks

**Comment by moezbhatti** [comment]
This question is very vague, I'm not quite sure what you mean. And that link goes to a very general "what is a nullpointerexception" page
