### ISSUE TITLE
Invite friends

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#825]
Add an option to invite friends from the app

**Comment by realmain** [comment]
Curious... what do you mean by inviting friends to the app? If it is to send a download link to the app to friends via text, I don't think it's really needed. I think it's more important in data-based apps, not SMS/MMS apps.

**Comment by moezbhatti** [comment]
This becomes more relevant in the future when there is some functionality added which might not work depending on the other person's SMS app

A couple examples
- RCS (both apps need to be compatible)
- Markdown formatting (recipient won't see formatted text)
