### ISSUE TITLE
New message from wearable

### ISSUE THREAD

**Issue by maxsin** [moezbhatti/qksms#846]
DESCRIPTION
When using a wearable, give the ability to send a predefined text to a contact.

STEPS
Go to defining set of Quick Responses screen
Open the wearable app on the device (currently NONE for QKSMS)
Select contact (maybe importing favorites ones from the phone)
Select predefined text to be sent.

EXPECTED
Predefined text gets sent to the desired contact.

OBSERVATIONS
Maybe closing the wear app right after the message gets sent.

**Comment by moezbhatti** [comment]
Merging with #802
