### ISSUE TITLE
App Shortcuts

### ISSUE THREAD

**Issue by JayDoc386** [moezbhatti/qksms#848]
Add support for App Shortcuts for versions of Android that support this by long-pressing on the app icon.

**Comment by gkomarnicki** [comment]
Having app shortcuts will definitely save a lot of time, especially if one has a lot of conversation threads. A static shortcut like "New message" would also benefit for those on pre-7.1 devices.

**Comment by armandojrod** [comment]
This should be look into before full release please, it's a basic feature for all other sms apps

**Comment by moezbhatti** [comment]
For later reference: https://developer.android.com/guide/topics/ui/shortcuts

**Comment by JavaCafe01** [comment]
[Shortbread](https://github.com/MatthiasRobbers/shortbread) might be a great help.

**Comment by moezbhatti** [comment]
@JavaCafe01 this looks like an awesome library, thanks for the link! Unfortunately, it doesn't really apply to QKSMS, because I'll need to create shortcuts for specific contacts, not just different pages in the app (with the exception of Compose)
