### ISSUE TITLE
Enable sending of GIFs or other media inserted from the keyboard

### ISSUE THREAD

**Issue by zackaryry** [moezbhatti/qksms#850]
I noticed when using Preview 6, when using Gboard to select a GIF to send from within a conversation thread already started, QKSMS would open a new message dialog, requiring us to reselect the recipient. Even upon doing so, the GIF is not added to the message (i.e. there is no preview as there is after selecting a photo from system storage.)

**Comment by moezbhatti** [comment]
Mergine with #751
