### ISSUE TITLE
Deleting conversation from within thread causes force close

### ISSUE THREAD

**Issue by jtsurf18** [moezbhatti/qksms#857]
From within the conversation, clicking menu and delete causes the app to force close. The thread does get removed though.

**Comment by moezbhatti** [comment]
Confirmed

**Comment by jtsurf18** [comment]
@moezbhatti nice! that was quick

**Comment by moezbhatti** [comment]
@jtsurf18 trying to get qksms 3.0 ready as fast as possible!
