### ISSUE TITLE
no back or cancel in theme selector (3.0.0 Preview 8)

### ISSUE THREAD

**Issue by TeeTeeHaa** [moezbhatti/qksms#863]
When the theme selector (that popup with the many, colored circles) is open,...
* there is no "cancel" button
* the hardware "back" button does not work
* there is no indication which theme is currently active

QKSMS 3.0.0 Preview 8 on Android 8.0.0 beta with January 2018 security patch level on Nokia phone

**Comment by moezbhatti** [comment]
Merging with #804
