### ISSUE TITLE
"Help & feedback" crashes app (3.0.0 Preview 8)

### ISSUE THREAD

**Issue by TeeTeeHaa** [moezbhatti/qksms#864]
When clicking "Help & feedback" in the menu, the app crashes and Android tells me "QKSMS has stopped".

QKSMS 3.0.0 Preview 8 on Android 8.0.0 beta with January 2018 security patch level on Nokia phone

**Comment by moezbhatti** [comment]
@TeeTeeHaa is your email app configured on your phone?

**Comment by moezbhatti** [comment]
For my own reference: https://stackoverflow.com/questions/14331953/no-activity-found-to-handle-intent-while-sending-email

**Comment by TeeTeeHaa** [comment]
No, neither the Gmail app nor another email app is configured or set as default.

**Comment by moezbhatti** [comment]
@TeeTeeHaa I'll make sure to get this fixed before 3.0 is launched!

**Comment by moezbhatti** [comment]
@TeeTeeHaa can you try this build and let me know if it resolves the crash? You may need to uninstall the current installation of the app

[qksms-noAnalytics-debug.apk.zip](https://github.com/moezbhatti/qksms/files/1715403/qksms-noAnalytics-debug.apk.zip)

**Comment by TeeTeeHaa** [comment]
See https://github.com/moezbhatti/qksms/issues/869#issuecomment-365041460.

**Comment by TeeTeeHaa** [comment]
Same crash in 3.0.0 Beta 1.

**Comment by moezbhatti** [comment]
@TeeTeeHaa can you try the latest build I've linked in #869?

**Comment by moezbhatti** [comment]
I'm going to close this as the solution will be the same as what's described in #869, and is likely already solved
