### ISSUE TITLE
"Notifications" didn't show anything initially (3.0.0 Preview 8)

### ISSUE THREAD

**Issue by TeeTeeHaa** [moezbhatti/qksms#865]
When clicking "Notifications" in the settings for the first and second time, nothing happened. I then did other things within QKSMS and some other things in the stock Android settings and then I clicked "Notifications" in QKSMS a third time and then it suddenly worked, showing the stock Android "Notifications" screen for QKSMS.

QKSMS 3.0.0 Preview 8 on Android 8.0.0 beta with January 2018 security patch level on Nokia phone

**Comment by moezbhatti** [comment]
Confirmed repro on a fresh install

**Comment by moezbhatti** [comment]
Fixed in 4ed4e01ed21efb4b6bd856e0be5baee0ebe08b36
