### ISSUE TITLE
filter messages containing keywords

### ISSUE THREAD

**Issue by ephestione** [moezbhatti/qksms#866]
I receive sms's from an online casino, Everytime from a different number. I find it useful to block/disable notifications for messages that contain a customizable set of keywords

**Comment by moezbhatti** [comment]
Hmm, I thought there was another issue open for this, but I can't seem to find it. Anyway, yes I certainly plan to implement this in QKSMS 3.0!

**Comment by homersimpsons** [comment]
#228

**Comment by moezbhatti** [comment]
Thanks @homersimpsons ! I'll close this one then
