### ISSUE TITLE
Display character count while typing new message

### ISSUE THREAD

**Issue by TeeTeeHaa** [moezbhatti/qksms#867]
Feature request for QKSMS 3: While typing a new message I'd like to see a character count. In addition I'd like the color of that number turn red if the message contains more characters than fitting in a single SMS (or some other method to indicate that more than one single SMS is required).

**Comment by moezbhatti** [comment]
Added in 6d6b3fbf77f02bc1f601e5eaf3a16f671d3bbbdf

**Comment by TeeTeeHaa** [comment]
Thank you for addressing this feature request, but where in the UI is that displayed? I cannot find it:

![qksms-3 0 9-compose](https://user-images.githubusercontent.com/739754/39268829-41940a8a-48d1-11e8-92e5-7e9642932bad.jpg)

I am using:
* QKSMS 3.0.9
* AnySoftKeyboard 1.9.1117
* AnySoftKeyboard: German 2.0.4 (language pack for AnySoftKeyboard)

**Comment by realmain** [comment]
I also do not see this in QKSMS 3.0.9

**Comment by moezbhatti** [comment]
It will only appear when you're close to the size limit for a single message
