### ISSUE TITLE
Crash when touching person icon in conversion with automated sender (3.0.0 Preview 8)

### ISSUE THREAD

**Issue by TeeTeeHaa** [moezbhatti/qksms#869]
When you get a SMS message from an automated sender, for example from a mobile phone carrier or a bank, and open the "conversion" and then touch the round "person" icon left of the received message text, QKSMS crashes.

QKSMS 3.0.0 Preview 8 on Android 8.0.0 with January 2018 security patch level on Nokia phone

Using [Simple-Contacts](https://github.com/SimpleMobileTools/Simple-Contacts) as default contacts app, having the stock Android "Contacts" app from Google disabled

Using stock Android "Phone" app from Google as default dialer (not having found an open source replacement yet...)

**Comment by moezbhatti** [comment]
If you go into the app settings and click `Sync messages` and try again, does this still happen?

**Comment by TeeTeeHaa** [comment]
Yes, it crashed the first time when opening the conversion and after a restart it crashed when touching the "person" icon, just like before.

Is there a way to retrieve log files which might help you?

**Comment by moezbhatti** [comment]
@TeeTeeHaa can you try this build and let me know if it resolves the crash? You may need to uninstall the current installation of the app

[qksms-noAnalytics-debug.apk.zip](https://github.com/moezbhatti/qksms/files/1715403/qksms-noAnalytics-debug.apk.zip)

**Comment by TeeTeeHaa** [comment]
I tried to install the provided APK file but that did not work: "App not installed." it said. 
[Logcat attached](https://github.com/moezbhatti/qksms/files/1717555/logcat-install-qksmsnoanalytics.txt).

**Comment by TeeTeeHaa** [comment]
I installed the APK file of 3.0.0 Beta 1 instead, that did work. Unfortunately both crashes still happen.

**Comment by moezbhatti** [comment]
@TeeTeeHaa can you try this one? [qksms-noAnalytics-release.apk.zip](https://github.com/moezbhatti/qksms/files/1715678/qksms-noAnalytics-release.apk.zip)

**Comment by TeeTeeHaa** [comment]
With this build:
* Installation works, app starts, app can be set as default app for SMS.
* Touching person icon left of SMS from automated sender in list of SMS shows message "No apps can perform this action."
* Touching person icon left of SMS from automated sender in conversation shows the very same message.
* Touching "Help & feedback" in menu shows the very same message (Chrome and Firefox are installed, Firefox is the default browser).

Wild guess: Trying to create a new contact from an SMS to/from a sender not in the address book where some information in the new contact will be prefilled from the SMS *or* trying to create a new contact from an SMS without an actual telephone number (automated sender), that does not work. Maybe this it is not (yet) supported by [Simple-Contacts](https://github.com/SimpleMobileTools/Simple-Contacts) or maybe QKSMS does initiate it in a "wrong" way.

Another info: When I touch a person icon in the default dialer app "Phone" (from Google) within the call history for a telephone number being not yet in my contacts, simply nothing happens. I'm not sure whether that is default behavior. Naively I would expect that a new contact will be created, prefilled with some information taken from the call history.

**Comment by moezbhatti** [comment]
So it seems to me like there's something strange going on with how Nokia's version of android is handling defaut apps. I'm using standard intents for sending an email or creating a contact, as I'm assuming the Phone app is as well. Even if Simple Contacts doesn't support it, then the phone's default contacts app should be displayed as an option.

And for clarification, the help & feedback open should open your email client, not your browser.

At this point I'm not exactly sure what a solution could be. I've tried a slightly different method of building the add contact intent. Can you try this build and let me know if anything different happens

[qksms-noAnalytics-release.apk.zip](https://github.com/moezbhatti/qksms/files/1721949/qksms-noAnalytics-release.apk.zip)

For reference, I've changed the intent uri from `Uri.parse("tel: $address")` to `Uri.fromParts("tel", address, null)` as recommended in the `ContactsContract.Intents.SHOW_OR_CREATE_CONTACT` documentation

**Comment by TeeTeeHaa** [comment]
Nokia always says it is using an Android as stock as possible.
The default contacts app won't open because it is disabled on my device.
I do not have an email app installed and the GMail app is disabled on my device.
I'll try your new build later today.

**Comment by TeeTeeHaa** [comment]
With that build:
* Installation works, app starts.
* Touching person icon left of SMS from automated sender in list of SMS shows message "No apps can perform this action."
* Touching person icon left of SMS from automated sender in conversation shows the very same message.
* Touching "Help & feedback" in menu shows the very same message.

So it seems that nothing changed.

I'm not sure whether this is an issue of QKSMS or Simple-Contacts. Maybe Simple-Contacts is simply not providing the correct intend. After your next Beta build, which hopefully contains the changes of "my personal" builds, I might open an issue for Simple-Contacts.

**Comment by moezbhatti** [comment]
Could you see what happens if you temporarily enable your email and contacts apps?

**Comment by TeeTeeHaa** [comment]
After enabling "Contacts" and "GMail":
* Touching person icon left of SMS from automated sender in list of SMS: The first time "Contacts" was opened, second third and other times nothing happened.
* Touching person icon left of SMS from automated sender in conversation: A message appears "Add 'somename' to contacts? CANCEL OK". Touching OK opens "Contacts" with the title "Add to contact". When Touching "Create Contact" the dialog to create a new contact appears with phone number field prefilled with 'somename' (currently I have only SMS from automated senders or from people being already present in my contacts list; I do not have a normal SMS from somebody not in my contacts list yet)
* Touching "Help & feedback" in menu: GMail opens.

**Comment by moezbhatti** [comment]
Okay, it sounds like things are working as expected in that case. And it sounds like Simple-Contacts simply hasn't added support yet for adding a contact via intent from other apps

The crash has been resolved (now if there are no supported apps, it will display that instead of crashing), so I'll close the issue. Thanks for all the help in narrowing this down!

**Comment by TeeTeeHaa** [comment]
Does 3.0 Beta 2 include all necessary fixes?

**Comment by moezbhatti** [comment]
@TeeTeeHaa yep, these changes have been incorporated in Beta 2
