### ISSUE TITLE
QK Reply window occasionally pops up for wrong user

### ISSUE THREAD

**Issue by gmerrall** [moezbhatti/qksms#87]
Version: 1.10.4 on Nexus 6 and Nexus 5

Not fully reproduceable but occasionally the QK Reply window will display the incorrect sender name along with an empty message after receiving an SMS.

**Comment by stevenroose** [comment]
I have the same issue, fairly often, v2.2.1. 

Usually, the QK window shows the contact from the latest conversation instead of the newly incoming message. 

This makes the QK Reply window quite useless.

**Comment by moezbhatti** [comment]
Yep, seems like it started happening again. I'll look into it

**Comment by stevenroose** [comment]
@moezbhatti Any progress?

**Comment by cirelli94** [comment]
Is this still happening to you?

**Comment by stevenroose** [comment]
For me it seems to be solved.
