### ISSUE TITLE
Multi selection for conversations

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#874]

**Comment by Bill-Stewart** [comment]
Hi Moez, do you mean select multiple messages within a thread for easy delete?

**Comment by moezbhatti** [comment]
This particular issue is referring to multi selection of conversations within the main list, to be able to archive / mark read / delete multiple conversations at once. Issue #42 may be what you're looking for

**Comment by Bill-Stewart** [comment]
Yes that's it, thanks!

**Comment by justiceo** [comment]
I'm unable to multi-select messages. I have tried, long-press, press on conversation icon, long-press on conversation icon etc. Please how do I do this. Running version 3.5.4 on Pixel 2
