### ISSUE TITLE
Can't see action in delete convo modal.

### ISSUE THREAD

**Issue by dponinski** [moezbhatti/qksms#875]
I looked for a bug report with the same issue but couldn't find one so I apologize if this is a duplicate.

I noticed that if you long press on a conversation a modal pops up but I think the text is white on the white background. If I press in the bottom right corner of the modal, it will delete the conversation so the action is available, you just can't read what's in the modal.

Let me know if you need further clarification.

**Comment by dogg94** [comment]
I came to submit this, it only happens in night mode.

**Comment by dponinski** [comment]
Thanks for the tip. When switching off night mode it's still a little hard to read with the light blue text on the grey background. I might suggest just plain white for dark modals and dark grey/black for white modals. I'm sure this is something still in development.

**Comment by moezbhatti** [comment]
If you restart the app, does it work properly?

I think I know what's causing this

**Comment by dogg94** [comment]
yes it works now, it is no longer a white box with white text, now it's a black box with white text

⁣Sent from BlueMail ​

**Comment by dponinski** [comment]
I confirm as well. It's now dark background with white text after restarting.

**Comment by moezbhatti** [comment]
Fixed in 784b625f6f5366169b994641e73dbac8315073b3
