### ISSUE TITLE
Draft messages are not saved when returning to the conversation list

### ISSUE THREAD

**Issue by CalculusWarrior** [moezbhatti/qksms#876]
When halfway through typing a message, and I click the back arrow to return to the conversation list, the message I typed is entirely deleted when returning. 

Assuming this behaviour is due to the 3.0 rewrite and should be fixed soon, but wanted to bring it to your attention. If I could suggest my view on how it should work:

- When clicking back, text of draft message is saved and remains in box when returning to specific 
conversation.
- Conversation in question moves to the top of the list (or to the point in time when the draft message was last edited, so if a newer message arrives, its conversation goes above the draft's).
- Text of conversation becomes italicized, or some other method of being able to tell at a glance that this message is a draft.

Apologies if this is already known, I'm otherwise loving the update!

**Comment by moezbhatti** [comment]
Thanks for bringing this up - this is something I'll need to get working very soon! I've added it to the list

**Comment by ZatsuneNoMokou** [comment]
It will be fixed in the old version too or we'll have to wait the version 3?

**Comment by moezbhatti** [comment]
@ZatsuneNoMokou This will be implemented for the next preview release of 3.0

**Comment by ZatsuneNoMokou** [comment]
So it mean, have to wait, ok

**Comment by moezbhatti** [comment]
Added in 9ac7fadfdd0b7b8cacd10d9658914d2c4a9c3ca2
