### ISSUE TITLE
Force Close when opening app

### ISSUE THREAD

**Issue by seriosbrad** [moezbhatti/qksms#878]
Galaxy Note 4, Android 6.0.1

Upon first launch of the app, it will load and attempt to update the database, but it never does.  I've left it for like 20 minutes.  So I close the app, attempt to re-open, and get an instant force close/crash.

I've tried clearing cache/data, and reinstalling the app, giving the app full permissions before first launch, but it still force closes.

[logcat_and_device_info.zip](https://github.com/moezbhatti/qksms/files/1710580/logcat_and_device_info.zip)

**Comment by moezbhatti** [comment]
Thanks for attaching the crash logs

Can you try this build and let me know if it crashes for you? You may need to uninstall the current one on your phone

Thanks!

[qksms-noAnalytics-debug.apk.zip](https://github.com/moezbhatti/qksms/files/1715382/qksms-noAnalytics-debug.apk.zip)

**Comment by seriosbrad** [comment]
@moezbhatti thanks for digging into the issue. 

I'm getting an "App not installed." error message with that one.

[logcat_app_not_installed.zip](https://github.com/moezbhatti/qksms/files/1715393/logcat_app_not_installed.zip)

**Comment by moezbhatti** [comment]
@seriosbrad can you try this one out?

[qksms-noAnalytics-release.apk.zip](https://github.com/moezbhatti/qksms/files/1715678/qksms-noAnalytics-release.apk.zip)

**Comment by seriosbrad** [comment]
@moezbhatti That one installs, but still force closes when opening D:
[logcat_and_device_info.zip](https://github.com/moezbhatti/qksms/files/1715800/logcat_and_device_info.zip)

**Comment by moezbhatti** [comment]
@seriosbrad I think this should fix it now. Thanks for attaching the logs!

[qksms-noAnalytics-release.apk.zip](https://github.com/moezbhatti/qksms/files/1718184/qksms-noAnalytics-release.apk.zip)

**Comment by moezbhatti** [comment]
@seriosbrad awesome, that's good to hear! These changes have been incorporated in Beta 2, among a few other things
