### ISSUE TITLE
Automatically sending failed texts; a problem which should be fixed

### ISSUE THREAD

**Issue by Miscbrah87** [moezbhatti/qksms#882]
Hi
This is just a suggestion. I downloaded QKSMS, and after I set it as my default messaging app, it automatically sent out a bunch of failed texts from conversations I had backed up. I saw some old conversation threads move up to the top. Some of them were from a few years ago, and ones which I did not want sent out (like to a couple of exes, which I didnt even realize I still had). Already dealing with the fallout from this. I don't know how common this problem is, but there should maybe be a default setting to not send out unsent or failed texts without clicking on retry. 

Thanks for considering any suggestions

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0!
