### ISSUE TITLE
Add unknown number to Contacts

### ISSUE THREAD

**Issue by CalculusWarrior** [moezbhatti/qksms#894]
A feature I find I like in other SMS apps is when texting a number which does not have a contact associated with it, the app provides the ability to quickly add a new contact using this number, basically by sharing the number to the default Contacts app of the system.

This would be a nice quality of life feature to add to QKSMS as well. Obviously it is low-priority and the rest of the 3.0 update takes precedence, but it is a nice 'one day' feature to add to the list. 😃

**Comment by moezbhatti** [comment]
I'll actually be working on this pretty soon.

In the meantime, you can click on the avatar and then it will have the behavior that you're looking for, it's just not very intuitive

**Comment by moezbhatti** [comment]
Added in 4024cb83d1952f290c253d0a4f43f0717dfcd63c
