### ISSUE TITLE
Unable to See Contact Names in Group MMS Conversation

### ISSUE THREAD

**Issue by ChillMasterT** [moezbhatti/qksms#901]
### Bug Description
The bug is visible in all group MMS conversations. There is no way to tell between senders (especially if they are not in your contacts). Instead, above each message it reads "NoSubject."

### Device Details
* Device: ONEPLUS A3000
* Operating System: OxygenOS 5.0.1 (Android 8.0.0 Oreo)
* QKSMS Version: 3.0 Beta 2

**Comment by moezbhatti** [comment]
Fixed in fbe74aa316bd1aa71952b9c18f874e4cc0d91808
