### ISSUE TITLE
Close Keyboard When Opening Hamburger Menu

### ISSUE THREAD

**Issue by ChillMasterT** [moezbhatti/qksms#903]
### Bug Description
They keyboard (if opened in order to search inbox) does not close when the hamburger menu is opened from the conversation list.

### Steps to Replicate
1. Open QKSMS
2. Make sure you are on the conversation list view (default if you opened from the launcher shortcut)
3. Tap "Search inbox..." at the top
4. Tap the hamburger menu icon at the top left

### Device Details
* Device: ONEPLUS A3000
* Operating System: OxygenOS 5.0.1 (Android 8.0.0 Oreo)
* QKSMS Version: 3.0 Beta 2

**Comment by moezbhatti** [comment]
Are there any apps you're aware of that work in the way you'd expect? I'm not sure what the recommended pattern is for this behavior

**Comment by ChillMasterT** [comment]
Actually, the only app I could find that animation I mentioned in is the Google Play Store, so it might not be publicly available.

**Comment by ChillMasterT** [comment]
![](https://i.imgur.com/YeL9dnx.jpg)
I just don't think you should be able to search while the hamburger menu is open. The keyboard displays over it and the search results are obstructed.

**Comment by ChillMasterT** [comment]
Most apps I am comparing to are designed to prevent the hamburger menu from being opened while a search is being made

**Comment by ChillMasterT** [comment]
I guess what I'm saying is that opening the hamburger menu should either:
* End the search entirely (and close the keyboard)
* Keep the search behind the menu in case the user wants to return to it, but close the keyboard
* or instead change the hamburger menu button into an exit search button when a search is open so both search and menu can't be open at the same time

**Comment by moezbhatti** [comment]
Ah. Yes, you're totally right. For some reason I was imagining that the drawer opened above the keyboard - without actually verifying it. Your screenshot was helpful!

I'll make sure to get this fixed, sorry for the misunderstanding

**Comment by ChillMasterT** [comment]
No problem, I totally understand the mistake. Thanks for you hard work!

**Comment by moezbhatti** [comment]
Fixed in 2e9193784fff44409572456b27c3a0148a0ee6f9
