### ISSUE TITLE
Messages won't sync on certain Huawei and HTC devices

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#910]
Known list of devices with repro:
- Huawei P10 Lite | 7.0
- HTC U11 | 8.0

cc @krux3r

**Comment by krux3r** [comment]
If you need any info feel free to tell :)

**Comment by gkomarnicki** [comment]
Have the same bug on my Huawei Nova 2i (Mate 10 Lite), running 7.0 Nougat.
![screenshot_20180301-151202](https://user-images.githubusercontent.com/20436870/36832854-4dfe5a62-1d68-11e8-93b8-8464f102bb00.png)

**Comment by ksaad9** [comment]
Same problem on HTC U11 running Android 8.0

**Comment by prohde** [comment]
Same for Huawei P9 Lite on Android 7.0.

**Comment by JNuss71** [comment]
Same for Huawei Honor 5X

**Comment by moezbhatti** [comment]
@prohde @JNuss71 can you see if Beta 7 fixes the issue for you?

**Comment by MyNameIsCosmo** [comment]
If any of you are on Linux/Mac, could you do the following:
1. Install Beta 7
2. Open up a terminal/cmd prompt and type in the following command:
    ```console
    adb logcat | grep -F "`adb shell ps | grep QK | cut -c10-15`" >> qksms.log
    ```
3. Open QKSMS
    1. Go to Settings
    2. At the bottom hit *Sync messages*
4. `Ctrl+C` the `adb logcat` in the terminal
3. Paste the contents of `qksms.log` on [gist.github.com](https://gist.github.com) or [pastebin.com](https://pastebin.com) and drop a link in this issue

**Comment by krux3r** [comment]
Fixed for me!
Huawei P10 Lite, stock 7.0.

**Comment by prohde** [comment]
@moezbhatti Beta 7 fixed it for me.

**Comment by ksaad9** [comment]
Beta 7 fixed it for me as well!

HTC U11 running Android 8.0.

Thanks!

**Comment by gkomarnicki** [comment]
Messages are showing up for me as well on the latest beta! Huawei Nova 2i (Mate 10 Lite) on 8.0 beta.

**Comment by moezbhatti** [comment]
That's fantastic news. I believe this was fixed by https://github.com/moezbhatti/qksms/commit/73aafca2323054d232d1ddb2bde93e6292b1ab07
