### ISSUE TITLE
Incorrect photo thumbnail in pre-existing MMS

### ISSUE THREAD

**Issue by ahattat** [moezbhatti/qksms#92]
All thumbnails of photos received by MMS prior to installing QKSMS are the same one (seems to be corresponding to the first thumbnail displayed after installing the app).
When tapping the thumbnail the correct photo is opened though.

This issue does NOT concern MMS received after installing QKSMS, those show the correct thumbnail.

**Comment by moezbhatti** [comment]
Was your previous app Textra?

**Comment by ahattat** [comment]
Yes it was Textra.

**Comment by CyanBlob** [comment]
I've got the same problem. Also from Textra.

**Comment by moezbhatti** [comment]
Okay, thought so

Something about the way they store their thumbnails is weird and QK doesn't currently know how to read them properly

If you want to repro it, just send/receive MMS messages while Textra is your main messenger and then switch back to QK

**Comment by ahattat** [comment]
Repro worked for me.
So the cure is simply to never use Textra ever again ;-)

**Comment by imsnowjn** [comment]
I am a former textra user with this same issue.   I've tried doing an SMS backup, delete all and restore, hoping that it might straighten out the thumbnail storage.  It didn't work.  I've tried a bunch of different SMS apps.  QKSMS is the only one to have this issue.

Are there any known steps to correct this condition?

**Comment by moezbhatti** [comment]
This should be resolved in QKSMS 3.0
