### ISSUE TITLE
App crashes when app icon in tapped

### ISSUE THREAD

**Issue by fazlerabbi37** [moezbhatti/qksms#921]
App crashes when app icon is tapped both in menu icon and home screen. Incoming message are being displayed on notification bar and when that notification are tapped they lead to app as expected but while tapping the app in menu or home screen for composing new message app crashes.
Steps to reproduce the issue
    - Tap the app icon in either main menu or home screen
Expected: Open app with threaded view
Version: 2.7.3

**Comment by moezbhatti** [comment]
This should be fixed in QKSMS 3.0
