### ISSUE TITLE
[BUG] MMS image different size displayed

### ISSUE THREAD

**Issue by Woodzrul** [moezbhatti/qksms#922]
Device: OnePlus 2 A2001
Version: 7.1.2

When attaching an MMS then the size of the image (when in the conversation) differs depending on the length of the caption. Should this not be consistent throughout?

**Comment by moezbhatti** [comment]
There's a minimum size, but if the text is wider then the image will expand to fit the width that the text would normally take up

This is the intended behavior - but if I think of a better way to handle this then I'm certainly open to improving it
