### ISSUE TITLE
Archiving messages instead of deleting them

### ISSUE THREAD

**Issue by StripedMonkey** [moezbhatti/qksms#927]
I'm very much of a pack rat and NEED to be able to keep a record of all past messages but this gets very cluttered obviously. The ability to hide conversations without deleting it's contents is important to me and something this app lacks the ability to do. This is a pretty big QOL improvement and I honestly can't use the app until then.

The default Google client allows this with a swipe and I would honestly like to have the same for this app.

**Comment by moezbhatti** [comment]
This functionality exists in QKSMS 3.0 :)

**Comment by moezbhatti** [comment]
You can swipe a conversation to archive it, or archive via the menu
