### ISSUE TITLE
[Request] Floating reply window/QK Reply, like in 2.0 version

### ISSUE THREAD

**Issue by zawyer1** [moezbhatti/qksms#929]
I feel like this is a crucial feature which makes QKSMS stand out among other alternative SMS apps. Not only was this a unique feature that worked slightly differently from other SMS apps that claim to have floating reply windows, but it worked much better and much smoother.

Is there any chance you can implement this in QKSMS 3.0?

**Comment by moezbhatti** [comment]
Seems like a lot of people want this - I'll make sure to include this in 3.0

**Comment by Jrdnkasparek** [comment]
Can we make this an optional feature though

**Comment by moezbhatti** [comment]
@Jrdnkasparek yep, definitely. It will also be off by default for devices that support inline replies in notifications

**Comment by moezbhatti** [comment]
Added by https://github.com/moezbhatti/qksms/commit/481c0336ff09fad5532e1983e46cc3a8f9cd561f
