### ISSUE TITLE
Proposal for an icon and a logo type for the application

### ISSUE THREAD

**Issue by richardbmx** [moezbhatti/qksms#939]
Hello my name is Richard Caseres I am a graphic designer and I like to make contributions for open source projects from the graphic and advertising point of view. in this opportunity I contact you to propose a new icon and a logo more personalized and more current for your application in development this in order to give a better image to your project.

I develop within the platform Utopian.io with blockchain of steemit, the rewards I receive from them however they require me to contact the developer of the project so that they can verify that my logo proposal will be used in the project and so do not compensate contributions that will not be used in the projects.

Here I show you a model of the proposal of the logo if it is of tua degree I can provide you all the necessary files within a contribution in GitHub to be added to your project.

![presentationnew](https://user-images.githubusercontent.com/35604837/37567150-1da9bddc-2a99-11e8-8762-5d85b674821e.png)

So that within Utopian-io my contribution to your project is valid you must place on the main page of the project on GitHub an application for a new logo or icon as a contribution to your project to simply demonstrate that you will use the new icon and the new logo.

Well I hope you like my proposal, thank you very much for your time to read this and I hope we are in contact. Greetings.

**Comment by Woodzrul** [comment]
+1

Great designs. :-)

**Comment by nmvega** [comment]
The B/W and One Color blue ones are nice. :blush:

**Comment by MyNameIsCosmo** [comment]
I prefer the rotation on the old logo, where the bubble "leg" (for lack of a better term) is in contact with the bottom.
The old logo has a subtle "Q" in it, which is very touching.

A solid white outline like in the "one color" example is clean. Black and white are great to stick with in terms of notification and icon colors in my opinion.

Nice documentation!

**Comment by moezbhatti** [comment]
@richardbmx thanks for working on this, I really appreciate all the effort you've put in.

I'm afraid I won't be able to use your design in QKSMS however. I don't feel it fits with the design language of the app, and this is especially true with 3.0 (which happens to include a redesigned icon!)

Best of luck with the rest of your contributions, this is a really great thing that you're doing.
