### ISSUE TITLE
Message counter isn't accurate

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#94]
https://www.reddit.com/r/Android/comments/3h7kqr/dev_qksms_is_now_completely_free_and_open_source/cu53myr?context=3

**Comment by jayrox** [comment]
this is actually an interesting bug to read about.  
the message length is limited by the constraints of the signaling protocol to precisely 140 octets (140 octets * 8 bits / octet = 1120 bits)

Depending on which alphabet the subscriber has configured in the handset, this leads to the maximum individual short message sizes of 160 7-bit characters, 140 8-bit characters, or 70 16-bit characters. GSM 7-bit alphabet support is mandatory for GSM handsets and network elements,[49] but characters in languages such as Arabic, Chinese, Korean, Japanese, or Cyrillic alphabet languages (e.g., Ukrainian, Serbian, Bulgarian, etc.) must be encoded using the 16-bit UCS-2 character encoding (see Unicode). Routing data and other metadata is additional to the payload size.

https://en.wikipedia.org/wiki/Short_Message_Service#Message_size

i guess an easy fix would be look at the alphabet config and base the counter from that. 

a more fun exercise would be count the used bits, subtract them from the max of 1120, divide by 7.
this could be slightly confusing to someone who doesn't understand the bits to characters as to why one 16bit character would use two from the counter.


ahh the joys of character encodings.

**Comment by LanderN** [comment]
This also applies when using emoji in messages, in Textra I can see the message counter changing from 160 to 70 when an emoji is added (so the whole message is converted to Unicode I suppose)

**Comment by jayrox** [comment]
@LanderN Yeah, that's kind of what I was trying to get at and it would make sense that it would work that way.

**Comment by LanderN** [comment]
This bug is still not fixed, I think it should be high priority because for people who are roaming for example, the accuracy of this counter is very important.

**Comment by l2dy** [comment]
Any progress?

**Comment by moezbhatti** [comment]
Fixed in 6d6b3fbf77f02bc1f601e5eaf3a16f671d3bbbdf
