### ISSUE TITLE
[Request] Only clear notification when conversation is read

### ISSUE THREAD

**Issue by mikeblazanin** [moezbhatti/qksms#944]
A request to only clear the notification for a conversation/thread when that particular conversation is read (or the notification is dismissed by user), and not whenever the app is opened.

Currently:
1. Have multiple unread conversations
2. Open app & read one conversation
3. Notifications for all conversations are cleared

Requested:
1. Have multiple unread conversations
2. Open app & read one conversation
3. Notification for that conversation is cleared, but notifications for other conversations remain in notification tray

**Comment by moezbhatti** [comment]
This is the behaviour in QKSMS 3.0 :)

**Comment by mikeblazanin** [comment]
Oh great, happy to hear it!!

Mike
