### ISSUE TITLE
Can't receive MMS

### ISSUE THREAD

**Issue by DadouLapous** [moezbhatti/qksms#945]
Hello :) ,

I'm using a samsung galaxy s5 with lineageos (7.1.2) with the beta 7 version, and i can't receive any mms. I tried with with different sizes, with no changes (100KB-1000KB)

STEPS : 
(after resetting app and reinstalling it)
-> I send a MMS to myself
(wait and nothing come back)
https://user-images.githubusercontent.com/15857585/37869847-e938ac76-2fbf-11e8-9dd0-fdbea18af394.jpg

Here's some catlog (i don't understand any of this :) ) 

https://user-images.githubusercontent.com/15857585/37869864-74d7d158-2fc0-11e8-9051-ff6b45e14095.jpg

https://user-images.githubusercontent.com/15857585/37869865-7fd2ebec-2fc0-11e8-89fa-ff971c3ebfd6.jpg

And everything works fine with the stock sms app :/ 
(when i send something to myself, it comes back ~5s later)
Thanks, for your work !

**Comment by MyNameIsCosmo** [comment]
Hi @DadouLapous 
Is it possible for you to export the entire log from catlog?

May you also try:
1. Open QKSMS3
2. Go to Settings > Sync Messages
3. Check to see if your MMS message is synced

**Comment by DadouLapous** [comment]
Hey, 
I tried to sync messages, without success.
Here's the entire logcat :
[logcat_and_device_info.zip](https://github.com/moezbhatti/qksms/files/1845107/logcat_and_device_info.zip)

**Comment by MyNameIsCosmo** [comment]
```console
03-25 09:40:01.850 E/CursorToMessage$Message(31199): Couldn't find column 'err_type' in [_id, thread_id, date, date_sent, msg_box, read, m_id, sub, sub_cs, ct_t, ct_l, exp, m_cls, m_type, v, m_size, pri, rr, rpt_a, resp_st, st, tr_id, retr_st, retr_txt, retr_txt_cs, read_status, ct_cls, resp_txt, d_tm, d_rpt, locked, sub_id, seen, creator, text_only]
```

I think the error has to do with determining the message type in `CursorToMessage.kt`
I don't have time right now to dig into the issue, but it seems similar to the issue for the LG devices from #934 

@moezbhatti - should `data/mapper/CursorToMessage.kt` handle an "unknown" type?

**Comment by moezbhatti** [comment]
It looks like when it's trying to sync the message after receiving it, it queries the native MMS database incorrectly which results in an error preventing the sync

@DadouLapous if you go into the settings and sync all messages, do these missed messages appear?

**Comment by DadouLapous** [comment]
I think that's not far from the bug indeed. 
I sent to myself a MMS, and i synced the message ( after ~15s), but when i oppened the conversation back, the app crashed. I repeated this bug, and when i sync with nothing to sync, there is no crash by comming back to the conversation.
Here's a catlog : 
[2018-03-27-22-32-16.txt](https://github.com/moezbhatti/qksms/files/1853726/2018-03-27-22-32-16.txt)

**Comment by bennaux** [comment]
For me, I cannot even send MMS, running on Fairphone Open on an Fairphone 2.

**Comment by ThatAdonis** [comment]
Okay, so decided to send a MMS to myself to test if mms is working? Instantly received, however no one else can receive any pictures I send. LG v30 running 7.1.2

**Comment by ron-edison** [comment]
I have similar issue. Just updated to qksms 3.0.4 cannot send or receive mms, resync doesn't change anything. Mms with an image fails to send.

Anyone know if installing prior version is possible without losing my sms history?

Thanks

**Comment by ron-edison** [comment]
Sorry left out my device which is OnePlus 5 on T-Mobile (us)

**Comment by moezbhatti** [comment]
@ron-edison you won't lose your history if you switch to another SMS app (or a prior version of QKSMS)

**Comment by ron-edison** [comment]
Ok thanks am trying to install 2.7.3 from GitHub and getting a message the package is corrupt, would rather not install via Google play, f-droid looks like it no longer has that version, any suggestions?

**Comment by moezbhatti** [comment]
@ron-edison I just tested the version from Github and it seems to work fine for me. Make sure to first uninstall the newer version of QK before you try to install 2.7.3

**Comment by ron-edison** [comment]
Ok thanks that resolved it, also mms is fully working again for me on 2.7.3 just fyi, let me know if I can assist with testing this any further with the current version

**Comment by X-dark** [comment]
I still have this issue with latest version from F-Droid (3.3.3) on a Moto G4 with Android 7.0.
Do you need any additional info to debug this?

**Comment by X-dark** [comment]
I seem to have different results depending of the sim card (both work fine with stock app).

Here is the log when it fails:
```
13032:07-25 16:44:52.533  3433  3433 V MmsReceivedReceiver: MMS has finished downloading, persisting it to the database
13033:07-25 16:44:52.534  3433  3433 V MmsReceivedReceiver: /data/user/0/com.moez.QKSMS/cache/download.6643992410225025514.dat
13034:07-25 16:44:52.534  3433  3433 V MmsReceivedReceiver: No MMSC information set, so no notification tasks will be able to complete
13038:07-25 16:44:52.563  3433  3433 D DownloadRequest: DownloadRequest.persistIfRequired
13040:07-25 16:44:52.563  3433  3433 E DownloadRequest: DownloadRequest.persistIfRequired: invalid parsed PDU
13068:07-25 16:44:52.648  3433  3433 V MmsReceivedReceiver: response saved successfully
13069:07-25 16:44:52.648  3433  3433 V MmsReceivedReceiver: response length: 72
```

And here is a successful reception:
```
10218:07-25 16:43:52.800  3433  3433 V MmsReceivedReceiver: MMS has finished downloading, persisting it to the database
10219:07-25 16:43:52.800  3433  3433 V MmsReceivedReceiver: /data/user/0/com.moez.QKSMS/cache/download.5342284690116028298.dat
10220:07-25 16:43:52.804  3433  3433 V MmsReceivedReceiver: No MMSC information set, so no notification tasks will be able to complete
10223:07-25 16:43:52.833  3433  3433 D DownloadRequest: DownloadRequest.persistIfRequired
10278:07-25 16:43:53.601  3433  3433 V MmsReceivedReceiver: response saved successfully
10279:07-25 16:43:53.601  3433  3433 V MmsReceivedReceiver: response length: 278177
10280:07-25 16:43:53.673  3433  7219 E CursorToMessage$Message: Couldn't find column 'err_type' in [_id, thread_id, date, date_sent, msg_box, read, m_id, sub, sub_cs, ct_t, ct_l, exp, m_cls, m_type, v, m_size, pri, rr, rpt_a, resp_st, st, tr_id, retr_st, retr_txt, retr_txt_cs, read_status, ct_cls, resp_txt, d_tm, d_rpt, locked, seen, text_only, image_resize_status, sub_id, creator, rcs_contribution_id, rcs_message_id, rcs_delivered_to, rcs_extra, rcs_message_type, rcs_timestamp_delivered, rcs_timestamp_displayed, rcs_file_resumable, rcs_alias_name]
```

**Comment by DadouLapous** [comment]
I no longer have this issue, thanks for your work !

**Comment by maverick74** [comment]
I can send but can't receive

**Comment by bennaux** [comment]
Same for me, I think...

**Comment by Nosion** [comment]
Samsung S7 - worked before with build in Samsung message app.
Version 3.6.1
I can send MMS, but I am receiving SMS messages saying "failed to receive an MMS from phone number, please check that your phone supports MMS and is correctly configured."

Also let me know if I can do some debugging (will need some kind of instructions).

**Comment by Jouski** [comment]
Hello,
I have this bug on Xiaomi Redmi Note 5, with QKSMS 3.6.3, from Frdoid.

**Comment by mwgonzalez** [comment]
I also have a Xiaomi Redmi Note 5 (codename "whyred")
https://en.wikipedia.org/wiki/Redmi_Note_5
I installed QKSMS 3.6.4 (com.moez.QKSMS) from the Google Play Store on 2019/04/22.
As soon as I made QKSMS the default messaging app, I could no longer receive MMS.
Approximately 72 hours after someone tried to send me an MMS, I would receive an SMS notification from my mobile operator saying I could download the MMS from their website. (Perhaps it is defined in the MMS protocol to try delivering an MMS for 3 days before giving up, a bit like SMTP.)
As soon as I changed the default messaging app back to the stock app, I could receive MMS again.
(NB: I could always successfully *send* SMS with QKSMS.)

@moezbhatti : Do you need additional info to help fix this bug?

**Comment by moezbhatti** [comment]
@mwgonzalez any chance you could also get a logcat for a min before and a couple mins after sending an mms to yourself?

**Comment by mwgonzalez** [comment]
@moezbhatti did you receive the logcats I sent by email last week?
Did they provide any insight?

**Comment by moezbhatti** [comment]
Hey @mwgonzalez, thanks for following up. I did get your email - just been a bit busy this week and haven't had time to look into it yet. I'll try to take a peek this weekend or early next week and I'll let you know if I find anything or not!

**Comment by moezbhatti** [comment]
Hey @mwgonzalez, I just took a look at the logs and I think I have an idea what might be causing the issue for you. What version of Android you running?

**Comment by mwgonzalez** [comment]
Hello @moezbhatti 
I was just about to write :-)
I used to run MIUI 10 which was based on Android 8.1 (I think) at the time.
This weekend, I flashed a custom ROM called /e/ or eelo.
/e/ comes with a forked version of qksms, which does not have the issue.
I don't know if it's a different Android, or a patch they applied.

**Comment by moezbhatti** [comment]
Okay interesting. Upon further inspection from those logs, I'm still not entirely sure what's causing it. In the next update I'll be adding some improved automated logging, and hopefully this will help funnel in a bunch more info to help me figure out what the problem is

**Comment by kelido** [comment]
Hello,
As mwgonzalez, I can send MMS but I can't receive it.
I have a Redmi note 7 and I'am running QKSMS 3.6.6 from F-Droid. My phone works on MIUI 10.2 based on Android 9 PKQ1 version.

**Comment by mwgonzalez** [comment]
Additional information:
I replaced the official Xiaomi ROM, with the /e/ beta
(a Lineage OS fork based on Android 8.1 for whyred)

Running their fork of QKSMS:
1) I can receive MMS, although I still receive the notification 3 days later that an MMS is available to download from a webserver.
2) sending MMS fails always
Given these symptoms, this is probably a different bug...
https://gitlab.e.foundation/e/apps/Message

**Comment by bennaux** [comment]
When will the new version with the fix be available on Fdroid? Or shall I test it again already?

**Comment by moezbhatti** [comment]
I'm planning to push it out in the next couple days. If you have the ability to build the project yourself, you're welcome to test it and let me know if it helps you!

**Comment by bennaux** [comment]
I only have that opportunity at work, the Android debugging environment at home is one of the things I did not manage to install for the last years. :D So I can only install and test it, but I'll let you know if it helps!

**Comment by mwgonzalez** [comment]
@moezbhatti, thanks for looking into this.  
I am no longer able to test on MIUI, but I will test on /e/ ASAP.  
Are you using a recent version of the android-smsmms library?  
(They pushed an update on Jun 16)

**Comment by moezbhatti** [comment]
@mwgonzalez I looked through the recent changes there and couldn't seem to find anything related to this issue sadly. I'm still using my modified version of that lib
