### ISSUE TITLE
Rounded compose box

### ISSUE THREAD

**Issue by gkomarnicki** [moezbhatti/qksms#946]
It would be better if the compose box was rounded like in WhatsApp or Android Messages. The current rectangular one seems a bit out of place with the rounded send button to the right of it, IMO.

A "pill-shaped" compose box (à la early versions of Google Allo) might also fit in with QKSMS' UI.

**Comment by moezbhatti** [comment]
I'll play around with some alternate designs once 3.0 is released :)

**Comment by moezbhatti** [comment]
In the meantime, here's a quick mockup

![messages - default](https://user-images.githubusercontent.com/4358785/37991754-01ca8664-31d8-11e8-94bb-035d55be46e9.png)

**Comment by gkomarnicki** [comment]
That looks awesome!

This is my idea of how the compose box could look like:

![qksms-compose-box-mockup](https://user-images.githubusercontent.com/20436870/38006528-fa4a56da-3277-11e8-9af1-bd02272eb50f.png)

Tapping on the plus sign would enable users to add images, as well as possibly anything else in the future. 

When there's no text in the compose box, the send button would be disabled (figure 1). 

When there is text, the send button becomes enabled and inherits the theme colour (figure 2).

The plus sign could also be on the right side next to the send button, but then the compose box would look awkward with nothing on the left side. An emoji button on the left side perhaps? 

With the plus sign on the right side, it could also transform into a send button the moment text is being entered.

Just my two cents!

**Comment by moezbhatti** [comment]
Released this in 3.3.5 but forgot to update the issue! https://github.com/moezbhatti/qksms/commit/ad202a2f64524a94e872efddcccc635bec01a3ca
