### ISSUE TITLE
In dark modus the navigation bar is still 'white' 

### ISSUE THREAD

**Issue by Jatarii** [moezbhatti/qksms#955]
With navigation bar I mean the bottom bar where you go 'back - home - recent apps'.

**Comment by Jatarii** [comment]
![screenshot_20180401-231523__01](https://user-images.githubusercontent.com/18144491/38177476-aae0fb88-3602-11e8-8680-c7119722d334.jpg)

**Comment by Jatarii** [comment]
No problem, just wanted to bring this to your attention ;)

**Comment by moezbhatti** [comment]
Fixed in c8c5dd3aad08ed5ddb05a500955f53c311e92847
