### ISSUE TITLE
Title bar doesn't change color according to the theme in the overview screen (recents apps)

### ISSUE THREAD

**Issue by armandojrod** [moezbhatti/qksms#957]
For example, I have dark mode enable and the title bar is white.

![screenshot_20180402-042658](https://user-images.githubusercontent.com/10835960/38189633-0e6f6514-362f-11e8-9016-08212a661903.png)

**Comment by moezbhatti** [comment]
Fixed in ab4c134090cc6fab0e96f7135eae85f1e7c961d2
