### ISSUE TITLE
Beta: clicking a link or phone number in SMS crashes the app

### ISSUE THREAD

**Issue by poiNt3D** [moezbhatti/qksms#958]
- clicking a link or phone number in SMS crashes the app
- 1. Recieve an SMS with a link or phone number 2. Tap the SMS

**Comment by moezbhatti** [comment]
Works fine for me, which phone and beta version are you running?

**Comment by moezbhatti** [comment]
Fixed in 0190f4bef8355fbbe2467b214574e63d85e0e11d
