### ISSUE TITLE
Sticky Notification Text

### ISSUE THREAD

**Issue by MyNameIsCosmo** [moezbhatti/qksms#966]
Using the latest QKSMS3 Beta 8.
I received a message, read it, and any message afterwards would display as the "first" message in my notifications.

This did not happen I'm beta 7.

I won't be by a computer for the next day or so, so I cannot debug the issue fully.

EX:
Received message: "First Message"
Notification: "First Message"
Respond to message
Receive another message: "Second Message"
Notification: "First Message"

It may also be worth noting that notifications are displayed even though qksms is open in the same chat the message was received.

**Comment by moezbhatti** [comment]
Fixed in 30759c66d40c84038c3d67f3594562a765d0c701
