### ISSUE TITLE
Swipe conversation actions

### ISSUE THREAD

**Issue by Jrdnkasparek** [moezbhatti/qksms#967]
Can there be an option in settings to also swipe one direction to delete conversation instead of archiving it?

- For instance, swipe right to archive and swipe left to delete.
     --Maybe an undo option for unintentional deletion

- Settings option to turn this off

Keep up the amazing work! I stopped using this app when the development stopped and moved to Pulse, but now I am using it again and love it! Even bought Qksms+ to support you and this app

**Comment by moezbhatti** [comment]
I plan to allow customization for the left and right swipe actions, with the following options

- None
- Archive
- Call
- Delete

**Comment by spocko** [comment]
Mark read/unread and block could also be offered as swipe actions.

When the swipe options are implemented, I suggest the same swipe actions apply to the archived conversation list (except the archive option would become unarchive). Currently there are no swipe actions in the archived conversation list.
