### ISSUE TITLE
Conversations all say the same date after Sync

### ISSUE THREAD

**Issue by Jrdnkasparek** [moezbhatti/qksms#971]
When the conversations are synced with Android the conversations all say the day they synced until you open and close the conversation

![screenshot_20180403-202943](https://user-images.githubusercontent.com/20908630/38283947-88eeb380-377e-11e8-93f7-e6b048e75cb6.jpg)

**Comment by Jrdnkasparek** [comment]
Yes I did actually, had to reset my phone

**Comment by moezbhatti** [comment]
Okay gotcha. Merging with #897
