### ISSUE TITLE
Not able to attach pictures

### ISSUE THREAD

**Issue by Jrdnkasparek** [moezbhatti/qksms#972]
When I go to attach a photo, it gives no photos to attach. This was working before beta 8

- Has all permissions enabled
- No option to pick photos from Google Drive, Photos app

**Comment by moezbhatti** [comment]
What happens when you click on the attachment button?

**Comment by Jrdnkasparek** [comment]
It brings up the file explorer and says no files available. Doesn't give me the option to look in Google Photos or drive
