### ISSUE TITLE
Better Message Details

### ISSUE THREAD

**Issue by MyNameIsCosmo** [moezbhatti/qksms#975]
Currently tapping a message will bring up the time the message was received from contact or sent from the user.

There should be more details such as the sent datetime,  revived datetime, message type, sent to, and message status.

**Comment by zawyer1** [comment]
I was going to point this out as well. There should be an option to show sent/received datetime on each message by default. As for sent & delivered status, I think something like this is a good solution to save space (see the picture). The first check mark indicates sent status, and the second check mark indicates delivered status.

![4ippv5b](https://user-images.githubusercontent.com/37254938/38336505-4301254e-3862-11e8-9efa-eecfcec51fbe.png)

**Comment by realmain** [comment]
Example of text message:

**Message details**
Type: SMS
From: +18884567896
To: +18009658746
Received: 04/13/18, 17:36

Example of a MMS:


**Message details**
Type: MMS
From: +18884567896
To: +18009658746
Received: 04/13/18, 17:36
Size: 500 kB
