### ISSUE TITLE
App does not wake phone/give notification when new SMS is received

### ISSUE THREAD

**Issue by zawyer1** [moezbhatti/qksms#987]
This is something I've experienced with both 3.0 and the old versions of QKSMS, and I'm honestly unsure whether it's on my end or a problem with the app.

About 20% of the time, the app won't "wake" the phone and give me a sound/vibration. I only realize a new message is received once I open the app and see the message. When I used the old QKSMS I even converted it to a system app but it would still "ignore" about 5-10% of messages and wouldn't give a notification at all.

I've pondered whether the app is underprivileged and could use 1 or 2 more permissions to successfully wake the phone 100% of the time. My phone is rooted and I'm sure that it has all the requested permissions. I haven't experienced this issue with neither the stock SMS app nor Textra, which makes me think it might be an issue with QKSMS.

Is this something anyone else has experienced? I'd be happy to debug it if someone tells me how to do it. I've got CatLog installed but it seems hard to reproduce/test.

**Comment by zawyer1** [comment]
I was able to solve this issue. 99% confident it's not app related but ROM/phone related.

You can delete/remove this issue. Love all the work you're putting into the app by the way!

**Comment by moezbhatti** [comment]
Hey, thank you for the update!

Just in case any other users report the issue to me, would you mind explaining what you did to solve it?

**Comment by zawyer1** [comment]
Sure! My phone has a built-in battery saving feature called "Battery Optimization", which apparently works a bit like Greenify. The feature will automatically kill all apps that are open in the background and will "hibernate" them to prevent them from waking the phone unnecessarily. Crucial apps are supposed to be exempted automatically (phone/SMS/alarms, etc), but for some reason QKSMS was considered a normal app and thus was shut off/hibernated automatically whenever the screen was shut off. I had to manually add it as an exemption in the settings.

I think this is what caused the issue and it seems to be fully working now.

All the best.
