### ISSUE TITLE
Cannot delete images/mms in conversation thread

### ISSUE THREAD

**Issue by RyanPMcLaughlin** [moezbhatti/qksms#994]
I can touch and hold messages to have options to delete them, but there is no clear way for me to delete received or sent mms messages.

If an mms gets stuck sending, I don't have the option to delete it, it's just... There

**Comment by moezbhatti** [comment]
Will make this easier!

In the meantime, you should be able to delete it if you press and hold outside of the message bubble, so just beside it

**Comment by moezbhatti** [comment]
Fixed in 199edea
