### ISSUE TITLE
[BUG] Search display

### ISSUE THREAD

**Issue by Woodzrul** [moezbhatti/qksms#999]
Device: OnePlus 2 A2001
Version: 7.1.2
QKSMS: 3.0.3. 

Search inbox... -> Type 'Joe Bloggs' = Returns a result
Use the backspace key on the Android keyboard to delete the name 'Joe Bloggs' then returns all received messages.

Search inbox... -> Type 'Joe Bloggs' = Returns a result
Press the X button (to the right) to delete name does not return any received messages.

Inconsistent and should display the same when using both of the above methods.

**Comment by moezbhatti** [comment]
Fixed in 223d789f5f1de219867226cba417f83bbffc7537
